objects/Advertiser__c.object
<CustomObject>
    <fields>
        <fullName>Advertiser_Approved_to_Book__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Checked = Advertiser has been approved to book by Finance 
Unchecked = Advertiser has NOT been approved to book by Finance</inlineHelpText>
        <label>Advertiser Approved to Book</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Duplicate_Approval__c</fullName>
        <description>Used to prevent duplicate advertisers from being created.</description>
        <label>Duplicate Approval</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Not Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Advertiser</label>
    <nameField>
        <label>Advertiser Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Advertisers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Brands__c.object
<CustomObject>
    <fields>
        <fullName>Advertiser__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Advertiser</label>
        <referenceTo>Advertiser__c</referenceTo>
        <relationshipLabel>Brands</relationshipLabel>
        <relationshipName>Brands</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approved_Duplicate__c</fullName>
        <label>Duplicate Approval</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Not Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>.Com/E-Commerce</fullName>
                </value>
                <value>
                    <fullName>Apparel/Accessories</fullName>
                </value>
                <value>
                    <fullName>Appliances/Home Gadgets</fullName>
                </value>
                <value>
                    <fullName>Attorney/General Legal Services</fullName>
                </value>
                <value>
                    <fullName>Attorney-Medical Services/Equipments/Prescriptions</fullName>
                </value>
                <value>
                    <fullName>Auto Accessories/Parts/Repair</fullName>
                </value>
                <value>
                    <fullName>Baby</fullName>
                </value>
                <value>
                    <fullName>Beauty/Cosmetics/Hair Care</fullName>
                </value>
                <value>
                    <fullName>Business/Professional Services</fullName>
                </value>
                <value>
                    <fullName>Charity</fullName>
                </value>
                <value>
                    <fullName>Cleaning Supplies</fullName>
                </value>
                <value>
                    <fullName>Crafts/Hobbies/Sporting goods/Toys</fullName>
                </value>
                <value>
                    <fullName>Education</fullName>
                </value>
                <value>
                    <fullName>Electronics/Software</fullName>
                </value>
                <value>
                    <fullName>Entertainment/Gaming</fullName>
                </value>
                <value>
                    <fullName>Fitness/Health/Medical Equipment</fullName>
                </value>
                <value>
                    <fullName>Food and Beverages</fullName>
                </value>
                <value>
                    <fullName>Home Improvement/Furniture</fullName>
                </value>
                <value>
                    <fullName>Insurance- Auto</fullName>
                </value>
                <value>
                    <fullName>Insurance- Health/ Dental/ Disability</fullName>
                </value>
                <value>
                    <fullName>Insurance- Life</fullName>
                </value>
                <value>
                    <fullName>Media/Telecom</fullName>
                </value>
                <value>
                    <fullName>Medical Services</fullName>
                </value>
                <value>
                    <fullName>Mental Health</fullName>
                </value>
                <value>
                    <fullName>Mobile Apps</fullName>
                </value>
                <value>
                    <fullName>Office Supplies</fullName>
                </value>
                <value>
                    <fullName>Pets</fullName>
                </value>
                <value>
                    <fullName>Pharmaceuticals/Drugs</fullName>
                </value>
                <value>
                    <fullName>Social Networking/Dating</fullName>
                </value>
                <value>
                    <fullName>Toiletry</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Brands</label>
    <nameField>
        <label>Brand</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Deal__c.object
<CustomObject>
    <fields>
        <fullName>Advertiser__c</fullName>
        <formula>Brands__r.Advertiser__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Advertiser</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Brands__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Brands</label>
        <referenceTo>Brands__c</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ClientCode__c</fullName>
        <formula>Program__r.ClientCode__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ClientCode</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Type__c</field>
                <operation>notEqual</operation>
                <value>history</value>
            </filterItems>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>Do Not Call</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Length__c</fullName>
        <label>Length</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>30</fullName>
                    <color>#0B6FCE</color>
                    <label>30</label>
                </value>
                <value>
                    <fullName>60</fullName>
                    <color>#78C953</color>
                    <label>60</label>
                </value>
                <value>
                    <fullName>120</fullName>
                    <color>#E27001</color>
                    <label>120</label>
                </value>
                <value>
                    <fullName>300</fullName>
                    <color>#A845DC</color>
                    <label>300</label>
                </value>
                <value>
                    <fullName>15</fullName>
                    <color>#F3D904</color>
                    <label>15</label>
                </value>
                <value>
                    <fullName>1710</fullName>
                    <color>#A53711</color>
                    <label>1710</label>
                </value>
                <value>
                    <fullName>90</fullName>
                    <color>#66E9BD</color>
                    <label>90</label>
                </value>
                <value>
                    <fullName>180</fullName>
                    <color>#0B24BE</color>
                    <label>180</label>
                </value>
                <value>
                    <fullName>240</fullName>
                    <color>#419249</color>
                    <label>240</label>
                </value>
                <value>
                    <fullName>45</fullName>
                </value>
                <value>
                    <fullName>75</fullName>
                </value>
                <value>
                    <fullName>05</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>150</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>105</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>35</fullName>
                </value>
                <value>
                    <fullName>40</fullName>
                </value>
                <value>
                    <fullName>1714</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Program</label>
        <referenceTo>Programs__c</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Deal</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Deal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PrelogData__c.object
<CustomObject>
    <fields>
        <fullName>Version__c</fullName>
        <label>Version</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Week__c</fullName>
        <formula>CASE( 
MOD(  AirDate__c - DATE(1900, 1, 7), 7), 
0, AirDate__c - 6, 
1, AirDate__c , 
2, AirDate__c -1, 
3, AirDate__c - 2, 
4,AirDate__c - 3, 
5, AirDate__c - 4, 
6, AirDate__c - 5, DATE(2001, 1, 1))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Week</label>
        <type>Date</type>
    </fields>
    <label>Prelog Data</label>
    <nameField>
        <displayFormat>Pre-{0000000}</displayFormat>
        <label>Prelog Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prelog Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Programs__c.object
<CustomObject>
    <description>Program/Distributor</description>
    <fields>
        <fullName>Barter__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Barter</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Cable_Synd__c</fullName>
        <label>Cable/Synd/PP</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cable</fullName>
                </value>
                <value>
                    <fullName>Syndication</fullName>
                </value>
                <value>
                    <fullName>PP</fullName>
                </value>
                <value>
                    <fullName>Bundle</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ClientCode__c</fullName>
        <description>Assigned by Finance</description>
        <inlineHelpText>Assigned by Finance</inlineHelpText>
        <label>ClientCode</label>
        <length>3</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Prelog_Version__c</fullName>
        <label>Prelog Version</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Station_Call_Letter__c</fullName>
        <label>Station Call Letter</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Schedules__c.object
<CustomObject>
    <fields>
        <fullName>Deal_Parent__c</fullName>
        <label>Deal Parent</label>
        <referenceTo>Deal__c</referenceTo>
        <relationshipLabel>Schedules</relationshipLabel>
        <relationshipName>Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Units_Available__c</fullName>
        <label>Units Available</label>
        <precision>17</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Units_Preempted__c</fullName>
        <label>Units Preempted</label>
        <precision>17</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Week__c</fullName>
        <label>Week</label>
        <type>Date</type>
    </fields>
    <label>Schedule</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/PrelogClearanceControllerTest.cls
@IsTest
private class PrelogClearanceControllerTest {

    @IsTest static void PrelogClearanceControllerTest() {

        Date constDate = Date.today().toStartOfWeek().addDays(1);

        Contact con = new Contact(
                LastName = 'Test',
                Email = 'test@test.com',
                Phone = '8001234567'
        );
        insert con;

        Advertiser__c advertiser = new Advertiser__c(
                Duplicate_Approval__c = 'Approved',
                Advertiser_Approved_to_Book__c = true
        );
        insert advertiser;

        Brands__c brand = new Brands__c(
                Name = 'Availability',
                Category__c = 'Other',
                Advertiser__c = advertiser.Id,
                Approved_Duplicate__c = 'Approved'
        );
        insert brand;

        //Program
        Programs__c program = new Programs__c(
                Name = 'BounceTV',
                Cable_Synd__c = 'Cable',
                ClientCode__c = 'h1',
                Barter__c = true,
                Station_Call_Letter__c = 'a',
                Prelog_Version__c = 5
        );
        insert program;

        Deal__c deal = new Deal__c(
                Contact__c = con.Id,
                Brands__c = brand.Id,
                Program__c = program.Id,
                Length__c = '5'
        );
        insert deal;

        //Schedule
        Schedules__c schedule = new Schedules__c(
                Units_Available__c = 1.0,
                Units_Preempted__c = 0,
                Week__c = constDate,
                Deal_Parent__c = deal.Id,
                Status__c = 'Sold',
                Rate__c = 300
        );
        insert schedule;

        PrelogData__c pdata = new PrelogData__c(
                Schedule__c = schedule.Id,
                AirDate__c = constDate,
                Version__c = 5
        );
        insert pdata;

        deal = [
                SELECT Id,
                    (SELECT Id, Deal_Parent__c, OrderLineNumber__c, Total_Dollars__c FROM Schedules__r),
                    Contact__c,
                    Brands__c,
                    Program__c,
                    Length__c
                FROM Deal__c
                WHERE Id = :deal.Id
                LIMIT 1
        ];

        PrelogClearanceController dc = new PrelogClearanceController() ;

        dc.CurrentFP = [
                SELECT Id,
                        FiscalYearSettings.Name,
                        StartDate,
                        EndDate,
                        Number,
                        PeriodLabel
                FROM Period
                WHERE Type = 'Month'
                LIMIT 1
        ];

        dc.Searchfield = 'BounceTV' ;
        dc.SelectedDateLiteral = null ;
        dc.ReturnSOQLDateString() ;
        dc.DoSearch() ;
        dc.SelectedDateLiteral = 'Custom' ;
        dc.ReturnSOQLDateString() ;
        dc.DoSearch() ;
        dc.SelectedDateLiteral = 'Current And Previous 2 FY';
        dc.ReturnSOQLDateString() ;
        dc.DoSearch() ;
        dc.SelectedDateLiteral = 'Current And Next 3 FQ';
        dc.ReturnSOQLDateString() ;
        dc.DoSearch() ;
        dc.SelectedDateLiteral = 'Current And Previous FP';
        dc.ReturnSOQLDateString() ;
        dc.DoSearch() ;
        dc.SelectedDateLiteral = 'Current And Next FP';
        dc.ReturnSOQLDateString() ;
        dc.DoSearch() ;
        dc.SelectedDateLiteral = 'Last FW';
        dc.ReturnSOQLDateString() ;
        dc.DoSearch() ;
        dc.SelectedDateLiteral = 'This FW';
        dc.ReturnSOQLDateString() ;
        dc.DoSearch() ;
        dc.SelectedDateLiteral = 'Next FW';
        dc.ReturnSOQLDateString() ;
        dc.DoSearch() ;
        dc.SelectedDateLiteral = 'Current And Previous 2 CY';
        dc.ReturnSOQLDateString() ;
        dc.DoSearch() ;
        Test.startTest();
        dc.SelectedDateLiteral = 'Current And Next CY';
        dc.ReturnSOQLDateString() ;
        dc.DoSearch() ;
        dc.SelectedDateLiteral = 'Current And Previous CQ';
        dc.ReturnSOQLDateString() ;
        dc.DoSearch() ;
        dc.SelectedDateLiteral = 'Current And Next 3 CQ';
        dc.ReturnSOQLDateString() ;
        dc.DoSearch() ;
        dc.SelectedDateLiteral = 'Current And Last Month';
        dc.ReturnSOQLDateString() ;
        dc.DoSearch() ;
        dc.SelectedDateLiteral = 'Current And Next Month';
        dc.ReturnSOQLDateString() ;
        dc.DoSearch() ;
        dc.SelectedDateLiteral = 'Last Week';
        dc.ReturnSOQLDateString() ;
        dc.DoSearch() ;
        dc.SelectedDateLiteral = 'This Week';
        dc.ReturnSOQLDateString() ;
        dc.DoSearch() ;
        dc.SelectedDateLiteral = 'Next Week';
        dc.ReturnSOQLDateString() ;
        dc.DoSearch() ;
        dc.SelectedDateLiteral = 'Yesterday';
        dc.ReturnSOQLDateString() ;
        dc.DoSearch() ;
        dc.SelectedDateLiteral = 'Today';
        dc.ReturnSOQLDateString() ;
        dc.DoSearch() ;
        dc.SelectedDateLiteral = 'Tomorrow';
        dc.ReturnSOQLDateString() ;
        dc.DoSearch() ;
        dc.SelectedDateLiteral = 'Last 120 Days';
        dc.ReturnSOQLDateString() ;
        dc.DoSearch() ;
        dc.SelectedDateLiteral = 'Next 120 Days';
        dc.ReturnSOQLDateString() ;
        dc.DoSearch() ;
        Test.stopTest();
        dc.SelectedDateLiteral = 'This Week';
        dc.Searchfield = 'BounceTV,BounceTV' ;
        dc.ReturnSOQLDateString() ;
        dc.DoSearch() ;
        dc.Searchfield = 'BounceTV' ;
        dc.BarterCheckbox = true;
        dc.getDealResult() ;
        Date d = Date.today();
        DealUtils.ReturnStringDate(d.toStartOfMonth()) ;
        DealUtils.ReturnStringDate(d.toStartOfMonth().addDays(10));
        Date d2 = Date.newInstance(2014, 12, 1) ;
        DealUtils.ReturnStringDate(d2.toStartOfMonth()) ;
        DealUtils.ReturnStringDate(d2.toStartOfMonth().addDays(10));
        dc.SortDealResultList() ;
        dc.RemoveDealId = deal.Id;
        dc.RemoveDealButton() ;
        dc.AddMoreToDeal() ;
        List<DoubleCheckReadOnlyHelper.HeadingModel> headList = dc.ListOfDates(d, d2);
        dc.tempSchedule.Week__c = constDate;
        dc.DealId = deal.Id;
        dc.SelectedDealMap.put(deal.Id, deal);
        dc.updatePrelogClearanceReport() ;
        dc.setPrelogClearanceReport() ;
        System.assertEquals(Date.today().toStartOfWeek().addDays(1), dc.getMonday()) ;
        System.assertEquals(Date.today().toStartOfWeek().addDays(7), dc.getSunday()) ;

        //Previous Coverage is 54%
        //New Code for increase the coverage
        Date tempDate = dc.thisMonday;
        tempDate = dc.thisSunday;

        //Method Calling
        DealUtils.formatDatetime(System.now());

        //Set controller properties
        dc.BarterCheckbox = true;
        dc.SelectedCableSynd = 'Cable';
        dc.Searchfield = ' BounceTV , ' + ', ';
        dc.SelectedDateLiteral = '';
        dc.DoSearch();

        //Wrapper instance
        DoubleCheckReadOnlyHelper.PrelogDataWrapper con2 =
                new DoubleCheckReadOnlyHelper.PrelogDataWrapper(new PrelogData__c());

        //Method Calling
        Map<String, Decimal> rteMap = new Map<String, Decimal>();
        rteMap.put('1', 10);
        rteMap.put('2', 20);
        rteMap.put('3', 30);

        //Set controller properties
        con2.rateMap = rteMap;
        con2.unitClearanceMap = rteMap;
        try {
            con2.calculateTotals();
        } catch (Exception e) {
        }
        tempDate = dc.getMonday();
    }

    @IsTest static void PrelogClearanceControllerTest2() {

        Contact con = new Contact(
                LastName = 'Test',
                Email = 'test@test.com',
                Phone = '8001234567'
        ) ;
        insert con ;

        Advertiser__c advertiser = new Advertiser__c(
                Duplicate_Approval__c = 'Approved',
                Advertiser_Approved_to_Book__c = true
        );
        insert advertiser;

        Brands__c brand = new Brands__c(
                Name = 'Availability',
                Category__c = 'Other',
                Advertiser__c = advertiser.Id,
                Approved_Duplicate__c = 'Approved'
        );
        insert brand;

        //Program
        Programs__c program = new Programs__c(
                Name = 'BounceTV',
                Cable_Synd__c = 'Cable',
                ClientCode__c = 'h1',
                Barter__c = true,
                Station_Call_Letter__c = 'a'
        );
        insert program;

        Deal__c deal = new Deal__c(
                Contact__c = con.Id,
                Brands__c = brand.Id,
                Program__c = program.Id,
                Length__c = '5'
        );
        insert deal;

        //Schedule
        Schedules__c schedule = new Schedules__c(
                Units_Available__c = 1.0,
                Units_Preempted__c = 0,
                Week__c = Date.today().toStartOfWeek().addDays(7).addDays(1),
                Deal_Parent__c = deal.Id,
                Status__c = 'Sold',
                Rate__c = 300
        );
        insert schedule;


        PrelogData__c pd = new PrelogData__c(
                Schedule__c = schedule.Id,
                AirDate__c = Date.today().addDays(7),
                Version__c = 1
        );
        insert pd;

        PrelogData__c pd1 = [
                SELECT Id,
                        AirDate__c,
                        Schedule__r.Week__c,
                        Week__c
                FROM PrelogData__c
                WHERE Id = :pd.Id
        ];
        System.debug('####' + pd1);

        PrelogClearanceController dc = new PrelogClearanceController() ;
        dc.CurrentFP = [
                SELECT Id,
                        FiscalYearSettings.Name,
                        StartDate,
                        EndDate,
                        Number,
                        PeriodLabel
                FROM Period
                WHERE Type = 'Month'
                LIMIT 1
        ];

        dc.BarterCheckbox = true;
        dc.prelogVersion = '1';
        dc.DealId = deal.Id;
        dc.tempSchedule.Week__c = Date.today().toStartOfWeek().addDays(-6);
        dc.Searchfield = 'BounceTV';
        dc.SelectedDateLiteral = null ;
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Custom' ;
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Previous FY';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Previous 2 FY';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = '2 FY Ago';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Current FY';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Current And Previous FY';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Current And Previous 2 FY';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Current FQ';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Current And Next FQ';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Current And Previous FQ';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Next FQ';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Previous FQ';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Current And Next 3 FQ';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Last FP';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'This FP';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Next FP';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Current And Previous FP';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Current And Next FP';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Last FW';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'This FW';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Next FW';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Current CY';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Previous CY';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Previous 2 CY';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = '2 CY Ago';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Next CY';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Current And Previous CY';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Current And Previous 2 CY';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Current And Next CY';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Current CQ';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Current And Next CQ';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Current And Previous CQ';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Next CQ';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Previous CQ';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Current And Next 3 CQ';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Last Month';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'This Month';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Next Month';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Current And Last Month';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Current And Next Month';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Last Week';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'This Week';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Next Week';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Yesterday';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Today';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Tomorrow';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Last 7 Days';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Last 30 Days';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Last 60 Days';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Last 90 Days';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Last 120 Days';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Next 7 Days';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Next 30 Days';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Next 60 Days';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Next 90 Days';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Next 120 Days';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Current FY';
        dc.ReturnSOQLDateString() ;
        dc.Searchfield = 'BounceTV,BounceTV' ;
        dc.DoSearch() ;
        dc.Searchfield = 'BounceTV' ;
        dc.getDealResult() ;
        dc.DealId = deal.Id;
        Date d = Date.today();
        DealUtils.ReturnStringDate(d.toStartOfMonth()) ;
        DealUtils.ReturnStringDate(d.toStartOfMonth().addDays(10));
        Date d2 = Date.newInstance(2014, 12, 1) ;
        DealUtils.ReturnStringDate(d2.toStartOfMonth()) ;
        DealUtils.ReturnStringDate(d2.toStartOfMonth().addDays(10));
        dc.SortDealResultList() ;

        dc.AddMoreToDeal() ;
        List<DoubleCheckReadOnlyHelper.HeadingModel> headList = dc.ListOfDates(d, d2);
        dc.updatePrelogClearanceReport() ;
        dc.setPrelogClearanceReport() ;
        System.assertEquals(Date.today().toStartOfWeek().addDays(1), dc.getMonday()) ;
        System.assertEquals(Date.today().toStartOfWeek().addDays(7), dc.getSunday()) ;

        //Previous Coverage is 54%
        //New Code for increase the coverage
        Date tempDate = dc.thisMonday;
        tempDate = dc.thisSunday;

        //Method Calling
        DealUtils.formatDatetime(System.now());

        //Set controller properties
        dc.BarterCheckbox = true;
        dc.SelectedCableSynd = 'Cable';
        dc.Searchfield = ' BounceTV , ' + ', ';
        dc.SelectedDateLiteral = '';
        dc.DoSearch();

        //Wrapper instance
        DoubleCheckReadOnlyHelper.PrelogDataWrapper con2 =
                new DoubleCheckReadOnlyHelper.PrelogDataWrapper(new PrelogData__c());

        //Method Calling
        Map<String, Decimal> rteMap = new Map<String, Decimal>();
        rteMap.put('1', 10);
        rteMap.put('2', 20);
        rteMap.put('3', 30);
        dc.getKeys();
        //Set controller properties
        con2.rateMap = rteMap;
        con2.unitClearanceMap = rteMap;
        try {
            con2.calculateTotals();
        } catch (Exception e) {
        }

        tempDate = dc.getMonday();
        dc.getWeekData();
        dc.FillDealResultList();
        dc.RemoveDealId = deal.Id;
        dc.RemoveDealButton() ;
    }

    @IsTest static void PrelogClearanceControllerTest3() {

        Contact con = new Contact(
                LastName = 'Test',
                Email = 'test@test.com',
                Phone = '8001234567'
        ) ;
        insert con ;

        Advertiser__c advertiser = new Advertiser__c(
                Duplicate_Approval__c = 'Approved',
                Advertiser_Approved_to_Book__c = true
        );
        insert advertiser;

        Brands__c brand = new Brands__c(
                Name = 'Availability',
                Category__c = 'Other',
                Advertiser__c = advertiser.Id,
                Approved_Duplicate__c = 'Approved'
        );
        insert brand;

        //Program
        Programs__c program = new Programs__c(
                Name = 'BounceTV',
                Cable_Synd__c = 'Cable',
                ClientCode__c = 'h1',
                Barter__c = true,
                Station_Call_Letter__c = 'a'
        );
        insert program;

        Deal__c deal = new Deal__c(
                Contact__c = con.Id,
                Brands__c = brand.Id,
                Program__c = program.Id,
                Length__c = '5'
        );
        insert deal;

        //Schedule
        Schedules__c schedule = new Schedules__c();
        schedule.Units_Available__c = 1.0;
        schedule.Units_Preempted__c = 0;
        schedule.Week__c = Date.today().addDays(7).toStartOfWeek().addDays(1);
        schedule.Deal_Parent__c = deal.Id;
        schedule.Status__c = 'Sold';
        schedule.Rate__c = 300;
        insert schedule;


        PrelogData__c pd = new PrelogData__c();
        pd.Schedule__c = schedule.Id;
        pd.AirDate__c = Date.today().addDays(7);
        pd.Version__c = 1;
        insert pd;

        PrelogClearanceController dc = new PrelogClearanceController() ;

        dc.CurrentFP = [
                SELECT Id,
                        FiscalYearSettings.Name,
                        StartDate,
                        EndDate,
                        Number,
                        PeriodLabel
                FROM Period
                WHERE Type = 'Month'
                LIMIT 1
        ];

        dc.BarterCheckbox = true;
        dc.prelogVersion = '1';
        dc.DealId = deal.Id;
        dc.tempSchedule.Week__c = Date.today().toStartOfWeek().addDays(-6);
        dc.Searchfield = 'BounceTV, BounceTV';
        dc.SelectedDateLiteral = null ;
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Custom' ;
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Previous FY';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Previous 2 FY';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = '2 FY Ago';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Current FY';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Current And Previous FY';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Current And Previous 2 FY';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Current FQ';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Current And Next FQ';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Current And Previous FQ';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Next FQ';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Previous FQ';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Current And Next 3 FQ';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Last FP';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'This FP';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Next FP';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Current And Previous FP';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Current And Next FP';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Last FW';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'This FW';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Next FW';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Current CY';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Previous CY';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Previous 2 CY';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = '2 CY Ago';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Next CY';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Current And Previous CY';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Current And Previous 2 CY';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Current And Next CY';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Current CQ';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Current And Next CQ';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Current And Previous CQ';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Next CQ';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Previous CQ';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Current And Next 3 CQ';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Last Month';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'This Month';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Next Month';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Current And Last Month';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Current And Next Month';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Last Week';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'This Week';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Next Week';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Yesterday';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Today';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Tomorrow';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Last 7 Days';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Last 30 Days';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Last 60 Days';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Last 90 Days';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Last 120 Days';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Next 7 Days';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Next 30 Days';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Next 60 Days';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Next 90 Days';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Next 120 Days';
        dc.ReturnSOQLDateString() ;
        dc.SelectedDateLiteral = 'Current FY';
        dc.ReturnSOQLDateString() ;
        dc.Searchfield = 'BounceTV,BounceTV' ;
        dc.DoSearch() ;
        dc.Searchfield = 'BounceTV' ;
        dc.getDealResult() ;
        dc.DealId = deal.Id;
        Date d = Date.today();
        DealUtils.ReturnStringDate(d.toStartOfMonth()) ;
        DealUtils.ReturnStringDate(d.toStartOfMonth().addDays(10));
        Date d2 = Date.newInstance(2014, 12, 1) ;
        DealUtils.ReturnStringDate(d2.toStartOfMonth()) ;
        DealUtils.ReturnStringDate(d2.toStartOfMonth().addDays(10));
        dc.SortDealResultList() ;

        dc.AddMoreToDeal() ;
        List<DoubleCheckReadOnlyHelper.HeadingModel> headList = dc.ListOfDates(d, d2);
        dc.updatePrelogClearanceReport() ;
        dc.setPrelogClearanceReport() ;
        System.assertEquals(Date.today().toStartOfWeek().addDays(1), dc.getMonday()) ;
        System.assertEquals(Date.today().toStartOfWeek().addDays(7), dc.getSunday()) ;

        //Previous Coverage is 54%
        //New Code for increase the coverage
        Date tempDate = dc.thisMonday;
        tempDate = dc.thisSunday;

        //Method Calling
        DealUtils.formatDatetime(System.now());

        //Set controller properties
        dc.BarterCheckbox = true;
        dc.SelectedCableSynd = 'Cable';
        dc.Searchfield = ' BounceTV,BounceTV, ' + ', ';
        dc.SelectedDateLiteral = '';
        dc.DoSearch();

        //Wrapper instance
        DoubleCheckReadOnlyHelper.PrelogDataWrapper con2 =
                new DoubleCheckReadOnlyHelper.PrelogDataWrapper(new PrelogData__c());

        //Method Calling
        Map<String, Decimal> rteMap = new Map<String, Decimal>();
        rteMap.put('1', 10);
        rteMap.put('2', 20);
        rteMap.put('3', 30);
        dc.getKeys();
        //Set controller properties
        con2.rateMap = rteMap;
        con2.unitClearanceMap = rteMap;
        try {
            con2.calculateTotals();
        } catch (Exception e) {
        }

        tempDate = dc.getMonday();
        dc.getWeekData();
        dc.FillDealResultList();
        dc.RemoveDealId = deal.Id;
        dc.RemoveDealButton() ;
    }

    @IsTest static void PrelogClearanceController_coverage() {
        PrelogClearanceController pc = new PrelogClearanceController();
        PrelogClearanceController.setDealSelector(null);
        PrelogClearanceController.setFYSSelector(null);
        PrelogClearanceController.setPeriodSelector(null);
        PrelogClearanceController.setPrelogDataSelector(null);
        PrelogClearanceController.setScheduleSelector(null);
        pc.Display();
    }
}