objects/Advertiser__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Specifies the Agency (Account) associated with the Advertiser</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Advertisers</relationshipLabel>
        <relationshipName>Advertisers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Advertiser_Approved_to_Book__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Checked = Advertiser has been approved to book by Finance 
Unchecked = Advertiser has NOT been approved to book by Finance</inlineHelpText>
        <label>Advertiser Approved to Book</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Duplicate_Approval__c</fullName>
        <description>Used to prevent duplicate advertisers from being created.</description>
        <label>Duplicate Approval</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Not Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Advertiser</label>
    <nameField>
        <label>Advertiser Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Advertisers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Brands__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Brands</relationshipLabel>
        <relationshipName>Brands</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Advertiser__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Advertiser</label>
        <referenceTo>Advertiser__c</referenceTo>
        <relationshipLabel>Brands</relationshipLabel>
        <relationshipName>Brands</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approved_Duplicate__c</fullName>
        <label>Duplicate Approval</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Not Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>.Com/E-Commerce</fullName>
                </value>
                <value>
                    <fullName>Apparel/Accessories</fullName>
                </value>
                <value>
                    <fullName>Appliances/Home Gadgets</fullName>
                </value>
                <value>
                    <fullName>Attorney/General Legal Services</fullName>
                </value>
                <value>
                    <fullName>Attorney-Medical Services/Equipments/Prescriptions</fullName>
                </value>
                <value>
                    <fullName>Auto Accessories/Parts/Repair</fullName>
                </value>
                <value>
                    <fullName>Baby</fullName>
                </value>
                <value>
                    <fullName>Beauty/Cosmetics/Hair Care</fullName>
                </value>
                <value>
                    <fullName>Business/Professional Services</fullName>
                </value>
                <value>
                    <fullName>Charity</fullName>
                </value>
                <value>
                    <fullName>Cleaning Supplies</fullName>
                </value>
                <value>
                    <fullName>Crafts/Hobbies/Sporting goods/Toys</fullName>
                </value>
                <value>
                    <fullName>Education</fullName>
                </value>
                <value>
                    <fullName>Electronics/Software</fullName>
                </value>
                <value>
                    <fullName>Entertainment/Gaming</fullName>
                </value>
                <value>
                    <fullName>Fitness/Health/Medical Equipment</fullName>
                </value>
                <value>
                    <fullName>Food and Beverages</fullName>
                </value>
                <value>
                    <fullName>Home Improvement/Furniture</fullName>
                </value>
                <value>
                    <fullName>Insurance- Auto</fullName>
                </value>
                <value>
                    <fullName>Insurance- Health/ Dental/ Disability</fullName>
                </value>
                <value>
                    <fullName>Insurance- Life</fullName>
                </value>
                <value>
                    <fullName>Media/Telecom</fullName>
                </value>
                <value>
                    <fullName>Medical Services</fullName>
                </value>
                <value>
                    <fullName>Mental Health</fullName>
                </value>
                <value>
                    <fullName>Mobile Apps</fullName>
                </value>
                <value>
                    <fullName>Office Supplies</fullName>
                </value>
                <value>
                    <fullName>Pets</fullName>
                </value>
                <value>
                    <fullName>Pharmaceuticals/Drugs</fullName>
                </value>
                <value>
                    <fullName>Social Networking/Dating</fullName>
                </value>
                <value>
                    <fullName>Toiletry</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Brands</label>
    <nameField>
        <label>Brand</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Deal__c.object
<CustomObject>
    <fields>
        <fullName>Advertiser__c</fullName>
        <formula>Brands__r.Advertiser__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Advertiser</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Brands__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Brands</label>
        <referenceTo>Brands__c</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ClientCode__c</fullName>
        <formula>Program__r.ClientCode__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ClientCode</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Type__c</field>
                <operation>notEqual</operation>
                <value>history</value>
            </filterItems>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>Do Not Call</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Program</label>
        <referenceTo>Programs__c</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Deal</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Deal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Programs__c.object
<CustomObject>
    <description>Program/Distributor</description>
    <fields>
        <fullName>Account_Exec_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Exec 1</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Assistant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assistant</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Programs3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cable_Synd__c</fullName>
        <label>Cable/Synd/PP</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cable</fullName>
                </value>
                <value>
                    <fullName>Syndication</fullName>
                </value>
                <value>
                    <fullName>PP</fullName>
                </value>
                <value>
                    <fullName>Bundle</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ClientCode__c</fullName>
        <description>Assigned by Finance</description>
        <inlineHelpText>Assigned by Finance</inlineHelpText>
        <label>ClientCode</label>
        <length>3</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Network_System_Entry__c</fullName>
        <label>Network System Entry</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Network_System_Entry</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Network_System__c</fullName>
        <label>Network System</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Network_System</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Post_Log__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Post Log</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Programs8</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Prelog__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Prelog</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Programs5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reconciled_Week__c</fullName>
        <inlineHelpText>The last fully reconciled week in Salesforce</inlineHelpText>
        <label>Reconciled Week</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Station_Call_Letter__c</fullName>
        <label>Station Call Letter</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <inlineHelpText>Blue, Red, Green, Orange</inlineHelpText>
        <label>Team</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Schedules__c.object
<CustomObject>
    <fields>
        <fullName>Week__c</fullName>
        <label>Week</label>
        <type>Date</type>
    </fields>
    <label>Schedule</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Spot_Data__c.object
<CustomObject>
    <description>Post log information for schedule</description>
    <fields>
        <fullName>Air_Date__c</fullName>
        <label>Air Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Raycom_Order_Number__c</fullName>
        <label>Order Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Spot Data</label>
    <nameField>
        <displayFormat>S-{000000}</displayFormat>
        <label>Spot Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Spot Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/Network_System.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>WO</fullName>
    </customValue>
    <customValue>
        <fullName>Broadway</fullName>
    </customValue>
    <customValue>
        <fullName>Salesforce</fullName>
    </customValue>
    <customValue>
        <fullName>Local System</fullName>
    </customValue>
    <customValue>
        <fullName>Broadview</fullName>
    </customValue>
    <masterLabel>Network System</masterLabel>
</GlobalValueSet>

globalValueSets/Network_System_Entry.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Ahmed</fullName>
    </customValue>
    <customValue>
        <fullName>Anai</fullName>
    </customValue>
    <customValue>
        <fullName>Kris</fullName>
    </customValue>
    <customValue>
        <fullName>Michael</fullName>
    </customValue>
    <customValue>
        <fullName>Brett</fullName>
    </customValue>
    <customValue>
        <fullName>Regina</fullName>
    </customValue>
    <customValue>
        <fullName>Cyre</fullName>
    </customValue>
    <customValue>
        <fullName>Client Entry</fullName>
    </customValue>
    <customValue>
        <fullName>Kara</fullName>
    </customValue>
    <customValue>
        <fullName>Jillian</fullName>
    </customValue>
    <customValue>
        <fullName>FBN Internal</fullName>
    </customValue>
    <customValue>
        <fullName>MAV Internal</fullName>
    </customValue>
    <customValue>
        <fullName>TVG Internal</fullName>
    </customValue>
    <customValue>
        <fullName>Jillian/Cornelia</fullName>
    </customValue>
    <customValue>
        <fullName>Cornelia/Jillian</fullName>
    </customValue>
    <customValue>
        <fullName>Lindsay</fullName>
    </customValue>
    <customValue>
        <fullName>Emily</fullName>
    </customValue>
    <customValue>
        <fullName>Josuel</fullName>
    </customValue>
    <customValue>
        <fullName>Cheng</fullName>
    </customValue>
    <customValue>
        <fullName>Cornelia</fullName>
    </customValue>
    <customValue>
        <fullName>Jaclyn</fullName>
    </customValue>
    <customValue>
        <fullName>Jose</fullName>
    </customValue>
    <masterLabel>Network System Entry</masterLabel>
</GlobalValueSet>

classes/AgingReportMapperTest.cls
@isTest
public class AgingReportMapperTest {
    
    @testSetup static void setup(){
        //query for test data spots 
     	List<Spot_Data__c> spotResults = [select id, air_date__c, Raycom_Order_Number__c from spot_data__c where Raycom_Order_Number__c = '100' or Raycom_Order_Number__c = '200'];

        //if no spots exist, run the createTestData method to generate all necesarry objects for spot data and related objects
        if(spotResults.size() == 0){
      		//creates 60 instances of spot data 
       		//30 with order#100, 1 for each day 03/01/2019 to 03/30/2019
       		//30 have order#200, 1 for each day 04/01/2019 to 04/30/2019
           createTestData(); 
         }
       
    }
    
     @isTest public static void testAprilSpots(){ 
        
        Date broadcastMonthStartDate = date.newInstance(2019, 04, 01);
        Date broadcastMonthEndDate = date.newInstance(2019, 04, 28);

        List<Spot_Data__c>  aprilSpots =  [
            select id, air_date__c, Raycom_Order_Number__c 
            from spot_data__c where Raycom_Order_Number__c = '200' 
            and air_date__c >= :broadcastMonthStartDate 
            and air_date__c <= :broadcastMonthEndDate 
        ];
        //check assertion
        System.assertEquals(28 , aprilSpots.size());
  
    }
    
   	public static void createTestData(){
            Profile p = [SELECT Id FROM Profile WHERE Name='Standard Platform User'];
      
            User u = new User(Alias = 'standt', Email='BrianHorowitz@mvmediasales.com', 
            EmailEncodingKey='UTF-8', LastName='exec', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='TestAugustTestUser@testorg.com');
            
            User u2 = new User(Alias = 'standt', Email='BrianHorowitz@mvmediasales.com', 
           	EmailEncodingKey='UTF-8', LastName='oper', LanguageLocaleKey='en_US', 
         	LocaleSidKey='en_US', ProfileId = p.Id, 
         	TimeZoneSidKey='America/Los_Angeles', UserName='TestAugustTestUser2@testorg.com');
              
            List<User> executives = [SELECT Id FROM User WHERE LastName = 'exec'];
            User executive = executives[0];
            
            List<User> operations = [SELECT Id FROM User WHERE LastName = 'oper'];
            User operations1 = operations[0];
            
            Account acct = new Account();
            acct.Name = 'name';
            acct.Emerald_AE__c = executive.id;
            acct.Red_AE__c = executive.id;
            acct.Onyx_AE__c = executive.id;
            acct.Pine_AE__c = executive.id;
            acct.Oak_AE__c = executive.id;
            acct.Silver_AE__c = executive.id;
            acct.Maple_AE__c = executive.id;
            acct.Yellow_AE__c = executive.id;
           
       		insert acct; 
                
        
            Programs__c program = new Programs__c();
            program.Name = 'Retro Raycom Two';
            program.Reconciled_Week__c = Date.today().adddays(-21).toStartofWeek().adddays(1);
            program.Cable_Synd__c = 'Cable';
            program.ClientCode__c = 'br7';
            program.Team__c = 'Onyx';
            program.Account_Exec_1__c = executive.id;
            program.Assistant__c = operations1.id;
            program.Network_System_Entry__c = Programs__c.Network_System_Entry__c.getDescribe().getPicklistValues()[0].getValue();
            program.Network_System__c = Programs__c.Network_System__c.getDescribe().getPicklistValues()[0].getValue();
            program.Prelog__c = operations1.id;
            program.Post_Log__c = operations1.id;          
            program.Station_Call_Letter__c = 'kt';
           
            insert program; 
        
            
            Contact con = new Contact(LastName = 'TestTesterson', Email = 'test@test154.com', Phone = '8001294567', Emerald_AE__c = executive.id, Green_AE__c = executive.id, Onyx_AE__c = executive.id, Silver_AE__c = executive.id, Maple_AE__c = executive.id, Pine_AE__c = executive.id, Oak_AE__c = executive.id, Fire_AE_Bounce__c = executive.id, Fire_AE_Escape__c = executive.id, Red_AE__c = executive.id, Fire_AE_Grit__c = executive.id, Fire_AE_Laff__c = executive.id, Yellow_AE__c = executive.id);
            insert con; 
        
        
            Advertiser__c advertiser = new Advertiser__c(Duplicate_Approval__c = 'Approved', Advertiser_Approved_to_Book__c = true, Account__c = acct.id);
            insert advertiser; 
        
            Brands__c brand = new Brands__c();
            brand.Name = 'Available';
            brand.Category__c = 'Other';
            brand.Advertiser__c = advertiser.id;
            brand.Approved_Duplicate__c = 'Approved' ;
            insert brand; 
        
            Deal__c deal = new Deal__c(Contact__c = con.Id, Brands__c = brand.Id, Program__c = program.Id, Length__c = '30', Network_Deal_Number__c = '111111');
            insert deal; 
        
        
            Schedules__c schedule4 = new Schedules__c();
              schedule4.Units_Available__c = 2.0;
              schedule4.Units_Preempted__c = 0;
              schedule4.Week__c = Date.today().adddays(-14).toStartofWeek().adddays(1);
              schedule4.Deal_Parent__c = deal.Id;
              schedule4.Status__c = 'Sold';
              schedule4.Rate__c = 1800;
              insert schedule4; 
        
			Integer counter = 1;
            Integer counter2 = 1;
            
            List<Spot_Data__c> insertData = new List<Spot_Data__c>();
            
            while(counter < 31){
                Spot_Data__c spotTest = new Spot_Data__c();
                Integer day = counter; 
                Integer month = 3;
                Integer year = 2019;
                Date myDate = Date.newInstance(year, month, day); 
                spotTest.Schedule__c = [select id from schedules__c limit 1].id;
                spotTest.air_date__c = myDate;
                spotTest.Raycom_Order_Number__c  = '100';
                insertData.add(spotTest);
                counter++;
            }
            
            while(counter2 < 31){
             Spot_Data__c spotTest = new Spot_Data__c();
             Integer day = counter2; 
             Integer month = 4;
             Integer year = 2019;
             Date myDate = Date.newInstance(year, month, day); 
             spotTest.Schedule__c = [select id from schedules__c limit 1].id;
             spotTest.air_date__c = myDate;
             spotTest.Raycom_Order_Number__c  = '200';
             insertData.add(spotTest);
             counter2++;
            }
            insert insertData;
        }
 

   
}