objects/Advertiser__c.object
<CustomObject>
    <fields>
        <fullName>Commercial__c</fullName>
        <description>END - Endemic
PSA - Public Service Announcement</description>
        <label>SF Commercial Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>DR</fullName>
                </value>
                <value>
                    <fullName>GM</fullName>
                </value>
                <value>
                    <fullName>HYBRID</fullName>
                </value>
                <value>
                    <fullName>PSA</fullName>
                </value>
                <value>
                    <fullName>END</fullName>
                </value>
                <value>
                    <fullName>PROMO</fullName>
                </value>
                <value>
                    <fullName>TUNE IN</fullName>
                </value>
                <value>
                    <fullName>--</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Advertiser</label>
    <nameField>
        <label>Advertiser Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Advertisers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Brands__c.object
<CustomObject>
    <fields>
        <fullName>Advertiser__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Advertiser</label>
        <referenceTo>Advertiser__c</referenceTo>
        <relationshipLabel>Brands</relationshipLabel>
        <relationshipName>Brands</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Brands</label>
    <nameField>
        <label>Brand</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Deal__c.object
<CustomObject>
    <label>Deal</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Deal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Prelog_Week__c.object
<CustomObject>
    <fields>
        <fullName>Commercial_Type__c</fullName>
        <label>Commercial Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>DR</fullName>
                </value>
                <value>
                    <fullName>GM</fullName>
                </value>
                <value>
                    <fullName>HYBRID</fullName>
                </value>
                <value>
                    <fullName>PSA</fullName>
                </value>
                <value>
                    <fullName>END</fullName>
                </value>
                <value>
                    <fullName>PROMO</fullName>
                </value>
                <value>
                    <fullName>TUNE IN</fullName>
                </value>
                <value>
                    <fullName>--</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Daypart__c</fullName>
        <label>Daypart</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1-EM 6-9a</fullName>
                </value>
                <value>
                    <fullName>2-DT 9a-6p</fullName>
                </value>
                <value>
                    <fullName>4-PR 6-12a</fullName>
                </value>
                <value>
                    <fullName>6-LN 12-3a</fullName>
                </value>
                <value>
                    <fullName>7-OV 3-6a</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Equiv_30_Sum__c</fullName>
        <label>Equiv :30 Sum</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Programs__c</referenceTo>
        <relationshipLabel>Prelog Weeks</relationshipLabel>
        <relationshipName>Prelog_Weeks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rate_Sum__c</fullName>
        <label>Rate Sum</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <label>Version</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Week__c</fullName>
        <label>Week</label>
        <type>Date</type>
    </fields>
    <label>Prelog Week</label>
    <nameField>
        <displayFormat>PW-{0000}</displayFormat>
        <label>Prelog Weekly Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prelog Weeks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PrelogData__c.object
<CustomObject>
    <fields>
        <fullName>Commercial_Type__c</fullName>
        <label>WO Commercial Type</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hour_of_Day__c</fullName>
        <formula>IF(LEFT( ScheduleTime__c , 2)=&quot;1:&quot;,&quot;1&quot;, 
IF(LEFT( ScheduleTime__c , 2)=&quot;2:&quot;,&quot;2&quot;, 
IF(LEFT( ScheduleTime__c , 2)=&quot;3:&quot;,&quot;3&quot;, 
IF(LEFT( ScheduleTime__c , 2)=&quot;4:&quot;,&quot;4&quot;, 
IF(LEFT( ScheduleTime__c , 2)=&quot;5:&quot;,&quot;5&quot;,
IF(LEFT( ScheduleTime__c , 2)=&quot;6:&quot;,&quot;6&quot;,
IF(LEFT( ScheduleTime__c , 2)=&quot;7:&quot;,&quot;7&quot;,
IF(LEFT( ScheduleTime__c , 2)=&quot;8:&quot;,&quot;8&quot;,
IF(LEFT( ScheduleTime__c , 2)=&quot;9:&quot;,&quot;9&quot;,
IF(LEFT( ScheduleTime__c , 2)=&quot;10&quot;,&quot;10&quot;,
IF(LEFT( ScheduleTime__c , 2)=&quot;11&quot;,&quot;11&quot;,
IF(LEFT( ScheduleTime__c , 2)=&quot;12&quot;,&quot;12&quot;,

IF(LEFT( ScheduleTime__c , 2)=&quot;01&quot;,&quot;1&quot;, 
IF(LEFT( ScheduleTime__c , 2)=&quot;02&quot;,&quot;2&quot;, 
IF(LEFT( ScheduleTime__c , 2)=&quot;03&quot;,&quot;3&quot;, 
IF(LEFT( ScheduleTime__c , 2)=&quot;04&quot;,&quot;4&quot;, 
IF(LEFT( ScheduleTime__c , 2)=&quot;05&quot;,&quot;5&quot;,
IF(LEFT( ScheduleTime__c , 2)=&quot;06&quot;,&quot;6&quot;,
IF(LEFT( ScheduleTime__c , 2)=&quot;07&quot;,&quot;7&quot;,
IF(LEFT( ScheduleTime__c , 2)=&quot;08&quot;,&quot;8&quot;,
IF(LEFT( ScheduleTime__c , 2)=&quot;09&quot;,&quot;9&quot;,

&quot;FALSE&quot;)))))))))))))))))))))

&amp;

IF( RIGHT( ScheduleTime__c ,2)=&quot;am&quot;,&quot;am&quot;, 
IF( RIGHT( ScheduleTime__c ,2)=&quot;AM&quot;,&quot;am&quot;, 
IF( RIGHT( ScheduleTime__c ,2)=&quot;pm&quot;,&quot;pm&quot;, 
IF( RIGHT( ScheduleTime__c ,2)=&quot;PM&quot;,&quot;pm&quot;, 
IF( RIGHT( ScheduleTime__c ,2)=&quot;XM&quot;,&quot;am&quot;, 
IF( RIGHT( ScheduleTime__c ,2)=&quot;xm&quot;,&quot;am&quot;, 

&quot;False&quot;))))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Hour of Day</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Prelog_Equiv_30__c</fullName>
        <formula>VALUE(ScheduleLength__c)/30</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>CASE(ScheduleLength__c, &quot;10&quot;,10, &quot;30&quot;, 30, &quot;45&quot;, 45, &quot;60&quot;, 60, &quot;75&quot;, 75, &quot;120&quot;, 120, &quot;240&quot;, 240, &quot;300&quot;, 300, &quot;15&quot;, 15, &quot;90&quot;, 90, &quot;180&quot;, 180, 0)/30</inlineHelpText>
        <label>Prelog Equiv :30</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <label>Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Schedule__c</fullName>
        <label>Schedule</label>
        <referenceTo>Schedules__c</referenceTo>
        <relationshipLabel>Prelog Data</relationshipLabel>
        <relationshipName>Prelog_Data</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <label>Version</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Week__c</fullName>
        <formula>CASE( 
MOD(  AirDate__c - DATE(1900, 1, 7), 7), 
0, AirDate__c - 6, 
1, AirDate__c , 
2, AirDate__c -1, 
3, AirDate__c - 2, 
4,AirDate__c - 3, 
5, AirDate__c - 4, 
6, AirDate__c - 5, DATE(2001, 1, 1))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Week</label>
        <type>Date</type>
    </fields>
    <label>Prelog Data</label>
    <nameField>
        <displayFormat>Pre-{0000000}</displayFormat>
        <label>Prelog Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prelog Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Programs__c.object
<CustomObject>
    <description>Program/Distributor</description>
    <label>Program</label>
    <nameField>
        <label>Program</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Schedules__c.object
<CustomObject>
    <fields>
        <fullName>Daypart__c</fullName>
        <formula>IF(OR(LEFT(TEXT(MGM_HD_Daypart__c), 2) = &quot;DA&quot;, LEFT(TEXT(MGM_HD_Daypart__c), 2) = &quot;EM&quot;, LEFT(TEXT(MGM_HD_Daypart__c), 2) = &quot;ON&quot;, LEFT(TEXT(MGM_HD_Daypart__c), 2) = &quot;PR&quot;, LEFT(TEXT(MGM_HD_Daypart__c), 2) = &quot;LN&quot;, LEFT(TEXT(MGM_HD_Daypart__c), 2) = &quot;EF&quot;, LEFT(TEXT(MGM_HD_Daypart__c), 2) = &quot;LF&quot;),LEFT(TEXT(MGM_HD_Daypart__c), 2), CASE( MGM_HD_Daypart__c, 

&quot;9A-6P – Day&quot;,&quot;DA&quot;, 
&quot;Day Live Game&quot;,&quot;DA&quot;, 
&quot;6P-12A – PR&quot;,&quot;PR&quot;, 
&quot;Prime Live Game&quot;,&quot;PR&quot;, 
&quot;JC - MS 7p-12a&quot;,&quot;PR&quot;, 
&quot;6A-9A – EM&quot;,&quot;EM&quot;, 
&quot;3A-6A -- ON&quot;,&quot;ON&quot;, 
&quot;JC - MS 12a-5a&quot;,&quot;ON&quot;, 
&quot;12A-3A -- LN&quot;,&quot;LN&quot;, 
&quot;SS 9a-4p&quot;,&quot;DA&quot;, 
&quot;MS 12a-2a&quot;,&quot;WC&quot;,
&quot;MS 2a-6a&quot;,&quot;ON&quot;, 
&quot;MS 1p-6p&quot;,&quot;DA&quot;, 
&quot;WC - MS 12a-2a&quot;,&quot;WC&quot;, 
&quot;Matinee Game MS&quot;,&quot;DA&quot;, 
&quot;Prime Game MS&quot;,&quot;PR&quot;, 
&quot;MS 7p-12a&quot;,&quot;PR&quot;, 
&quot;ROS-&quot;,&quot;ROS-&quot;, 
&quot;&quot;) 
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Daypart</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Deal_Parent__c</fullName>
        <label>Deal Parent</label>
        <referenceTo>Deal__c</referenceTo>
        <relationshipLabel>Schedules</relationshipLabel>
        <relationshipName>Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <label>Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Week__c</fullName>
        <label>Week</label>
        <type>Date</type>
    </fields>
    <label>Schedule</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/PrelogWeekBatch.cls
public class PrelogWeekBatch implements Database.Batchable<SObject>, Database.Stateful, Schedulable {

    private static final Integer maxProgramsPerBatch = 5;

    private Date weekStartDate;
    private Date weekEndDate;
    private Date endDate;

    private List<Programs__c> networks;
    private List<Programs__c> remainingNetworks;
    private Set<String> programIds;
    private Map<Prelog_Week__c, Prelog_Week__c> prelogWeekMap = new Map<Prelog_Week__c, Prelog_Week__c>();

    public PrelogWeekBatch(Date startDate, Date endDate, List<Programs__c> networks) {
        this(startDate, endDate, networks, new List<Programs__c>(networks));
    }

    public PrelogWeekBatch(Date startDate, Date endDate, List<Programs__c> networks, List<Programs__c> remainingNetworks) {
        this.weekStartDate = startDate;
        this.weekEndDate = this.weekStartDate.addDays(6);
        this.endDate = endDate;
        this.networks = networks;
        this.remainingNetworks = remainingNetworks;
    }

    public Database.QueryLocator start(Database.BatchableContext bc) {
        programIds = new Set<String>();
        for (Integer i = 0; i < maxProgramsPerBatch; i++) {
            if (remainingNetworks.isEmpty()) break;

            programIds.add(remainingNetworks.remove(0).Id);
        }

        String query = 'SELECT Id, Rate__c, Prelog_Equiv_30__c, Version__c, Schedule__r.Week__c, Hour_of_Day__c, ' +
                'Schedule__r.Deal_Parent__r.Program__c, Schedule__r.Deal_Parent__r.Program__r.Name, ' +
                'Schedule__r.Deal_Parent__r.Brands__c, Schedule__r.Deal_Parent__r.Brands__r.Advertiser__c, ' +
                'Schedule__r.Deal_Parent__r.Brands__r.Advertiser__r.Commercial__c';
        query += ' FROM PrelogData__c';
        query += ' WHERE Schedule__r.Deal_Parent__r.Program__c IN :programIds';
        query += ' AND Schedule__r.Week__c >= :weekStartDate AND Schedule__r.Week__c <= :weekEndDate';
        query += ' AND Schedule__r.Deal_Parent__r.Brands__r.Name != \'long form\'';
        query += ' AND Version__c = 6';

        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext bc, List<PrelogData__c> records) {
        for(PrelogData__c record : records) {
            Prelog_Week__c key = initializePrelogWeek(record);
            if (key == null) continue;

            Prelog_Week__c prelogWeek = prelogWeekMap.get(key);
            prelogWeek.Rate_Sum__c += record.Rate__c;
            prelogWeek.Equiv_30_Sum__c += record.Prelog_Equiv_30__c;
        }
    }

    public void finish(Database.BatchableContext bc) {
        checkForDuplicates();
        upsert prelogWeekMap.values();

        if (!remainingNetworks.isEmpty()) {
            // Reschedule Batch using remaining programs
            PrelogWeekBatch batch = new PrelogWeekBatch(this.weekStartDate, this.endDate, this.networks, this.remainingNetworks);
            if (!Test.isRunningTest()) {
                Database.executeBatch(batch, 200);
            }
        }
        else if (this.weekEndDate < this.endDate) {
            // Reschedule Batch using next week
            Date nextWeekStartDate = weekStartDate.addDays(7);
            PrelogWeekBatch batch = new PrelogWeekBatch(nextWeekStartDate, this.endDate, this.networks);
            if (!Test.isRunningTest()) {
                Database.executeBatch(batch, 200);
            }
        }
    }

    private Prelog_Week__c initializePrelogWeek(PrelogData__c prelogData) {
        Prelog_Week__c key = PrelogWeekBatchService.newPrelogWeekKey(prelogData, this.weekStartDate);
        if (key == null || key.Program__c == null) return null;

        if (!prelogWeekMap.containsKey(key)) {
            prelogWeekMap.put(key, new Prelog_Week__c(
                Program__c = key.Program__c,
                Commercial_Type__c = key.Commercial_Type__c,
                Week__c = this.weekStartDate,
                Daypart__c = key.Daypart__c,
                Version__c = key.Version__c,
                Rate_Sum__c = 0,
                Equiv_30_Sum__c = 0
            ));
        }

        return key;
    }

    private void checkForDuplicates() {
        List<Prelog_Week__c> prelogWeeks = PrelogWeekBatchService.getAllPrelogWeeksByProgram(this.programIds, this.weekStartDate);
        for(Prelog_Week__c prelogWeek : prelogWeeks) {
            Prelog_Week__c value = prelogWeekMap.get(PrelogWeekBatchService.newPrelogWeekKey(prelogWeek));
            if (value != null) {
                value.Id = prelogWeek.Id;
            }
        }
    }

    public static void run(Date startDate, Date endDate, Set<String> programIds) {
        List<Programs__c> programs = PrelogWeekBatchService.getPrograms(programIds);
        PrelogWeekBatch batch = new PrelogWeekBatch(startDate, endDate, programs);
        Database.executeBatch(batch, 200);
    }

    public static void run(Date startDate, Date endDate) {
        List<Programs__c> programs = PrelogWeekBatchService.getPrograms();
        PrelogWeekBatch batch = new PrelogWeekBatch(startDate, endDate, programs);
        Database.executeBatch(batch, 200);
    }

    public static void execute(SchedulableContext param1) {
        Date thisMonday = Date.today().toStartOfWeek().addDays(1);
        run(thisMonday, thisMonday.addDays(6));
    }
}