objects/Advertiser__c.object
<CustomObject>
    <fields>
        <fullName>Duplicate_Approval__c</fullName>
        <description>Used to prevent duplicate advertisers from being created.</description>
        <label>Duplicate Approval</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Not Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Advertiser</label>
    <nameField>
        <label>Advertiser Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Advertisers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Brands__c.object
<CustomObject>
    <fields>
        <fullName>Advertiser__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Advertiser</label>
        <referenceTo>Advertiser__c</referenceTo>
        <relationshipLabel>Brands</relationshipLabel>
        <relationshipName>Brands</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approved_Duplicate__c</fullName>
        <label>Duplicate Approval</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Not Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>.Com/E-Commerce</fullName>
                </value>
                <value>
                    <fullName>Apparel/Accessories</fullName>
                </value>
                <value>
                    <fullName>Appliances/Home Gadgets</fullName>
                </value>
                <value>
                    <fullName>Attorney/General Legal Services</fullName>
                </value>
                <value>
                    <fullName>Attorney-Medical Services/Equipments/Prescriptions</fullName>
                </value>
                <value>
                    <fullName>Auto Accessories/Parts/Repair</fullName>
                </value>
                <value>
                    <fullName>Baby</fullName>
                </value>
                <value>
                    <fullName>Beauty/Cosmetics/Hair Care</fullName>
                </value>
                <value>
                    <fullName>Business/Professional Services</fullName>
                </value>
                <value>
                    <fullName>Charity</fullName>
                </value>
                <value>
                    <fullName>Cleaning Supplies</fullName>
                </value>
                <value>
                    <fullName>Crafts/Hobbies/Sporting goods/Toys</fullName>
                </value>
                <value>
                    <fullName>Education</fullName>
                </value>
                <value>
                    <fullName>Electronics/Software</fullName>
                </value>
                <value>
                    <fullName>Entertainment/Gaming</fullName>
                </value>
                <value>
                    <fullName>Fitness/Health/Medical Equipment</fullName>
                </value>
                <value>
                    <fullName>Food and Beverages</fullName>
                </value>
                <value>
                    <fullName>Home Improvement/Furniture</fullName>
                </value>
                <value>
                    <fullName>Insurance- Auto</fullName>
                </value>
                <value>
                    <fullName>Insurance- Health/ Dental/ Disability</fullName>
                </value>
                <value>
                    <fullName>Insurance- Life</fullName>
                </value>
                <value>
                    <fullName>Media/Telecom</fullName>
                </value>
                <value>
                    <fullName>Medical Services</fullName>
                </value>
                <value>
                    <fullName>Mental Health</fullName>
                </value>
                <value>
                    <fullName>Mobile Apps</fullName>
                </value>
                <value>
                    <fullName>Office Supplies</fullName>
                </value>
                <value>
                    <fullName>Pets</fullName>
                </value>
                <value>
                    <fullName>Pharmaceuticals/Drugs</fullName>
                </value>
                <value>
                    <fullName>Social Networking/Dating</fullName>
                </value>
                <value>
                    <fullName>Toiletry</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Brands</label>
    <nameField>
        <label>Brand</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Deal__c.object
<CustomObject>
    <fields>
        <fullName>Advertiser__c</fullName>
        <formula>Brands__r.Advertiser__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Advertiser</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Brands__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Brands</label>
        <referenceTo>Brands__c</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ClientCode__c</fullName>
        <formula>Program__r.ClientCode__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ClientCode</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Type__c</field>
                <operation>notEqual</operation>
                <value>history</value>
            </filterItems>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>Do Not Call</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Length__c</fullName>
        <label>Length</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>30</fullName>
                    <color>#0B6FCE</color>
                    <label>30</label>
                </value>
                <value>
                    <fullName>60</fullName>
                    <color>#78C953</color>
                    <label>60</label>
                </value>
                <value>
                    <fullName>120</fullName>
                    <color>#E27001</color>
                    <label>120</label>
                </value>
                <value>
                    <fullName>300</fullName>
                    <color>#A845DC</color>
                    <label>300</label>
                </value>
                <value>
                    <fullName>15</fullName>
                    <color>#F3D904</color>
                    <label>15</label>
                </value>
                <value>
                    <fullName>1710</fullName>
                    <color>#A53711</color>
                    <label>1710</label>
                </value>
                <value>
                    <fullName>90</fullName>
                    <color>#66E9BD</color>
                    <label>90</label>
                </value>
                <value>
                    <fullName>180</fullName>
                    <color>#0B24BE</color>
                    <label>180</label>
                </value>
                <value>
                    <fullName>240</fullName>
                    <color>#419249</color>
                    <label>240</label>
                </value>
                <value>
                    <fullName>45</fullName>
                </value>
                <value>
                    <fullName>75</fullName>
                </value>
                <value>
                    <fullName>05</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>150</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>105</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>35</fullName>
                </value>
                <value>
                    <fullName>40</fullName>
                </value>
                <value>
                    <fullName>1714</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Network_Deal_Number__c</fullName>
        <description>Deal number in Network&apos;s paper work, in Network&apos;s records.</description>
        <externalId>true</externalId>
        <inlineHelpText>Deal number in Network&apos;s paper work, in Network&apos;s records.  Equals 1 if the PI campaign is no longer airing on the network.</inlineHelpText>
        <label>Network Deal Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Program</label>
        <referenceTo>Programs__c</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Deal</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Deal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Programs__c.object
<CustomObject>
    <description>Program/Distributor</description>
    <fields>
        <fullName>ClientCode__c</fullName>
        <description>Assigned by Finance</description>
        <inlineHelpText>Assigned by Finance</inlineHelpText>
        <label>ClientCode</label>
        <length>3</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Schedules__c.object
<CustomObject>
    <fields>
        <fullName>Deal_Parent__c</fullName>
        <label>Deal Parent</label>
        <referenceTo>Deal__c</referenceTo>
        <relationshipLabel>Schedules</relationshipLabel>
        <relationshipName>Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Network_Deal_Number__c</fullName>
        <formula>Deal_Parent__r.Network_Deal_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Network Deal Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Units_Available__c</fullName>
        <label>Units Available</label>
        <precision>17</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X800_Number__c</fullName>
        <description>800 Number for Spot</description>
        <label>800 Number</label>
        <type>Phone</type>
    </fields>
    <label>Schedule</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SpotDataMirror__c.object
<CustomObject>
    <fields>
        <fullName>Length__c</fullName>
        <label>Length</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>30</fullName>
                </value>
                <value>
                    <fullName>45</fullName>
                </value>
                <value>
                    <fullName>60</fullName>
                </value>
                <value>
                    <fullName>90</fullName>
                </value>
                <value>
                    <fullName>120</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>75</fullName>
                </value>
                <value>
                    <fullName>180</fullName>
                </value>
                <value>
                    <fullName>300</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Network_Deal_Number__c</fullName>
        <label>Network Deal Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Spot Data Mirror</label>
    <nameField>
        <label>Spot Data Mirror Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Spot Data Mirrors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestSpotDataServices.cls
@isTest
private class TestSpotDataServices
{
    /*
    static testMethod void validateScheduleOnSDM()
    {
        
        Test.startTest();
        Programs__c prg = new Programs__c(Name = 'Tennis Channel', ClientCode__c = 'TC1');
        insert prg; 
        
        Account act = new Account (name='test Act');
        insert act;
        
        Contact con = new Contact(LastName='TestCon',AccountId=act.id);
        insert con;

        Advertiser__c advertiser = new Advertiser__c(Duplicate_Approval__c = 'Approved');
        insert advertiser;
         
        Brands__c brand = new Brands__c();
        brand.Name = 'Availability';
        brand.Category__c = 'Other';
        brand.Advertiser__c = advertiser.id;
        brand.Approved_Duplicate__c = 'Approved' ;
        insert brand;
        
        Deal__c deal= new Deal__c(Length__c='120',Program__c = prg.id, Contact__c = con.id,Network_Deal_Number__c ='1420', Brands__c = brand.Id);
        insert deal;
   
        list<Schedules__c> schlist = new list<Schedules__c>();
        for(Integer i = 0 ; i<10; i++){
            Schedules__c sch = new Schedules__c(Deal_Parent__c=deal.id,X800_Number__c= '9658969856',Units_Available__c= 4.0, Rate__c= 60+i,Start_Time__c='09:00A',End_Time__c='05:00P',Days_Allowed__c = 'Mon; Tue; Wed; Thu; Fri; Sat; Sun', Week__c=date.newinstance(2013, 6, 10),Status__c='Sold');
            schlist.add(sch); 
        }
        for(Integer i = 0 ; i<10; i++){
            Schedules__c sch = new Schedules__c(Deal_Parent__c=deal.id,X800_Number__c= '9658969856',Units_Available__c= 5.0,Rate__c= 60+i,Start_Time__c='09:00A',End_Time__c='05:00P',Days_Allowed__c = 'Wed;',Week__c=date.newinstance(2013, 6, 3),Status__c='Sold');
            schlist.add(sch); 
        }
        
        insert schlist;

        List< SpotDataMirror__c> sdms = new List< SpotDataMirror__c>();
        SpotDataMirror__c sdm2 = new SpotDataMirror__c(Name = 'test1', Air_Date__c = date.newinstance(2013, 6, 10), 
        Air_Time__c = '12:04:32 PM', Length__c = '120', Network_Deal_Number__C = '1420', SPOT_RATE__C = 60, 
        NETWORK__C = 'Tennis Channel');
        sdms.add(sdm2);
        
        SpotDataMirror__c sdm3 = new SpotDataMirror__c(Name = 'test1', Air_Date__c = date.newinstance(2013, 6, 3), 
        Air_Time__c = '3:04:32 AM', Network_Deal_Number__C = '14201', SPOT_RATE__C = 60, 
        NETWORK__C = 'Cricket Channel');
        sdms.add(sdm3);
        
        SpotDataMirror__c sdm4 = new SpotDataMirror__c(Name = 'test1', Air_Date__c = date.newinstance(2013, 6, 3), 
        Air_Time__c = '3:04:32 P', Network_Deal_Number__C = '14201', SPOT_RATE__C = 60, 
        NETWORK__C = 'Cricket Channel');
        sdms.add(sdm4);

        /*SpotDataMirror__c sdm3 = new SpotDataMirror__c(Name = 'SDM1', Air_Date__c = date.newinstance(2012, 2, 19),
         Air_Time__c = '11:27:25 AM',Network_Deal_Number__C = '377659', SPOT_RATE__C = 20, 
         NETWORK__C = 'Tennis Channel');
       
        
         SpotDataMirror__c sdm4 = new SpotDataMirror__c(Name = 'test1', Air_Date__c = date.newinstance(2013, 2, 17), 
        Air_Time__c = '10:27:25 AM', Length__c = '60', Network_Deal_Number__C = '1444', SPOT_RATE__C = 60, 
        NETWORK__C = 'Cricket Channel');
      

        SpotDataMirror__c sdm5 = new SpotDataMirror__c(Name = 'SDM1', Air_Date__c = date.newinstance(2012, 2, 19),
         Air_Time__c = '11:27:25 PM',Network_Deal_Number__C = '98745965588', SPOT_RATE__C = 20, 
         NETWORK__C = 'Tennis Channel');

        SpotDataMirror__c sdm6 = new SpotDataMirror__c(Name = 'test1', Air_Date__c = date.newinstance(2013, 2, 18), 
        Air_Time__c = '11:27:25 AM', Length__c = '20', Network_Deal_Number__C = '98745965588', SPOT_RATE__C = 60, 
        NETWORK__C = 'Cricket Channel');
      
        sdms.add(sdm);
        sdms.add(sdm2);
        sdms.add(sdm3);
        sdms.add(sdm4);
        sdms.add(sdm5);
        sdms.add(sdm6);*//*
        insert sdms;
        Test.stopTest();

        List<SpotDataMirror__c> spotdatamirrorrecords=[select  Name ,Air_Date__c ,Air_Time__c ,Network_Deal_Number__C ,SPOT_RATE__C,NETWORK__C  from  SpotDataMirror__c];
        
        List<SpotDataMirror__c> updatespotdatamirrorrecords=new List<SpotDataMirror__c>();
        for(SpotDataMirror__c s:spotdatamirrorrecords)
        {
        s.Length__c = '120';
        updatespotdatamirrorrecords.add(s);
        }
        update updatespotdatamirrorrecords;
        
        
        
        List<SpotDataMirror__c> spotdatamirrorrecords1=[select  Name ,Air_Date__c ,Air_Time__c ,Network_Deal_Number__C ,SPOT_RATE__C,NETWORK__C  from  SpotDataMirror__c];
        
        List<SpotDataMirror__c> updatespotdatamirrorrecords1=new List<SpotDataMirror__c>();
        for(SpotDataMirror__c s:spotdatamirrorrecords1)
        {
        s.Length__c = '120';
        s.NETWORK__C = 'BounceTV';
        updatespotdatamirrorrecords1.add(s);
        }
        update updatespotdatamirrorrecords1;
    }
    
    static testMethod void validateScheduleOnSDM1()
    {
        
        Test.startTest();
        Programs__c prg = new Programs__c(Name = 'Tennis Channel', ClientCode__c = 'TC1');
        insert prg; 
        
        Account act = new Account (name='test Act');
        insert act;
        
        Contact con = new Contact(LastName='TestCon',AccountId=act.id);
        insert con;

        Advertiser__c advertiser = new Advertiser__c(Duplicate_Approval__c = 'Approved');
        insert advertiser;
         
        Brands__c brand = new Brands__c();
        brand.Name = 'Availability';
        brand.Category__c = 'Other';
        brand.Advertiser__c = advertiser.id;
        brand.Approved_Duplicate__c = 'Approved' ;
        insert brand;
        
        Deal__c deal= new Deal__c(Length__c='120',Program__c = prg.id, Contact__c = con.id,Network_Deal_Number__c ='1420', Brands__c = brand.Id);
        insert deal;
   
        list<Schedules__c> schlist = new list<Schedules__c>();

        for(Integer i = 0 ; i<10; i++){
            Schedules__c sch = new Schedules__c(Deal_Parent__c=deal.id,X800_Number__c= '9658969856',Units_Available__c= 5.0,Rate__c= 60+i,Start_Time__c='09:00A',End_Time__c='05:00P',Days_Allowed__c = 'Wed;',Week__c=date.newinstance(2013, 6, 3),Status__c='Sold');
            schlist.add(sch); 
        }
        
        insert schlist;

        List< SpotDataMirror__c> sdms = new List< SpotDataMirror__c>();
        SpotDataMirror__c sdm2 = new SpotDataMirror__c(Name = 'test1', Air_Date__c = date.newinstance(2013, 6, 10), 
        Air_Time__c = '6:04:32 PM', Length__c = '120', Network_Deal_Number__C = '1420', SPOT_RATE__C = 60, 
        NETWORK__C = 'Tennis Channel');
       sdms.add(sdm2);
        
        SpotDataMirror__c sdm3 = new SpotDataMirror__c(Name = 'test1', Air_Date__c = date.newinstance(2013, 6, 3), 
        Air_Time__c = '3:04:32 AM', Network_Deal_Number__C = '14201', SPOT_RATE__C = 60, 
        NETWORK__C = 'Cricket Channel');

        /*SpotDataMirror__c sdm3 = new SpotDataMirror__c(Name = 'SDM1', Air_Date__c = date.newinstance(2012, 2, 19),
         Air_Time__c = '11:27:25 AM',Network_Deal_Number__C = '377659', SPOT_RATE__C = 20, 
         NETWORK__C = 'Tennis Channel');
       
        
         SpotDataMirror__c sdm4 = new SpotDataMirror__c(Name = 'test1', Air_Date__c = date.newinstance(2013, 2, 17), 
        Air_Time__c = '10:27:25 AM', Length__c = '60', Network_Deal_Number__C = '1444', SPOT_RATE__C = 60, 
        NETWORK__C = 'Cricket Channel');
      

        SpotDataMirror__c sdm5 = new SpotDataMirror__c(Name = 'SDM1', Air_Date__c = date.newinstance(2012, 2, 19),
         Air_Time__c = '11:27:25 PM',Network_Deal_Number__C = '98745965588', SPOT_RATE__C = 20, 
         NETWORK__C = 'Tennis Channel');

        SpotDataMirror__c sdm6 = new SpotDataMirror__c(Name = 'test1', Air_Date__c = date.newinstance(2013, 2, 18), 
        Air_Time__c = '11:27:25 AM', Length__c = '20', Network_Deal_Number__C = '98745965588', SPOT_RATE__C = 60, 
        NETWORK__C = 'Cricket Channel');
      
        sdms.add(sdm);
        sdms.add(sdm2);
        sdms.add(sdm3);
        sdms.add(sdm4);
        sdms.add(sdm5);
        sdms.add(sdm6);*//*
        insert sdms;
        Test.stopTest();

    List<SpotDataMirror__c> spotdatamirrorrecords=[select  Name ,Air_Date__c ,Air_Time__c ,Network_Deal_Number__C ,SPOT_RATE__C,NETWORK__C  from  SpotDataMirror__c];
    
    List<SpotDataMirror__c> updatespotdatamirrorrecords=new List<SpotDataMirror__c>();
    for(SpotDataMirror__c s:spotdatamirrorrecords)
    {
    s.Length__c = '120';
    updatespotdatamirrorrecords.add(s);
    }
    update updatespotdatamirrorrecords;
    
    
    
    List<SpotDataMirror__c> spotdatamirrorrecords1=[select  Name ,Air_Date__c ,Air_Time__c ,Network_Deal_Number__C ,SPOT_RATE__C,NETWORK__C  from  SpotDataMirror__c];
    
    List<SpotDataMirror__c> updatespotdatamirrorrecords1=new List<SpotDataMirror__c>();
    for(SpotDataMirror__c s:spotdatamirrorrecords1)
    {
    s.Length__c = '120';
    s.NETWORK__C = 'BounceTV';
    updatespotdatamirrorrecords1.add(s);
    }
    update updatespotdatamirrorrecords1;
    
    
    }
    */
}