objects/Advertiser__c.object
<CustomObject>
    <fields>
        <fullName>Advertiser_Approved_to_Book__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Checked = Advertiser has been approved to book by Finance 
Unchecked = Advertiser has NOT been approved to book by Finance</inlineHelpText>
        <label>Advertiser Approved to Book</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Duplicate_Approval__c</fullName>
        <description>Used to prevent duplicate advertisers from being created.</description>
        <label>Duplicate Approval</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Not Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Advertiser</label>
    <nameField>
        <label>Advertiser Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Advertisers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Brands__c.object
<CustomObject>
    <fields>
        <fullName>Advertiser__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Advertiser</label>
        <referenceTo>Advertiser__c</referenceTo>
        <relationshipLabel>Brands</relationshipLabel>
        <relationshipName>Brands</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Brands</label>
    <nameField>
        <label>Brand</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Deal__c.object
<CustomObject>
    <fields>
        <fullName>Advertiser__c</fullName>
        <formula>Brands__r.Advertiser__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Advertiser</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ClientCode__c</fullName>
        <formula>Program__r.ClientCode__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ClientCode</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Commercial_Type__c</fullName>
        <description>Pulls the Commercial Type in from the Advertiser.</description>
        <formula>TEXT(Brands__r.Advertiser__r.Commercial__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>HYBRID or DR, based on Advertiser.</inlineHelpText>
        <label>Commercial Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Program</label>
        <referenceTo>Programs__c</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Deal</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Deal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Prelog_Week__c.object
<CustomObject>
    <fields>
        <fullName>Commercial_Type__c</fullName>
        <label>Commercial Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>DR</fullName>
                </value>
                <value>
                    <fullName>GM</fullName>
                </value>
                <value>
                    <fullName>HYBRID</fullName>
                </value>
                <value>
                    <fullName>PSA</fullName>
                </value>
                <value>
                    <fullName>END</fullName>
                </value>
                <value>
                    <fullName>PROMO</fullName>
                </value>
                <value>
                    <fullName>TUNE IN</fullName>
                </value>
                <value>
                    <fullName>--</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Daypart__c</fullName>
        <label>Daypart</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1-EM 6-9a</fullName>
                </value>
                <value>
                    <fullName>2-DT 9a-6p</fullName>
                </value>
                <value>
                    <fullName>4-PR 6-12a</fullName>
                </value>
                <value>
                    <fullName>6-LN 12-3a</fullName>
                </value>
                <value>
                    <fullName>7-OV 3-6a</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Equiv_30_Sum__c</fullName>
        <label>Equiv :30 Sum</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Programs__c</referenceTo>
        <relationshipLabel>Prelog Weeks</relationshipLabel>
        <relationshipName>Prelog_Weeks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rate_Sum__c</fullName>
        <label>Rate Sum</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <label>Version</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Week__c</fullName>
        <label>Week</label>
        <type>Date</type>
    </fields>
    <label>Prelog Week</label>
    <nameField>
        <displayFormat>PW-{0000}</displayFormat>
        <label>Prelog Weekly Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prelog Weeks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PrelogData__c.object
<CustomObject>
    <fields>
        <fullName>Commercial_Type__c</fullName>
        <label>WO Commercial Type</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <label>Version</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Week__c</fullName>
        <formula>CASE( 
MOD(  AirDate__c - DATE(1900, 1, 7), 7), 
0, AirDate__c - 6, 
1, AirDate__c , 
2, AirDate__c -1, 
3, AirDate__c - 2, 
4,AirDate__c - 3, 
5, AirDate__c - 4, 
6, AirDate__c - 5, DATE(2001, 1, 1))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Week</label>
        <type>Date</type>
    </fields>
    <label>Prelog Data</label>
    <nameField>
        <displayFormat>Pre-{0000000}</displayFormat>
        <label>Prelog Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prelog Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Programs__c.object
<CustomObject>
    <description>Program/Distributor</description>
    <fields>
        <fullName>Cable_Synd__c</fullName>
        <label>Cable/Synd/PP</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cable</fullName>
                </value>
                <value>
                    <fullName>Syndication</fullName>
                </value>
                <value>
                    <fullName>PP</fullName>
                </value>
                <value>
                    <fullName>Bundle</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ClientCode__c</fullName>
        <description>Assigned by Finance</description>
        <inlineHelpText>Assigned by Finance</inlineHelpText>
        <label>ClientCode</label>
        <length>3</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Clock_Start_Time__c</fullName>
        <label>Clock Start Time</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>5AM</fullName>
                </value>
                <value>
                    <fullName>6AM</fullName>
                </value>
                <value>
                    <fullName>4AM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Station_Call_Letter__c</fullName>
        <label>Station Call Letter</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Schedules__c.object
<CustomObject>
    <fields>
        <fullName>Daypart__c</fullName>
        <formula>IF(OR(LEFT(TEXT(MGM_HD_Daypart__c), 2) = &quot;DA&quot;, LEFT(TEXT(MGM_HD_Daypart__c), 2) = &quot;EM&quot;, LEFT(TEXT(MGM_HD_Daypart__c), 2) = &quot;ON&quot;, LEFT(TEXT(MGM_HD_Daypart__c), 2) = &quot;PR&quot;, LEFT(TEXT(MGM_HD_Daypart__c), 2) = &quot;LN&quot;, LEFT(TEXT(MGM_HD_Daypart__c), 2) = &quot;EF&quot;, LEFT(TEXT(MGM_HD_Daypart__c), 2) = &quot;LF&quot;),LEFT(TEXT(MGM_HD_Daypart__c), 2), CASE( MGM_HD_Daypart__c, 

&quot;9A-6P – Day&quot;,&quot;DA&quot;, 
&quot;Day Live Game&quot;,&quot;DA&quot;, 
&quot;6P-12A – PR&quot;,&quot;PR&quot;, 
&quot;Prime Live Game&quot;,&quot;PR&quot;, 
&quot;JC - MS 7p-12a&quot;,&quot;PR&quot;, 
&quot;6A-9A – EM&quot;,&quot;EM&quot;, 
&quot;3A-6A -- ON&quot;,&quot;ON&quot;, 
&quot;JC - MS 12a-5a&quot;,&quot;ON&quot;, 
&quot;12A-3A -- LN&quot;,&quot;LN&quot;, 
&quot;SS 9a-4p&quot;,&quot;DA&quot;, 
&quot;MS 12a-2a&quot;,&quot;WC&quot;,
&quot;MS 2a-6a&quot;,&quot;ON&quot;, 
&quot;MS 1p-6p&quot;,&quot;DA&quot;, 
&quot;WC - MS 12a-2a&quot;,&quot;WC&quot;, 
&quot;Matinee Game MS&quot;,&quot;DA&quot;, 
&quot;Prime Game MS&quot;,&quot;PR&quot;, 
&quot;MS 7p-12a&quot;,&quot;PR&quot;, 
&quot;ROS-&quot;,&quot;ROS-&quot;, 
&quot;&quot;) 
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Daypart</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <label>Start Time</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>MGM_HD_Daypart__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>01:00A</fullName>
                </value>
                <value>
                    <fullName>01:30A</fullName>
                </value>
                <value>
                    <fullName>02:00A</fullName>
                </value>
                <value>
                    <fullName>02:30A</fullName>
                </value>
                <value>
                    <fullName>03:00A</fullName>
                </value>
                <value>
                    <fullName>03:30A</fullName>
                </value>
                <value>
                    <fullName>04:00A</fullName>
                </value>
                <value>
                    <fullName>04:30A</fullName>
                </value>
                <value>
                    <fullName>05:00A</fullName>
                </value>
                <value>
                    <fullName>05:30A</fullName>
                </value>
                <value>
                    <fullName>06:00A</fullName>
                    <default>true</default>
                    <label>06:00A</label>
                </value>
                <value>
                    <fullName>06:30A</fullName>
                </value>
                <value>
                    <fullName>07:00A</fullName>
                </value>
                <value>
                    <fullName>07:30A</fullName>
                </value>
                <value>
                    <fullName>08:00A</fullName>
                </value>
                <value>
                    <fullName>08:30A</fullName>
                </value>
                <value>
                    <fullName>09:00A</fullName>
                </value>
                <value>
                    <fullName>09:30A</fullName>
                </value>
                <value>
                    <fullName>10:00A</fullName>
                </value>
                <value>
                    <fullName>10:30A</fullName>
                </value>
                <value>
                    <fullName>11:00A</fullName>
                </value>
                <value>
                    <fullName>11:30A</fullName>
                </value>
                <value>
                    <fullName>12:00P</fullName>
                </value>
                <value>
                    <fullName>12:30P</fullName>
                </value>
                <value>
                    <fullName>01:00P</fullName>
                </value>
                <value>
                    <fullName>01:30P</fullName>
                </value>
                <value>
                    <fullName>02:00P</fullName>
                </value>
                <value>
                    <fullName>02:30P</fullName>
                </value>
                <value>
                    <fullName>03:00P</fullName>
                </value>
                <value>
                    <fullName>03:30P</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Week__c</fullName>
        <label>Week</label>
        <type>Date</type>
    </fields>
    <label>Schedule</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/PrelogWeekBatchTests.cls
@IsTest
public class PrelogWeekBatchTests {

    @IsTest
    private static void testPrelogWeekBatch() {
        Schedules__c testSchedule = createSchedule('123', 'AntennaTV', 'Mon');
        createPrelogData(testSchedule.Id);

        Test.startTest();
        Date endDate = Date.today().toStartOfWeek();
        Date startDate = endDate.addDays(-6);
        PrelogWeekBatch.run(startDate, endDate);
        Test.stopTest();

        List<Prelog_Week__c> prelogWeeks = getAllPrelogWeeksByDaypart('2-DT 9a-6p');
        System.assertEquals(1, prelogWeeks.size());
        System.assertEquals(600.00, prelogWeeks[0].Rate_Sum__c);
        System.assertEquals(4, prelogWeeks[0].Equiv_30_Sum__c);

        prelogWeeks = getAllPrelogWeeksByDaypart('4-PR 6-12a');
        System.assertEquals(1, prelogWeeks.size());
        System.assertEquals(300.00, prelogWeeks[0].Rate_Sum__c);
        System.assertEquals(6, prelogWeeks[0].Equiv_30_Sum__c);
    }

    @IsTest
    private static void testPrelogWeekBatchSpecifiedProgramName() {
        Schedules__c testSchedule = createSchedule('123', 'AntennaTV', 'Mon');
        createPrelogData(testSchedule.Id);

        Test.startTest();
        Date endDate = Date.today().toStartOfWeek();
        Date startDate = endDate.addDays(-6);
        Programs__c program = [SELECT Id
                                FROM Programs__c
                                WHERE Name = 'AntennaTV'
                                LIMIT 1];
        PrelogWeekBatch.run(startDate, endDate, new Set<String>{program.Id});
        Test.stopTest();

        List<Prelog_Week__c> prelogWeeks = getAllPrelogWeeksByDaypart('2-DT 9a-6p');
        System.assertEquals(1, prelogWeeks.size());
        System.assertEquals(600.00, prelogWeeks[0].Rate_Sum__c);
        System.assertEquals(4, prelogWeeks[0].Equiv_30_Sum__c);

        prelogWeeks = getAllPrelogWeeksByDaypart('4-PR 6-12a');
        System.assertEquals(1, prelogWeeks.size());
        System.assertEquals(300.00, prelogWeeks[0].Rate_Sum__c);
        System.assertEquals(6, prelogWeeks[0].Equiv_30_Sum__c);
    }

    @IsTest
    private static void testCleanDuplicates() {
        Schedules__c testSchedule = createSchedule('123', 'AntennaTV', 'Mon');
        createPrelogData(testSchedule.Id);

        Programs__c program = [SELECT Id
                               FROM Programs__c
                               WHERE Name = 'AntennaTV'
                               LIMIT 1];
        Prelog_Week__c pw =  new Prelog_Week__c(
                Program__c = program.Id,
                Commercial_Type__c = 'DR',
                Week__c = Date.today().toStartOfWeek().addDays(-6),
                Daypart__c = '2-DT 9a-6p',
                Version__c = 6,
                Rate_Sum__c = 100.00,
                Equiv_30_Sum__c = 20
        );
        insert pw;

        Test.startTest();
        Date endDate = Date.today().toStartOfWeek();
        Date startDate = endDate.addDays(-6);
        PrelogWeekBatch.run(startDate, endDate);
        Test.stopTest();

        Prelog_Week__c prelogWeek = [SELECT Id, Rate_Sum__c
                                      FROM Prelog_Week__c
                                      WHERE Id = :pw.Id];
        System.assertEquals(600.00, prelogWeek.Rate_Sum__c);
    }

    private static Schedules__c createSchedule(String dealNumber, String programName, String airDate ) {
        Account testAcct = new Account();
        testAcct.Name = 'PrelogDataMirror Test';
        testAcct.BillingCity = 'Wakarusa';
        insert testAcct;

        Contact contact = new Contact();
        contact.FirstName = 'Test';
        contact.LastName = 'Name';
        contact.Email = 'test@testemail.com';
        contact.Phone = '(758) 771-0091';
        contact.Account = testAcct;
        insert contact;

        Programs__c program = new Programs__c();
        program.Name = programName;
        program.Cable_Synd__c = 'Cable';
        program.Station_Call_Letter__c = 'AWED';
        program.ClientCode__c = dealNumber;
        program.Clock_Start_Time__c = '7AM';
        insert program;

        Advertiser__c advertiser = new Advertiser__c(
            Name = Utils.randomString(10),
            Duplicate_Approval__c = 'Approved',
            Advertiser_Approved_to_Book__c = true,
            Commercial__c = 'DR'
        );
        insert advertiser;

        Brands__c brand = new Brands__c(
            Name = 'Availability',
            Advertiser__c = advertiser.Id,
            Approved_Duplicate__c = 'Approved',
            Category__c = 'Other'
        );
        insert brand;

        Deal__c testDeal = new Deal__c(
            Program__c = program.Id,
            Brands__c = brand.Id,
            Contact__c = contact.Id,
            Network_Deal_Number__c = dealNumber,
            Length__c = '1'
        );
        insert testDeal;

        Schedules__c schedule = new Schedules__c();
        schedule.Week__c = Date.today().toStartOfWeek().addDays(-6);
        schedule.Units_Available__c = 5;
        schedule.Deal_Parent__c = testDeal.Id;
        schedule.Days_Allowed__c = airDate;
        schedule.Start_Time__c = '09:00A';
        schedule.End_Time__c = '09:30A';
        schedule.Rate__c = 100;
        schedule.Units_Available__c = 5;
        insert schedule;
        return [
                SELECT Id, Week__c, Deal_Parent__c, Deal_Parent__r.Network_Deal_Number__c,
                        Days_Allowed__c, Start_Time__c, End_Time__c, Rate__c, Units_Available__c
                FROM Schedules__c
                WHERE Id =: schedule.Id
        ];
    }

    private static List<PrelogData__c> createPrelogData(String scheduleId){
        List<PrelogData__c> prelogs = new List<PrelogData__c> {
            new PrelogData__c(
                Schedule__c = scheduleId,
                Version__c = 6,
                ScheduleTime__c='11:57:01 AM',
                Rate__c = 300.00,
                ScheduleLength__c = '60'
            ),
            new PrelogData__c(
                    Schedule__c = scheduleId,
                    Version__c = 6,
                    ScheduleTime__c='12:57:01 PM',
                    Rate__c = 300.00,
                    ScheduleLength__c = '60'
            ),
            new PrelogData__c(
                    Schedule__c = scheduleId,
                    Version__c = 6,
                    ScheduleTime__c='9:57:01 PM',
                    Rate__c = 150.00,
                    ScheduleLength__c = '90'
            ),
            new PrelogData__c(
                    Schedule__c = scheduleId,
                    Version__c = 6,
                    ScheduleTime__c='10:57:01 PM',
                    Rate__c = 150.00,
                    ScheduleLength__c = '90'
            )
        };

        insert prelogs;
        return prelogs;
    }

    private static List<Prelog_Week__c>  getAllPrelogWeeksByDaypart(String daypart){
        return [
                SELECT Id, Week__c, Rate_Sum__c, Equiv_30_Sum__c
                FROM Prelog_Week__c
                WHERE Daypart__c = :daypart
        ];
    }

}