objects/Advertiser__c.object
<CustomObject>
    <fields>
        <fullName>Advertiser_Approved_to_Book__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Checked = Advertiser has been approved to book by Finance 
Unchecked = Advertiser has NOT been approved to book by Finance</inlineHelpText>
        <label>Advertiser Approved to Book</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Duplicate_Approval__c</fullName>
        <description>Used to prevent duplicate advertisers from being created.</description>
        <label>Duplicate Approval</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Not Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Advertiser</label>
    <nameField>
        <label>Advertiser Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Advertisers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Brands__c.object
<CustomObject>
    <fields>
        <fullName>Advertiser__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Advertiser</label>
        <referenceTo>Advertiser__c</referenceTo>
        <relationshipLabel>Brands</relationshipLabel>
        <relationshipName>Brands</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approved_Duplicate__c</fullName>
        <label>Duplicate Approval</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Not Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>.Com/E-Commerce</fullName>
                </value>
                <value>
                    <fullName>Apparel/Accessories</fullName>
                </value>
                <value>
                    <fullName>Appliances/Home Gadgets</fullName>
                </value>
                <value>
                    <fullName>Attorney/General Legal Services</fullName>
                </value>
                <value>
                    <fullName>Attorney-Medical Services/Equipments/Prescriptions</fullName>
                </value>
                <value>
                    <fullName>Auto Accessories/Parts/Repair</fullName>
                </value>
                <value>
                    <fullName>Baby</fullName>
                </value>
                <value>
                    <fullName>Beauty/Cosmetics/Hair Care</fullName>
                </value>
                <value>
                    <fullName>Business/Professional Services</fullName>
                </value>
                <value>
                    <fullName>Charity</fullName>
                </value>
                <value>
                    <fullName>Cleaning Supplies</fullName>
                </value>
                <value>
                    <fullName>Crafts/Hobbies/Sporting goods/Toys</fullName>
                </value>
                <value>
                    <fullName>Education</fullName>
                </value>
                <value>
                    <fullName>Electronics/Software</fullName>
                </value>
                <value>
                    <fullName>Entertainment/Gaming</fullName>
                </value>
                <value>
                    <fullName>Fitness/Health/Medical Equipment</fullName>
                </value>
                <value>
                    <fullName>Food and Beverages</fullName>
                </value>
                <value>
                    <fullName>Home Improvement/Furniture</fullName>
                </value>
                <value>
                    <fullName>Insurance- Auto</fullName>
                </value>
                <value>
                    <fullName>Insurance- Health/ Dental/ Disability</fullName>
                </value>
                <value>
                    <fullName>Insurance- Life</fullName>
                </value>
                <value>
                    <fullName>Media/Telecom</fullName>
                </value>
                <value>
                    <fullName>Medical Services</fullName>
                </value>
                <value>
                    <fullName>Mental Health</fullName>
                </value>
                <value>
                    <fullName>Mobile Apps</fullName>
                </value>
                <value>
                    <fullName>Office Supplies</fullName>
                </value>
                <value>
                    <fullName>Pets</fullName>
                </value>
                <value>
                    <fullName>Pharmaceuticals/Drugs</fullName>
                </value>
                <value>
                    <fullName>Social Networking/Dating</fullName>
                </value>
                <value>
                    <fullName>Toiletry</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Brands</label>
    <nameField>
        <label>Brand</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Deal__c.object
<CustomObject>
    <fields>
        <fullName>Advertiser__c</fullName>
        <formula>Brands__r.Advertiser__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Advertiser</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Brands__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Brands</label>
        <referenceTo>Brands__c</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ClientCode__c</fullName>
        <formula>Program__r.ClientCode__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ClientCode</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Type__c</field>
                <operation>notEqual</operation>
                <value>history</value>
            </filterItems>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>Do Not Call</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Program</label>
        <referenceTo>Programs__c</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <label>[Dep]Rate</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Deal</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Deal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Programs__c.object
<CustomObject>
    <description>Program/Distributor</description>
    <fields>
        <fullName>ClientCode__c</fullName>
        <description>Assigned by Finance</description>
        <inlineHelpText>Assigned by Finance</inlineHelpText>
        <label>ClientCode</label>
        <length>3</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Schedules__c.object
<CustomObject>
    <fields>
        <fullName>DealProgram__c</fullName>
        <formula>Deal_Parent__r.Program__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>DealProgram</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Deal_Parent__c</fullName>
        <label>Deal Parent</label>
        <referenceTo>Deal__c</referenceTo>
        <relationshipLabel>Schedules</relationshipLabel>
        <relationshipName>Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Long_Form__c</fullName>
        <description>Long Form Time Periods for All Networks</description>
        <label>Long Form</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>A-12:00</fullName>
                </value>
                <value>
                    <fullName>A-12:30</fullName>
                </value>
                <value>
                    <fullName>A-1:00</fullName>
                </value>
                <value>
                    <fullName>A-1:30</fullName>
                </value>
                <value>
                    <fullName>A-2:00</fullName>
                </value>
                <value>
                    <fullName>A-2:30</fullName>
                </value>
                <value>
                    <fullName>A-3:00</fullName>
                </value>
                <value>
                    <fullName>A-3:30</fullName>
                </value>
                <value>
                    <fullName>A-4:00</fullName>
                </value>
                <value>
                    <fullName>A-4:30</fullName>
                </value>
                <value>
                    <fullName>A-5:00</fullName>
                </value>
                <value>
                    <fullName>A-5:30</fullName>
                </value>
                <value>
                    <fullName>A-6:00</fullName>
                </value>
                <value>
                    <fullName>A-6:30</fullName>
                </value>
                <value>
                    <fullName>A-7:00</fullName>
                </value>
                <value>
                    <fullName>A-7:30</fullName>
                </value>
                <value>
                    <fullName>A-8:00</fullName>
                </value>
                <value>
                    <fullName>A-8:30</fullName>
                </value>
                <value>
                    <fullName>A-9:00</fullName>
                </value>
                <value>
                    <fullName>A-9:30</fullName>
                </value>
                <value>
                    <fullName>A-10:00</fullName>
                </value>
                <value>
                    <fullName>A-10:30</fullName>
                </value>
                <value>
                    <fullName>A-11:00</fullName>
                </value>
                <value>
                    <fullName>A-11:30</fullName>
                </value>
                <value>
                    <fullName>P-12:00</fullName>
                </value>
                <value>
                    <fullName>P-12:30</fullName>
                </value>
                <value>
                    <fullName>P-1:00</fullName>
                </value>
                <value>
                    <fullName>P-1:30</fullName>
                </value>
                <value>
                    <fullName>P-2:00</fullName>
                </value>
                <value>
                    <fullName>P-2:30</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <label>Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Dollars__c</fullName>
        <formula>if(  PI_Payout_TEST__c &gt;0,  PI_Payout_TEST__c *20/17, 

if( PI_Payout__c &gt; 0 ,  PI_Payout__c * 20/17, 

if( Units_Aired__c &lt; 0,  0,
CASE(Deal_Parent__r.Status__c, &quot;Canceled&quot;, 0,  &quot;Pre-Empted&quot;, 0,

 Rate__c  *   Units_Aired__c)

)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Dollars</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Units_Aired__c</fullName>
        <formula>case( Status__c, &quot;Canceled&quot;, 0, Units_Available__c - Units_Preempted__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Units Aired</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Units_Available__c</fullName>
        <label>Units Available</label>
        <precision>17</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Units_Preempted__c</fullName>
        <label>Units Preempted</label>
        <precision>17</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Week__c</fullName>
        <label>Week</label>
        <type>Date</type>
    </fields>
    <label>Schedule</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TestTennisChannelTrafficGridController.cls
/**
@ name          :    TestTennisChannelTrafficGridController    
@ author        :
@ date          :    9 Augest, 2011
@ descripton    :  Test Class For TennisChannelTrafficGridController Class
*/
@isTest
public class TestTennisChannelTrafficGridController {
    @isTest
    public static void Test () {     
                
        Account acc = New Account();
        acc.name = 'Test';
        insert acc;
        
        Contact con = new Contact(Email = 'test@test.com', Phone = '8001234567');
        con.AccountID = acc.id;
        con.LastName = 'Test';
        insert con;
        
        Programs__c pro = new Programs__c();
        pro.Name = 'Tennis PP';
        pro.ClientCode__C = 'TC2';
        insert pro;

        Advertiser__c advertiser = new Advertiser__c(Duplicate_Approval__c = 'Approved', Advertiser_Approved_to_Book__c = true);
        insert advertiser;
         
        Brands__c brand = new Brands__c();
        brand.Name = 'Availability';
        brand.Category__c = 'Other';
        brand.Advertiser__c = advertiser.id;
        brand.Approved_Duplicate__c = 'Approved' ;
        insert brand;
        
        Deal__C de = new Deal__C(Contact__c = con.Id);
        de.Program__c = pro.id;     
        de.Brands__c = brand.Id ;   
        insert de;
        
        Schedules__c sch = new Schedules__c();        
        sch.Deal_Parent__c = de.Id;
        //sch.DealProgram__c = pro.Id;
        sch.Week__c = system.today();                
        sch.Long_Form__c = 'A-2:00';        
        sch.Units_Preempted__c = 0;
        //sch.Units_Aired__c = 0.0;
        sch.Rate__c = 100;
        sch.Units_Available__c = 1;
        
        //sch.Total_Dollars__c = 0;                
        
        insert sch;        
        
        Date weekFrom = sch.week__c;
        date weekTo = sch.week__c;        
        
        list<Schedules__c> scList = new List<Schedules__c>([SELECT id,Deal_Parent__c,Week__c,Long_Form__c,Units_Preempted__c,
                                    Rate__c FROM Schedules__c WHERE Units_Preempted__c != 1 AND
                                    DealProgram__c =: 'Tennis PP'  AND Week__c >=: weekFrom AND Week__c <=: weekTo
                                    LIMIT 5 ]);
                                    
        apexPages.CurrentPage().getParameters().put('chk_1', sch.id);
        TennisChannelTrafficGridController T=new TennisChannelTrafficGridController(); 
        
        T.dealKeyword = acc.name;
        T.months = 'Aug-2011';        
        T.save();

        

        T.requestTraffic();
        T.requestTrafficWeek();
        

        //T.SendEmail();
        
        
        
        System.assert(scList.size()>0,'No Record Saved');
        t.search();        
        System.assert(scList.size()>0,'No Record Found');
    }
}