objects/Advertiser__c.object
<CustomObject>
    <fields>
        <fullName>Advertiser_Approved_to_Book__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Checked = Advertiser has been approved to book by Finance 
Unchecked = Advertiser has NOT been approved to book by Finance</inlineHelpText>
        <label>Advertiser Approved to Book</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Duplicate_Approval__c</fullName>
        <description>Used to prevent duplicate advertisers from being created.</description>
        <label>Duplicate Approval</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Not Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Advertiser</label>
    <nameField>
        <label>Advertiser Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Advertisers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Brands__c.object
<CustomObject>
    <fields>
        <fullName>Advertiser__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Advertiser</label>
        <referenceTo>Advertiser__c</referenceTo>
        <relationshipLabel>Brands</relationshipLabel>
        <relationshipName>Brands</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approved_Duplicate__c</fullName>
        <label>Duplicate Approval</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Not Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>.Com/E-Commerce</fullName>
                </value>
                <value>
                    <fullName>Apparel/Accessories</fullName>
                </value>
                <value>
                    <fullName>Appliances/Home Gadgets</fullName>
                </value>
                <value>
                    <fullName>Attorney/General Legal Services</fullName>
                </value>
                <value>
                    <fullName>Attorney-Medical Services/Equipments/Prescriptions</fullName>
                </value>
                <value>
                    <fullName>Auto Accessories/Parts/Repair</fullName>
                </value>
                <value>
                    <fullName>Baby</fullName>
                </value>
                <value>
                    <fullName>Beauty/Cosmetics/Hair Care</fullName>
                </value>
                <value>
                    <fullName>Business/Professional Services</fullName>
                </value>
                <value>
                    <fullName>Charity</fullName>
                </value>
                <value>
                    <fullName>Cleaning Supplies</fullName>
                </value>
                <value>
                    <fullName>Crafts/Hobbies/Sporting goods/Toys</fullName>
                </value>
                <value>
                    <fullName>Education</fullName>
                </value>
                <value>
                    <fullName>Electronics/Software</fullName>
                </value>
                <value>
                    <fullName>Entertainment/Gaming</fullName>
                </value>
                <value>
                    <fullName>Fitness/Health/Medical Equipment</fullName>
                </value>
                <value>
                    <fullName>Food and Beverages</fullName>
                </value>
                <value>
                    <fullName>Home Improvement/Furniture</fullName>
                </value>
                <value>
                    <fullName>Insurance- Auto</fullName>
                </value>
                <value>
                    <fullName>Insurance- Health/ Dental/ Disability</fullName>
                </value>
                <value>
                    <fullName>Insurance- Life</fullName>
                </value>
                <value>
                    <fullName>Media/Telecom</fullName>
                </value>
                <value>
                    <fullName>Medical Services</fullName>
                </value>
                <value>
                    <fullName>Mental Health</fullName>
                </value>
                <value>
                    <fullName>Mobile Apps</fullName>
                </value>
                <value>
                    <fullName>Office Supplies</fullName>
                </value>
                <value>
                    <fullName>Pets</fullName>
                </value>
                <value>
                    <fullName>Pharmaceuticals/Drugs</fullName>
                </value>
                <value>
                    <fullName>Social Networking/Dating</fullName>
                </value>
                <value>
                    <fullName>Toiletry</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Brands</label>
    <nameField>
        <label>Brand</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Deal__c.object
<CustomObject>
    <fields>
        <fullName>Advertiser__c</fullName>
        <formula>Brands__r.Advertiser__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Advertiser</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Brands__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Brands</label>
        <referenceTo>Brands__c</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ClientCode__c</fullName>
        <formula>Program__r.ClientCode__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ClientCode</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>[Dep]Client Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Type__c</field>
                <operation>notEqual</operation>
                <value>history</value>
            </filterItems>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>Do Not Call</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Length__c</fullName>
        <label>Length</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>30</fullName>
                    <color>#0B6FCE</color>
                    <label>30</label>
                </value>
                <value>
                    <fullName>60</fullName>
                    <color>#78C953</color>
                    <label>60</label>
                </value>
                <value>
                    <fullName>120</fullName>
                    <color>#E27001</color>
                    <label>120</label>
                </value>
                <value>
                    <fullName>300</fullName>
                    <color>#A845DC</color>
                    <label>300</label>
                </value>
                <value>
                    <fullName>15</fullName>
                    <color>#F3D904</color>
                    <label>15</label>
                </value>
                <value>
                    <fullName>1710</fullName>
                    <color>#A53711</color>
                    <label>1710</label>
                </value>
                <value>
                    <fullName>90</fullName>
                    <color>#66E9BD</color>
                    <label>90</label>
                </value>
                <value>
                    <fullName>180</fullName>
                    <color>#0B24BE</color>
                    <label>180</label>
                </value>
                <value>
                    <fullName>240</fullName>
                    <color>#419249</color>
                    <label>240</label>
                </value>
                <value>
                    <fullName>45</fullName>
                </value>
                <value>
                    <fullName>75</fullName>
                </value>
                <value>
                    <fullName>05</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>150</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>105</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>35</fullName>
                </value>
                <value>
                    <fullName>40</fullName>
                </value>
                <value>
                    <fullName>1714</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Program</label>
        <referenceTo>Programs__c</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <label>[Dep]Rate</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Sold</fullName>
                    <default>true</default>
                    <label>Sold</label>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Historical</fullName>
                </value>
                <value>
                    <fullName>Budget</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Deal</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Deal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Programs__c.object
<CustomObject>
    <description>Program/Distributor</description>
    <fields>
        <fullName>ClientCode__c</fullName>
        <description>Assigned by Finance</description>
        <inlineHelpText>Assigned by Finance</inlineHelpText>
        <label>ClientCode</label>
        <length>3</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Schedules__c.object
<CustomObject>
    <fields>
        <fullName>Deal_Parent__c</fullName>
        <label>Deal Parent</label>
        <referenceTo>Deal__c</referenceTo>
        <relationshipLabel>Schedules</relationshipLabel>
        <relationshipName>Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Ghost_Order__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Ghost Order</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OrderNumber__c</fullName>
        <label>OrderNumber</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <label>Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Sold</fullName>
                    <default>true</default>
                    <label>Sold</label>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TEST__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Notes whether a particular schedule is a test.</description>
        <label>TEST</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Week__c</fullName>
        <label>Week</label>
        <type>Date</type>
    </fields>
    <label>Schedule</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/DoubleCheckReportControllerTest.cls
@IsTest
private class DoubleCheckReportControllerTest {

	@IsTest
	public static void testDoubleCheckReportController_doSearch_dealFound() {
		Brands__c brand = createBrand();
        Deal__c deal = createDeal(brand);
        Programs__c program = createProgram();
        Account acc = createAccount();
		createSchedules(deal.Id);

        Test.setCurrentPage(Page.DoubleCheckReportV7);
        //ApexPages.CurrentPage().getParameters().put('DealId', deal.id) ;
        DoubleCheckReportControllerV7 v7 = new DoubleCheckReportControllerV7();
        String dateString = DealUtils.ReturnStringDate(Date.today());
        
        Test.startTest();
		v7.Searchfield = 'Availability';
		v7.SelectedDateLiteral = '';
		v7.BarterCheckbox = false;
    	v7.SelectedCableSynd = '';
        v7.SelectedDateLiteral = '';
        v7.DoSearch();
		System.assert(v7.DealResultList.size() > 0);
		System.assertEquals(v7.DealResultList[0].Id, deal.Id);
		Test.stopTest();
	}

    @IsTest
    public static void testDoubleCheckReportController_showDetail() {
        Brands__c brand = createBrand();
        Deal__c deal = createDeal(brand);
        Programs__c program = createProgram();
        Account acc = createAccount();

        DoubleCheckReportController dc = new DoubleCheckReportController();

        Test.startTest();
        dc.showDetail();
        
        dc.deal.Program__c=program.Id;
        dc.deal.Client_Account__c=acc.Id;
        dc.deal.Brands__c = brand.Id;
        dc.showDetail();
        
        dc.did = deal.Id;
        dc.searchByDeal();
        
        dc.schedule.Deal_Parent__c = deal.Id;
        dc.showDetail();
        Test.stopTest();
    }
        
    @IsTest
    public static void testDoubleCheckReportController_searchAndSearchByDetail() {
        Brands__c brand = createBrand();
        Deal__c deal = createDeal(brand);
        Programs__c program = createProgram();
        Account acc = createAccount();
        
        DoubleCheckReportController dc2 = new DoubleCheckReportController();
        Test.startTest();
        dc2.schedule.Deal_Parent__c = deal.Id;
        dc2.showDetail();
        dc2.search();
        dc2.searchByDeal();
        dc2.save();
        Test.stopTest();
    }
        
    @IsTest
    public static void testDoubleCheckReportController_testUpdates() {  
        Brands__c brand = createBrand();
        Deal__c deal = createDeal(brand);
        Programs__c program = createProgram();
        Account acc = createAccount();

        Test.setCurrentPage(Page.DoubleCheckReportV7);
        ApexPages.currentPage().getParameters().put('DealId', deal.Id) ;
        DoubleCheckReportControllerV7 v7 = new DoubleCheckReportControllerV7();
        String dateString = DealUtils.ReturnStringDate(Date.today());
        v7.dealSelector = new DealTestSelector();
        v7.scheduleSelector = new ScheduleTestSelector();
        v7.Searchfield = ' Test Brand,Test Brand ';
        Test.startTest();
        v7.DoSearch();
        v7.DealId = deal.Id;
        v7.SearchforSchedules();
        v7.ScheduleChange();
        v7.RateUpdate();
        v7.UnitsAvailableUpdate();
        v7.ExtensionUpdate();
        v7.testTabUpdate();
        v7.capTabUpdate();
        v7.dayPartTabUpdate();
        v7.maxTabUpdate();
        v7.cellsave();
        DoubleCheckReportControllerV7.getDayOptions();
        DoubleCheckReportControllerV7.getProgramTeamOptions();
        v7.updateSchedule();
        Test.stopTest();
    }

    @IsTest
    public static void testDoubleCheckReportController_testSave() {
        Brands__c brand = createBrand();
        Deal__c deal = createDeal(brand);
        Programs__c program = createProgram();
        Account acc = createAccount();
        Schedules__c sch = createSchedules(deal.Id);


        Test.setCurrentPage(Page.DoubleCheckReportV7);
        ApexPages.currentPage().getParameters().put('DealId', deal.Id) ;
        DoubleCheckReportControllerV7 v7 = new DoubleCheckReportControllerV7();
        String dateString = DealUtils.ReturnStringDate(Date.today());
        v7.Searchfield = ' Test Brand, Test Brand ';
        Test.startTest();
        v7.DoSearch();
        v7.DealId = deal.Id;
        v7.SelectedOrderLineNumber = '0';
        Date extensionDate = Date.today().toStartOfWeek().addDays(15);
        v7.SelectedExtensionDate = extensionDate.year() + '-' + extensionDate.month() + '-' + extensionDate.day();
		sch.OrderNumber__c = '0';
        sch.Week__c = Date.today().toStartOfWeek().addDays(8);
        update sch;
        v7.currentRateModelIndex = 0;
        v7.currentScheduleId = sch.Id;
        v7.dayPartTabList[0] = new DoubleCheckReportControllerV7.rateModel();
        v7.dayPartTabList[0].weeks.add(new DoubleCheckReportControllerV7.weekModel(Date.today(), sch, false, new DateSelector()));
        
        v7.updateWeeks();
        v7.cellcancel();
        v7.ExtensionSave();
        
        v7.CellId = sch.Id;
        sch.Status__c = 'Canceled';
        update sch;
        v7.LTCsave();
        sch.Status__c = 'Sold';
        update sch;
        v7.LTCsave();
        
        v7.UnitsAvailableSave();
        v7.GhostChecksave();
        v7.TestChecksave();
        
        new DoubleCheckReportControllerV7.weekModel(Date.today(), sch, false, new DateSelector());
        sch.Status__c = 'Canceled';
        new DoubleCheckReportControllerV7.weekModel(Date.today(), sch, false, new DateSelector());
        sch.Status__c = 'Sold';
        sch.TEST__c = true;
        sch.Ghost_Order__c = true;
        (new DoubleCheckReportControllerV7.weekModel(Date.today(), sch, false, new DateSelector())).changerate = 1;
        Test.stopTest();
        
    }
    
    @IsTest public static void test_pageNavigation() {
        Brands__c brand = createBrand();
        Deal__c deal = createDeal(brand);
        Programs__c program = createProgram();
        Account acc = createAccount();
        Schedules__c sch = createSchedules(deal.Id);

        DoubleCheckReportControllerV7 v7 = new DoubleCheckReportControllerV7();
        Test.startTest();
        v7.currentPage = 1;
        v7.loadNextPage();
        v7.loadPrevPage();
        v7.goToPage();
        
        v7.currentPageCap = 1;
        v7.loadNextPageCap();
        v7.loadPrevPageCap();
        v7.goToPageCap();
        
        v7.currentPageMax = 1;
        v7.loadNextPageMax();
        v7.loadPrevPageMax();
        v7.goToPageMax();
        Test.stopTest();
    }
    
    @IsTest public static void DoubleCheck_ReturnSOQL_Empty() {
        DoubleCheckReportControllerV7 dc = new DoubleCheckReportControllerV7(new DateSelector(Date.newInstance(2016, 1, 1)));
        dc.SelectedDateLiteral = '';
        dc.ReturnSOQLDateString();
    }

    @IsTest public static void DoubleCheck_ReturnSOQL_Custom() {
        DoubleCheckReportControllerV7 dc = new DoubleCheckReportControllerV7(new DateSelector(Date.newInstance(2016, 1, 1)));
        dc.SelectedDateLiteral = 'Custom';
        dc.ReturnSOQLDateString();
    }

    @IsTest public static void DoubleCheck_ReturnSOQL_FiscalYear() {
        DoubleCheckReportControllerV7 dc = new DoubleCheckReportControllerV7(new DateSelector(Date.newInstance(2016, 1, 1)));
        dc.SelectedDateLiteral = 'Current And Previous 2 FY';
        dc.ReturnSOQLDateString();
    }

    @IsTest public static void DoubleCheck_ReturnSOQL_FiscalQuarter() {
        DoubleCheckReportControllerV7 dc = new DoubleCheckReportControllerV7(new DateSelector(Date.newInstance(2016, 1, 1)));
        dc.SelectedDateLiteral = 'Current And Previous FQ';
        dc.ReturnSOQLDateString();

        dc = new DoubleCheckReportControllerV7(new DateSelector(Date.newInstance(2016, 12, 1)));
        dc.SelectedDateLiteral = 'Current And Next FQ';
        dc.ReturnSOQLDateString();
    }

    @IsTest public static void DoubleCheck_ReturnSOQL_FiscalMonth() {
        DoubleCheckReportControllerV7 dc = new DoubleCheckReportControllerV7(new DateSelector(Date.newInstance(2016, 1, 1)));
        dc.SelectedDateLiteral = 'Current And Previous FP';
        dc.ReturnSOQLDateString();
    }

    @IsTest public static void DoubleCheck_ReturnSOQL_FiscalWeek() {
        DoubleCheckReportControllerV7 dc = new DoubleCheckReportControllerV7(new DateSelector(Date.newInstance(2016, 1, 1)));
        dc.SelectedDateLiteral = 'Last FW';
        dc.ReturnSOQLDateString();

        dc = new DoubleCheckReportControllerV7(new DateSelector(Date.newInstance(2016, 12, 30)));
        dc.SelectedDateLiteral = 'Next FW';
        dc.ReturnSOQLDateString();
    }

    @IsTest public static void DoubleCheck_ReturnSOQL_CalYear() {
        DoubleCheckReportControllerV7 dc = new DoubleCheckReportControllerV7(new DateSelector(Date.newInstance(2016, 1, 1)));
        dc.SelectedDateLiteral = 'Previous 2 CY';
        dc.ReturnSOQLDateString();
    }

    @IsTest public static void DoubleCheck_ReturnSOQL_CalQuarter() {
        DoubleCheckReportControllerV7 dc = new DoubleCheckReportControllerV7(new DateSelector(Date.newInstance(2016, 1, 1)));
        dc.SelectedDateLiteral = 'Current And Previous CQ';
        dc.ReturnSOQLDateString();

        dc = new DoubleCheckReportControllerV7(new DateSelector(Date.newInstance(2016, 12, 1)));
        dc.SelectedDateLiteral = 'Current And Next CQ';
        dc.ReturnSOQLDateString();
    }

    @IsTest public static void DoubleCheck_ReturnSOQL_CalMonth() {
        DoubleCheckReportControllerV7 dc = new DoubleCheckReportControllerV7(new DateSelector(Date.newInstance(2016, 1, 1)));
        dc.SelectedDateLiteral = 'Last Month';
        dc.ReturnSOQLDateString();

        dc = new DoubleCheckReportControllerV7(new DateSelector(Date.newInstance(2016, 12, 10)));
        dc.SelectedDateLiteral = 'Next Month';
        dc.ReturnSOQLDateString();
    }

    @IsTest public static void DoubleCheck_ReturnSOQL_CalWeek() {
        DoubleCheckReportControllerV7 dc = new DoubleCheckReportControllerV7(new DateSelector(Date.newInstance(2016, 1, 1)));
        dc.SelectedDateLiteral = 'Last Week';
        dc.ReturnSOQLDateString();
    }

    @IsTest public static void DoubleCheck_ReturnSOQL_CalDay() {
        DoubleCheckReportControllerV7 dc = new DoubleCheckReportControllerV7(new DateSelector(Date.newInstance(2016, 1, 1)));
        dc.SelectedDateLiteral = 'Last 120 Days';
        dc.ReturnSOQLDateString();
    }

    @IsTest public static void test_DoubleCheck_DoSearch() {
        DoubleCheckReportControllerV7 dc = new DoubleCheckReportControllerV7();
        dc.Searchfield = '1,2,3,4,5';
        dc.DoSearch();
    }

    private static Deal__c createDeal(Brands__c brand) {
        Contact con = new Contact(LastName = 'Test', Email = 'test@test.com', Phone = '8001234567') ;
        insert con ;

        Deal__c deal = new Deal__c(Contact__c = con.Id, Brands__c = brand.Id, Length__c = '30');
        insert deal;

        return deal;
    }

    private static Account createAccount() {
        Account acc = new Account();
        acc.Name='test';
        insert acc;
        return acc;
    }

    private static Brands__c createBrand() {
        Advertiser__c advertiser = new Advertiser__c(Duplicate_Approval__c = 'Approved', Advertiser_Approved_to_Book__c = true);
        insert advertiser;

        Brands__c brand = new Brands__c();
        brand.Name = 'Availability';
        brand.Category__c = 'Other';
        brand.Advertiser__c = advertiser.Id;
        brand.Approved_Duplicate__c = 'Approved' ;
        insert brand;
        return brand;
    }

    private static Programs__c createProgram() {
        Programs__c program = new Programs__c();
        program.Name='Availability';
        program.ClientCode__c='123';
        insert program;

        return program;
    }

    private static Schedules__c createSchedules(String dealId){

        Schedules__c sch = new Schedules__c();
        sch.Deal_Parent__c = dealId;
        sch.Rate__c = 100;
        sch.Comments__c = 'test';
        sch.Week__c = System.today().toStartOfWeek().addDays(1);
        sch.Units_Available__c = 1;
        insert sch;

        Schedules__c sch2 = new Schedules__c();
        sch2.Deal_Parent__c = dealId;
        sch2.Rate__c = 100;
        sch2.Comments__c = 'test';
        sch2.Week__c = System.today().toStartOfWeek().addDays(-6);
        sch2.Units_Available__c = 1;
        insert sch2;

        return sch;
    }
}