objects/Advertiser__c.object
<CustomObject>
    <fields>
        <fullName>Advertiser_Approved_to_Book__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Checked = Advertiser has been approved to book by Finance 
Unchecked = Advertiser has NOT been approved to book by Finance</inlineHelpText>
        <label>Advertiser Approved to Book</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Duplicate_Approval__c</fullName>
        <description>Used to prevent duplicate advertisers from being created.</description>
        <label>Duplicate Approval</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Not Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Advertiser</label>
    <nameField>
        <label>Advertiser Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Advertisers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Brands__c.object
<CustomObject>
    <fields>
        <fullName>Advertiser__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Advertiser</label>
        <referenceTo>Advertiser__c</referenceTo>
        <relationshipLabel>Brands</relationshipLabel>
        <relationshipName>Brands</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approved_Duplicate__c</fullName>
        <label>Duplicate Approval</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Not Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>.Com/E-Commerce</fullName>
                </value>
                <value>
                    <fullName>Apparel/Accessories</fullName>
                </value>
                <value>
                    <fullName>Appliances/Home Gadgets</fullName>
                </value>
                <value>
                    <fullName>Attorney/General Legal Services</fullName>
                </value>
                <value>
                    <fullName>Attorney-Medical Services/Equipments/Prescriptions</fullName>
                </value>
                <value>
                    <fullName>Auto Accessories/Parts/Repair</fullName>
                </value>
                <value>
                    <fullName>Baby</fullName>
                </value>
                <value>
                    <fullName>Beauty/Cosmetics/Hair Care</fullName>
                </value>
                <value>
                    <fullName>Business/Professional Services</fullName>
                </value>
                <value>
                    <fullName>Charity</fullName>
                </value>
                <value>
                    <fullName>Cleaning Supplies</fullName>
                </value>
                <value>
                    <fullName>Crafts/Hobbies/Sporting goods/Toys</fullName>
                </value>
                <value>
                    <fullName>Education</fullName>
                </value>
                <value>
                    <fullName>Electronics/Software</fullName>
                </value>
                <value>
                    <fullName>Entertainment/Gaming</fullName>
                </value>
                <value>
                    <fullName>Fitness/Health/Medical Equipment</fullName>
                </value>
                <value>
                    <fullName>Food and Beverages</fullName>
                </value>
                <value>
                    <fullName>Home Improvement/Furniture</fullName>
                </value>
                <value>
                    <fullName>Insurance- Auto</fullName>
                </value>
                <value>
                    <fullName>Insurance- Health/ Dental/ Disability</fullName>
                </value>
                <value>
                    <fullName>Insurance- Life</fullName>
                </value>
                <value>
                    <fullName>Media/Telecom</fullName>
                </value>
                <value>
                    <fullName>Medical Services</fullName>
                </value>
                <value>
                    <fullName>Mental Health</fullName>
                </value>
                <value>
                    <fullName>Mobile Apps</fullName>
                </value>
                <value>
                    <fullName>Office Supplies</fullName>
                </value>
                <value>
                    <fullName>Pets</fullName>
                </value>
                <value>
                    <fullName>Pharmaceuticals/Drugs</fullName>
                </value>
                <value>
                    <fullName>Social Networking/Dating</fullName>
                </value>
                <value>
                    <fullName>Toiletry</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Brands</label>
    <nameField>
        <label>Brand</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Deal__c.object
<CustomObject>
    <fields>
        <fullName>Advertiser__c</fullName>
        <formula>Brands__r.Advertiser__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Advertiser</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Brands__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Brands</label>
        <referenceTo>Brands__c</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ClientCode__c</fullName>
        <formula>Program__r.ClientCode__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ClientCode</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Type__c</field>
                <operation>notEqual</operation>
                <value>history</value>
            </filterItems>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>Do Not Call</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Length__c</fullName>
        <label>Length</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>30</fullName>
                    <color>#0B6FCE</color>
                    <label>30</label>
                </value>
                <value>
                    <fullName>60</fullName>
                    <color>#78C953</color>
                    <label>60</label>
                </value>
                <value>
                    <fullName>120</fullName>
                    <color>#E27001</color>
                    <label>120</label>
                </value>
                <value>
                    <fullName>300</fullName>
                    <color>#A845DC</color>
                    <label>300</label>
                </value>
                <value>
                    <fullName>15</fullName>
                    <color>#F3D904</color>
                    <label>15</label>
                </value>
                <value>
                    <fullName>1710</fullName>
                    <color>#A53711</color>
                    <label>1710</label>
                </value>
                <value>
                    <fullName>90</fullName>
                    <color>#66E9BD</color>
                    <label>90</label>
                </value>
                <value>
                    <fullName>180</fullName>
                    <color>#0B24BE</color>
                    <label>180</label>
                </value>
                <value>
                    <fullName>240</fullName>
                    <color>#419249</color>
                    <label>240</label>
                </value>
                <value>
                    <fullName>45</fullName>
                </value>
                <value>
                    <fullName>75</fullName>
                </value>
                <value>
                    <fullName>05</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>150</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>105</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>35</fullName>
                </value>
                <value>
                    <fullName>40</fullName>
                </value>
                <value>
                    <fullName>1714</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Program</label>
        <referenceTo>Programs__c</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <label>[Dep]Rate</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Deal</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Deal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Programs__c.object
<CustomObject>
    <description>Program/Distributor</description>
    <fields>
        <fullName>ClientCode__c</fullName>
        <description>Assigned by Finance</description>
        <inlineHelpText>Assigned by Finance</inlineHelpText>
        <label>ClientCode</label>
        <length>3</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Schedules__c.object
<CustomObject>
    <fields>
        <fullName>Deal_Parent__c</fullName>
        <label>Deal Parent</label>
        <referenceTo>Deal__c</referenceTo>
        <relationshipLabel>Schedules</relationshipLabel>
        <relationshipName>Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <label>Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Units_Available__c</fullName>
        <label>Units Available</label>
        <precision>17</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Week__c</fullName>
        <label>Week</label>
        <type>Date</type>
    </fields>
    <label>Schedule</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TennisChangesControllerTest.cls
@isTest
public class TennisChangesControllerTest {
    @isTest
    private static void testClass(){
        Programs__c program = new Programs__c();
        program.Name = 'Test PP TT';
        program.ClientCode__c = 'ZZ';
        insert program;

        Contact con = new Contact(LastName = 'Test', Email = 'test@test.com', Phone = '8001234567') ;
        insert con ;

        Advertiser__c advertiser = new Advertiser__c(Duplicate_Approval__c = 'Approved', Advertiser_Approved_to_Book__c = true);
        insert advertiser;
         
        Brands__c brand = new Brands__c();
        brand.Name = 'Availability';
        brand.Category__c = 'Other';
        brand.Advertiser__c = advertiser.id;
        brand.Approved_Duplicate__c = 'Approved' ;
        insert brand;
         
        Deal__c deal = new Deal__c(Contact__c = con.Id);
        deal.Program__c = program.Id;
        deal.RecordTypeId = getRecordTypeId('Short Form', 'Deal__c');
        deal.Length__c = '30' ;
        deal.Brands__c = brand.Id ;
        insert deal;
        
        Schedules__c schedule = new Schedules__c();
        schedule.Deal_Parent__c = deal.Id;
        schedule.Rate__c = 100;
        schedule.Week__c = date.newInstance(2011, 22, 8);
        schedule.Units_Available__c = 1;
        insert schedule;
        
        TennisChangesController tcc = new TennisChangesController();
        tcc.months = system.today().month() + '-' + system.today().year();
        tcc.searchMonth();
        
    }
    
    private static Id getRecordTypeId(String rtName, String SObjectType){
        return [SELECT Id FROM RecordType WHERE Name =: rtName AND SObjectType =: SObjectType].Id;
    }
}