objects/Advertiser__c.object
<CustomObject>
    <fields>
        <fullName>Commercial__c</fullName>
        <description>END - Endemic
PSA - Public Service Announcement</description>
        <label>SF Commercial Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>DR</fullName>
                </value>
                <value>
                    <fullName>GM</fullName>
                </value>
                <value>
                    <fullName>HYBRID</fullName>
                </value>
                <value>
                    <fullName>PSA</fullName>
                </value>
                <value>
                    <fullName>END</fullName>
                </value>
                <value>
                    <fullName>PROMO</fullName>
                </value>
                <value>
                    <fullName>TUNE IN</fullName>
                </value>
                <value>
                    <fullName>--</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Advertiser</label>
    <nameField>
        <label>Advertiser Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Advertisers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Brands__c.object
<CustomObject>
    <fields>
        <fullName>Advertiser__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Advertiser</label>
        <referenceTo>Advertiser__c</referenceTo>
        <relationshipLabel>Brands</relationshipLabel>
        <relationshipName>Brands</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Brands</label>
    <nameField>
        <label>Brand</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Deal__c.object
<CustomObject>
    <label>Deal</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Deal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Prelog_Week__c.object
<CustomObject>
    <fields>
        <fullName>Commercial_Type__c</fullName>
        <label>Commercial Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>DR</fullName>
                </value>
                <value>
                    <fullName>GM</fullName>
                </value>
                <value>
                    <fullName>HYBRID</fullName>
                </value>
                <value>
                    <fullName>PSA</fullName>
                </value>
                <value>
                    <fullName>END</fullName>
                </value>
                <value>
                    <fullName>PROMO</fullName>
                </value>
                <value>
                    <fullName>TUNE IN</fullName>
                </value>
                <value>
                    <fullName>--</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Daypart__c</fullName>
        <label>Daypart</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1-EM 6-9a</fullName>
                </value>
                <value>
                    <fullName>2-DT 9a-6p</fullName>
                </value>
                <value>
                    <fullName>4-PR 6-12a</fullName>
                </value>
                <value>
                    <fullName>6-LN 12-3a</fullName>
                </value>
                <value>
                    <fullName>7-OV 3-6a</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Programs__c</referenceTo>
        <relationshipLabel>Prelog Weeks</relationshipLabel>
        <relationshipName>Prelog_Weeks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <label>Version</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Week__c</fullName>
        <label>Week</label>
        <type>Date</type>
    </fields>
    <label>Prelog Week</label>
    <nameField>
        <displayFormat>PW-{0000}</displayFormat>
        <label>Prelog Weekly Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prelog Weeks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PrelogData__c.object
<CustomObject>
    <fields>
        <fullName>Commercial_Type__c</fullName>
        <label>WO Commercial Type</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hour_of_Day__c</fullName>
        <formula>IF(LEFT( ScheduleTime__c , 2)=&quot;1:&quot;,&quot;1&quot;, 
IF(LEFT( ScheduleTime__c , 2)=&quot;2:&quot;,&quot;2&quot;, 
IF(LEFT( ScheduleTime__c , 2)=&quot;3:&quot;,&quot;3&quot;, 
IF(LEFT( ScheduleTime__c , 2)=&quot;4:&quot;,&quot;4&quot;, 
IF(LEFT( ScheduleTime__c , 2)=&quot;5:&quot;,&quot;5&quot;,
IF(LEFT( ScheduleTime__c , 2)=&quot;6:&quot;,&quot;6&quot;,
IF(LEFT( ScheduleTime__c , 2)=&quot;7:&quot;,&quot;7&quot;,
IF(LEFT( ScheduleTime__c , 2)=&quot;8:&quot;,&quot;8&quot;,
IF(LEFT( ScheduleTime__c , 2)=&quot;9:&quot;,&quot;9&quot;,
IF(LEFT( ScheduleTime__c , 2)=&quot;10&quot;,&quot;10&quot;,
IF(LEFT( ScheduleTime__c , 2)=&quot;11&quot;,&quot;11&quot;,
IF(LEFT( ScheduleTime__c , 2)=&quot;12&quot;,&quot;12&quot;,

IF(LEFT( ScheduleTime__c , 2)=&quot;01&quot;,&quot;1&quot;, 
IF(LEFT( ScheduleTime__c , 2)=&quot;02&quot;,&quot;2&quot;, 
IF(LEFT( ScheduleTime__c , 2)=&quot;03&quot;,&quot;3&quot;, 
IF(LEFT( ScheduleTime__c , 2)=&quot;04&quot;,&quot;4&quot;, 
IF(LEFT( ScheduleTime__c , 2)=&quot;05&quot;,&quot;5&quot;,
IF(LEFT( ScheduleTime__c , 2)=&quot;06&quot;,&quot;6&quot;,
IF(LEFT( ScheduleTime__c , 2)=&quot;07&quot;,&quot;7&quot;,
IF(LEFT( ScheduleTime__c , 2)=&quot;08&quot;,&quot;8&quot;,
IF(LEFT( ScheduleTime__c , 2)=&quot;09&quot;,&quot;9&quot;,

&quot;FALSE&quot;)))))))))))))))))))))

&amp;

IF( RIGHT( ScheduleTime__c ,2)=&quot;am&quot;,&quot;am&quot;, 
IF( RIGHT( ScheduleTime__c ,2)=&quot;AM&quot;,&quot;am&quot;, 
IF( RIGHT( ScheduleTime__c ,2)=&quot;pm&quot;,&quot;pm&quot;, 
IF( RIGHT( ScheduleTime__c ,2)=&quot;PM&quot;,&quot;pm&quot;, 
IF( RIGHT( ScheduleTime__c ,2)=&quot;XM&quot;,&quot;am&quot;, 
IF( RIGHT( ScheduleTime__c ,2)=&quot;xm&quot;,&quot;am&quot;, 

&quot;False&quot;))))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Hour of Day</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Schedule__c</fullName>
        <label>Schedule</label>
        <referenceTo>Schedules__c</referenceTo>
        <relationshipLabel>Prelog Data</relationshipLabel>
        <relationshipName>Prelog_Data</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <label>Version</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Week__c</fullName>
        <formula>CASE( 
MOD(  AirDate__c - DATE(1900, 1, 7), 7), 
0, AirDate__c - 6, 
1, AirDate__c , 
2, AirDate__c -1, 
3, AirDate__c - 2, 
4,AirDate__c - 3, 
5, AirDate__c - 4, 
6, AirDate__c - 5, DATE(2001, 1, 1))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Week</label>
        <type>Date</type>
    </fields>
    <label>Prelog Data</label>
    <nameField>
        <displayFormat>Pre-{0000000}</displayFormat>
        <label>Prelog Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prelog Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Programs__c.object
<CustomObject>
    <description>Program/Distributor</description>
    <label>Program</label>
    <nameField>
        <label>Program</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Schedules__c.object
<CustomObject>
    <fields>
        <fullName>Daypart__c</fullName>
        <formula>IF(OR(LEFT(TEXT(MGM_HD_Daypart__c), 2) = &quot;DA&quot;, LEFT(TEXT(MGM_HD_Daypart__c), 2) = &quot;EM&quot;, LEFT(TEXT(MGM_HD_Daypart__c), 2) = &quot;ON&quot;, LEFT(TEXT(MGM_HD_Daypart__c), 2) = &quot;PR&quot;, LEFT(TEXT(MGM_HD_Daypart__c), 2) = &quot;LN&quot;, LEFT(TEXT(MGM_HD_Daypart__c), 2) = &quot;EF&quot;, LEFT(TEXT(MGM_HD_Daypart__c), 2) = &quot;LF&quot;),LEFT(TEXT(MGM_HD_Daypart__c), 2), CASE( MGM_HD_Daypart__c, 

&quot;9A-6P – Day&quot;,&quot;DA&quot;, 
&quot;Day Live Game&quot;,&quot;DA&quot;, 
&quot;6P-12A – PR&quot;,&quot;PR&quot;, 
&quot;Prime Live Game&quot;,&quot;PR&quot;, 
&quot;JC - MS 7p-12a&quot;,&quot;PR&quot;, 
&quot;6A-9A – EM&quot;,&quot;EM&quot;, 
&quot;3A-6A -- ON&quot;,&quot;ON&quot;, 
&quot;JC - MS 12a-5a&quot;,&quot;ON&quot;, 
&quot;12A-3A -- LN&quot;,&quot;LN&quot;, 
&quot;SS 9a-4p&quot;,&quot;DA&quot;, 
&quot;MS 12a-2a&quot;,&quot;WC&quot;,
&quot;MS 2a-6a&quot;,&quot;ON&quot;, 
&quot;MS 1p-6p&quot;,&quot;DA&quot;, 
&quot;WC - MS 12a-2a&quot;,&quot;WC&quot;, 
&quot;Matinee Game MS&quot;,&quot;DA&quot;, 
&quot;Prime Game MS&quot;,&quot;PR&quot;, 
&quot;MS 7p-12a&quot;,&quot;PR&quot;, 
&quot;ROS-&quot;,&quot;ROS-&quot;, 
&quot;&quot;) 
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Daypart</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Deal_Parent__c</fullName>
        <label>Deal Parent</label>
        <referenceTo>Deal__c</referenceTo>
        <relationshipLabel>Schedules</relationshipLabel>
        <relationshipName>Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Week__c</fullName>
        <label>Week</label>
        <type>Date</type>
    </fields>
    <label>Schedule</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/PrelogWeekBatchService.cls
public class PrelogWeekBatchService {

    public static Prelog_Week__c newPrelogWeekKey(PrelogData__c prelogData, Date startDate) {
        if (prelogData.Version__c == null) return null;
        if (prelogData.Hour_of_Day__c == null) return null;
        if (prelogData.Schedule__r.Week__c == null) return null;
        if (prelogData.Schedule__r.Deal_Parent__r.Program__c == null) return null;
        if (prelogData.Schedule__r.Deal_Parent__r.Brands__c == null) return null;
        if (prelogData.Schedule__r.Deal_Parent__r.Brands__r.Advertiser__c == null) return null;
        if (prelogData.Schedule__r.Deal_Parent__r.Brands__r.Advertiser__r.Commercial__c == null) return null;

        String daypart = calculateDaypart(prelogData.Hour_of_Day__c);
        return new Prelog_Week__c(
            Program__c = prelogData.Schedule__r.Deal_Parent__r.Program__c,
            Commercial_Type__c = prelogData.Schedule__r.Deal_Parent__r.Brands__r.Advertiser__r.Commercial__c,
            Week__c = startDate,
            Daypart__c = daypart,
            Version__c = Integer.valueOf(prelogData.Version__c)
        );

    }

    public static Prelog_Week__c newPrelogWeekKey(Prelog_Week__c prelogWeek) {
        return new Prelog_Week__c(
                Program__c = prelogWeek.Program__c,
                Commercial_Type__c = prelogWeek.Commercial_Type__c,
                Week__c = prelogWeek.Week__c,
                Daypart__c = prelogWeek.Daypart__c,
                Version__c = Integer.valueOf(prelogWeek.Version__c)
        );

    }

    public static List<Programs__c>  getPrograms(Set<String> programIds) {
        return [SELECT Id, Name FROM Programs__c WHERE Id IN :programIds];
    }

    public static List<Programs__c>  getPrograms() {
        return [SELECT Id, Name FROM Programs__c];
    }

    public static List<Prelog_Week__c>  getAllPrelogWeeksByProgram(Set<String> programIds, Date week) {
        return [
                SELECT Id, Program__c, Commercial_Type__c, Week__c, Daypart__c, Version__c
                FROM Prelog_Week__c
                WHERE Program__c IN :programIds
                AND Week__c = :week
                ORDER BY Name
        ];

    }

    private static final Map<String, String> hoursOfDayToDaypartMap = new Map<String, String>{
            '6am' => '1-EM 6-9a',
            '7am' => '1-EM 6-9a',
            '8am' => '1-EM 6-9a',
            '9am' => '2-DT 9a-6p',
            '10am' => '2-DT 9a-6p',
            '11am' => '2-DT 9a-6p',
            '12pm' => '2-DT 9a-6p',
            '1pm' => '2-DT 9a-6p',
            '2pm' => '2-DT 9a-6p',
            '3pm' => '2-DT 9a-6p',
            '4pm' => '2-DT 9a-6p',
            '5pm' => '2-DT 9a-6p',
            '6pm' => '4-PR 6-12a',
            '7pm' => '4-PR 6-12a',
            '8pm' => '4-PR 6-12a',
            '9pm' => '4-PR 6-12a',
            '10pm' => '4-PR 6-12a',
            '11m' => '4-PR 6-12a',
            '12am' => '6-LN 12-3a',
            '1am' => '6-LN 12-3a',
            '2am' => '6-LN 12-3a',
            '3am' => '7-OV 3-6a',
            '4am' => '7-OV 3-6a',
            '5am' => '7-OV 3-6a'
    };

    private static String calculateDaypart(String hourOfDay) {
        return hoursOfDayToDaypartMap.get(hourOfDay);
    }
}