objects/Advertiser__c.object
<CustomObject>
    <fields>
        <fullName>Duplicate_Approval__c</fullName>
        <description>Used to prevent duplicate advertisers from being created.</description>
        <label>Duplicate Approval</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Not Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Advertiser</label>
    <nameField>
        <label>Advertiser Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Advertisers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Brands__c.object
<CustomObject>
    <fields>
        <fullName>Advertiser__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Advertiser</label>
        <referenceTo>Advertiser__c</referenceTo>
        <relationshipLabel>Brands</relationshipLabel>
        <relationshipName>Brands</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approved_Duplicate__c</fullName>
        <label>Duplicate Approval</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Not Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>.Com/E-Commerce</fullName>
                </value>
                <value>
                    <fullName>Apparel/Accessories</fullName>
                </value>
                <value>
                    <fullName>Appliances/Home Gadgets</fullName>
                </value>
                <value>
                    <fullName>Attorney/General Legal Services</fullName>
                </value>
                <value>
                    <fullName>Attorney-Medical Services/Equipments/Prescriptions</fullName>
                </value>
                <value>
                    <fullName>Auto Accessories/Parts/Repair</fullName>
                </value>
                <value>
                    <fullName>Baby</fullName>
                </value>
                <value>
                    <fullName>Beauty/Cosmetics/Hair Care</fullName>
                </value>
                <value>
                    <fullName>Business/Professional Services</fullName>
                </value>
                <value>
                    <fullName>Charity</fullName>
                </value>
                <value>
                    <fullName>Cleaning Supplies</fullName>
                </value>
                <value>
                    <fullName>Crafts/Hobbies/Sporting goods/Toys</fullName>
                </value>
                <value>
                    <fullName>Education</fullName>
                </value>
                <value>
                    <fullName>Electronics/Software</fullName>
                </value>
                <value>
                    <fullName>Entertainment/Gaming</fullName>
                </value>
                <value>
                    <fullName>Fitness/Health/Medical Equipment</fullName>
                </value>
                <value>
                    <fullName>Food and Beverages</fullName>
                </value>
                <value>
                    <fullName>Home Improvement/Furniture</fullName>
                </value>
                <value>
                    <fullName>Insurance- Auto</fullName>
                </value>
                <value>
                    <fullName>Insurance- Health/ Dental/ Disability</fullName>
                </value>
                <value>
                    <fullName>Insurance- Life</fullName>
                </value>
                <value>
                    <fullName>Media/Telecom</fullName>
                </value>
                <value>
                    <fullName>Medical Services</fullName>
                </value>
                <value>
                    <fullName>Mental Health</fullName>
                </value>
                <value>
                    <fullName>Mobile Apps</fullName>
                </value>
                <value>
                    <fullName>Office Supplies</fullName>
                </value>
                <value>
                    <fullName>Pets</fullName>
                </value>
                <value>
                    <fullName>Pharmaceuticals/Drugs</fullName>
                </value>
                <value>
                    <fullName>Social Networking/Dating</fullName>
                </value>
                <value>
                    <fullName>Toiletry</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Brands</label>
    <nameField>
        <label>Brand</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Deal__c.object
<CustomObject>
    <fields>
        <fullName>Advertiser__c</fullName>
        <formula>Brands__r.Advertiser__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Advertiser</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Brands__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Brands</label>
        <referenceTo>Brands__c</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ClientCode__c</fullName>
        <formula>Program__r.ClientCode__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ClientCode</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Type__c</field>
                <operation>notEqual</operation>
                <value>history</value>
            </filterItems>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>Do Not Call</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PI__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether a deal represents a PI deal.</description>
        <label>PI</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Program</label>
        <referenceTo>Programs__c</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Sold</fullName>
                    <default>true</default>
                    <label>Sold</label>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Historical</fullName>
                </value>
                <value>
                    <fullName>Budget</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Deal</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Deal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Programs__c.object
<CustomObject>
    <description>Program/Distributor</description>
    <fields>
        <fullName>ClientCode__c</fullName>
        <description>Assigned by Finance</description>
        <inlineHelpText>Assigned by Finance</inlineHelpText>
        <label>ClientCode</label>
        <length>3</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestAddUpdateTarget.cls
/*
    Name        : TestAfterInsertUpdateDeal
    Description : It is a test class for "AfterInsertUpdateDeal" Trigger
*/
@isTest
public class TestAddUpdateTarget{
    @isTest
    public static void test(){
        //Creating new Programs__c
        /**Programs__c newProgram = new Programs__c(name='XX',ClientCode__c='xx');
        insert newProgram;
        //Creating new Advertiser__c
        Advertiser__c advertiser = new Advertiser__c(Duplicate_Approval__c = 'Approved');
        insert advertiser;
         
        Brands__c brand = new Brands__c();
        brand.Name = 'Availability';
        brand.Category__c = 'Other';
        brand.Advertiser__c = advertiser.id;
        brand.Approved_Duplicate__c = 'Approved' ;
        insert brand;

        Contact con = new Contact(LastName = 'Test') ;
        insert con ;

        //Creating new Dealobject
        Deal__c newDeal = new Deal__c(Program__c=newProgram.id,Brands__c=brand.id,Status__c='Historical',PI__c=false, Contact__c = con.Id);
        insert newDeal;
        upsert newDeal;
        List<Targets__c> lstTargets = [select id,Target_Name__c from targets__c 
                                        where Target_Name__c=:(newProgram.name+'-'+brand.name)];
        //System.assert(lstTargets.size()>0,'Didnot find corresponding Target');
	**/
    }
}