objects/Brands__c.object
<CustomObject>
    <label>Brands</label>
    <nameField>
        <label>Brand</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Deal__c.object
<CustomObject>
    <fields>
        <fullName>Agency_Deal_Number__c</fullName>
        <externalId>true</externalId>
        <label>Agency Deal Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Brands__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Brands</label>
        <referenceTo>Brands__c</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Campaign__c</fullName>
        <description>Campaign for a specific brand</description>
        <label>Campaign</label>
        <length>52</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>[Dep]Client Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ContactAccount__c</fullName>
        <formula>Contact__r.Account.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ContactAccount</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Type__c</field>
                <operation>notEqual</operation>
                <value>history</value>
            </filterItems>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>Do Not Call</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Length__c</fullName>
        <label>Length</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>30</fullName>
                    <color>#0B6FCE</color>
                    <label>30</label>
                </value>
                <value>
                    <fullName>60</fullName>
                    <color>#78C953</color>
                    <label>60</label>
                </value>
                <value>
                    <fullName>120</fullName>
                    <color>#E27001</color>
                    <label>120</label>
                </value>
                <value>
                    <fullName>300</fullName>
                    <color>#A845DC</color>
                    <label>300</label>
                </value>
                <value>
                    <fullName>15</fullName>
                    <color>#F3D904</color>
                    <label>15</label>
                </value>
                <value>
                    <fullName>1710</fullName>
                    <color>#A53711</color>
                    <label>1710</label>
                </value>
                <value>
                    <fullName>90</fullName>
                    <color>#66E9BD</color>
                    <label>90</label>
                </value>
                <value>
                    <fullName>180</fullName>
                    <color>#0B24BE</color>
                    <label>180</label>
                </value>
                <value>
                    <fullName>240</fullName>
                    <color>#419249</color>
                    <label>240</label>
                </value>
                <value>
                    <fullName>45</fullName>
                </value>
                <value>
                    <fullName>75</fullName>
                </value>
                <value>
                    <fullName>05</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>150</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>105</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>35</fullName>
                </value>
                <value>
                    <fullName>40</fullName>
                </value>
                <value>
                    <fullName>1714</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Network_Deal_Number__c</fullName>
        <description>Deal number in Network&apos;s paper work, in Network&apos;s records.</description>
        <externalId>true</externalId>
        <inlineHelpText>Deal number in Network&apos;s paper work, in Network&apos;s records.  Equals 1 if the PI campaign is no longer airing on the network.</inlineHelpText>
        <label>Network Deal Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Program</label>
        <referenceTo>Programs__c</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sum_of_Total_Dollars__c</fullName>
        <inlineHelpText>Sum of Total Dollars for the schedules for this deal.</inlineHelpText>
        <label>Sum of Total Dollars</label>
        <summarizedField>Schedules__c.Dollars_Booked__c</summarizedField>
        <summaryForeignKey>Schedules__c.Deal_Parent__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Sum_of_Units_Available__c</fullName>
        <label>Sum of Units Available</label>
        <summarizedField>Schedules__c.Units_Available__c</summarizedField>
        <summaryFilterItems>
            <field>Schedules__c.Status__c</field>
            <operation>equals</operation>
            <value>Sold</value>
        </summaryFilterItems>
        <summaryForeignKey>Schedules__c.Deal_Parent__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Week_MIN_Field__c</fullName>
        <label>Week MIN Field</label>
        <summarizedField>Schedules__c.Week__c</summarizedField>
        <summaryForeignKey>Schedules__c.Deal_Parent__c</summaryForeignKey>
        <summaryOperation>min</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Deal</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Deal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Programs__c.object
<CustomObject>
    <description>Program/Distributor</description>
    <label>Program</label>
    <nameField>
        <label>Program</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Schedules__c.object
<CustomObject>
    <fields>
        <fullName>Deal_Parent__c</fullName>
        <label>Deal Parent</label>
        <referenceTo>Deal__c</referenceTo>
        <relationshipLabel>Schedules</relationshipLabel>
        <relationshipName>Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>LF_Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Brand for Long Form.  Received in Allocation letter post deal</description>
        <label>[Dep]LF Brand</label>
        <referenceTo>Brands__c</referenceTo>
        <relationshipLabel>Schedules</relationshipLabel>
        <relationshipName>Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Network_Deal_Number__c</fullName>
        <formula>Deal_Parent__r.Network_Deal_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Network Deal Number</label>
        <type>Text</type>
    </fields>
    <label>Schedule</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/DealSearchController.cls
public class DealSearchController {
    public Schedules__c schedule { get; set; }
    public Deal__c deal { get; set; }
    public List<Deal__c> dealList { get; set; }
    public Boolean hasDeals { get; set; }
    public String dealId { get; set; }

    //Constructor definition
    public DealSearchController() {
        schedule = new Schedules__c();
        deal = new Deal__c();
        hasDeals = false;
    }

    //Method to Getting records
    public PageReference search() {
        hasDeals = true;
        getDealSection();
        return null;
    }
    //Method getting records for Deal Section
    private void getDealSection() {
        String agencyDealNumber;
        String networkDealNumber;
        String conId;
        String dealName;
        String brand;
        String agency;
        String program;
        String pid;
        String clId;
        String bid;
        String cid;

        String whereAnd = 'WHERE ';
        String dealQuery = 'SELECT id, Name, Program__c, Brands__c, Contact__c, Length__c, Campaign__c, Client_Account__c, ';
        dealQuery += 'Week_MIN_Field__c, Agency_Deal_Number__c, Network_Deal_Number__c, Sum_of_Total_Dollars__c, ';
        dealQuery += 'Sum_of_Units_Available__c, Program__r.Id, Contact__r.Id, Contact__r.Account.ID, Brands__r.Id, ';
        dealQuery += 'Program__r.Name, Contact__r.Name, Client_Account__r.Name, Brands__r.Name ,createdDate, ContactAccount__c ';
        dealQuery += ' FROM Deal__c ';

        if (schedule.Deal_Parent__c != null) {
            dealId = schedule.Deal_Parent__c;
            dealQuery += whereAnd + 'Id =: dealId ';
            whereAnd = 'AND ';
        }
        if (deal.Program__c != null) {
            pid = deal.Program__c;
            dealQuery += whereAnd + 'Program__c =: pid ';
            whereAnd = 'AND ';
        }
        if (deal.Client_Account__c != null) {
            clId = deal.Client_Account__c;
            dealQuery += whereAnd + 'Contact__r.Account.id =: clId ';
            whereAnd = 'AND ';
        }
        if (schedule.LF_Brand__c != null) {
            bid = schedule.LF_Brand__c;
            dealQuery += whereAnd + 'Brands__c =: bid ';
            whereAnd = 'AND ';
        }
        if (deal.Contact__c != null) {
            cid = deal.Contact__c;
            dealQuery += whereAnd + 'Contact__c =: cid ';
            whereAnd = 'AND ';
        }

        if (deal.Agency_Deal_Number__c != null && deal.Agency_Deal_Number__c.trim().length() > 0) {
            agencyDealNumber = deal.Agency_Deal_Number__c;
            dealQuery += whereAnd + 'Agency_Deal_Number__c =: agencyDealNumber ';
            whereAnd = 'AND ';
        }

        if (deal.Network_Deal_Number__c != null && deal.Network_Deal_Number__c.trim().length() > 0) {
            networkDealNumber = deal.Network_Deal_Number__c;
            dealQuery += whereAnd + 'Network_Deal_Number__c =: networkDealNumber ';
            whereAnd = 'AND ';
        }

        dealQuery += 'ORDER BY Week_MIN_Field__c DESC, Brands__r.Name  LIMIT 1000 ';
        dealList = Database.query(dealQuery);
        if (dealList.size() > 0) {
            hasDeals = true;
        } else {
            hasDeals = false;
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'No DEALS Found..!'));
        }
    }
}