objects/Brands__c.object
<CustomObject>
    <fields>
        <fullName>Advertiser__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Advertiser</label>
        <referenceTo>Advertiser__c</referenceTo>
        <relationshipLabel>Brands</relationshipLabel>
        <relationshipName>Brands</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Brands</label>
    <nameField>
        <label>Brand</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Deal__c.object
<CustomObject>
    <fields>
        <fullName>Advertiser__c</fullName>
        <formula>Brands__r.Advertiser__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Advertiser</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Brands__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Brands</label>
        <referenceTo>Brands__c</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ClientCode__c</fullName>
        <formula>Program__r.ClientCode__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ClientCode</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Type__c</field>
                <operation>notEqual</operation>
                <value>history</value>
            </filterItems>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>Do Not Call</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Estimate__c</fullName>
        <label>Estimate</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Length__c</fullName>
        <label>Length</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>30</fullName>
                    <color>#0B6FCE</color>
                    <label>30</label>
                </value>
                <value>
                    <fullName>60</fullName>
                    <color>#78C953</color>
                    <label>60</label>
                </value>
                <value>
                    <fullName>120</fullName>
                    <color>#E27001</color>
                    <label>120</label>
                </value>
                <value>
                    <fullName>300</fullName>
                    <color>#A845DC</color>
                    <label>300</label>
                </value>
                <value>
                    <fullName>15</fullName>
                    <color>#F3D904</color>
                    <label>15</label>
                </value>
                <value>
                    <fullName>1710</fullName>
                    <color>#A53711</color>
                    <label>1710</label>
                </value>
                <value>
                    <fullName>90</fullName>
                    <color>#66E9BD</color>
                    <label>90</label>
                </value>
                <value>
                    <fullName>180</fullName>
                    <color>#0B24BE</color>
                    <label>180</label>
                </value>
                <value>
                    <fullName>240</fullName>
                    <color>#419249</color>
                    <label>240</label>
                </value>
                <value>
                    <fullName>45</fullName>
                </value>
                <value>
                    <fullName>75</fullName>
                </value>
                <value>
                    <fullName>05</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>150</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>105</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>35</fullName>
                </value>
                <value>
                    <fullName>40</fullName>
                </value>
                <value>
                    <fullName>1714</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Network_Deal_Number__c</fullName>
        <description>Deal number in Network&apos;s paper work, in Network&apos;s records.</description>
        <externalId>true</externalId>
        <inlineHelpText>Deal number in Network&apos;s paper work, in Network&apos;s records.  Equals 1 if the PI campaign is no longer airing on the network.</inlineHelpText>
        <label>Network Deal Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <label>[Dep]Rate</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Deal</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Deal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Programs__c.object
<CustomObject>
    <description>Program/Distributor</description>
    <fields>
        <fullName>Cable_Synd__c</fullName>
        <label>Cable/Synd/PP</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cable</fullName>
                </value>
                <value>
                    <fullName>Syndication</fullName>
                </value>
                <value>
                    <fullName>PP</fullName>
                </value>
                <value>
                    <fullName>Bundle</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ClientCode__c</fullName>
        <description>Assigned by Finance</description>
        <inlineHelpText>Assigned by Finance</inlineHelpText>
        <label>ClientCode</label>
        <length>3</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Clock_Start_Time__c</fullName>
        <label>Clock Start Time</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>5AM</fullName>
                </value>
                <value>
                    <fullName>6AM</fullName>
                </value>
                <value>
                    <fullName>4AM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Station_Call_Letter__c</fullName>
        <label>Station Call Letter</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Schedules__c.object
<CustomObject>
    <fields>
        <fullName>Bundle_Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bundle Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Cancel_Date__c</fullName>
        <description>Updated by workflow that inputs the date field is canceled</description>
        <label>Cancel Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Day__c</fullName>
        <label>Day</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Deal_Parent__c</fullName>
        <label>Deal Parent</label>
        <referenceTo>Deal__c</referenceTo>
        <relationshipLabel>Schedules</relationshipLabel>
        <relationshipName>Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Discrepancy_Comment__c</fullName>
        <description>Used internally for comments regarding the error/discrepancy.</description>
        <inlineHelpText>Used internally for comments regarding the error or discrepancy.</inlineHelpText>
        <label>[Dep]Discrepancy Comment</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>LF_Rate_Needed__c</fullName>
        <description>Rate needed for rebooking of a long form schedule, based on agency results.</description>
        <inlineHelpText>Rate needed for rebooking of a long form schedule, based on agency results.</inlineHelpText>
        <label>[Dep]LF Rate Needed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Network_Deal_Number__c</fullName>
        <formula>Deal_Parent__r.Network_Deal_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Network Deal Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Performance__c</fullName>
        <label>Performance %</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <label>Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <label>Start Time</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>MGM_HD_Daypart__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>01:00A</fullName>
                </value>
                <value>
                    <fullName>01:30A</fullName>
                </value>
                <value>
                    <fullName>02:00A</fullName>
                </value>
                <value>
                    <fullName>02:30A</fullName>
                </value>
                <value>
                    <fullName>03:00A</fullName>
                </value>
                <value>
                    <fullName>03:30A</fullName>
                </value>
                <value>
                    <fullName>04:00A</fullName>
                </value>
                <value>
                    <fullName>04:30A</fullName>
                </value>
                <value>
                    <fullName>05:00A</fullName>
                </value>
                <value>
                    <fullName>05:30A</fullName>
                </value>
                <value>
                    <fullName>06:00A</fullName>
                    <default>true</default>
                    <label>06:00A</label>
                </value>
                <value>
                    <fullName>06:30A</fullName>
                </value>
                <value>
                    <fullName>07:00A</fullName>
                </value>
                <value>
                    <fullName>07:30A</fullName>
                </value>
                <value>
                    <fullName>08:00A</fullName>
                </value>
                <value>
                    <fullName>08:30A</fullName>
                </value>
                <value>
                    <fullName>09:00A</fullName>
                </value>
                <value>
                    <fullName>09:30A</fullName>
                </value>
                <value>
                    <fullName>10:00A</fullName>
                </value>
                <value>
                    <fullName>10:30A</fullName>
                </value>
                <value>
                    <fullName>11:00A</fullName>
                </value>
                <value>
                    <fullName>11:30A</fullName>
                </value>
                <value>
                    <fullName>12:00P</fullName>
                </value>
                <value>
                    <fullName>12:30P</fullName>
                </value>
                <value>
                    <fullName>01:00P</fullName>
                </value>
                <value>
                    <fullName>01:30P</fullName>
                </value>
                <value>
                    <fullName>02:00P</fullName>
                </value>
                <value>
                    <fullName>02:30P</fullName>
                </value>
                <value>
                    <fullName>03:00P</fullName>
                </value>
                <value>
                    <fullName>03:30P</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Units_Available__c</fullName>
        <label>Units Available</label>
        <precision>17</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Week__c</fullName>
        <label>Week</label>
        <type>Date</type>
    </fields>
    <label>Schedule</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/SaberGFTest.cls
@IsTest
public with sharing class SaberGFTest {
    @IsTest static void SaberGF_formatTime_CorrectlyFormattedTime() {
        Date testDate = Date.newInstance(2, 4, 6);
        System.assertEquals(SaberGF.FormatTime(testDate, 'Ft'), '19:00:00');
    }

    @IsTest static void SaberGF_formatDate_dateFormattedFromFormatString() {
        Date testDate = Date.newInstance(2, 4, 6);
        //test all the documented format strings (and a few undocumented ones)
        System.assertEquals(SaberGF.formatDate(testDate, 'Fd'), '04/06/2');
        System.assertEquals(SaberGF.formatDate(testDate, 'FD'), '04/06/2');
        System.assertEquals(SaberGF.formatDate(testDate, 'FM'), 'April 06');
        System.assertEquals(SaberGF.formatDate(testDate, 'FY'), 'April, 2');
        //this is undocumented
        System.assertEquals(SaberGF.formatDate(testDate, 'FQD'), '2-04-06');
        //this is undocumented
        System.assertEquals(SaberGF.formatDate(testDate, 'LFD'), 'April 06, 2');
        System.assertEquals(SaberGF.formatDate(testDate, 'YYYY'), '2');
        System.assertEquals(SaberGF.formatDate(testDate, 'MMMM'), 'April');
        System.assertEquals(SaberGF.formatDate(testDate, 'MMM'), 'April');
        System.assertEquals(SaberGF.formatDate(testDate, 'MM'), '04');
        System.assertEquals(SaberGF.formatDate(testDate, 'M'), '4');
        System.assertEquals(SaberGF.formatDate(testDate, 'DDDD'), 'Saturday');
        System.assertEquals(SaberGF.formatDate(testDate, 'DDD'), 'Sat');
        System.assertEquals(SaberGF.formatDate(testDate, 'DD'), '06');
        System.assertEquals(SaberGF.formatDate(testDate, 'D'), '6');
        try{
            System.debug(SaberGF.formatDate(testDate, 'YY'));
        }
        catch (System.StringException e){
            //not sure why this crashes but it does
            System.assert(true);
        }
    }

    @IsTest static void SaberGF_TemplateToString_stringFormattedByFormatSpecifier() {
        Deal__c testDeal = createDeal('5');
        Advertiser__c testAdvertiser = createAdvertiser();
        insert testAdvertiser;
        Brands__c testBrand = createBrand(testAdvertiser);
        insert testBrand;
        testDeal.Brands__c = testBrand.Id;
        insert testDeal;
        Schedules__c testSchedule = createSchedule(testDeal);
        testSchedule.Rate__c = 5;
        testSchedule.Cancel_Date__c = Date.newInstance(1990, 1, 2);
        testSchedule.Performance__c = 25;
        testSchedule.Day__c = Date.newInstance(1990, 1, 1);
        testSchedule.Bundle_Approved__c = true;
        testSchedule.LF_Rate_Needed__c = 6.23;
        testSchedule.Discrepancy_Comment__c = 'this is a comment';
        insert testSchedule;
        //First argument is any field of the object passed in as the second argument surrounded by {! and }
        System.assertEquals(SaberGF.TemplateToString('{!Rate__c} {!Cancel_Date__c}, {!Performance__c}, {!Day__c}, {!Bundle_Approved__c}, {!LF_Rate_Needed__c}, {!Discrepancy_Comment__c}, {!Cancel_Date__c}', 'Schedules__c', testSchedule.Id, true), '$5.00 1/2/1990 12:00 AM, 25%, 1/1/1990, TRUE, $6.23, this is a comment, 1/2/1990 12:00 AM');
        System.assertEquals(SaberGF.TemplateToString('{!Estimate__c}', 'Deal__c', testDeal.Id, true), '');
        System.assertEquals(SaberGF.TemplateToString('{!Rate__c}', 'Deal__c', testDeal.Id, true), '$0.00');
    }

    @IsTest static void SaberGF_GetObjectsFieldsTest_returnsAllObjectFields() {
        System.debug(SaberGF.GetObjectsFields('Deal__c', true, true, true));
        //this will error but the error is caught in the function
        System.debug(SaberGF.GetObjectsFields('Schedule__c', false, false, false));
        System.debug(SaberGF.GetObjectsFields('Schedules__c', false, false, false));
    }

    @IsTest static void SaberGF_ReturnDynamicQueryList_returnsListAsString() {
        List<String> stringList = new List<String>{'test1', 'test2', 'test3'};
        List<String> shortList = new List<String>{''};
        List<String> nullTest = null;
        System.assertEquals(SaberGF.ReturnDynamicQueryList(stringList), '(\'test1\',\'test2\',\'test3\')');
        System.assertEquals(SaberGF.ReturnDynamicQueryList(shortList), '(\'\')');
        System.assertEquals(SaberGF.ReturnDynamicQueryList(new List<String>()), '(\'\')');
        System.assertEquals(SaberGF.ReturnDynamicQueryList(nullTest), '(\'\')');
    }

    @IsTest static void SaberGF_ReturnDynamicQueryListSet_returnsSetAsString() {
        Set<String> stringSetTest = new Set<String>{
                'test1', 'test2', 'test3'
        };
        Set<String> nullSet = new Set<String>{
                null
        };
        Set<String> emptySet = new Set<String>();
        Set<String> nullTest = null;
        System.assertEquals(SaberGF.ReturnDynamicQueryList(stringSetTest), '(\'test1\',\'test2\',\'test3\')');
        System.assertEquals(SaberGF.ReturnDynamicQueryList(nullSet), '(\'null\')');
        System.assertEquals(SaberGF.ReturnDynamicQueryList(emptySet), '(\'\')');
        System.assertEquals(SaberGF.ReturnDynamicQueryList(nullTest), '(\'\')');
    }

    @IsTest static void SaberGF_GetValue_returnsValueOfStringOrDecimal() {
        String nullString = null;
        System.assertEquals(SaberGF.GetValue(nullString), '');
        System.assertEquals(SaberGF.GetValue('test'), 'test');
        Decimal nullDecimal = null;
        System.assertEquals(SaberGF.GetValue(nullDecimal), 0);
        System.assertEquals(SaberGF.GetValue(5), 5);
    }

    @IsTest static void SaberGF_getObjectsFieldsForQueriesFromFieldSet() {
        System.debug(SaberGF.getObjectsFieldsForQueriesFromFieldSet('Schedules__c', 'Advertiser__c'));
    }

    @IsTest static void SaberGF_GetObjectsFieldsForQueries_ListOfFields() {
        System.debug(SaberGF.GetObjectsFieldsForQueries('Deal__c'));
    }

    @IsTest static void SaberGF_CurrencyFormat_formattedCurrencyString() {
        System.assertEquals(SaberGF.CurrencyFormat(null), '$0.00');
        System.assertEquals(SaberGF.CurrencyFormat(0.1), '$0.10');
        System.assertEquals(SaberGF.CurrencyFormat(1.1), '$1.10');
        System.assertEquals(SaberGF.CurrencyFormat(1), '$1.00');
    }

    private static Account createAccount() {
        Account testAcct = new Account();
        testAcct.Name = 'Test Account';
        testAcct.BillingCity = 'Wakarusa';
        insert testAcct;
        return testAcct;
    }

    private static Contact createContact(Account testAcct){
        Contact contact = new Contact();
        contact.FirstName = 'Test';
        contact.LastName = 'Name';
        contact.Email = 'test@testemail.com';
        contact.Phone = '(758) 771-0091';
        contact.Account = testAcct;
        insert contact;
        return contact;
    }

    private static Programs__c createProgram(String dealNumber) {
        Programs__c program = new Programs__c();
        program.Name = 'test';
        program.Cable_Synd__c = 'Cable';
        program.Station_Call_Letter__c = 'AWED';
        program.ClientCode__c = dealNumber;
        program.Clock_Start_Time__c = '';
        insert program;
        return program;
    }

    static Deal__c createDeal(String dealNumber) {
        Account testAccount = createAccount();
        Contact testContact = createContact(testAccount);
        Deal__c testDeal = new Deal__c();
        testDeal.Contact__c = testContact.Id;
        testDeal.Network_Deal_Number__c = dealNumber;
        testDeal.Length__c = '5';
        return testDeal;
    }

    private static Schedules__c createSchedule(Deal__c testDeal) {

        Schedules__c schedule = new Schedules__c();
        schedule.Week__c = Date.today().toStartOfWeek().addDays(-6);
        schedule.Units_Available__c = 5;
        schedule.Units_Available__c = 5;
        schedule.Deal_Parent__c = testDeal.Id;
        schedule.Days_Allowed__c = 'Mon';
        schedule.Start_Time__c = '06:00A';
        schedule.End_Time__c = '06:30A';
        schedule.Rate__c = 100;
        schedule.Units_Available__c = 5;
        return schedule;
    }

    private static Advertiser__c createAdvertiser() {
        return new Advertiser__c(Duplicate_Approval__c = 'Approved');
    }

    private static Brands__c createBrand(Advertiser__c advertiser) {
        Brands__c brand = new Brands__c();
        brand.Name = 'Availability';
        brand.Category__c = 'Other';
        brand.Advertiser__c = advertiser.Id;
        brand.Approved_Duplicate__c = 'Approved';
        return brand;
    }
}