objects/Brands__c.object
<CustomObject>
    <label>Brands</label>
    <nameField>
        <label>Brand</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Deal__c.object
<CustomObject>
    <fields>
        <fullName>Brands__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Brands</label>
        <referenceTo>Brands__c</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ContactAccount__c</fullName>
        <formula>Contact__r.Account.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ContactAccount</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Type__c</field>
                <operation>notEqual</operation>
                <value>history</value>
            </filterItems>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>Do Not Call</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Length__c</fullName>
        <label>Length</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>30</fullName>
                    <color>#0B6FCE</color>
                    <label>30</label>
                </value>
                <value>
                    <fullName>60</fullName>
                    <color>#78C953</color>
                    <label>60</label>
                </value>
                <value>
                    <fullName>120</fullName>
                    <color>#E27001</color>
                    <label>120</label>
                </value>
                <value>
                    <fullName>300</fullName>
                    <color>#A845DC</color>
                    <label>300</label>
                </value>
                <value>
                    <fullName>15</fullName>
                    <color>#F3D904</color>
                    <label>15</label>
                </value>
                <value>
                    <fullName>1710</fullName>
                    <color>#A53711</color>
                    <label>1710</label>
                </value>
                <value>
                    <fullName>90</fullName>
                    <color>#66E9BD</color>
                    <label>90</label>
                </value>
                <value>
                    <fullName>180</fullName>
                    <color>#0B24BE</color>
                    <label>180</label>
                </value>
                <value>
                    <fullName>240</fullName>
                    <color>#419249</color>
                    <label>240</label>
                </value>
                <value>
                    <fullName>45</fullName>
                </value>
                <value>
                    <fullName>75</fullName>
                </value>
                <value>
                    <fullName>05</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>150</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>105</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>35</fullName>
                </value>
                <value>
                    <fullName>40</fullName>
                </value>
                <value>
                    <fullName>1714</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Program</label>
        <referenceTo>Programs__c</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <label>[Dep]Rate</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SF_Deal_ID__c</fullName>
        <description>Used for sending emails to Salesforce so that they can be filed directly to the Deal</description>
        <formula>&quot;(ref:&quot; &amp; Id &amp; &quot;)&quot;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Used for sending emails to Salesforce so that they can be filed directly to the Deal</inlineHelpText>
        <label>SF Deal ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Sold</fullName>
                    <default>true</default>
                    <label>Sold</label>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Historical</fullName>
                </value>
                <value>
                    <fullName>Budget</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sum_of_Total_Dollars__c</fullName>
        <inlineHelpText>Sum of Total Dollars for the schedules for this deal.</inlineHelpText>
        <label>Sum of Total Dollars</label>
        <summarizedField>Schedules__c.Dollars_Booked__c</summarizedField>
        <summaryForeignKey>Schedules__c.Deal_Parent__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Sum_of_Units_Available__c</fullName>
        <label>Sum of Units Available</label>
        <summarizedField>Schedules__c.Units_Available__c</summarizedField>
        <summaryFilterItems>
            <field>Schedules__c.Status__c</field>
            <operation>equals</operation>
            <value>Sold</value>
        </summaryFilterItems>
        <summaryForeignKey>Schedules__c.Deal_Parent__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Week_MIN_Field__c</fullName>
        <label>Week MIN Field</label>
        <summarizedField>Schedules__c.Week__c</summarizedField>
        <summaryForeignKey>Schedules__c.Deal_Parent__c</summaryForeignKey>
        <summaryOperation>min</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Deal</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Deal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Programs__c.object
<CustomObject>
    <description>Program/Distributor</description>
    <fields>
        <fullName>Reconciled_Week__c</fullName>
        <inlineHelpText>The last fully reconciled week in Salesforce</inlineHelpText>
        <label>Reconciled Week</label>
        <type>Date</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Schedules__c.object
<CustomObject>
    <fields>
        <fullName>DaysAllowedFormula__c</fullName>
        <formula>IF ( INCLUDES ( Days_Allowed__c , &quot;Mon&quot; ) , &quot;M&quot; , &quot;-&quot; ) &amp;
IF ( INCLUDES ( Days_Allowed__c , &quot;Tue&quot; ) , &quot;T&quot; , &quot;-&quot; ) &amp;
IF ( INCLUDES ( Days_Allowed__c , &quot;Wed&quot; ) , &quot;W&quot; , &quot;-&quot; ) &amp;
IF ( INCLUDES ( Days_Allowed__c , &quot;Thu&quot; ) , &quot;T&quot; , &quot;-&quot; ) &amp;
IF ( INCLUDES ( Days_Allowed__c , &quot;Fri&quot; ) , &quot;F&quot; , &quot;-&quot; ) &amp;
IF ( INCLUDES ( Days_Allowed__c , &quot;Sat&quot; ) , &quot;Sa&quot; , &quot;-&quot; ) &amp;
IF ( INCLUDES ( Days_Allowed__c , &quot;Sun&quot; ) , &quot;Su&quot; , &quot;-&quot; )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Days Allowed Formula</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Deal_Parent__c</fullName>
        <label>Deal Parent</label>
        <referenceTo>Deal__c</referenceTo>
        <relationshipLabel>Schedules</relationshipLabel>
        <relationshipName>Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Dollars_Booked__c</fullName>
        <formula>if( or(ispickval( Status__c , &quot;Canceled&quot;),Units_Aired__c &lt; 0), 0, 

Units_Available__c * Rate__c

)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Booked Dollars</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Filler__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check if this order is Filler to be used in case of a tape or inventory issue.</description>
        <inlineHelpText>Check if this order is Filler to be used in case of a tape or inventory issue.</inlineHelpText>
        <label>[Dep]Filler</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MilitaryTime__c</fullName>
        <formula>CASE ( TEXT ( Start_Time__c ) ,
&quot;06:00A&quot;,0,
&quot;06:30A&quot;,1,
&quot;07:00A&quot;,2,
&quot;07:30A&quot;,3,
&quot;08:00A&quot;,4,
&quot;08:30A&quot;,5,
&quot;09:00A&quot;,6,
&quot;09:30A&quot;,7,
&quot;10:00A&quot;,8,
&quot;10:30A&quot;,9,
&quot;11:00A&quot;,10,
&quot;11:30A&quot;,11,
&quot;12:00P&quot;,12,
&quot;12:30P&quot;,13,
&quot;01:00P&quot;,14,
&quot;01:30P&quot;,15,
&quot;02:00P&quot;,16,
&quot;02:30P&quot;,17,
&quot;03:00P&quot;,18,
&quot;03:30P&quot;,19,
&quot;04:00P&quot;,20,
&quot;04:30P&quot;,21,
&quot;05:00P&quot;,22,
&quot;05:30P&quot;,23,
&quot;06:00P&quot;,24,
&quot;06:30P&quot;,25,
&quot;07:00P&quot;,26,
&quot;07:30P&quot;,27,
&quot;08:00P&quot;,28,
&quot;08:30P&quot;,29,
&quot;09:00P&quot;,30,
&quot;09:30P&quot;,31,
&quot;10:00P&quot;,32,
&quot;10:30P&quot;,33,
&quot;11:00P&quot;,34,
&quot;11:30P&quot;,35,
&quot;12:00A&quot;,36,
&quot;12:30A&quot;,37,
&quot;01:00A&quot;,38,
&quot;01:30A&quot;,39,
&quot;02:00A&quot;,40,
&quot;02:30A&quot;,41,
&quot;03:00A&quot;,42,
&quot;03:30A&quot;,43,
&quot;04:00A&quot;,44,
&quot;04:30A&quot;,45,
&quot;05:00A&quot;,46,
47)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Military Time</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OrderNumber__c</fullName>
        <label>OrderNumber</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <label>Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Reconciled__c</fullName>
        <formula>if( LF_Week__c &lt;= Deal_Parent__r.Program__r.Reconciled_Week__c , &quot;Y&quot;, &quot;N&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Reconciled</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_End_Time__c</fullName>
        <formula>TEXT(Start_Time__c) &amp;&quot;-&quot;&amp; TEXT( End_Time__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Start End Time</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Sold</fullName>
                    <default>true</default>
                    <label>Sold</label>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Dollars__c</fullName>
        <formula>if(  PI_Payout_TEST__c &gt;0,  PI_Payout_TEST__c *20/17, 

if( PI_Payout__c &gt; 0 ,  PI_Payout__c * 20/17, 

if( Units_Aired__c &lt; 0,  0,
CASE(Deal_Parent__r.Status__c, &quot;Canceled&quot;, 0,  &quot;Pre-Empted&quot;, 0,

 Rate__c  *   Units_Aired__c)

)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Dollars</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>UnitLength__c</fullName>
        <formula>VALUE(TEXT(Deal_Parent__r.Length__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>UnitLength</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Units_Aired__c</fullName>
        <formula>case( Status__c, &quot;Canceled&quot;, 0, Units_Available__c - Units_Preempted__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Units Aired</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Units_Available__c</fullName>
        <label>Units Available</label>
        <precision>17</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Week__c</fullName>
        <label>Week</label>
        <type>Date</type>
    </fields>
    <label>Schedule</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/DoubleCheckReadOnly.cls
public virtual class DoubleCheckReadOnly {

    // Mocking Selectors
    private static DealSelector dealSelector = new DealSelector();
    public static void setDealSelector(DealSelector dSelector) {
        dealSelector = dSelector;
    }
    private static ScheduleSelector scheduleSelector = new ScheduleSelector();
    public static void setScheduleSelector(ScheduleSelector scSelector) {
        scheduleSelector = scSelector;
    }
    private static PeriodSelector periodSelector = new PeriodSelector();
    public static void setPeriodSelector(PeriodSelector pSelector) {
        periodSelector = pSelector;
    }

    public DateSelector dates = new DateSelector();

    public List<String> testlist;
    public Set<String> testset;
    public List<List<SObject>> DealSearchList;
    public List<DoubleCheckReadOnlyHelper.WeekModel> quarterweek { get; set; }
    public List<DoubleCheckReadOnlyHelper.HeadingModel> headingModels { get; set; }
    public List<Date> quarterdates { get; set; }
    public List<Deal__c> DealResultList { get; set; }
    public List<DoubleCheckReadOnlyHelper.DealWrapper> DealWrapperList { get; set; }
    public Set<Id> DealWrapperIdSet { get; set; }
    public List<String> SearchList;
    public String Searchfield { get; set; }
    public String DealId { get; set; }
    public String cellrate { get; set; }
    public String cellUnits { get; set; }
    public String CellId { get; set; }
    public String DealName { get; set; }
    public Decimal RateforCell { get; set; }
    public String SaveDescision { get; set; }
    public Boolean selectAll { get; set; }
    public Date anchordate;
    public Date startdate;
    public Date enddate;
    public Boolean schedulemessage { get; set; }
    public Boolean showtable { get; set; }
    public Deal__c SelectedDeal { get; set; }
    public Date LowestDate { get; set; }
    public Date HighestDate { get; set; }
    public Date QuarterEndDate { get; set; }
    public String RemoveDealId { get; set; }
    public String SelectedDealSet { get; set; }
    public Boolean BarterCheckbox { get; set; }
    public String SelectedCableSynd { get; set; }
    public List<SelectOption> CableSyndSOList { get; set; }

    public Schedules__c WeekStartDate { get; set; }
    public Schedules__c WeekEndDate { get; set; }
    public List<SelectOption> DateLiteralSOList { get; set; }
    public String SelectedDateLiteral { get; set; }
    public String SOQLDateString { get; set; }

    //Maps each selected deal Id to a map that maps each order line number to the prelog data.
    public Map<String, Map<String, DoubleCheckReadOnlyHelper.PrelogDataWrapper>> dealMap { get; set; }

    //Maps each selected deal Id to a list of grand totals.
    public Map<String, Map<String, Decimal>> grandTotalMap { get; set; }

    public DoubleCheckReadOnly() {
        CableSyndSOList = DealUtils.ReturnCableSyndSOList();
        DateLiteralSOList = DealUtils.ReturnDateLiteralSOList();

        DealWrapperList = new List<DoubleCheckReadOnlyHelper.DealWrapper>();
        DealWrapperIdSet = new Set<Id>();
        WeekStartDate = new Schedules__c();
        WeekEndDate = new Schedules__c();
        selectAll = false;
        SaveDescision = '';
        SelectedDealSet = '';
        SelectedDateLiteral = '';
        SelectedCableSynd = '';
    }

    public virtual void DoSearch()
    {
        try {
            DealResultList = new List<Deal__c>();
            SearchList = new List<String>();
            ReturnSOQLDateString();

            if (Searchfield == null || Searchfield == '') {
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Search field can not be empty'));
                return;
            }

            SearchList = Searchfield.split(',');
            DealResultList = dealSelector.getDealsFromSearchQuery(
                    SOQLDateString, SearchList, null, BarterCheckbox, SelectedCableSynd, null, '200');

            if (DealResultList.size() == 0 && Searchfield != null && Searchfield != '') {
                ApexPages.addMessage(new ApexPages.Message(
                        ApexPages.Severity.ERROR, 'The Search did not return any results'));
            }

            DealId = '';
            DealName = '';
            cellrate = '';
            CellId = '';
            showtable = false;
            schedulemessage = false;
            SortDealResultList();
        } catch (Exception e) {
            DealUtils.handleException(e);
        }
    }

    public virtual void SortDealResultList()
    {
        try
        {
            Map<Date, List<Deal__c>> DealDateList = new Map<Date, List<Deal__c>>();
            Set<Date> DateList = new Set<Date>();
            List<Deal__c> NoDateList = new List<Deal__c>();
            for (Deal__c DR : DealResultList) {
                if (DR.Week_MIN_Field__c != null) {
                    DateList.add(DR.Week_MIN_Field__c);
                    if (DealDateList.containsKey(DR.Week_MIN_Field__c)) {
                        List<Deal__c> DealL = DealDateList.get(DR.Week_MIN_Field__c);
                        DealL.add(DR);
                        DealDateList.put(DR.Week_MIN_Field__c, DealL);
                    } else {
                        List<Deal__c> DealL = new List<Deal__c>();
                        DealL.add(DR);
                        DealDateList.put(DR.Week_MIN_Field__c, DealL);
                    }
                } else {
                    NoDateList.add(DR);
                }
            }
            List<Date> DateSortList = new List<Date>();
            for (Date DS : DateList) {
                DateSortList.add(DS);
            }
            DateSortList.sort();
            DealResultList.clear();
            for (Integer i = DateSortList.size()-1 ; i >=0 ; i-- ) {
                if (DealDateList.containsKey(DateSortList[i])) {
                    DealResultList.addAll(DealDateList.get(DateSortList[i]));
                }
            }
            DealResultList.addAll(NoDateList);
        } catch(Exception e) {
            DealUtils.handleException(e);
        }
    }

    public virtual void AddMoreToDeal()
    {
        try
        {
            if (DealWrapperList.size() > 3)
            {
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'More than 4 Deals cannot be viewed at the same time'));
            }
            else if (!DealWrapperIdSet.contains(DealId))
            {
                testlist= new List<String>();
                testset = new Set<String>();
                List<DoubleCheckReadOnlyHelper.LineItemModel> ratelist = new List<DoubleCheckReadOnlyHelper.LineItemModel>();
                Map<String,List<Schedules__c>> schgroup = new Map<String,List<Schedules__c>>();
                Map<Date, Decimal> WeekDollarsMap = new Map<Date, Decimal>();
                LowestDate = Date.newInstance(3000,1,1);
                HighestDate = Date.newInstance(1000,1,1);
                for (Schedules__c schlist : Database.query('Select ' + SaberGF.GetObjectsFieldsForQueries('Schedules__c') + ', Deal_Parent__r.Week_MIN_Field__c from Schedules__c where Deal_Parent__c = \'' + DealId + '\' ORDER BY MilitaryTime__c, Rate__c' ))
                {
                    if (LowestDate > schlist.Week__c)
                    {
                        LowestDate = schlist.Week__c;
                    }
                    if (HighestDate < schlist.Week__c)
                    {
                        HighestDate = schlist.Week__c;
                    }
                    if(schlist.OrderNumber__c != null)
                    {
                        if(!testset.contains(schlist.OrderNumber__c))
                        {
                            testlist.add(schlist.OrderNumber__c);
                            testset.add(schlist.OrderNumber__c);
                        }
                        if(schgroup.containsKey(schlist.OrderNumber__c))
                        {
                            List<Schedules__c> temp = schgroup.get(schlist.OrderNumber__c);
                            temp.add(schlist);
                            schgroup.put(schlist.OrderNumber__c,temp);
                        }
                        else
                        {
                            List<Schedules__c> temp = new List<Schedules__c>();
                            temp.add(schlist);
                            schgroup.put(schlist.OrderNumber__c,temp);
                        }
                    }
                }
                List<Deal__c> DealList = [SELECT Id,Contact__c,ContactAccount__c, Contact__r.Name, Contact__r.AccountId, Contact__r.Account.Name,Sum_of_Total_Dollars__c,Sum_of_Units_Available__c, Program__r.Name, Program__r.Reconciled_Week__c, Brands__c, Brands__r.Name, Name, Week_MIN_Field__c, Length__c,SF_Deal_ID__c FROM Deal__c WHERE Id =: DealId];
                if (DealList.size() > 0)
                {
                    ListOfDates(DealList[0].Week_MIN_Field__c, DealList[0].Program__r.Reconciled_Week__c);
                    SelectedDeal = DealList[0];
                }
                Decimal TotalUnitsAired = 0;
                Decimal TotalUnitsAvailable = 0;
                Decimal TotalDollars = 0;
                Decimal TotalDollarsBooked = 0;
                for(String mapkeylist : testlist )
                {
                    List<Schedules__c> tempwraplist = schgroup.get(mapkeylist);
                    DoubleCheckReadOnlyHelper.LineItemModel Lm = new DoubleCheckReadOnlyHelper.LineItemModel();
                    Lm.OrderLineNumber = mapkeylist;
                    if(tempwraplist[0].Rate__c != 0 || tempwraplist[0].Rate__c != null)
                    {
                        Lm.rate = tempwraplist[0].Rate__c;
                    }
                    else
                    {
                        Lm.rate = 0;
                    }
                    Lm.DaysAllowed = tempwraplist[0].DaysAllowedFormula__c;
                    Lm.SETime = tempwraplist[0].Start_End_Time__c;
                    Lm.UnitLength = tempwraplist[0].UnitLength__c;
                    Date RMLowestDate = Date.newInstance(3000,1,1);
                    Date RMHighestDate = Date.newInstance(1000,1,1);
                    for(Schedules__c sch :tempwraplist)
                    {
                        if (RMLowestDate > sch.Week__c)
                        {
                            RMLowestDate = sch.Week__c;
                        }
                        if (RMHighestDate < sch.Week__c)
                        {
                            RMHighestDate = sch.Week__c;
                        }
                        if(sch.Week__c >= Date.today().toStartOfWeek().addDays(1) )
                        {
                            if(sch.Filler__c == true)
                            {
                                Lm.Filler = true;
                            }
                        }
                        if (sch.Reconciled__c == 'Y')
                        {
                            if (sch.Status__c != 'Canceled')
                            {
                                TotalUnitsAired += (sch.Units_Aired__c == null ? 0 : sch.Units_Aired__c );
                                TotalUnitsAvailable += (sch.Units_Available__c == null ? 0 : sch.Units_Available__c );
                            }

                            TotalDollars += (sch.Total_Dollars__c == null ? 0 : sch.Total_Dollars__c);
                            TotalDollarsBooked += (sch.Dollars_Booked__c == null ? 0 : sch.Dollars_Booked__c);
                        }
                    }
                    Lm.LowestDate = RMLowestDate;
                    Lm.HighestDate = RMHighestDate;
                    Map<Date,Schedules__c> weekMap = new Map<Date,Schedules__c>();
                    Map<Date, Boolean> DuplicateWeekMap = new Map<Date, Boolean>();
                    for(Schedules__c schtemp : tempwraplist )
                    {
                        if (weekMap.containsKey(schtemp.Week__c))
                        {
                            DuplicateWeekMap.put(schtemp.Week__c, true);
                        }
                        weekMap.put(schtemp.Week__c, schtemp);
                        if (WeekDollarsMap.containsKey(schtemp.Week__c))
                        {
                            Decimal WeekDollars = WeekDollarsMap.get(schtemp.Week__c);
                            WeekDollars = WeekDollars + schtemp.Total_Dollars__c;
                            WeekDollarsMap.put(schtemp.Week__c, WeekDollars);
                        }
                        else
                        {
                            Decimal WeekDollars = 0;
                            WeekDollars = WeekDollars + schtemp.Total_Dollars__c;
                            WeekDollarsMap.put(schtemp.Week__c, WeekDollars);
                        }
                    }
                    for(Date sow: quarterdates)
                    {
                        if (sow != null)
                        {
                            if (sow >= LowestDate)
                            {
                                if(weekMap.containsKey(sow))
                                {
                                    if (DuplicateWeekMap.containsKey(sow))
                                    {
                                        Lm.weeks.add(new DoubleCheckReadOnlyHelper.weekModel(sow,weekMap.get(sow), true));
                                    }
                                    else
                                    {
                                        Lm.weeks.add(new DoubleCheckReadOnlyHelper.weekModel(sow,weekMap.get(sow), false));
                                    }
                                }
                                else
                                {
                                    Lm.weeks.add(new DoubleCheckReadOnlyHelper.weekmodel(sow,tempwraplist[0].OrderNumber__c));
                                }
                            }
                        }
                    }
                    ratelist.add(Lm);
                    //Display();
                }
                DoubleCheckReadOnlyHelper.DealWrapper DW = new DoubleCheckReadOnlyHelper.DealWrapper();
                DW.DealRecord = SelectedDeal;
                DW.HeadingList = ListOfDates(DealList[0].Week_MIN_Field__c, DealList[0].Program__r.Reconciled_Week__c);
                List<String> TempWeekDollarsList = new List<String>();
                for (DoubleCheckReadOnlyHelper.HeadingModel HM : DW.HeadingList)
                {
                    if (WeekDollarsMap.containsKey(HM.startOfWeek))
                    {
                        Decimal DollarAmount = WeekDollarsMap.get(HM.startOfWeek);
                        String StringAmount;
                        if (DollarAmount < 1000)
                        {
                            StringAmount =  '$' + String.valueOf(DollarAmount);
                            StringAmount = StringAmount.replace('.00','');
                        }
                        else
                        {
                            DollarAmount = DollarAmount.setScale(0);
                            DollarAmount = DollarAmount/1000.0;
                            DollarAmount = DollarAmount.setScale(1);
                            StringAmount =  '$' + String.valueOf(DollarAmount);
                            StringAmount = StringAmount.replace('.0','') + 'K';
                        }
                        TempWeekDollarsList.add(StringAmount);
                    }
                    else
                    {
                        TempWeekDollarsList.add('$0');
                    }
                }
                DW.WeekDollarsList = TempWeekDollarsList;
                DW.LineItemModelList = ratelist;
                DW.UnitsAired = TotalUnitsAired;
                DW.UnitsAvailable = TotalUnitsAvailable;
                DW.WeekDollarsMap = WeekDollarsMap;
                DW.ClearancePercentage = (DW.UnitsAvailable == 0 ? 0 : ( DW.UnitsAired / DW.UnitsAvailable * 100.0).intValue());
                DW.TotalDollars = TotalDollars;
                DW.TotalDollarsBooked = TotalDollarsBooked;
                DW.DollarClearancePercentage = (DW.TotalDollarsBooked == 0 ? 0 : (DW.TotalDollars / DW.TotalDollarsBooked * 100.0).intValue());
                DealWrapperList.add(DW);
                DealWrapperIdSet.add(SelectedDeal.Id);
                SelectedDealSet += SelectedDeal.Id;
            }
        }
        catch(Exception e)
        {
            DealUtils.handleException(e);
        }
    }

    public virtual void RemoveDealButton()
    {
        try
        {
            if (RemoveDealId != null)
            {
                List<DoubleCheckReadOnlyHelper.DealWrapper> TempDealWrapper = new List<DoubleCheckReadOnlyHelper.DealWrapper>();
                TempDealWrapper.addAll(DealWrapperList);
                DealWrapperList = new List<DoubleCheckReadOnlyHelper.DealWrapper>();
                DealWrapperIdSet = new Set<Id>();
                SelectedDealSet = '';
                for (DoubleCheckReadOnlyHelper.DealWrapper DW : TempDealWrapper)
                {
                    if (DW.DealRecord.Id != Id.valueOf(RemoveDealId))
                    {
                        DealWrapperList.add(DW);
                        DealWrapperIdSet.add(DW.DealRecord.Id);
                        SelectedDealSet += DW.DealRecord.Id;
                    }
                }
            }
        }
        catch(Exception e)
        {
            DealUtils.handleException(e);
        }
    }

    public virtual void ReturnSOQLDateString()
    {
        try {
            SOQLDateString = '';
            if (SelectedDateLiteral == 'Custom') {
                if (WeekStartDate.Week__c != null && WeekEndDate.Week__c != null) {
                    SOQLDateString =
                            ' AND ( Week_MIN_Field__c >= ' + DealUtils.ReturnStringDate(WeekStartDate.Week__c)
                                    + ' AND Week_MIN_Field__c <= ' + DealUtils.ReturnStringDate(WeekEndDate.Week__c) + ' ) ';
                }
            }
            else {
                Map<String, CalendarPeriod> sel = DealUtils.getCustomCalendarPeriods(dates);
                CalendarPeriod val = sel.get(SelectedDateLiteral);
                if (val != null) {
                    if (val.setDates()) {
                        WeekStartDate.Week__c = val.weekStart;
                        WeekEndDate.Week__c = val.weekEnd;
                    }
                }
            }

            if (WeekStartDate.Week__c != null && WeekEndDate.Week__c != null) {
                SOQLDateString = ' AND ( Week_MIN_Field__c >= ' + DealUtils.ReturnStringDate(WeekStartDate.Week__c)
                        + ' AND Week_MIN_Field__c <= ' + DealUtils.ReturnStringDate(WeekEndDate.Week__c) + ' ) ';
            }
        } catch (Exception e) {
            DealUtils.handleException(e);
        }
    }

    public virtual void Display()
    {
        showtable = true;
        schedulemessage = false;
    }

    public virtual List<DoubleCheckReadOnlyHelper.HeadingModel> ListOfDates(Date pAnchorDate, Date pReconciledDate)
    {
        try
        {
            //Red Argyle - #2791:Controller issues with atypical fiscal quarters
            Date AnchorDate = pAnchorDate;

            Period period = periodSelector.getQuarterPeriodFromDate(AnchorDate);
            Date StartOfQuarter = period.StartDate;
            Date EndOfQuarter = period.EndDate;
            QuarterEndDate = period.EndDate;

            if (HighestDate > EndOfQuarter)
            {
                EndOfQuarter = HighestDate;
            }
            if (AnchorDate > EndOfQuarter)
            {
                ListOfDates(AnchorDate.addDays(7),pReconciledDate);
            }
            quarterdates = new List<Date>();
            while (StartOfQuarter <= EndOfQuarter)
            {
                quarterdates.add(StartOfQuarter);
                enddate = StartOfQuarter;
                StartOfQuarter = StartOfQuarter.addDays(7);
            }
            //quarterdates.add(enddate);
            headingModels  = new List<DoubleCheckReadOnlyHelper.HeadingModel>();
            quarterweek = new List<DoubleCheckReadOnlyHelper.WeekModel>();
            for(Date sow: quarterdates)
            {
                if (sow != null)
                {
                    DoubleCheckReadOnlyHelper.HeadingModel hm = new DoubleCheckReadOnlyHelper.HeadingModel();
                    hm.startOfWeek = sow;
                    if (pReconciledDate >= sow)
                    {
                        hm.bgcolor = '#848484';
                    }
                    else
                    {
                        hm.bgcolor = '#86BCFF';
                    }
                    System.debug('date compare - ' + sow + ' - ' + LowestDate + ' - ' + (sow >= LowestDate));
                    if (sow >= LowestDate)
                    {
                        headingModels.add(hm);
                    }
                }
            }
            return headingModels;
        }
        catch(Exception e)
        {
            DealUtils.handleException(e);
        }
        return null;
    }
}