objects/Brands__c.object
<CustomObject>
    <label>Brands</label>
    <nameField>
        <label>Brand</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Deal__c.object
<CustomObject>
    <fields>
        <fullName>Brands__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Brands</label>
        <referenceTo>Brands__c</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Client_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>[Dep]Client Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ContactAccount__c</fullName>
        <formula>Contact__r.Account.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ContactAccount</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Type__c</field>
                <operation>notEqual</operation>
                <value>history</value>
            </filterItems>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>Do Not Call</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Length__c</fullName>
        <label>Length</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>30</fullName>
                    <color>#0B6FCE</color>
                    <label>30</label>
                </value>
                <value>
                    <fullName>60</fullName>
                    <color>#78C953</color>
                    <label>60</label>
                </value>
                <value>
                    <fullName>120</fullName>
                    <color>#E27001</color>
                    <label>120</label>
                </value>
                <value>
                    <fullName>300</fullName>
                    <color>#A845DC</color>
                    <label>300</label>
                </value>
                <value>
                    <fullName>15</fullName>
                    <color>#F3D904</color>
                    <label>15</label>
                </value>
                <value>
                    <fullName>1710</fullName>
                    <color>#A53711</color>
                    <label>1710</label>
                </value>
                <value>
                    <fullName>90</fullName>
                    <color>#66E9BD</color>
                    <label>90</label>
                </value>
                <value>
                    <fullName>180</fullName>
                    <color>#0B24BE</color>
                    <label>180</label>
                </value>
                <value>
                    <fullName>240</fullName>
                    <color>#419249</color>
                    <label>240</label>
                </value>
                <value>
                    <fullName>45</fullName>
                </value>
                <value>
                    <fullName>75</fullName>
                </value>
                <value>
                    <fullName>05</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>150</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>105</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>35</fullName>
                </value>
                <value>
                    <fullName>40</fullName>
                </value>
                <value>
                    <fullName>1714</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Program</label>
        <referenceTo>Programs__c</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Sold</fullName>
                    <default>true</default>
                    <label>Sold</label>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Historical</fullName>
                </value>
                <value>
                    <fullName>Budget</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sum_of_Total_Dollars__c</fullName>
        <inlineHelpText>Sum of Total Dollars for the schedules for this deal.</inlineHelpText>
        <label>Sum of Total Dollars</label>
        <summarizedField>Schedules__c.Dollars_Booked__c</summarizedField>
        <summaryForeignKey>Schedules__c.Deal_Parent__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Sum_of_Units_Available__c</fullName>
        <label>Sum of Units Available</label>
        <summarizedField>Schedules__c.Units_Available__c</summarizedField>
        <summaryFilterItems>
            <field>Schedules__c.Status__c</field>
            <operation>equals</operation>
            <value>Sold</value>
        </summaryFilterItems>
        <summaryForeignKey>Schedules__c.Deal_Parent__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Test_PP__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Paid Programming ONLY.  Check to indicate a test deal for month.</description>
        <inlineHelpText>Paid Programming ONLY.  Check to indicate a test deal for month.</inlineHelpText>
        <label>[Dep]Test PP</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Week_MIN_Field__c</fullName>
        <label>Week MIN Field</label>
        <summarizedField>Schedules__c.Week__c</summarizedField>
        <summaryForeignKey>Schedules__c.Deal_Parent__c</summaryForeignKey>
        <summaryOperation>min</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Deal</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Deal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Programs__c.object
<CustomObject>
    <description>Program/Distributor</description>
    <fields>
        <fullName>Team__c</fullName>
        <inlineHelpText>Blue, Red, Green, Orange</inlineHelpText>
        <label>Team</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Schedules__c.object
<CustomObject>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Day__c</fullName>
        <label>Day</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Deal_Parent__c</fullName>
        <label>Deal Parent</label>
        <referenceTo>Deal__c</referenceTo>
        <relationshipLabel>Schedules</relationshipLabel>
        <relationshipName>Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Sold</fullName>
                    <default>true</default>
                    <label>Sold</label>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TEST__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Notes whether a particular schedule is a test.</description>
        <label>TEST</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Week__c</fullName>
        <label>Week</label>
        <type>Date</type>
    </fields>
    <label>Schedule</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TargetWeeklyController.cls
public class TargetWeeklyController {
    public list<selectoption> team{get;set;}
    public string selectedTeam {get;set;}
    public Schedules__c schedule {get;set;}
    public Deal__c deal {get;set;}
    Date fromDate;
    Date toDate;
    public List<Deal__c> dealList {get;set;}
    public List<Deal__c> dealList2 {get;set;}
    public List<Deal__c> dealList3 {get;set;}
    String programId;
    String agencyName;
    String conId;
    String brandId;
    String ownerId;
    
    /**public TargetWeeklyController (){
        team = new list<selectoption>();
        team.add(new selectoption('None','None'));
        team.add(new selectoption('Red','Red'));
        team.add(new selectoption('Blue','Blue'));
        team.add(new selectoption('Green','Green'));
        team.add(new selectoption('Orange','Orange'));
        deal = new Deal__c();
        deal.OwnerId = userInfo.getUserId();
        schedule = new Schedules__c();
        schedule.Day__c = system.today();
        schedule.Week__c = schedule.Day__c.addDays(-7);
        showReport();
    }
    public pagereference showReport(){
        if(schedule.Week__c != null){
            fromDate = schedule.Week__c;
        }
        if(schedule.Day__c != null){
            toDate = schedule.Day__c;
        }
        String dealQuery ='SELECT id, Name, ';
		        dealQuery += 'Week_MIN_Field__c,Sum_of_Total_Dollars__c, Status__c, Program__c, Brands__c, ';
		        dealQuery += 'Contact__c, Sum_of_Units_Available__c,ContactAccount__c, CreatedDate, Length__c, ';
		        dealQuery += 'Target__r.Status__c, Target__r.Name, Target__r.Comments__c, Target__r.To_Do__c, ';
		        dealQuery += 'Target__r.AE_LC__c, Target__r.AE_Status__c, Target__r.Status_Detail__c, ';
		        dealQuery += 'Target__r.LastModifiedDate, Target__r.LastModifiedById ';
		        dealQuery += 'FROM Deal__c WHERE Brands__r.Name != \'Budget\' AND Brands__r.Name != \'Availability\' ';
        
        system.debug('#### Dates:From '+fromDate+ 'TO '+toDate);
        
        if(selectedTeam != 'None' && selectedTeam != null){
            dealQuery += 'AND Program__r.Team__c like \'%' + selectedTeam + '%\' ';
        }
        if(deal.Program__c != null){
            programId = deal.Program__c;
            dealQuery += 'AND Program__c =: programId ';
        }
        if(deal.Client_Account__c != null){
            List<Account> acc = [SELECT id, Name from Account WHERE id =: deal.Client_Account__c];
            if(acc != null){
            	agencyName = acc.get(0).Name;
            	dealQuery += 'AND ContactAccount__c =: agencyName ';
            }
        }
        if(deal.Contact__c != null){
            conId = deal.Contact__c;
            dealQuery += 'AND Deal_Parent__r.Contact__c =: conId ';
        }
        if(deal.Brands__c != null){
            brandId = deal.Brands__c;
            dealQuery += 'AND Brands__c =: brandId ';
        }
        if(deal.OwnerId != null){
            ownerId = deal.OwnerId;
            dealQuery += 'AND OwnerId =: ownerId ';
        }
        if(schedule.TEST__c == true){
            dealQuery += 'AND Target__r.Status__c = \'Test\' ';
        }
        dealQuery += 'AND CreatedDate >: fromDate AND CreatedDate <: toDate ';
        getNewDealSection(dealQuery);
        getCanceledSection(dealQuery);
        getFollowUpSection(dealQuery);
        return null;
    }
    private void getNewDealSection(String q){        
        q += ' LIMIT 500';
        system.debug('### Query 1 : '+ q);
        dealList = Database.Query(q);
        system.debug('### Section 1 Records Found : '+dealList.size());
    }
    
    private void getCanceledSection(String q){
        q += 'AND  Status__c = \'Canceled\' ';
        //   AND LastModifiedDate >:fromDate AND LastModifiedDate <:toDate
        q += 'LIMIT 500 ';
        system.debug('### Query 2 : '+ q);
        dealList2 = Database.Query(q);
        system.debug('### Section 2 Records Found : '+dealList2.size());
    }
    private void getFollowUpSection(String q){
        q += 'AND Test_PP__c = true ';
        q += 'AND (Target__r.Status__c = \'Test\' OR Status__c = null) ';
        q += 'LIMIT 500 ';
        system.debug('### Query 3 : '+ q);
        dealList3 = Database.Query(q);
        system.debug('### Section 3 Records Found : '+dealList3.size());
    }
    public void save(){
        Set<Targets__c> targetSet = new Set<Targets__c>();
        for(Deal__c d : dealList){
            if(d.Target__r != null){
                Targets__c t = d.Target__r;
                targetSet.add(t);
            }
        }
        for(Deal__c d : dealList2){
            if(d.Target__r != null){
                Targets__c t = d.Target__r;
                targetSet.add(t);
            }
        }
        for(Deal__c d : dealList3){
            if(d.Target__r != null){
                Targets__c t = d.Target__r;
                targetSet.add(t);
            }
        }
        List<Targets__c> targets = new List<Targets__c>();
        targets.addAll(targetSet);
        if(targets.size()>0){
            update targets;
        }
        showReport();
    }**/
}