objects/Brands__c.object
<CustomObject>
    <label>Brands</label>
    <nameField>
        <label>Brand</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Deal__c.object
<CustomObject>
    <fields>
        <fullName>Brands__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Brands</label>
        <referenceTo>Brands__c</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ContactAccount__c</fullName>
        <formula>Contact__r.Account.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ContactAccount</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Program</label>
        <referenceTo>Programs__c</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Deal</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Deal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Programs__c.object
<CustomObject>
    <description>Program/Distributor</description>
    <fields>
        <fullName>Bundle_Name__c</fullName>
        <label>Bundle Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/XMLBundleDeal.cls
public with sharing class XMLBundleDeal {

	public String dealId {get; set;}
	public String zipFileName {get; set;}
	public String programId {get; set;}
	public String bundleName {get; set;}

	/**
	* @author Ryan Scott
	* @date 12/02/2015
	* @description Controller instantiation. Grabs the selected Deal's record Id from the URL query string
	*	and makes it accessible to the JavaScript code in XMLBundleDeal.page. Queries for Program and Program's Bundle Name.
	*	Also formulates the zip filename.
	**/
	public XMLBundleDeal() {
		this.dealId = ApexPages.currentPage().getParameters().get('id');
		Deal__c deal = [SELECT Brands__r.Name, ContactAccount__c, Name, Program__c, Program__r.Bundle_Name__c FROM Deal__c WHERE Id = :dealId];
		this.programId = deal.Program__c;
		this.bundleName = deal.Program__r.Bundle_Name__c;

		this.zipFileName = deal.Program__r.Bundle_Name__c + '-' + deal.Name + '-' + deal.ContactAccount__c + '-' + deal.Brands__r.Name + '-NEW BUY-';
		Date d = Date.today();
		this.zipFileName += d.year() + '-' + Utils.padIntegerWithLeadingZero(d.month()) + '-' + Utils.padIntegerWithLeadingZero(d.day()) + '.zip';
	}

	/**
	* @author Ryan Scott
	* @date 12/02/2015
	* @description Remote wrapper function for the XMLBundle.getXMLFiles() function. Passes along the Deal Id and returns result.
	**/
	@RemoteAction
	public static Map<String, String> getXMLFiles(String dealId) {
		return XMLBundle.getXMLFiles(dealId, null);
	}

	/**
	* @author Ryan Scott
	* @date 12/02/2015
	* @description Remote wrapper function for the XMLBundle.saveData() function. Passes along the required data and returns result.
	**/
	@RemoteAction
	public static String saveData(String recordId, String filename, String data) {
		return XMLBundle.saveData(recordId, filename.replace('&','and'), data);
	}

	/**
	* @author Ryan Scott
	* @date 12/18/2015
	* @description Remote wrapper function for the XMLBundle.markXMLSent() function. Passes along the required data and returns result.
	**/
	@RemoteAction
	public static String markXMLSent(String scheduleIds) {
		return XMLBundle.markXMLSent(scheduleIds);
	}
}