objects/Brands__c.object
<CustomObject>
    <label>Brands</label>
    <nameField>
        <label>Brand</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Deal__c.object
<CustomObject>
    <fields>
        <fullName>Brands__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Brands</label>
        <referenceTo>Brands__c</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Program</label>
        <referenceTo>Programs__c</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Deal</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Deal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Ratings_compiled__c.object
<CustomObject>
    <description>Compiled Ratings</description>
    <fields>
        <fullName>AUR__c</fullName>
        <inlineHelpText>Avg. Unit Rate</inlineHelpText>
        <label>AUR</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CPM__c</fullName>
        <inlineHelpText>Cost Per Impression</inlineHelpText>
        <label>CPM</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Daypart__c</fullName>
        <label>Daypart</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>DA</fullName>
                </value>
                <value>
                    <fullName>EM</fullName>
                </value>
                <value>
                    <fullName>LN</fullName>
                </value>
                <value>
                    <fullName>ON</fullName>
                </value>
                <value>
                    <fullName>PR</fullName>
                </value>
                <value>
                    <fullName>Total Day</fullName>
                </value>
                <value>
                    <fullName>-</fullName>
                </value>
                <value>
                    <fullName>EF</fullName>
                </value>
                <value>
                    <fullName>LF</fullName>
                </value>
                <value>
                    <fullName>WK</fullName>
                </value>
                <value>
                    <fullName>WKND</fullName>
                </value>
                <value>
                    <fullName>DA - MF</fullName>
                </value>
                <value>
                    <fullName>DA - SS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Dollar_Amount__c</fullName>
        <inlineHelpText>Total Dollar Amount</inlineHelpText>
        <label>Dollar Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>INV__c</fullName>
        <inlineHelpText>Investment</inlineHelpText>
        <label>INV</label>
        <precision>9</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Impressions__c</fullName>
        <label>Impressions</label>
        <precision>11</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Programs__c</referenceTo>
        <relationshipLabel>Ratings Compiled</relationshipLabel>
        <relationshipName>Ratings_Compiled</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reconciled__c</fullName>
        <formula>if( Week__c &lt;= Program__r.RCreconciled_Week__c , &quot;Y&quot;, &quot;N&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Reconciled</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Week__c</fullName>
        <label>Week</label>
        <type>Date</type>
    </fields>
    <label>Ratings Compiled</label>
    <nameField>
        <displayFormat>RC-{00000000}</displayFormat>
        <label>Ratings Compiled Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ratings Compiled</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Schedules__c.object
<CustomObject>
    <fields>
        <fullName>CALC_EQUIV_30__c</fullName>
        <formula>if( AND(Units_Available__c &gt;0, NOT(DealBrand__c = &quot;GM Units&quot;)), 
(VALUE(TEXT(Deal_Parent__r.Length__c)) * Units_Aired__c 
/ 30 ), 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>if( AND(Units_Available__c &gt;0,  NOT(DealBrand__c   =  &quot;GM Units&quot;)),
(case(Deal_Parent__r.Length__c, &quot;10&quot;,10, &quot;30&quot;, 30, &quot;45&quot;, 45, &quot;60&quot;, 60, &quot;75&quot;, 75, &quot;105&quot;, 105, &quot;120&quot;, 120, &quot;240&quot;, 240, &quot;300&quot;, 300, &quot;15&quot;, 15, &quot;90&quot;, 90, &quot;180&quot;, 180, &quot;1710&quot;, 1710, 0) * UnitsA</inlineHelpText>
        <label>CALC EQUIV :30</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>COUNTMENOT__c</fullName>
        <formula>if(or( case(Deal_Parent__r.Status__c, &quot;Canceled&quot;, &quot;N&quot;, &quot;Pre-Empted&quot;, &quot;N&quot;, &quot;Y&quot;) = &quot;N&quot;,  

case(Status__c, &quot;Canceled&quot;, &quot;N&quot;, &quot;Pre-Empted&quot;, &quot;N&quot;, &quot;Y&quot;) = &quot;N&quot;,

Units_Aired__c =0), &quot;N&quot;, &quot;Y&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>AIRED</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Daypart__c</fullName>
        <formula>IF(OR(LEFT(TEXT(MGM_HD_Daypart__c), 2) = &quot;DA&quot;, LEFT(TEXT(MGM_HD_Daypart__c), 2) = &quot;EM&quot;, LEFT(TEXT(MGM_HD_Daypart__c), 2) = &quot;ON&quot;, LEFT(TEXT(MGM_HD_Daypart__c), 2) = &quot;PR&quot;, LEFT(TEXT(MGM_HD_Daypart__c), 2) = &quot;LN&quot;, LEFT(TEXT(MGM_HD_Daypart__c), 2) = &quot;EF&quot;, LEFT(TEXT(MGM_HD_Daypart__c), 2) = &quot;LF&quot;),LEFT(TEXT(MGM_HD_Daypart__c), 2), CASE( MGM_HD_Daypart__c, 

&quot;9A-6P – Day&quot;,&quot;DA&quot;, 
&quot;Day Live Game&quot;,&quot;DA&quot;, 
&quot;6P-12A – PR&quot;,&quot;PR&quot;, 
&quot;Prime Live Game&quot;,&quot;PR&quot;, 
&quot;JC - MS 7p-12a&quot;,&quot;PR&quot;, 
&quot;6A-9A – EM&quot;,&quot;EM&quot;, 
&quot;3A-6A -- ON&quot;,&quot;ON&quot;, 
&quot;JC - MS 12a-5a&quot;,&quot;ON&quot;, 
&quot;12A-3A -- LN&quot;,&quot;LN&quot;, 
&quot;SS 9a-4p&quot;,&quot;DA&quot;, 
&quot;MS 12a-2a&quot;,&quot;WC&quot;,
&quot;MS 2a-6a&quot;,&quot;ON&quot;, 
&quot;MS 1p-6p&quot;,&quot;DA&quot;, 
&quot;WC - MS 12a-2a&quot;,&quot;WC&quot;, 
&quot;Matinee Game MS&quot;,&quot;DA&quot;, 
&quot;Prime Game MS&quot;,&quot;PR&quot;, 
&quot;MS 7p-12a&quot;,&quot;PR&quot;, 
&quot;ROS-&quot;,&quot;ROS-&quot;, 
&quot;&quot;) 
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Daypart</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Deal_Parent__c</fullName>
        <label>Deal Parent</label>
        <referenceTo>Deal__c</referenceTo>
        <relationshipLabel>Schedules</relationshipLabel>
        <relationshipName>Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Reconciled__c</fullName>
        <formula>if( LF_Week__c &lt;= Deal_Parent__r.Program__r.Reconciled_Week__c , &quot;Y&quot;, &quot;N&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Reconciled</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Dollars__c</fullName>
        <formula>if(  PI_Payout_TEST__c &gt;0,  PI_Payout_TEST__c *20/17, 

if( PI_Payout__c &gt; 0 ,  PI_Payout__c * 20/17, 

if( Units_Aired__c &lt; 0,  0,
CASE(Deal_Parent__r.Status__c, &quot;Canceled&quot;, 0,  &quot;Pre-Empted&quot;, 0,

 Rate__c  *   Units_Aired__c)

)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Dollars</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Week__c</fullName>
        <label>Week</label>
        <type>Date</type>
    </fields>
    <label>Schedule</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ratingsCompiledTriggerHandler.cls
public class ratingsCompiledTriggerHandler {

  @future 
  public static void compileFuture(Set<Id> ratingIds) {

    List<Ratings_compiled__c> ratingsComp = [SELECT Id, Daypart__c, Program__c, Week__c, Impressions__c, INV__c, Dollar_Amount__c, AUR__c, CPM__c 
                                             FROM Ratings_compiled__c 
                                             WHERE Id IN :ratingIds
                                             ORDER BY Week__c ASC];

    decimal d = 0;
    decimal i = 0;
    date oldest = date.newInstance(2015, 1, 1);
    if (!ratingsComp.isEmpty()) {
        oldest = ratingsComp[0].week__c;
    }
    
    List<String> enteringPrograms = new List<String>();
    
    for(Ratings_compiled__c rc : ratingsComp){
        enteringPrograms.add(rc.Program__c);
    }
    
    Schedules__c[] s = [SELECT Id, CALC_EQUIV_30__c, Total_Dollars__c, Week__c, Deal_Parent__r.Program__c, Daypart__c
                        FROM Schedules__c 
                        WHERE Week__c >= :oldest
                        AND Deal_Parent__r.Brands__r.Name != 'Availability'
                        AND COUNTMENOT__c != 'N'
                        AND Reconciled__c = 'Y'
                        AND Deal_Parent__r.Program__c IN :enteringPrograms];

    for(Ratings_compiled__c rcf : ratingsComp){
        for(Schedules__c c:s){
            if (rcf.week__c == c.week__c && rcf.Daypart__c == c.Daypart__c && rcf.Daypart__c != 'Total Day' && rcf.Program__c == c.Deal_Parent__r.Program__c) {
                i = i + c.CALC_EQUIV_30__c;
                d = d + c.Total_Dollars__c;
            }
            if (rcf.Daypart__c == 'Total Day' && rcf.week__c == c.week__c && rcf.Program__c == c.Deal_Parent__r.Program__c) {
                i = i + c.CALC_EQUIV_30__c;
                d = d + c.Total_Dollars__c;
            }
        }
        if(i > 0 && d > 0){
            rcf.Dollar_Amount__c = d;
            rcf.INV__c = i;
            rcf.AUR__c = d/i;
            
            if(rcf.Impressions__c != null){
            rcf.CPM__c = (d/i)/rcf.Impressions__c;
            }

            d=0;
            i=0;
        }
    }
    update ratingsComp;
  }
}