objects/Brands__c.object
<CustomObject>
    <fields>
        <fullName>Advertiser__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Advertiser</label>
        <referenceTo>Advertiser__c</referenceTo>
        <relationshipLabel>Brands</relationshipLabel>
        <relationshipName>Brands</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Brands</label>
    <nameField>
        <label>Brand</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Deal__c.object
<CustomObject>
    <fields>
        <fullName>Advertiser_ID__c</fullName>
        <formula>Brands__r.Advertiser__r.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Advertiser ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Advertiser__c</fullName>
        <formula>Brands__r.Advertiser__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Advertiser</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Agency_Deal_Number__c</fullName>
        <externalId>true</externalId>
        <label>Agency Deal Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Brands__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Brands</label>
        <referenceTo>Brands__c</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Bundle_Start_Week__c</fullName>
        <label>Bundle Start Week</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Campaign__c</fullName>
        <description>Campaign for a specific brand</description>
        <label>Campaign</label>
        <length>52</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>[Dep]Client Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ContactAccount__c</fullName>
        <formula>Contact__r.Account.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ContactAccount</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Type__c</field>
                <operation>notEqual</operation>
                <value>history</value>
            </filterItems>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>Do Not Call</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Length__c</fullName>
        <label>Length</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>30</fullName>
                    <color>#0B6FCE</color>
                    <label>30</label>
                </value>
                <value>
                    <fullName>60</fullName>
                    <color>#78C953</color>
                    <label>60</label>
                </value>
                <value>
                    <fullName>120</fullName>
                    <color>#E27001</color>
                    <label>120</label>
                </value>
                <value>
                    <fullName>300</fullName>
                    <color>#A845DC</color>
                    <label>300</label>
                </value>
                <value>
                    <fullName>15</fullName>
                    <color>#F3D904</color>
                    <label>15</label>
                </value>
                <value>
                    <fullName>1710</fullName>
                    <color>#A53711</color>
                    <label>1710</label>
                </value>
                <value>
                    <fullName>90</fullName>
                    <color>#66E9BD</color>
                    <label>90</label>
                </value>
                <value>
                    <fullName>180</fullName>
                    <color>#0B24BE</color>
                    <label>180</label>
                </value>
                <value>
                    <fullName>240</fullName>
                    <color>#419249</color>
                    <label>240</label>
                </value>
                <value>
                    <fullName>45</fullName>
                </value>
                <value>
                    <fullName>75</fullName>
                </value>
                <value>
                    <fullName>05</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>150</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>105</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>35</fullName>
                </value>
                <value>
                    <fullName>40</fullName>
                </value>
                <value>
                    <fullName>1714</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Network_Deal_Number__c</fullName>
        <description>Deal number in Network&apos;s paper work, in Network&apos;s records.</description>
        <externalId>true</externalId>
        <inlineHelpText>Deal number in Network&apos;s paper work, in Network&apos;s records.  Equals 1 if the PI campaign is no longer airing on the network.</inlineHelpText>
        <label>Network Deal Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program_Team_del__c</fullName>
        <formula>Program__r.Team__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Program Team</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Program</label>
        <referenceTo>Programs__c</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SF_Deal_ID__c</fullName>
        <description>Used for sending emails to Salesforce so that they can be filed directly to the Deal</description>
        <formula>&quot;(ref:&quot; &amp; Id &amp; &quot;)&quot;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Used for sending emails to Salesforce so that they can be filed directly to the Deal</inlineHelpText>
        <label>SF Deal ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Sold</fullName>
                    <default>true</default>
                    <label>Sold</label>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Historical</fullName>
                </value>
                <value>
                    <fullName>Budget</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sum_of_Total_Dollars__c</fullName>
        <inlineHelpText>Sum of Total Dollars for the schedules for this deal.</inlineHelpText>
        <label>Sum of Total Dollars</label>
        <summarizedField>Schedules__c.Dollars_Booked__c</summarizedField>
        <summaryForeignKey>Schedules__c.Deal_Parent__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Sum_of_Units_Available__c</fullName>
        <label>Sum of Units Available</label>
        <summarizedField>Schedules__c.Units_Available__c</summarizedField>
        <summaryFilterItems>
            <field>Schedules__c.Status__c</field>
            <operation>equals</operation>
            <value>Sold</value>
        </summaryFilterItems>
        <summaryForeignKey>Schedules__c.Deal_Parent__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Week_MIN_Field__c</fullName>
        <label>Week MIN Field</label>
        <summarizedField>Schedules__c.Week__c</summarizedField>
        <summaryForeignKey>Schedules__c.Deal_Parent__c</summaryForeignKey>
        <summaryOperation>min</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Week_Max__c</fullName>
        <label>Week Max</label>
        <summarizedField>Schedules__c.Week__c</summarizedField>
        <summaryForeignKey>Schedules__c.Deal_Parent__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Deal</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Deal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Programs__c.object
<CustomObject>
    <description>Program/Distributor</description>
    <fields>
        <fullName>Barter__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Barter</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Bundle_Name__c</fullName>
        <label>Bundle Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cable_Synd__c</fullName>
        <label>Cable/Synd/PP</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cable</fullName>
                </value>
                <value>
                    <fullName>Syndication</fullName>
                </value>
                <value>
                    <fullName>PP</fullName>
                </value>
                <value>
                    <fullName>Bundle</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Logs_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Primary contact for integration instructions at client/network</inlineHelpText>
        <label>Logs Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Prelog_Date_Time__c</fullName>
        <description>Captures date and time when the prelog version field is changed.</description>
        <label>Prelog Date / Time</label>
        <type>DateTime</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Schedules__c.object
<CustomObject>
    <fields>
        <fullName>Network_Deal_Number__c</fullName>
        <formula>Deal_Parent__r.Network_Deal_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Network Deal Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Sold</fullName>
                    <default>true</default>
                    <label>Sold</label>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Dollars__c</fullName>
        <formula>if(  PI_Payout_TEST__c &gt;0,  PI_Payout_TEST__c *20/17, 

if( PI_Payout__c &gt; 0 ,  PI_Payout__c * 20/17, 

if( Units_Aired__c &lt; 0,  0,
CASE(Deal_Parent__r.Status__c, &quot;Canceled&quot;, 0,  &quot;Pre-Empted&quot;, 0,

 Rate__c  *   Units_Aired__c)

)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Dollars</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Units_Available__c</fullName>
        <label>Units Available</label>
        <precision>17</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Week__c</fullName>
        <label>Week</label>
        <type>Date</type>
    </fields>
    <label>Schedule</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/DealSelector.cls
/**
 * @date 1/14/2019
 * @description Query Deal__c objects from Database
 */
public with sharing virtual class DealSelector {

    /**
     * @description Retrieve deal info from a deal Id
     * @param dealId The dealId being retrieved from
     * @return The resulting list of Deal__c objects with their specified fields
     */
    public virtual List<Deal__c> getDealsFromId(Id dealId) {
        return [
                SELECT Id,
                       Name,
                       Advertiser__c,
                       Campaign__c,
                       Week_MIN_Field__c,
                       Brands__r.Name,
                       Bundle_Start_Week__c,
                       ContactAccount__c,
                       Length__c,
                       Program__c,
                       Program__r.Name,
                       CreatedDate,
                       Program__r.Bundle_Name__c,
                       Program__r.Logs_Contact__c,
                       Program__r.Logs_Contact__r.FirstName,
                       Program__r.Logs_Contact__r.LastName,
                       Network_Deal_Number__c,
                       Agency_Deal_Number__c,
                       Sum_of_Units_Available__c,
                       Sum_of_Total_Dollars__c
                  FROM Deal__c
                 WHERE Id = :dealId
        ];
    }

    public virtual List<Deal__c> getDealsFromQueryForRevision(
            String SOQLDateString,
            String tempstringListLoop,
            String programTeam,
            Boolean BarterCheckbox,
            String SelectedCableSynd,
            String limitAmt)
    {
        String DealQuery = 'SELECT Id,Program__c,Contact__c,Client_Account__c,Brands__c,Name, Length__c, Campaign__c,'
                + 'Week_MIN_Field__c,Agency_Deal_Number__c,Contact__r.Name,Brands__r.Name,'
                + 'Network_Deal_Number__c,Sum_of_Total_Dollars__c,Sum_of_Units_Available__c,ContactAccount__c,'
                + 'Week_Max__c, Client_Account__r.Name, Contact__r.Account.id,'
                + 'Program__r.Name, Advertiser__c '
                + ' From Deal__c '
                + ' Where (Program__r.Name Like \'' + tempstringListLoop + '\''
                + ' OR Contact__r.Name Like \'' + tempstringListLoop + '\''
                + ' OR Client_Account__r.Name Like \'' + tempstringListLoop + '\''
                + ' OR Contact__r.Account.Name Like \'' + tempstringListLoop + '\''
                + ' OR Brands__r.Name Like \'' + tempstringListLoop + '\''
                + ' OR Network_Deal_Number__c Like \'' + tempstringListLoop + '\''
                + ' OR Name Like \'' + tempstringListLoop + '\' ) AND Week_MIN_Field__c != null '
                + SOQLDateString;
        if (BarterCheckbox) {
            DealQuery += ' AND Program__r.Barter__c = True ';
        }
        if (SelectedCableSynd != '' && SelectedCableSynd != null) {
            DealQuery += ' AND Program__r.Cable_Synd__c = \'' + SelectedCableSynd + '\'';
        }
        if (programTeam != '' && programTeam != null) {
            DealQuery += ' AND Program_Team_del__c = \'' + programTeam + '\'';
        }
        DealQuery += 'ORDER BY Week_MIN_Field__c DESC limit ' + limitAmt;

        return Database.query(DealQuery);
    }

    public virtual List<Deal__c> getDealsFromSearchQuery(
            String SOQLDateString,
            List<String> stringList,
            Period pr,
            Boolean BarterCheckbox,
            String SelectedCableSynd,
            String limitAmt)
    {
        return getDealsFromSearchQuery(SOQLDateString, stringList, pr, BarterCheckbox, SelectedCableSynd, null, limitAmt);
    }

    public virtual List<Deal__c> getDealsFromSearchQuery(
            String SOQLDateString,
            List<String> stringList,
            Period pr,
            Boolean BarterCheckbox,
            String SelectedCableSynd,
            String programTeam,
            String limitAmt)
    {
        String DealQuery = 'SELECT Id,Program__c,Contact__c,Client_Account__c,Brands__c,Name, Length__c, Campaign__c,'
                + 'Week_MIN_Field__c,Agency_Deal_Number__c,Contact__r.Name,Brands__r.Name, Network_Deal_Number__c,'
                + 'Sum_of_Total_Dollars__c,Sum_of_Units_Available__c,ContactAccount__c,Week_Max__c, '
                + 'Client_Account__r.Name, Contact__r.Account.id,SF_Deal_ID__c,'
                + ' Program__r.Name, Program__r.Prelog_Date_Time__c, Advertiser_ID__c, Advertiser__c, '
                + '(SELECT Status__c, Week__c, Name, Cap__c, LastModifiedDate FROM Schedules__r WHERE Status__c = \'Sold\') '
                + ' From Deal__c '
                + ' Where ';

        List<String> actualStrings = new List<String>();
        for (Integer i = 0; i < stringList.size(); i++) {
            if (stringList[i].trim() != '') {
                actualStrings.add('\'%' + stringList[i].trim() + '%\'');
            }
        }

        for (Integer i = 0; i < actualStrings.size(); i++) {
            String temp = actualStrings[i];
            DealQuery += ' (Program__r.Name Like ' + temp
            + ' OR Contact__r.Name Like ' + temp
            + ' OR Client_Account__r.Name Like ' + temp
            + ' OR Contact__r.Account.Name Like ' + temp
            + ' OR Brands__r.Name Like ' + temp
            + ' OR Network_Deal_Number__c Like ' + temp
            + ' OR Brands__r.Advertiser__r.Name Like ' + temp
            + ' OR Name Like ' + temp + ' )';
            if (i != actualStrings.size() - 1) {
                DealQuery += ' AND';
            }
        }

        DealQuery += ' AND Week_MIN_Field__c != null';

        if (pr != null) {
            Date start_date = pr.StartDate;
            Date end_date = pr.EndDate;
            DealQuery += ' AND Week_MIN_Field__c <= :end_date AND Week_MIN_Field__c >= :start_date';
        }

        DealQuery += SOQLDateString;

        if (BarterCheckbox != null && BarterCheckbox)
        {
            DealQuery += ' AND Program__r.Barter__c = True';
        }
        if (SelectedCableSynd != '' && SelectedCableSynd != null)
        {
            DealQuery += ' AND Program__r.Cable_Synd__c = \'' + SelectedCableSynd + '\'';
        }
        if (programTeam != null && programTeam != '')
        {
            DealQuery += ' AND Program_Team__c = \'' + programTeam + '\'';
        }

        DealQuery += ' ORDER BY Week_MIN_Field__c DESC LIMIT ' + limitAmt;
        System.debug(DealQuery);
        return Database.query(DealQuery);
    }

    public virtual List<Deal__c> getDealsForAddReadOnly(Id dealId) {
        return [
                SELECT Id,
                       Contact__c,
                       ContactAccount__c,
                       Contact__r.Name,
                       Contact__r.AccountId,
                       Contact__r.Account.Name,
                       Sum_of_Total_Dollars__c,
                       Sum_of_Units_Available__c,
                       Program__r.Name,
                       Program__r.Reconciled_Week__c,
                       Brands__c,
                       Brands__r.Name,
                       Name,
                       Week_MIN_Field__c,
                       Length__c,
                       SF_Deal_ID__c
                  FROM Deal__c
                 WHERE Id = :dealId
        ];

    }

    public virtual List<Deal__c> getDealsForAdd(Id dealId, Date week) {
        return [
                SELECT Id,
                       Name,
                       Contact__c,
                       ContactAccount__c,
                       Campaign__c,
                       Contact__r.Name,
                       Contact__r.AccountId,
                       Contact__r.Account.Name,
                       Sum_of_Total_Dollars__c,
                       Sum_of_Units_Available__c,
                       Program__c,
                       Program__r.Prelog_Date_Time__c,
                       Program__r.Name,
                       Program__r.Reconciled_Week__c,
                       Brands__c, Brands__r.Name,
                       Week_MIN_Field__c,
                       Length__c,
                       SF_Deal_ID__c,
                       Advertiser_ID__c,
                       Advertiser__c, (
                           SELECT Name,
                                  Deal_Parent__r.Brands__r.Name,
                                  OrderLineNumber__c,
                                  Days_Allowed_Formula__c,
                                  Start_Time__c,
                                  Days_Allowed__c,
                                  End_Time__c,
                                  Rate__c,
                                  MGM_HD_Daypart__c,
                                  Total_Dollars__c,
                                  Units_Available__c,
                                  Units_Aired__c,
                                  Cap__c,
                                  LastModifiedDate
                             FROM Schedules__r
                            WHERE Status__c = 'Sold'
                              AND Week__c =: week
                       )
                  FROM Deal__c
                 WHERE Id =: dealId
        ];
    }

    public virtual List<Deal__c> getDealsFromQuery(String query) {
        return Database.query(query);
    }
}