objects/Bundle_Pricing__c.object
<CustomObject>
    <fields>
        <fullName>Start_Time__c</fullName>
        <label>Start Time</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>01:00A</fullName>
                </value>
                <value>
                    <fullName>01:30A</fullName>
                </value>
                <value>
                    <fullName>02:00A</fullName>
                </value>
                <value>
                    <fullName>02:30A</fullName>
                </value>
                <value>
                    <fullName>03:00A</fullName>
                </value>
                <value>
                    <fullName>03:30A</fullName>
                </value>
                <value>
                    <fullName>04:00A</fullName>
                </value>
                <value>
                    <fullName>04:30A</fullName>
                </value>
                <value>
                    <fullName>05:00A</fullName>
                </value>
                <value>
                    <fullName>05:30A</fullName>
                </value>
                <value>
                    <fullName>06:00A</fullName>
                </value>
                <value>
                    <fullName>06:30A</fullName>
                </value>
                <value>
                    <fullName>07:00A</fullName>
                </value>
                <value>
                    <fullName>07:30A</fullName>
                </value>
                <value>
                    <fullName>08:00A</fullName>
                </value>
                <value>
                    <fullName>08:30A</fullName>
                </value>
                <value>
                    <fullName>09:00A</fullName>
                </value>
                <value>
                    <fullName>09:30A</fullName>
                </value>
                <value>
                    <fullName>10:00A</fullName>
                </value>
                <value>
                    <fullName>10:30A</fullName>
                </value>
                <value>
                    <fullName>11:00A</fullName>
                </value>
                <value>
                    <fullName>11:30A</fullName>
                </value>
                <value>
                    <fullName>12:00P</fullName>
                </value>
                <value>
                    <fullName>12:30P</fullName>
                </value>
                <value>
                    <fullName>01:00P</fullName>
                </value>
                <value>
                    <fullName>01:30P</fullName>
                </value>
                <value>
                    <fullName>02:00P</fullName>
                </value>
                <value>
                    <fullName>02:30P</fullName>
                </value>
                <value>
                    <fullName>03:00P</fullName>
                </value>
                <value>
                    <fullName>03:30P</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Bundle Pricing</label>
    <nameField>
        <displayFormat>BDP-{000}</displayFormat>
        <label>Bundle Daypart Pricing Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bundle Pricing</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Deal__c.object
<CustomObject>
    <fields>
        <fullName>ClientCode__c</fullName>
        <formula>Program__r.ClientCode__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ClientCode</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Type__c</field>
                <operation>notEqual</operation>
                <value>history</value>
            </filterItems>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>Do Not Call</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Network_Deal_Number__c</fullName>
        <description>Deal number in Network&apos;s paper work, in Network&apos;s records.</description>
        <externalId>true</externalId>
        <inlineHelpText>Deal number in Network&apos;s paper work, in Network&apos;s records.  Equals 1 if the PI campaign is no longer airing on the network.</inlineHelpText>
        <label>Network Deal Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Deal</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Deal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Programs__c.object
<CustomObject>
    <description>Program/Distributor</description>
    <fields>
        <fullName>Cable_Synd__c</fullName>
        <label>Cable/Synd/PP</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cable</fullName>
                </value>
                <value>
                    <fullName>Syndication</fullName>
                </value>
                <value>
                    <fullName>PP</fullName>
                </value>
                <value>
                    <fullName>Bundle</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ClientCode__c</fullName>
        <description>Assigned by Finance</description>
        <inlineHelpText>Assigned by Finance</inlineHelpText>
        <label>ClientCode</label>
        <length>3</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Clock_Start_Time__c</fullName>
        <label>Clock Start Time</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>5AM</fullName>
                </value>
                <value>
                    <fullName>6AM</fullName>
                </value>
                <value>
                    <fullName>4AM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Reconciled_Week__c</fullName>
        <inlineHelpText>The last fully reconciled week in Salesforce</inlineHelpText>
        <label>Reconciled Week</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Station_Call_Letter__c</fullName>
        <label>Station Call Letter</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Schedules__c.object
<CustomObject>
    <fields>
        <fullName>Days_Allowed__c</fullName>
        <description>Select days that the schedule is allowed to air</description>
        <inlineHelpText>Select the days that this schedule CAN air on.</inlineHelpText>
        <label>Days Allowed</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Mon</fullName>
                </value>
                <value>
                    <fullName>Tue</fullName>
                </value>
                <value>
                    <fullName>Wed</fullName>
                </value>
                <value>
                    <fullName>Thu</fullName>
                </value>
                <value>
                    <fullName>Fri</fullName>
                </value>
                <value>
                    <fullName>Sat</fullName>
                </value>
                <value>
                    <fullName>Sun</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Deal_Parent__c</fullName>
        <label>Deal Parent</label>
        <referenceTo>Deal__c</referenceTo>
        <relationshipLabel>Schedules</relationshipLabel>
        <relationshipName>Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Network_Deal_Number__c</fullName>
        <formula>Deal_Parent__r.Network_Deal_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Network Deal Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <label>Start Time</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>MGM_HD_Daypart__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>01:00A</fullName>
                </value>
                <value>
                    <fullName>01:30A</fullName>
                </value>
                <value>
                    <fullName>02:00A</fullName>
                </value>
                <value>
                    <fullName>02:30A</fullName>
                </value>
                <value>
                    <fullName>03:00A</fullName>
                </value>
                <value>
                    <fullName>03:30A</fullName>
                </value>
                <value>
                    <fullName>04:00A</fullName>
                </value>
                <value>
                    <fullName>04:30A</fullName>
                </value>
                <value>
                    <fullName>05:00A</fullName>
                </value>
                <value>
                    <fullName>05:30A</fullName>
                </value>
                <value>
                    <fullName>06:00A</fullName>
                    <default>true</default>
                    <label>06:00A</label>
                </value>
                <value>
                    <fullName>06:30A</fullName>
                </value>
                <value>
                    <fullName>07:00A</fullName>
                </value>
                <value>
                    <fullName>07:30A</fullName>
                </value>
                <value>
                    <fullName>08:00A</fullName>
                </value>
                <value>
                    <fullName>08:30A</fullName>
                </value>
                <value>
                    <fullName>09:00A</fullName>
                </value>
                <value>
                    <fullName>09:30A</fullName>
                </value>
                <value>
                    <fullName>10:00A</fullName>
                </value>
                <value>
                    <fullName>10:30A</fullName>
                </value>
                <value>
                    <fullName>11:00A</fullName>
                </value>
                <value>
                    <fullName>11:30A</fullName>
                </value>
                <value>
                    <fullName>12:00P</fullName>
                </value>
                <value>
                    <fullName>12:30P</fullName>
                </value>
                <value>
                    <fullName>01:00P</fullName>
                </value>
                <value>
                    <fullName>01:30P</fullName>
                </value>
                <value>
                    <fullName>02:00P</fullName>
                </value>
                <value>
                    <fullName>02:30P</fullName>
                </value>
                <value>
                    <fullName>03:00P</fullName>
                </value>
                <value>
                    <fullName>03:30P</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Week__c</fullName>
        <label>Week</label>
        <type>Date</type>
    </fields>
    <label>Schedule</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Spot_Data__c.object
<CustomObject>
    <description>Post log information for schedule</description>
    <fields>
        <fullName>Network_Deal_Number__c</fullName>
        <formula>Schedule__r.Deal_Parent__r.Network_Deal_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Network Deal Number</label>
        <type>Text</type>
    </fields>
    <label>Spot Data</label>
    <nameField>
        <displayFormat>S-{000000}</displayFormat>
        <label>Spot Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Spot Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/BundleSpotsBatchTest.cls
@IsTest
public with sharing class BundleSpotsBatchTest {

    private static Account createAccount() {
        Account testAcct = new Account();
        testAcct.Name = 'Test Account';
        return testAcct;
    }

    private static Contact createContact(Account testAcct){
        Contact contact = new Contact();
        contact.FirstName = 'Test';
        contact.LastName = 'Name';
        contact.Email = 'test@testemail.com';
        contact.Phone = '(758) 771-0091';
        contact.Account = testAcct;
        return contact;
    }


    private static Programs__c createProgram(String dealNumber) {
        Programs__c program = new Programs__c();
        program.Name = 'testNetwork';
        program.Cable_Synd__c = 'Cable';
        program.Station_Call_Letter__c = Utils.generateRandomCallsign();
        program.ClientCode__c = dealNumber;
        program.Clock_Start_Time__c = '';
        program.Reconciled_Week__c = Date.newInstance(2019, 1, 7);
        return program;
    }

    static Deal__c createDeal(Contact testContact, String dealNumber) {
        Deal__c testDeal = new Deal__c();
        testDeal.Contact__c = testContact.id;
        testDeal.Network_Deal_Number__c = dealNumber;
        return testDeal;
    }


    private static Schedules__c createSchedule(Deal__c testDeal) {

        Schedules__c schedule = new Schedules__c();
        schedule.Deal_Parent__c = testDeal.id;
        schedule.Week__c = Date.newInstance(2019, 1, 7);
        schedule.Days_Allowed__c = 'Mon';
        schedule.Start_Time__c = '06:00A';
        schedule.End_Time__c = '06:30A';
        schedule.Rate__c = 100;
        schedule.Units_Available__c = 5;
        return schedule;
    }

    private static Station__c createStation() {
        Station__c testStation = new Station__c();
        testStation.Call_Letters__c = Utils.generateRandomCallsign();
        return testStation;

    }

    private static Bundle_Pricing__c createBundlePricing(Programs__c testProgram, Station__c testStation, Stationn__c testStationn) {
        Bundle_Pricing__c testBundlePricing = new Bundle_Pricing__c();
        testBundlePricing.Program__c = testProgram.Id;
        testBundlePricing.Rate_per_30__c = 35;
        testBundlePricing.Station__c = testStation.Id;
        testBundlePricing.Active__c = true;
        testBundlePricing.Units__c = 35;
        testBundlePricing.Stationn__c = testStationn.Id;
        testBundlePricing.Start_Time__c = '6:00A';
        return testBundlePricing;
    }

    private static Markett__c makeMarkett() {
        return new Markett__c();
    }

    private static Stationn__c createStationn(Markett__c testMarkett) {
        Stationn__c testStationn = new Stationn__c();
        testStationn.Markett__c = testMarkett.id;
        testStationn.Call_Letters__c = Utils.generateRandomCallsign();
        return testStationn;
    }



    private static void prepExecuteTest(Integer totalPrograms) {
        List<Schedules__c> scheduleList = new List<Schedules__c>();
        List<Deal__c> dealList = new List<Deal__c>();
        List<Account> accountList = new List<Account>();
        List<Contact> contactList = new List<Contact>();
        List<Programs__c> programList = new List<Programs__c>();
        List<Bundle_Pricing__c> bundlePricingList = new List<Bundle_Pricing__c>();
        List<Station__c> stationList = new List<Station__c>();
        List<Markett__c> markettList = new List<Markett__c>();
        List<Stationn__c> stationnList = new List<Stationn__c>();
        Integer i = 0;
        for (i = 0; i < totalPrograms; i++) {
            accountList.add(createAccount());
            contactList.add(createContact(accountList[i]));
            markettList.add(makeMarkett());
        }

        insert accountList;
        insert contactList;
        insert markettList;

        for (i = 0; i < totalPrograms; i++){
            programList.add(createProgram(String.valueOf(i)));
            stationList.add(createStation());
            stationnList.add(createStationn(markettList[i]));
        }

        insert stationList;
        insert stationnList;
        insert programList;


        i = 0;
        Deal__c tempDeal;
        for (Contact contact : contactList) {
            tempDeal = createDeal(contact, String.valueOf(i));
            tempDeal.Program__c = programList[i].id;
            dealList.add(tempDeal);
            i++;
        }

        insert dealList;
        for (Deal__c deal : dealList) {
            scheduleList.add(createSchedule(deal));
        }

        insert scheduleList;


        for (i = 0; i < totalPrograms; i++) {
            bundlePricingList.add(createBundlePricing(programList[i], stationList[i], stationnList[i]));
        }



        insert bundlePricingList;
    }

    @IsTest
    private static void BundleSpotsBatch_execute_correctAmountOfSpotsFound() {
        Integer totalPrograms = 5;
        prepExecuteTest(totalPrograms);

        Test.startTest();
        BundleSpotsBatch testBatch = new BundleSpotsBatch('testNetwork');
        testBatch.setBundleSelector(new BundleTestSelector());
        testBatch.setScheduleSelector(new ScheduleTestSelector());
        testBatch.setProgramSelector(new ProgramTestSelector());
        testBatch.setSpotDataSelector(new SpotDataTestSelector());
        Database.executeBatch(testBatch);
        Test.stopTest();

        List<Spot_Data__c> returnedSpotData = [SELECT Id FROM Spot_Data__c];
        System.assert(returnedSpotData.size() == totalPrograms);

    }
}