objects/Bundle_Pricing__c.object
<CustomObject>
    <fields>
        <fullName>Call_Letters__c</fullName>
        <formula>Station__r.Call_Letters__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Call Letters</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Days__c</fullName>
        <label>Days</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Monday</fullName>
                </value>
                <value>
                    <fullName>Tuesday</fullName>
                </value>
                <value>
                    <fullName>Wednesday</fullName>
                </value>
                <value>
                    <fullName>Thursday</fullName>
                </value>
                <value>
                    <fullName>Friday</fullName>
                </value>
                <value>
                    <fullName>Saturday</fullName>
                </value>
                <value>
                    <fullName>Sunday</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <referenceTo>Programs__c</referenceTo>
        <relationshipName>Bundle_Daypart_Pricing</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Rate_per_30__c</fullName>
        <label>Rate per 30</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total__c</fullName>
        <formula>Rate_per_30__c  *  Units__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Units__c</fullName>
        <label>Units</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Bundle Pricing</label>
    <nameField>
        <displayFormat>BDP-{000}</displayFormat>
        <label>Bundle Daypart Pricing Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bundle Pricing</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Deal__c.object
<CustomObject>
    <fields>
        <fullName>Length__c</fullName>
        <label>Length</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>30</fullName>
                    <color>#0B6FCE</color>
                    <label>30</label>
                </value>
                <value>
                    <fullName>60</fullName>
                    <color>#78C953</color>
                    <label>60</label>
                </value>
                <value>
                    <fullName>120</fullName>
                    <color>#E27001</color>
                    <label>120</label>
                </value>
                <value>
                    <fullName>300</fullName>
                    <color>#A845DC</color>
                    <label>300</label>
                </value>
                <value>
                    <fullName>15</fullName>
                    <color>#F3D904</color>
                    <label>15</label>
                </value>
                <value>
                    <fullName>1710</fullName>
                    <color>#A53711</color>
                    <label>1710</label>
                </value>
                <value>
                    <fullName>90</fullName>
                    <color>#66E9BD</color>
                    <label>90</label>
                </value>
                <value>
                    <fullName>180</fullName>
                    <color>#0B24BE</color>
                    <label>180</label>
                </value>
                <value>
                    <fullName>240</fullName>
                    <color>#419249</color>
                    <label>240</label>
                </value>
                <value>
                    <fullName>45</fullName>
                </value>
                <value>
                    <fullName>75</fullName>
                </value>
                <value>
                    <fullName>05</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>150</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>105</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>35</fullName>
                </value>
                <value>
                    <fullName>40</fullName>
                </value>
                <value>
                    <fullName>1714</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Program</label>
        <referenceTo>Programs__c</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <label>[Dep]Rate</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Units__c</fullName>
        <description>DELETE- Used in Q4 2008.  Think this is deleteable, but not sure.</description>
        <label>[Dep]Units</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Deal</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Deal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Schedules__c.object
<CustomObject>
    <fields>
        <fullName>DealBrand__c</fullName>
        <formula>Deal_Parent__r.Brands__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>DealBrand</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Deal_Parent__c</fullName>
        <label>Deal Parent</label>
        <referenceTo>Deal__c</referenceTo>
        <relationshipLabel>Schedules</relationshipLabel>
        <relationshipName>Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PI_Payout_TEST__c</fullName>
        <description>Roll up of payout amount from the PI Payout Child object</description>
        <label>PI Payout TEST</label>
        <summarizedField>PI_Payout__c.Payout_Amount__c</summarizedField>
        <summaryForeignKey>PI_Payout__c.Schedule__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <label>Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Spot_Total__c</fullName>
        <label>Spot Total $</label>
        <summarizedField>Spot_Data__c.Spot_Rate__c</summarizedField>
        <summaryFilterItems>
            <field>Spot_Data__c.Status__c</field>
            <operation>notEqual</operation>
            <value>Discrepancy</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Spot_Data__c.Availability__c</field>
            <operation>equals</operation>
            <value>False</value>
        </summaryFilterItems>
        <summaryForeignKey>Spot_Data__c.Schedule__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Sum_Spot_Equiv_30__c</fullName>
        <label>Sum of Spot Equiv 30</label>
        <summarizedField>Spot_Data__c.Spot_Equiv_30__c</summarizedField>
        <summaryForeignKey>Spot_Data__c.Schedule__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>UnitLength__c</fullName>
        <formula>VALUE(TEXT(Deal_Parent__r.Length__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>UnitLength</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Units_Aired__c</fullName>
        <formula>case( Status__c, &quot;Canceled&quot;, 0, Units_Available__c - Units_Preempted__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Units Aired</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Week__c</fullName>
        <label>Week</label>
        <type>Date</type>
    </fields>
    <label>Schedule</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Spot_Data__c.object
<CustomObject>
    <description>Post log information for schedule</description>
    <fields>
        <fullName>Length__c</fullName>
        <label>Length</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>30</fullName>
                </value>
                <value>
                    <fullName>45</fullName>
                </value>
                <value>
                    <fullName>60</fullName>
                </value>
                <value>
                    <fullName>90</fullName>
                </value>
                <value>
                    <fullName>120</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>75</fullName>
                </value>
                <value>
                    <fullName>180</fullName>
                </value>
                <value>
                    <fullName>300</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Spot Data</label>
    <nameField>
        <displayFormat>S-{000000}</displayFormat>
        <label>Spot Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Spot Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Station__c.object
<CustomObject>
    <fields>
        <fullName>Call_Letters__c</fullName>
        <externalId>true</externalId>
        <label>Call Letters</label>
        <length>55</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Station</label>
    <nameField>
        <displayFormat>ST-{00000}</displayFormat>
        <label>Station Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Stationn__c.object
<CustomObject>
    <description>Sample station test</description>
    <fields>
        <fullName>Call_Letters__c</fullName>
        <externalId>true</externalId>
        <label>Owner Call Letters</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Stationn</label>
    <nameField>
        <label>Stationn Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stationns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CreateSpotsForBundles.cls
// Status = Sold
// Program = Bundle Program
// 
// Reconciled = 'Y'
// 
public class CreateSpotsForBundles{
    public List<Spot_Data__c> availSpots  = new List<Spot_Data__c>();
    public class ApplicationException extends Exception {}
    
    @InvocableMethod
    public static void SpotstoInsert(List<Id> Scheds)
    {   
        List<Spot_Data__c> newSpots = new List<Spot_Data__c>();
        newSpots = CreateSpots(Scheds);       
        insert newSpots;
    }
    
    public static List<Spot_Data__c> CreateSpots(List<Id> SchedsIds){
        List<Spot_Data__c> availSpots  = new List<Spot_Data__c>();
        List<Id> Progid = new List<Id>();
        Integer i;
        
        Schedules__c[] ssch = [SELECT Id, Units_Aired__c, Sum_Spot_Equiv_30__c, PI_Payout_TEST__c, Spot_Total__c, Rate__c, Week__c, Deal_Parent__r.Program__c, DealBrand__c, Deal_Parent__r.Program__r.Id, UnitLength__c
                        FROM Schedules__c 
                        WHERE Id in :SchedsIds];
    
        Progid.add(ssch[0].Deal_Parent__r.Program__r.Id);    

        Bundle_Pricing__c[] bundles = [SELECT Call_Letters__c, Rate_per_30__c, Days__c, Program__c, Units__c, Total__c, Start_Time__c, Market__c, Station__c 
                        FROM Bundle_Pricing__c
                        WHERE Active__c != false
                        AND Program__r.Id in :Progid];

    
        if(ssch[0].Id == null){
            throw new ApplicationException('The Advertiser lookup is missing from the Deal. Please add an Advertiser and try again.');
        }
        if(ssch[0].UnitLength__c == null){
            throw new ApplicationException('The Units are missing from either the Bundle or the Schedule');
        }
        
        for(i = 0; i < bundles.size(); i++){
        if(bundles[i].Units__c == null){
            throw new ApplicationException('The Units for the Bundle:' + bundles[i] + ' is empty' );
        }
        if(bundles[i].Rate_per_30__c == null || bundles[i].Units__c == null){
            throw new ApplicationException('The Units or the Rate for the Bundle is empty');
        }
        if(bundles[i].Station__c == null){
            throw new ApplicationException('The Stationn for the Bundle is empty');
        }
            
        String a = bundles[0].Start_Time__c;
        String aTime = a.left(3) + String.valueOf(Math.random()*60).left(1) + String.valueOf(Math.random()*100).left(1) + a.right(1);
        Spot_Data__c spot = new Spot_Data__c(); 
                    spot.Schedule__c = ssch[0].Id;
                    spot.Length__c = String.valueOf((ssch[0].UnitLength__c)*(bundles[i].Units__c));
                    spot.Spot_Rate__c = ((bundles[i].Rate_per_30__c)*(bundles[i].Units__c));                    
                    spot.Stationn__c = bundles[i].Station__c;
                    spot.Availability__c = true;
                    spot.Air_Date__c = ssch[0].Week__c;
                    spot.Air_Time__c = aTime;

                    availSpots.add(spot);
        }
        
        return availSpots;
    }
    

}