objects/Bundle_Pricing__c.object
<CustomObject>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <referenceTo>Programs__c</referenceTo>
        <relationshipName>Bundle_Daypart_Pricing</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Rate_per_30__c</fullName>
        <label>Rate per 30</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <label>Start Time</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>01:00A</fullName>
                </value>
                <value>
                    <fullName>01:30A</fullName>
                </value>
                <value>
                    <fullName>02:00A</fullName>
                </value>
                <value>
                    <fullName>02:30A</fullName>
                </value>
                <value>
                    <fullName>03:00A</fullName>
                </value>
                <value>
                    <fullName>03:30A</fullName>
                </value>
                <value>
                    <fullName>04:00A</fullName>
                </value>
                <value>
                    <fullName>04:30A</fullName>
                </value>
                <value>
                    <fullName>05:00A</fullName>
                </value>
                <value>
                    <fullName>05:30A</fullName>
                </value>
                <value>
                    <fullName>06:00A</fullName>
                </value>
                <value>
                    <fullName>06:30A</fullName>
                </value>
                <value>
                    <fullName>07:00A</fullName>
                </value>
                <value>
                    <fullName>07:30A</fullName>
                </value>
                <value>
                    <fullName>08:00A</fullName>
                </value>
                <value>
                    <fullName>08:30A</fullName>
                </value>
                <value>
                    <fullName>09:00A</fullName>
                </value>
                <value>
                    <fullName>09:30A</fullName>
                </value>
                <value>
                    <fullName>10:00A</fullName>
                </value>
                <value>
                    <fullName>10:30A</fullName>
                </value>
                <value>
                    <fullName>11:00A</fullName>
                </value>
                <value>
                    <fullName>11:30A</fullName>
                </value>
                <value>
                    <fullName>12:00P</fullName>
                </value>
                <value>
                    <fullName>12:30P</fullName>
                </value>
                <value>
                    <fullName>01:00P</fullName>
                </value>
                <value>
                    <fullName>01:30P</fullName>
                </value>
                <value>
                    <fullName>02:00P</fullName>
                </value>
                <value>
                    <fullName>02:30P</fullName>
                </value>
                <value>
                    <fullName>03:00P</fullName>
                </value>
                <value>
                    <fullName>03:30P</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Stationn__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Stationn</label>
        <referenceTo>Stationn__c</referenceTo>
        <relationshipLabel>Bundle Pricing</relationshipLabel>
        <relationshipName>Bundle_Pricing</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Units__c</fullName>
        <label>Units</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Bundle Pricing</label>
    <nameField>
        <displayFormat>BDP-{000}</displayFormat>
        <label>Bundle Daypart Pricing Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bundle Pricing</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Deal__c.object
<CustomObject>
    <fields>
        <fullName>Length__c</fullName>
        <label>Length</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>30</fullName>
                    <color>#0B6FCE</color>
                    <label>30</label>
                </value>
                <value>
                    <fullName>60</fullName>
                    <color>#78C953</color>
                    <label>60</label>
                </value>
                <value>
                    <fullName>120</fullName>
                    <color>#E27001</color>
                    <label>120</label>
                </value>
                <value>
                    <fullName>300</fullName>
                    <color>#A845DC</color>
                    <label>300</label>
                </value>
                <value>
                    <fullName>15</fullName>
                    <color>#F3D904</color>
                    <label>15</label>
                </value>
                <value>
                    <fullName>1710</fullName>
                    <color>#A53711</color>
                    <label>1710</label>
                </value>
                <value>
                    <fullName>90</fullName>
                    <color>#66E9BD</color>
                    <label>90</label>
                </value>
                <value>
                    <fullName>180</fullName>
                    <color>#0B24BE</color>
                    <label>180</label>
                </value>
                <value>
                    <fullName>240</fullName>
                    <color>#419249</color>
                    <label>240</label>
                </value>
                <value>
                    <fullName>45</fullName>
                </value>
                <value>
                    <fullName>75</fullName>
                </value>
                <value>
                    <fullName>05</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>150</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>105</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>35</fullName>
                </value>
                <value>
                    <fullName>40</fullName>
                </value>
                <value>
                    <fullName>1714</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Program</label>
        <referenceTo>Programs__c</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Units__c</fullName>
        <description>DELETE- Used in Q4 2008.  Think this is deleteable, but not sure.</description>
        <label>[Dep]Units</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Deal</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Deal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Programs__c.object
<CustomObject>
    <description>Program/Distributor</description>
    <fields>
        <fullName>Reconciled_Week__c</fullName>
        <inlineHelpText>The last fully reconciled week in Salesforce</inlineHelpText>
        <label>Reconciled Week</label>
        <type>Date</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Schedules__c.object
<CustomObject>
    <fields>
        <fullName>DealProgram__c</fullName>
        <formula>Deal_Parent__r.Program__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>DealProgram</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Deal_Parent__c</fullName>
        <label>Deal Parent</label>
        <referenceTo>Deal__c</referenceTo>
        <relationshipLabel>Schedules</relationshipLabel>
        <relationshipName>Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>UnitLength__c</fullName>
        <formula>VALUE(TEXT(Deal_Parent__r.Length__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>UnitLength</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Week__c</fullName>
        <label>Week</label>
        <type>Date</type>
    </fields>
    <label>Schedule</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Spot_Data__c.object
<CustomObject>
    <description>Post log information for schedule</description>
    <fields>
        <fullName>Length__c</fullName>
        <label>Length</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>30</fullName>
                </value>
                <value>
                    <fullName>45</fullName>
                </value>
                <value>
                    <fullName>60</fullName>
                </value>
                <value>
                    <fullName>90</fullName>
                </value>
                <value>
                    <fullName>120</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>75</fullName>
                </value>
                <value>
                    <fullName>180</fullName>
                </value>
                <value>
                    <fullName>300</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Stationn__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Stationn</label>
        <referenceTo>Stationn__c</referenceTo>
        <relationshipLabel>Spot Data</relationshipLabel>
        <relationshipName>Spot_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Spot Data</label>
    <nameField>
        <displayFormat>S-{000000}</displayFormat>
        <label>Spot Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Spot Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/BundleSpotsBatch.cls
/**
* @author Adrian Pichardo
* @date 06/30/2018
* @description APEX Batch class that creates Spot Data for Bundle Availability Schedules. Code is invoked in Process Builder.
*              Process: BundlesSpotsProgram.
**/
global class BundleSpotsBatch implements Database.batchable <sobject>
{

    private static BundleSelector bundleSelector = new BundleSelector();

    public void setBundleSelector(BundleSelector bSelector){
        bundleSelector = bSelector;
    }

    private static ScheduleSelector scheduleSelector = new ScheduleSelector();

    public void setScheduleSelector(ScheduleSelector sSelector){
        scheduleSelector = sSelector;
    }

    private static ProgramSelector programSelector = new ProgramSelector();

    public void setProgramSelector(ProgramSelector pSelector){
        programSelector = pSelector;
    }

    private static SpotDataSelector spotDataSelector = new SpotDataSelector();

    public void setSpotDataSelector(SpotDataSelector sDSelector){
        spotDataSelector = sDSelector;
    }

    global static List<String> listedPrograms = new List<String> {'Raycom Bounce Locals','Raycom Connect','Raycom Connect Extra','Retro Raycom','Hearst Unwired'};
    global String network;
    global class ApplicationException extends Exception {}

    global BundleSpotsBatch(String n)
    {
        if(n == 'All') {
            this.network = '' ;
        } else {
            this.network = n;
        }
    }

    global Database.QueryLocator start(Database.BatchableContext bc) {
        List<Programs__c> weeksReconciled = programSelector.getProgramsForBundleSpotsBatchStart(network);
        Date week = weeksReconciled[0].Reconciled_Week__c;
        return Database.getQueryLocator([SELECT Id,
                                       	 	    UnitLength__c,
                                       	 	    Week__c
                                           FROM Schedules__c
                                          WHERE DealProgram__c = :network
                                            AND Week__c = :week]);
    }

    global void execute(Database.BatchableContext bc, List<Schedules__c> records){

        if(records.isEmpty()){
            throw new ApplicationException('No Schedules for the Reconciled week listed');
        }
        if(spotsExist(records[0].Id) == 1){
            throw new ApplicationException('Avail Spot Data already exists for this Week');
        }

        Integer i;
        List<Spot_Data__c> spotsToInsert = new List<Spot_Data__c>();

        for(Schedules__c schedule : records){
            spotsToInsert.addAll(BuildSpots(schedule.Id));
        }
        database.insert(spotsToInsert, false);
    }

    global void finish(Database.BatchableContext bc){
        //Necessary for Batch code
    }

    /**
    * @author Adrian Pichardo
    * @date 06/30/2018
    * @description Returns a list of new Spot Data records using a schedule from the start method. Takes Bundle Pricing Units
    *              for each Schedule and creates a Spot Data record accordingly. One Spot Data record corresponds to one Bundle
    *              Pricing Unit.
    * @param Id sch - ID of a Schedule record
    * @return List<Spot_Data__c> - List of new Spot Data that will be inserted into our Salesforce Org in the execute method.
    **/
    global static List<Spot_Data__c> BuildSpots(Id sch)
    {
        List<Spot_Data__c> availSpots  = new List<Spot_Data__c>();
        List<Id> Progid = new List<Id>();
        Integer j;

        Schedules__c[] ssch = scheduleSelector.getSchedulesForBuildSpots(sch);


        Progid.add(ssch[0].Deal_Parent__r.Program__r.Id);
        Bundle_Pricing__c[] bundles = bundleSelector.getBundlePricingForBuildSpots(progid);

        if(ssch[0].UnitLength__c == null){
            throw new ApplicationException('The Units are missing from either the Bundle or the Schedule');
        }

        for(j = 0; j < bundles.size(); j++){
            if(bundles[j].Units__c == null){
                throw new ApplicationException('The Units for the Bundle:' + bundles[j] + ' is empty' );
            }
            if(bundles[j].Rate_per_30__c == null || bundles[j].Units__c == null){
                throw new ApplicationException('The Units or the Rate for the Bundle is empty');
            }
            if(bundles[j].Stationn__c == null){
                throw new ApplicationException('The Stationn for the Bundle is empty');
            }

            String aTime = RandomTime(bundles[j].Start_Time__c);

            Spot_Data__c spot = new Spot_Data__c(
                    Schedule__c = ssch[0].Id,
                    Length__c = String.valueOf((ssch[0].UnitLength__c)*(bundles[j].Units__c)),
                    Spot_Rate__c = bundles[j].Total__c,
                    Stationn__c = bundles[j].Stationn__c,
                    Availability__c = true,
                    Air_Date__c = ssch[0].Week__c,
                    Air_Time__c = aTime
            );
            availSpots.add(spot);
        }

        return availSpots;
    }

    /**
    * @author Adrian Pichardo
    * @date 06/30/2018
    * @description Uses the hour of the start string (parameter) and gives random minutes and seconds for the new time string.
    * @param String start - String of time
    * @return String - new String that corresponds to a time.
    **/
    global static String RandomTime(String start)
    {
        String randomTime = '';
        randomTime = start.left(3) + String.valueOf(Math.random()*60).left(1) + String.valueOf(Math.random()*100).left(1) + ':' + String.valueOf(Math.random()*6).left(1) + String.valueOf(Math.random()*10).left(1) + ' ' + start.right(1) + 'M';
        return randomTime;
    }

    /**
    * @author Adrian Pichardo
    * @date 07/14/2018
    * @description Returns the Integer 1 if Avail Spot Data exists for the record given
    * @param Id sch - ID of a Schedule record
    * @return Integer - Integer that returns 1 if Avail Spots exist.
    **/
    global static Integer spotsExist(Id sch)
    {
        Spot_Data__c[] s = spotDataSelector.getSpotsForSpotsExist(sch);
        if(s.isEmpty()){
            return 0;
        }else{
            return 1;
        }
    }

}