objects/Deal__c.object
<CustomObject>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Program</label>
        <referenceTo>Programs__c</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Deal</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Deal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Programs__c.object
<CustomObject>
    <description>Program/Distributor</description>
    <label>Program</label>
    <nameField>
        <label>Program</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Schedules__c.object
<CustomObject>
    <fields>
        <fullName>Networks__c</fullName>
        <description>Select a Network to dynamically filter the list of relevant cable dayparts.</description>
        <inlineHelpText>Select a Network to dynamically filter the list of relevant cable dayparts.</inlineHelpText>
        <label>Networks</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Justice Network</fullName>
                </value>
                <value>
                    <fullName>CBS Sports</fullName>
                </value>
                <value>
                    <fullName>MAV TV</fullName>
                </value>
                <value>
                    <fullName>Antenna TV</fullName>
                </value>
                <value>
                    <fullName>This TV</fullName>
                </value>
                <value>
                    <fullName>Bounce</fullName>
                </value>
                <value>
                    <fullName>TENNIS</fullName>
                </value>
                <value>
                    <fullName>MLB</fullName>
                </value>
                <value>
                    <fullName>MGM HD</fullName>
                </value>
                <value>
                    <fullName>GritTV</fullName>
                </value>
                <value>
                    <fullName>EscapeTV</fullName>
                </value>
                <value>
                    <fullName>DOC</fullName>
                </value>
                <value>
                    <fullName>FamilyNet</fullName>
                </value>
                <value>
                    <fullName>COOL</fullName>
                </value>
                <value>
                    <fullName>NFLN</fullName>
                </value>
                <value>
                    <fullName>JLTV</fullName>
                </value>
                <value>
                    <fullName>SiTV</fullName>
                </value>
                <value>
                    <fullName>OUTSIDE</fullName>
                </value>
                <value>
                    <fullName>Univision Select</fullName>
                </value>
                <value>
                    <fullName>Telefutura Select</fullName>
                </value>
                <value>
                    <fullName>Youtoo</fullName>
                </value>
                <value>
                    <fullName>Test Network</fullName>
                </value>
                <value>
                    <fullName>Cozi</fullName>
                </value>
                <value>
                    <fullName>BuzzrTV</fullName>
                </value>
                <value>
                    <fullName>FidoTV</fullName>
                </value>
                <value>
                    <fullName>Laff</fullName>
                </value>
                <value>
                    <fullName>Tribune Sports</fullName>
                </value>
                <value>
                    <fullName>NHL Network</fullName>
                </value>
                <value>
                    <fullName>NHL Network - Local</fullName>
                </value>
                <value>
                    <fullName>TVG</fullName>
                </value>
                <value>
                    <fullName>BounceTV - Local</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Schedule</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ApricotDealButton.cls
public class ApricotDealButton {

    //
    // Fields
    //
    public ApexPages.StandardController controller { get; set; }
    public DealSelector dealSelector { get; set; }
    public String dealId { get; set; }
    public String dealName { get; set; }
    public String network = null;

    /**
     * @description Construct ApricotDealButton with injected DealSelector
     * @param controller The page view controller
     * @param dealSelector The custom dealSelector being injected
     */
    public ApricotDealButton(ApexPages.StandardController controller, DealSelector dealSelector) {
        this.controller = controller;
        this.dealSelector = dealSelector;
        this.dealSelector = dealSelector;
        this.pageSetup();
    }

    /**
     * @description Construct ApricotDealButton with default DealSelector
     * @param controller The page view controller being assigned
     */
    public ApricotDealButton(ApexPages.StandardController controller) {
        this.controller = controller;
        this.dealSelector = new DealSelector();
        this.pageSetup();
    }

    /**
     * @description Set up the page from the selected controller ID
     */
    private void pageSetup() {
        // Retrieve all picklist values from Networks__c
        Set<String> picklistNetworkStrings = this.getPickListValues(Schedules__c.class, Schedules__c.Networks__c.getDescribe().name);
        List<Deal__c> deals = dealSelector.getDealsFromId(controller.getId());
        Map<String, String> programNetworkMap = this.setupProgramNetworkMap();

        for (Deal__c deal : deals) {
            this.dealName = deal.Name;
            this.dealId = deal.Id;
            String programName = deal.Program__r.Name;

            this.network = programNetworkMap.get(programName);

            // If the network was not listed, check if it's in the picklist
            if (network == null) {
                if (picklistNetworkStrings.contains(programName)) {
                    network = programName;
                } else {
                    network = 'None';
                }
            }
        }
    }

    /**
     * @description Retrieve an instance of the page reference based on selected deal data
     * @return The view-page reference
     */
    public PageReference viewPage() {
        PageReference pageRef = new PageReference('/a08/e?retURL=' + dealId + '&RecordType=012C0000000QexD&ent=01I80000000G533&CF00N80000002dVQS=' + dealName + '&00N80000004dNEJ=' + network);
        return pageRef;
    }

    /**
     * @description Retrieve a set of picklist values from an object type
     * @param obj The Object being selected from
     * @param picklist The picklist whose values are being retrieved
     * @return The constructed set of picklist values
     */
    private Set<String> getPickListValues(Type obj, String picklist) {
        Set<String> result = new Set<String>();
        String objectName = obj.getName();
        if (Schema.getGlobalDescribe().containsKey(objectName)) {
            if (Schema.getGlobalDescribe().get(objectName).getDescribe().fields.getMap().containsKey(picklist)) {
                for (Schema.PicklistEntry PE : Schema.getGlobalDescribe().get(objectName).getDescribe().fields.getMap().get(picklist).getDescribe().getPicklistValues()) {
                    result.add(PE.getValue());
                }
            }
        }
        return result;
    }

    /**
     * Retrieve a map of program to network names
     *
     * @return The mapped values of program names to network names
     */
    private Map<String, String> setupProgramNetworkMap() {
        return new Map<String, String>{
                'BounceTV - Local' => 'BounceTV - Local',
                'Bounce' => 'Bounce',
                'Tennis Channel' => 'MGM HD',
                'COZI' => 'COZI',
                'COZI - Local' => 'COZI',
                'MLB Network' => 'MLB',
                'Documentary Channel' => 'DOC',
                'AntennaTV' => 'Antenna TV',
                'Antenna TV - Local' => 'Antenna TV',
                'ThisTV' => 'This TV',
                'ThisTV - Local' => 'This TV'
        };
    }
}