objects/Deal__c.object
<CustomObject>
    <fields>
        <fullName>ContactAccount__c</fullName>
        <formula>Contact__r.Account.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ContactAccount</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Program</label>
        <referenceTo>Programs__c</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Week_MIN_Field__c</fullName>
        <label>Week MIN Field</label>
        <summarizedField>Schedules__c.Week__c</summarizedField>
        <summaryForeignKey>Schedules__c.Deal_Parent__c</summaryForeignKey>
        <summaryOperation>min</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Deal</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Deal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Programs__c.object
<CustomObject>
    <description>Program/Distributor</description>
    <label>Program</label>
    <nameField>
        <label>Program</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/OUTDOORFilterByDealAccountController.cls
/*
    Name        : OUTDOORFilterByDealAccountController
    Author      :
    Date        : 24th August 2011
    Description : This controller will generates a Lookup like VFPage for selecting Deal Account on DOCEntruCheck VFPage
*/
public class OUTDOORFilterByDealAccountController{

    public List<Deal__c> lstDealAccount{set;get;}
    public void dealAccountName{set;get;}
    public OUTDOORFilterByDealAccountController(){
        createList();
    }
    //This function will fetch the Deals according to criteria passed as Parameters
    public void createList(){
        String program = ApexPages.currentPage().getParameters().get('pg');
        String month = ApexPages.currentPage().getParameters().get('month');
        String year = ApexPages.currentPage().getParameters().get('year');
        System.debug('=='+program+' , '+month+' , '+year);
        if(program!=null && program.trim().equals('')==false && month!=null && month.trim().equals('')==false && year!=null && year.trim().equals('')==false){
            integer iMonth = Integer.valueOf(month);
            integer iYear = Integer.valueOf(year);
            Programs__c pg = [select id from Programs__c where name=:program].get(0);    
            lstDealAccount = [select ContactAccount__c, name 
                                from Deal__c 
                                Where program__c = :pg.id
                                and week_min_Field__c >=:Date.newInstance(iYear,iMonth,1)
                                and week_min_Field__c <:Date.newInstance(iYear,iMonth+1,1)
                                limit 1000
                            ];    
            /*
                [select ContactAccount__c, name 
                                from Deal__c 
                                Where program__c =:program
                                and week_min_Field__c >=:Date.newInstance(iYear,iMonth,1)
                                and week_min_Field__c <:Date.newInstance(iYear,iMonth+1,1)
                            ];        
            */
        }
    }
    public PageReference selectAccount(){
        System.debug('##YesSelectAccount() is called# #');
        String accName = ApexPages.currentPage().getParameters().get('accName');
        PageReference pf =new PageReference('/apex/DOCEntryCheck?acc='+accName);
        pf.setRedirect(true);
        return pf;
    }
}