objects/Deal__c.object
<CustomObject>
    <fields>
        <fullName>Brands__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Brands</label>
        <referenceTo>Brands__c</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <label>[Dep]Rate</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Deal</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Deal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PrelogData__c.object
<CustomObject>
    <fields>
        <fullName>PrelogDataMirrorReference__c</fullName>
        <label>Prelog Data Mirror Reference</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PrelogDataMirror__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Prelog Data Mirror</label>
        <referenceTo>PrelogDataMirror__c</referenceTo>
        <relationshipLabel>Prelog Data</relationshipLabel>
        <relationshipName>Prelog_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <label>Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Schedule__c</fullName>
        <label>Schedule</label>
        <referenceTo>Schedules__c</referenceTo>
        <relationshipLabel>Prelog Data</relationshipLabel>
        <relationshipName>Prelog_Data</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Prelog Data</label>
    <nameField>
        <displayFormat>Pre-{0000000}</displayFormat>
        <label>Prelog Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prelog Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PrelogDataMirror__c.object
<CustomObject>
    <fields>
        <fullName>PrelogData__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Prelog Data</label>
        <referenceTo>PrelogData__c</referenceTo>
        <relationshipLabel>Prelog Data Mirrors</relationshipLabel>
        <relationshipName>Prelog_Data_Mirrors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <label>Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Schedule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Schedule</label>
        <referenceTo>Schedules__c</referenceTo>
        <relationshipLabel>Prelog Data Mirrors</relationshipLabel>
        <relationshipName>Prelog_Data_Mirrors</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Prelog Data Mirror</label>
    <nameField>
        <displayFormat>Prelog-{0000000}</displayFormat>
        <label>Prelog Data Mirror Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prelog Data Mirrors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Schedules__c.object
<CustomObject>
    <fields>
        <fullName>Days_Allowed_Formula__c</fullName>
        <formula>IF ( INCLUDES ( Days_Allowed__c , &quot;Mon&quot; ) , &quot;M&quot; , &quot;-&quot; ) &amp;
IF ( INCLUDES ( Days_Allowed__c , &quot;Tue&quot; ) , &quot;T&quot; , &quot;-&quot; ) &amp;
IF ( INCLUDES ( Days_Allowed__c , &quot;Wed&quot; ) , &quot;W&quot; , &quot;-&quot; ) &amp;
IF ( INCLUDES ( Days_Allowed__c , &quot;Thu&quot; ) , &quot;T&quot; , &quot;-&quot; ) &amp;
IF ( INCLUDES ( Days_Allowed__c , &quot;Fri&quot; ) , &quot;F&quot; , &quot;-&quot; ) &amp;
IF ( INCLUDES ( Days_Allowed__c , &quot;Sat&quot; ) , &quot;Sa&quot; , &quot;-&quot; ) &amp;
IF ( INCLUDES ( Days_Allowed__c , &quot;Sun&quot; ) , &quot;Su&quot; , &quot;-&quot; )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Days Allowed Formula</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Deal_Parent__c</fullName>
        <label>Deal Parent</label>
        <referenceTo>Deal__c</referenceTo>
        <relationshipLabel>Schedules</relationshipLabel>
        <relationshipName>Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>End_Time__c</fullName>
        <label>End Time</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>MGM_HD_Daypart__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>01:00A</fullName>
                </value>
                <value>
                    <fullName>01:30A</fullName>
                </value>
                <value>
                    <fullName>02:00A</fullName>
                </value>
                <value>
                    <fullName>02:30A</fullName>
                </value>
                <value>
                    <fullName>03:00A</fullName>
                </value>
                <value>
                    <fullName>03:30A</fullName>
                </value>
                <value>
                    <fullName>04:00A</fullName>
                </value>
                <value>
                    <fullName>04:30A</fullName>
                </value>
                <value>
                    <fullName>05:00A</fullName>
                </value>
                <value>
                    <fullName>05:30A</fullName>
                </value>
                <value>
                    <fullName>06:00A</fullName>
                    <default>true</default>
                    <label>06:00A</label>
                </value>
                <value>
                    <fullName>06:30A</fullName>
                </value>
                <value>
                    <fullName>07:00A</fullName>
                </value>
                <value>
                    <fullName>07:30A</fullName>
                </value>
                <value>
                    <fullName>08:00A</fullName>
                </value>
                <value>
                    <fullName>08:30A</fullName>
                </value>
                <value>
                    <fullName>09:00A</fullName>
                </value>
                <value>
                    <fullName>09:30A</fullName>
                </value>
                <value>
                    <fullName>10:00A</fullName>
                </value>
                <value>
                    <fullName>10:30A</fullName>
                </value>
                <value>
                    <fullName>11:00A</fullName>
                </value>
                <value>
                    <fullName>11:30A</fullName>
                </value>
                <value>
                    <fullName>12:00P</fullName>
                </value>
                <value>
                    <fullName>12:30P</fullName>
                </value>
                <value>
                    <fullName>01:00P</fullName>
                </value>
                <value>
                    <fullName>01:30P</fullName>
                </value>
                <value>
                    <fullName>02:00P</fullName>
                </value>
                <value>
                    <fullName>02:30P</fullName>
                </value>
                <value>
                    <fullName>03:00P</fullName>
                </value>
                <value>
                    <fullName>03:30P</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OrderLineNumber__c</fullName>
        <label>Order Line Number</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <label>Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <label>Start Time</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>MGM_HD_Daypart__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>01:00A</fullName>
                </value>
                <value>
                    <fullName>01:30A</fullName>
                </value>
                <value>
                    <fullName>02:00A</fullName>
                </value>
                <value>
                    <fullName>02:30A</fullName>
                </value>
                <value>
                    <fullName>03:00A</fullName>
                </value>
                <value>
                    <fullName>03:30A</fullName>
                </value>
                <value>
                    <fullName>04:00A</fullName>
                </value>
                <value>
                    <fullName>04:30A</fullName>
                </value>
                <value>
                    <fullName>05:00A</fullName>
                </value>
                <value>
                    <fullName>05:30A</fullName>
                </value>
                <value>
                    <fullName>06:00A</fullName>
                    <default>true</default>
                    <label>06:00A</label>
                </value>
                <value>
                    <fullName>06:30A</fullName>
                </value>
                <value>
                    <fullName>07:00A</fullName>
                </value>
                <value>
                    <fullName>07:30A</fullName>
                </value>
                <value>
                    <fullName>08:00A</fullName>
                </value>
                <value>
                    <fullName>08:30A</fullName>
                </value>
                <value>
                    <fullName>09:00A</fullName>
                </value>
                <value>
                    <fullName>09:30A</fullName>
                </value>
                <value>
                    <fullName>10:00A</fullName>
                </value>
                <value>
                    <fullName>10:30A</fullName>
                </value>
                <value>
                    <fullName>11:00A</fullName>
                </value>
                <value>
                    <fullName>11:30A</fullName>
                </value>
                <value>
                    <fullName>12:00P</fullName>
                </value>
                <value>
                    <fullName>12:30P</fullName>
                </value>
                <value>
                    <fullName>01:00P</fullName>
                </value>
                <value>
                    <fullName>01:30P</fullName>
                </value>
                <value>
                    <fullName>02:00P</fullName>
                </value>
                <value>
                    <fullName>02:30P</fullName>
                </value>
                <value>
                    <fullName>03:00P</fullName>
                </value>
                <value>
                    <fullName>03:30P</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Schedule</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/PrelogDataSelector.cls
public with sharing virtual class PrelogDataSelector {

    public PrelogDataSelector() {}

    public virtual List<PrelogData__c> getProcessPrelogDataRecords(
            Map<String, PrelogDataMirror__c> UniqueIdPrelogDataMirrorMap) {
        return [
                SELECT Id,
                       Schedule__c,
                       Name,
                       PrelogDataMirrorReference__c
                  FROM PrelogData__c
                 WHERE PrelogDataMirrorReference__c IN :UniqueIdPrelogDataMirrorMap.keySet()
        ];
    }

    public virtual List<PrelogData__c> getPrelogDataForWeekReadOnly(Set<Id> dealWrapperIds, Date monday, Date sunday) {
        System.debug('DEAL WRAPPER IDs: ' + dealWrapperIds);
        return [
                SELECT Schedule__r.Deal_Parent__r.Brands__r.Name,
                       Schedule__r.OrderLineNumber__c,
                       Schedule__r.Days_Allowed_Formula__c,
                       Schedule__r.Start_Time__c,
                       Schedule__r.End_Time__c,
                       Schedule__r.Rate__c,
                       Schedule__r.MGM_HD_Daypart__c,
                       Day_of_Week__c,
                       Rate__c,
                       Schedule__r.Total_Dollars__c
                  FROM PrelogData__c
                 WHERE Schedule__r.Deal_Parent__c IN :dealWrapperIds
                   AND Current_Version__c = TRUE
                   AND AirDate__c >= :monday
                   AND AirDate__c <= :sunday
        ];
    }

    public virtual List<PrelogData__c> getPrelogDataForWeek(Set<Id> dealWrapperIds, Date week, String prelogVersion) {
        //** Modified the Query by Sanjay *//
        Date currentMonday = week;
        Date currentSunday = week.addDays(6);

        //String to hold the query
        String queryString = 'SELECT Schedule__r.Deal_Parent__r.Brands__r.Name, Schedule__r.OrderLineNumber__c,'
                + 'Schedule__r.Days_Allowed_Formula__c, Schedule__r.Start_Time__c, Schedule__r.Days_Allowed__c,'
                + 'Schedule__r.End_Time__c, Schedule__r.Rate__c, Schedule__c,'
                + 'Schedule__r.MGM_HD_Daypart__c, Day_of_Week__c,'
                + 'Rate__c, Schedule__r.Total_Dollars__c, Schedule__r.Units_Available__c,'
                + 'Schedule__r.Units_Aired__c, Schedule__r.Name, Schedule__r.Id,'
                + 'Schedule__r.Cap__c, Schedule__r.LastModifiedDate, Version__c '
                + 'FROM PrelogData__c '
                + 'WHERE Schedule__r.Deal_Parent__c IN: dealWrapperIds '
                + 'AND AirDate__c >=: currentMonday AND AirDate__c <=: currentSunday';

        //Check for version
        if(String.isNotBlank(prelogVersion)) {
            Integer tempInt = Integer.valueOf(prelogVersion);
            queryString += ' AND Version__c =: tempInt';
        }
        else {
            queryString += ' AND Current_Version__c = true';
        }

        return Database.query(queryString);
    }

    public virtual List<PrelogData__c> getPrelogDataWithDeals(List<Deal__c> deals, Date week, String prelogVersion) {
        //** Modified the Query by Sanjay *//
        Date currentMonday = week;
        Date currentSunday = week.addDays(6);

        // String to hold soql string
        // MG  APR20.2016    added  Version__c, Current_Version__c   with respect to
        // "sOQLString += ' AND Current_Version__c = true';"
        String sOQLString = 'SELECT Id, Version__c, Current_Version__c, Schedule__r.Deal_Parent__c,'
                + 'Schedule__r.Deal_Parent__r.name, Schedule__c, Schedule__r.Id, Schedule__r.Name,'
                + 'Schedule__r.Cap__c FROM PrelogData__c WHERE Schedule__r.Deal_Parent__c IN: deals '
                + 'AND AirDate__c >=: currentMonday AND AirDate__c <=: currentSunday ';

        //Check for version
        if(String.isNotBlank(prelogVersion)) {
            Integer tempInt = Integer.valueOf(prelogVersion);
            sOQLString += ' AND Version__c =: tempInt';
        }
        else {
            sOQLString += ' AND Current_Version__c = true';
        }

        System.debug('#### Query::  ' + sOQLString);

        return Database.query(sOQLString);
    }

    public virtual List<PrelogDataMirror__c> getMirrorsFromIds(List<Id> ids) {
        return [
                SELECT Id,
                        Name,
                        PrelogData__c,
                        Schedule__c
                FROM PrelogDataMirror__c
                WHERE Id IN :ids
        ];
    }

    public virtual List<AsyncApexJob> getJobsForMirrors() {
        return [
                SELECT Id,
                        ApexClassId,
                        Status FROM AsyncApexJob
                WHERE ((Status = 'Processing' OR Status = 'Queued' OR Status = 'Preparing')
                AND (ApexClass.Name='PrelogDataScheduleBatch' OR ApexClass.Name='PrelogDataBatch')
                AND JobType='BatchApex')
        ];
    }
}