objects/Deal__c.object
<CustomObject>
    <fields>
        <fullName>ContactAccount__c</fullName>
        <formula>Contact__r.Account.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ContactAccount</label>
        <type>Text</type>
    </fields>
    <label>Deal</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Deal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Schedules__c.object
<CustomObject>
    <fields>
        <fullName>Deal_Parent__c</fullName>
        <label>Deal Parent</label>
        <referenceTo>Deal__c</referenceTo>
        <relationshipLabel>Schedules</relationshipLabel>
        <relationshipName>Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>LF_Week__c</fullName>
        <description>Calculated field to allow &quot;Non-Monday&quot; days in the Week field for Long Form.  This field autocalculates the relevant broadcast week for a Long Form &quot;Day&quot; entered in the week field.</description>
        <formula>CASE(
MOD(  Week__c  - DATE(1900, 1, 7), 7), 
0, Week__c - 6, 
1, Week__c, 
2, Week__c -1, 
3, Week__c - 2, 
4, Week__c - 3, 
5, Week__c- 4, 
6, Week__c - 5, DATE(2001, 1, 1))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>LF Week</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Total_Dollars__c</fullName>
        <formula>if(  PI_Payout_TEST__c &gt;0,  PI_Payout_TEST__c *20/17, 

if( PI_Payout__c &gt; 0 ,  PI_Payout__c * 20/17, 

if( Units_Aired__c &lt; 0,  0,
CASE(Deal_Parent__r.Status__c, &quot;Canceled&quot;, 0,  &quot;Pre-Empted&quot;, 0,

 Rate__c  *   Units_Aired__c)

)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Dollars</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Schedule</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Accounts_CIA_Balance_Class.cls
public class Accounts_CIA_Balance_Class {
    
    public static Decimal previousMonthBookingNetTotal(Account accountRecord) {
        List<ffps_dealinv__Broadcast_Month__c> startDateList = previousBroadcastMonthStartDate();
        List<ffps_dealinv__Broadcast_Month__c> endDateList = previousBroadcastMonthEndDate();
        Datetime rawStartDate = startDateList[0].ffps_dealinv__Start_Date__c;
        Datetime rawEndDate = endDateList[0].ffps_dealinv__End_Date__c;
        Date soqlStartDate = rawStartDate.date();
        Date soqlEndDate = rawEndDate.date();
        String soqlAccountName = '%' + accountRecord.Name + '%';
        // When pushed to live, replace LIKE %CHIEF% with :soqlAccountName
        List<AggregateResult> getGrossTotalDollars = [SELECT SUM(Total_Dollars__c) FROM schedules__c WHERE Deal_Parent__c IN (SELECT id FROM deal__c WHERE ContactAccount__c LIKE :soqlAccountName) AND LF_Week__c >= 2018-01-01 AND LF_Week__c <= 2018-01-30];
        Object sum = getGrossTotalDollars[0].get('expr0');
        Decimal getNetTotalDollars = .85 * (Decimal) sum;
        System.debug('Here is the total net dollars of the previous month: ' + getNetTotalDollars);
        return getNetTotalDollars;
    }
    
    public static List<ffps_dealinv__Broadcast_Month__c> previousBroadcastMonthStartDate() {
       List<ffps_dealinv__Broadcast_Month__c> startDateList = new List<ffps_dealinv__Broadcast_Month__c>();
       startDateList.add([SELECT ffps_dealinv__Start_Date__c FROM ffps_dealinv__Broadcast_Month__c WHERE ffps_dealinv__Start_Date__c <= TODAY ORDER BY ffps_dealinv__Start_Date__c DESC LIMIT 1 OFFSET 1][0]);
       System.debug('PreviousBroadcastMonthStartDate first array position start date: ' + startDateList[0].ffps_dealinv__Start_Date__c);
       return startDateList;
    }
    
    public static List<ffps_dealinv__Broadcast_Month__c> previousBroadcastMonthEndDate() {
        List<ffps_dealinv__Broadcast_Month__c> endDateList = new List<ffps_dealinv__Broadcast_Month__c>();
        endDateList.add([SELECT ffps_dealinv__End_Date__c FROM ffps_dealinv__Broadcast_Month__c WHERE ffps_dealinv__End_Date__c <= TODAY ORDER BY ffps_dealinv__End_Date__c DESC LIMIT 1][0]);
        System.debug('PreviousBroadcastMonthEndDate first array position end date: ' + endDateList[0].ffps_dealinv__End_Date__c);
        return endDateList;
    }    
    
}