objects/Deal__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Type__c</field>
                <operation>notEqual</operation>
                <value>history</value>
            </filterItems>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>Do Not Call</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <label>[Dep]Rate</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Sold</fullName>
                    <default>true</default>
                    <label>Sold</label>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Historical</fullName>
                </value>
                <value>
                    <fullName>Budget</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Deal</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Deal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/RaycomMonthlyLineItem__c.object
<CustomObject>
    <description>This object is a temporary holder for Raycom data. A report is run monthly and sent to Marathon. Marathon uploads the report via a Salesforce import. As the records are created a Visual Flow sees them and does some manipulation to compare them against the Raycom Key (indexed) field on Spot Data records. When it finds a match it copies the Invoice Number (the Order number plus a suffix) into the Spot Data. The Flow also marks these records for deletion after 15 days in order to keep stored data size down.</description>
    <fields>
        <fullName>BillingMonth__c</fullName>
        <label>Billing Month</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <label>Invoice #</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrderNumber__c</fullName>
        <label>Order #</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Spot_Data_Failure_Count__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Spot Data Failure Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Raycom Monthly Line Item</label>
    <nameField>
        <displayFormat>{YYYY}-{MM}-{00000}</displayFormat>
        <label>Raycom Monthly Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Raycom Monthly Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Schedules__c.object
<CustomObject>
    <fields>
        <fullName>Deal_Parent__c</fullName>
        <label>Deal Parent</label>
        <referenceTo>Deal__c</referenceTo>
        <relationshipLabel>Schedules</relationshipLabel>
        <relationshipName>Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>OrderNumber__c</fullName>
        <label>OrderNumber</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <label>Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Sold</fullName>
                    <default>true</default>
                    <label>Sold</label>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Units_Available__c</fullName>
        <label>Units Available</label>
        <precision>17</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Week__c</fullName>
        <label>Week</label>
        <type>Date</type>
    </fields>
    <label>Schedule</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Spot_Data__c.object
<CustomObject>
    <description>Post log information for schedule</description>
    <fields>
        <fullName>Air_Date__c</fullName>
        <label>Air Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Raycom_Invoice_Number__c</fullName>
        <description>Raycom Invoice Number, Order number + Month/Version</description>
        <label>Invoice Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Raycom_Order_Number__c</fullName>
        <label>Order Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Schedule__c</fullName>
        <label>Schedule</label>
        <referenceTo>Schedules__c</referenceTo>
        <relationshipLabel>Spot Data</relationshipLabel>
        <relationshipName>Spot_Data</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Aired</fullName>
                    <default>true</default>
                    <label>Aired</label>
                </value>
                <value>
                    <fullName>Discrepancy</fullName>
                </value>
                <value>
                    <fullName>Credited</fullName>
                </value>
                <value>
                    <fullName>Discrepancy - Paid</fullName>
                </value>
                <value>
                    <fullName>Credited - Partial</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Spot Data</label>
    <nameField>
        <displayFormat>S-{000000}</displayFormat>
        <label>Spot Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Spot Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/RaycomMonthlyLineItemTests.cls
@isTest
public class RaycomMonthlyLineItemTests {
	
    @testSetup
    public static void setup() {
        
        Contact con = new Contact(
        	FirstName = 'TEST',
            LastName = 'TEST',
            Email = 'test@test.com',
            Phone = '5555551212'
        );
        insert con;
        
        Deal__c deal = new Deal__c(
        	Contact__c = con.Id,
            Status__c = 'Historical'
        );
        insert deal;
        
        Schedules__c sch = new Schedules__c(
        	Week__c = Date.newInstance(2017,1,2),
            Deal_Parent__c = deal.Id,
            Units_Available__c = 1,
            Rate__c = 1
        );
        insert sch;
        
        Spot_Data__c sd = new Spot_Data__c(
            Raycom_Order_Number__c = '12345',
            Schedule__c = sch.Id,
            Air_Date__c = sch.Week__c
        );
        insert sd;
        
        RaycomMonthlyLineItem__c li = new RaycomMonthlyLineItem__c(
        	OrderNumber__c = '12345',
            Invoice__c = '99999',
            BillingMonth__c = Date.newInstance(2017,1,2)
        );
        insert li;
        
    }
    
    @isTest
    public static void test() {
        
        RaycomMonthlyLineItem__c li = [select Id, Invoice__c from RaycomMonthlyLineItem__c limit 1];
        
        Test.startTest();
        Database.executeBatch(new RaycomMonthlyLineItemBatch(), 1);
        Test.stopTest();
        
        Spot_Data__c sd = [select Id, Raycom_Invoice_Number__c from Spot_Data__c limit 1];
        
        system.assertEquals(li.Invoice__c, sd.Raycom_Invoice_Number__c);
        
        // assert the delete works
        List<RaycomMonthlyLineItem__c> lis = [select Id from RaycomMonthlyLineItem__c];
        system.assertEquals(0, lis.size());
        
    }
    
    @isTest
    public static void testException() {
        
        Test.startTest();
        RaycomMonthlyLineItemBatch.forceExceptionError = true;
        Database.executeBatch(new RaycomMonthlyLineItemBatch(), 1);
        Test.stopTest();
        
        RaycomMonthlyLineItem__c li = [select Id, Spot_Data_Failure_Count__c, Invoice__c from RaycomMonthlyLineItem__c limit 1];
        system.assertEquals(1, li.Spot_Data_Failure_Count__c);
        
    }
    
}