objects/Deal__c.object
<CustomObject>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Program</label>
        <referenceTo>Programs__c</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Deal</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Deal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Programs__c.object
<CustomObject>
    <description>Program/Distributor</description>
    <label>Program</label>
    <nameField>
        <label>Program</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Schedules__c.object
<CustomObject>
    <fields>
        <fullName>Networks__c</fullName>
        <description>Select a Network to dynamically filter the list of relevant cable dayparts.</description>
        <inlineHelpText>Select a Network to dynamically filter the list of relevant cable dayparts.</inlineHelpText>
        <label>Networks</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Justice Network</fullName>
                </value>
                <value>
                    <fullName>CBS Sports</fullName>
                </value>
                <value>
                    <fullName>MAV TV</fullName>
                </value>
                <value>
                    <fullName>Antenna TV</fullName>
                </value>
                <value>
                    <fullName>This TV</fullName>
                </value>
                <value>
                    <fullName>Bounce</fullName>
                </value>
                <value>
                    <fullName>TENNIS</fullName>
                </value>
                <value>
                    <fullName>MLB</fullName>
                </value>
                <value>
                    <fullName>MGM HD</fullName>
                </value>
                <value>
                    <fullName>GritTV</fullName>
                </value>
                <value>
                    <fullName>EscapeTV</fullName>
                </value>
                <value>
                    <fullName>DOC</fullName>
                </value>
                <value>
                    <fullName>FamilyNet</fullName>
                </value>
                <value>
                    <fullName>COOL</fullName>
                </value>
                <value>
                    <fullName>NFLN</fullName>
                </value>
                <value>
                    <fullName>JLTV</fullName>
                </value>
                <value>
                    <fullName>SiTV</fullName>
                </value>
                <value>
                    <fullName>OUTSIDE</fullName>
                </value>
                <value>
                    <fullName>Univision Select</fullName>
                </value>
                <value>
                    <fullName>Telefutura Select</fullName>
                </value>
                <value>
                    <fullName>Youtoo</fullName>
                </value>
                <value>
                    <fullName>Test Network</fullName>
                </value>
                <value>
                    <fullName>Cozi</fullName>
                </value>
                <value>
                    <fullName>BuzzrTV</fullName>
                </value>
                <value>
                    <fullName>FidoTV</fullName>
                </value>
                <value>
                    <fullName>Laff</fullName>
                </value>
                <value>
                    <fullName>Tribune Sports</fullName>
                </value>
                <value>
                    <fullName>NHL Network</fullName>
                </value>
                <value>
                    <fullName>NHL Network - Local</fullName>
                </value>
                <value>
                    <fullName>TVG</fullName>
                </value>
                <value>
                    <fullName>BounceTV - Local</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Schedule</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/DealButton.cls
public class DealButton
{
    public String Dealid {get;set;}
    public String Dealname {get;set;}
    public String Network;
    public DealButton(ApexPages.StandardController controller)
    {
        Set<String> PicklistNetworkStrings = new Set<String>();
        if (Schema.getGlobalDescribe().containsKey('Schedules__c'))
        {
            if (Schema.getGlobalDescribe().get('Schedules__c').getDescribe().fields.getMap().containsKey('Networks__c'))
            {
                for (Schema.PicklistEntry PE : Schema.getGlobalDescribe().get('Schedules__c').getDescribe().fields.getMap().get('Networks__c').getDescribe().getPicklistValues())
                {
                    PicklistNetworkStrings.add(PE.getValue());
                }
            }
        }
        
        Dealid = controller.getId();
        for(Deal__c deal : [SELECT Id, Name, Program__r.Name FROM Deal__c WHERE Id =:Dealid])
        {
            Dealname = deal.Name; 
            if(deal.Program__r.Name.contains('BounceTV - Local'))
            {
                Network ='BounceTV - Local';     
            }
            else if(deal.Program__r.Name.contains('Bounce'))
            {
                Network ='Bounce';     
            }
            else if(deal.Program__r.Name.contains('Tennis Channel'))
            {
                Network ='TENNIS';     
            }
            else if(deal.Program__r.Name.contains('MGM HD'))
            {
                Network ='MGM HD';     
            }
            else if(deal.Program__r.Name.contains('COZI'))
            {
                Network ='COZI';     
            }
            else if(deal.Program__r.Name.contains('COZI - Local'))
            {
                Network ='COZI';     
            }
            else if(deal.Program__r.Name.contains('MLB Network'))
            {
                Network ='MLB';     
            }
            else if(deal.Program__r.Name.contains('Documentary Channel'))
            {
                Network ='DOC';     
            }
            else if(deal.Program__r.Name.contains('AntennaTV'))
            {
                Network ='Antenna TV';     
            }
            else if(deal.Program__r.Name.contains('Antenna TV – Local'))
            {
                Network ='Antenna TV';     
            }
            else if(deal.Program__r.Name.contains('ThisTV'))
            {
                Network ='This TV';     
            }
            else if(deal.Program__r.Name.contains('ThisTV – Local'))
            {
                Network ='This TV';     
            }
            else if(PicklistNetworkStrings.contains(deal.Program__r.Name))
            {
                Network = deal.Program__r.Name;     
            }
            else
            {
                Network  ='None';     
            }
        } 
    }
    public PageReference ViewPage()
    {
        PageReference pageRef = new PageReference('/a08/e?retURL='+Dealid+'&RecordType=012C0000000Lxq9IAC&ent=01I80000000G533&CF00N80000002dVQS='+Dealname+'&00N80000004dNEJ='+Network);
        return pageRef; 
    }
}