objects/Deal__c.object
<CustomObject>
    <fields>
        <fullName>ClientCode__c</fullName>
        <formula>Program__r.ClientCode__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ClientCode</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Type__c</field>
                <operation>notEqual</operation>
                <value>history</value>
            </filterItems>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>Do Not Call</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Network_Deal_Number__c</fullName>
        <description>Deal number in Network&apos;s paper work, in Network&apos;s records.</description>
        <externalId>true</externalId>
        <inlineHelpText>Deal number in Network&apos;s paper work, in Network&apos;s records.  Equals 1 if the PI campaign is no longer airing on the network.</inlineHelpText>
        <label>Network Deal Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Program</label>
        <referenceTo>Programs__c</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Deal</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Deal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Programs__c.object
<CustomObject>
    <description>Program/Distributor</description>
    <fields>
        <fullName>Cable_Synd__c</fullName>
        <label>Cable/Synd/PP</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cable</fullName>
                </value>
                <value>
                    <fullName>Syndication</fullName>
                </value>
                <value>
                    <fullName>PP</fullName>
                </value>
                <value>
                    <fullName>Bundle</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ClientCode__c</fullName>
        <description>Assigned by Finance</description>
        <inlineHelpText>Assigned by Finance</inlineHelpText>
        <label>ClientCode</label>
        <length>3</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Clock_Start_Time__c</fullName>
        <label>Clock Start Time</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>5AM</fullName>
                </value>
                <value>
                    <fullName>6AM</fullName>
                </value>
                <value>
                    <fullName>4AM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Station_Call_Letter__c</fullName>
        <label>Station Call Letter</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Schedules__c.object
<CustomObject>
    <fields>
        <fullName>Network_Deal_Number__c</fullName>
        <formula>Deal_Parent__r.Network_Deal_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Network Deal Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <label>Start Time</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>MGM_HD_Daypart__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>01:00A</fullName>
                </value>
                <value>
                    <fullName>01:30A</fullName>
                </value>
                <value>
                    <fullName>02:00A</fullName>
                </value>
                <value>
                    <fullName>02:30A</fullName>
                </value>
                <value>
                    <fullName>03:00A</fullName>
                </value>
                <value>
                    <fullName>03:30A</fullName>
                </value>
                <value>
                    <fullName>04:00A</fullName>
                </value>
                <value>
                    <fullName>04:30A</fullName>
                </value>
                <value>
                    <fullName>05:00A</fullName>
                </value>
                <value>
                    <fullName>05:30A</fullName>
                </value>
                <value>
                    <fullName>06:00A</fullName>
                    <default>true</default>
                    <label>06:00A</label>
                </value>
                <value>
                    <fullName>06:30A</fullName>
                </value>
                <value>
                    <fullName>07:00A</fullName>
                </value>
                <value>
                    <fullName>07:30A</fullName>
                </value>
                <value>
                    <fullName>08:00A</fullName>
                </value>
                <value>
                    <fullName>08:30A</fullName>
                </value>
                <value>
                    <fullName>09:00A</fullName>
                </value>
                <value>
                    <fullName>09:30A</fullName>
                </value>
                <value>
                    <fullName>10:00A</fullName>
                </value>
                <value>
                    <fullName>10:30A</fullName>
                </value>
                <value>
                    <fullName>11:00A</fullName>
                </value>
                <value>
                    <fullName>11:30A</fullName>
                </value>
                <value>
                    <fullName>12:00P</fullName>
                </value>
                <value>
                    <fullName>12:30P</fullName>
                </value>
                <value>
                    <fullName>01:00P</fullName>
                </value>
                <value>
                    <fullName>01:30P</fullName>
                </value>
                <value>
                    <fullName>02:00P</fullName>
                </value>
                <value>
                    <fullName>02:30P</fullName>
                </value>
                <value>
                    <fullName>03:00P</fullName>
                </value>
                <value>
                    <fullName>03:30P</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Units_Available__c</fullName>
        <label>Units Available</label>
        <precision>17</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <label>Schedule</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Spot_Data__c.object
<CustomObject>
    <description>Post log information for schedule</description>
    <fields>
        <fullName>Air_Date__c</fullName>
        <label>Air Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Error__c</fullName>
        <label>Error</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Deal entry error</fullName>
                </value>
                <value>
                    <fullName>Ran out of time rotation</fullName>
                </value>
                <value>
                    <fullName>Overran units</fullName>
                </value>
                <value>
                    <fullName>Wrong rate</fullName>
                </value>
                <value>
                    <fullName>Wrong Traffic</fullName>
                </value>
                <value>
                    <fullName>Network - Deal Entry Error</fullName>
                </value>
                <value>
                    <fullName>Network - Ran Out Of Rotation</fullName>
                </value>
                <value>
                    <fullName>Network - Overran Units</fullName>
                </value>
                <value>
                    <fullName>Network - Wrong Rate</fullName>
                </value>
                <value>
                    <fullName>Network - Wrong Traffic</fullName>
                </value>
                <value>
                    <fullName>Network - Min Separation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Schedule__c</fullName>
        <label>Schedule</label>
        <referenceTo>Schedules__c</referenceTo>
        <relationshipLabel>Spot Data</relationshipLabel>
        <relationshipName>Spot_Data</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SpotDataMirror__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SpotDataMirror</label>
        <referenceTo>SpotDataMirror__c</referenceTo>
        <relationshipLabel>Spot Data</relationshipLabel>
        <relationshipName>Spot_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Spot Data</label>
    <nameField>
        <displayFormat>S-{000000}</displayFormat>
        <label>Spot Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Spot Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SpotDataMirror__c.object
<CustomObject>
    <fields>
        <fullName>Air_Date__c</fullName>
        <label>Air Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ErrorReason__c</fullName>
        <label>[Dep]Error Reason</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Unit Length not found</fullName>
                </value>
                <value>
                    <fullName>Air Date does not match</fullName>
                </value>
                <value>
                    <fullName>Air Time does not match</fullName>
                </value>
                <value>
                    <fullName>Rate not found</fullName>
                </value>
                <value>
                    <fullName>Network Deal number not found</fullName>
                </value>
                <value>
                    <fullName>No Network Deal number</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Error__c</fullName>
        <label>[Dep]Error</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Deal entry error</fullName>
                </value>
                <value>
                    <fullName>Ran out of time rotation</fullName>
                </value>
                <value>
                    <fullName>Overran units</fullName>
                </value>
                <value>
                    <fullName>Wrong rate</fullName>
                </value>
                <value>
                    <fullName>Wrong Traffic</fullName>
                </value>
                <value>
                    <fullName>Network - Ran Out of Rotation</fullName>
                </value>
                <value>
                    <fullName>Network - Deal Entry Error</fullName>
                </value>
                <value>
                    <fullName>Network - Overran Units</fullName>
                </value>
                <value>
                    <fullName>Network - Wrong Rate</fullName>
                </value>
                <value>
                    <fullName>Network - Wrong Traffic</fullName>
                </value>
                <value>
                    <fullName>Network - Min Separation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Schedule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Schedule</label>
        <referenceTo>Schedules__c</referenceTo>
        <relationshipLabel>Spot Data</relationshipLabel>
        <relationshipName>SpotDataMirror</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Spot_Data__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is used to link the related spot date record Created/Updated</description>
        <label>Spot Data</label>
        <referenceTo>Spot_Data__c</referenceTo>
        <relationshipLabel>Spot Data Mirrors</relationshipLabel>
        <relationshipName>Spot_Data_Mirrors</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Spot Data Mirror</label>
    <nameField>
        <label>Spot Data Mirror Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Spot Data Mirrors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SpotDataBatchTest.cls
@isTest
private class SpotDataBatchTest {
	@isTest
	private static void spotDataBatch_createSpotDataFromMirror_spotDataCreated() {

		Schedules__c testSchedule = createSchedule('123');
		List<SpotDataMirror__c> mirrors = createSpotDataMirrors(true, Integer.valueOf(testSchedule.Units_Available__c), '123');
		insert new Prelog_Batch_Networks__c(Name = 'test');

		Test.startTest();
		SpotDataBatch batch = new SpotDataBatch('test');
		Database.executeBatch(batch);
		Test.stopTest();

		List<Spot_Data__c> spots = getSpotDataFromScheduleId(testSchedule.Id);

		System.debug('Size: '+spots.size());
		System.assert(spots.size() == 4);
		System.assertEquals(spots[0].Schedule__c, testSchedule.Id);
		System.assertEquals(spots[0].Air_Date__c, date.today().toStartofWeek().addDays(-6));
		for (Spot_Data__c spot: spots) {
			System.assertEquals(null, spot.Error__c);
		}
	}

	@isTest
	private static void spotDataBatch_createSpotDataFromMirror_SpotDataMirrorLookupPopulated() {
		Schedules__c testSchedule = createSchedule('123');
		List<SpotDataMirror__c> mirrors = createSpotDataMirrors(true, Integer.valueOf(testSchedule.Units_Available__c), '123');
		List<Id> mirrorIds = new List<Id>();
		for (SpotDataMirror__c mirror: mirrors) {
			mirrorIds.add(mirror.id);
		}

		insert new Prelog_Batch_Networks__c(Name = 'test');

		Test.startTest();
		SpotDataBatch batch = new SpotDataBatch('test');
		Database.executeBatch(batch);
		Test.stopTest();

		List<Spot_Data__c> spots = getSpotDataFromMirrorIds(mirrorIds);
		List<Id> spotIds = new List<Id>();
		for(Spot_Data__c spot: spots) {
			spotIds.add(spot.Id);
		}

		System.debug('Spot Id size: '+spotIds.size());

		Map<Id, SpotDataMirror__c> updatedMirrors = getSpotDataMirrorsFromSpotData(spotIds);
		System.debug('Updated mirrors: '+updatedMirrors);
		for (SpotDataMirror__c mirror: updatedMirrors.values()) {
			System.assert(mirror.Spot_Data__c != null);
			System.assert(mirror.ErrorReason__c == null);
		}
	}

	@isTest
	private static void spotDataBatch_createErrorSpotDataMirrors_spotDataMirrorErrorFieldMessageFound() {
		Schedules__c testSchedule = createSchedule('123');
		List<SpotDataMirror__c> mirrors = createSpotDataMirrors(false, Integer.valueOf(testSchedule.Units_Available__c), '123');
		insert new Prelog_Batch_Networks__c(Name = 'test');

		Test.startTest();
		SpotDataBatch batch = new SpotDataBatch('test');
		Database.executeBatch(batch);
		Test.stopTest();

		List<Spot_Data__c> spots = getSpotDataFromScheduleId(testSchedule.Id);
		System.assert(spots.size() == 0);

		List<SpotDataMirror__c> failedMirrors = getFailedSpotDataMirrors();
		System.assert(failedMirrors.size() > 0);

		for(SpotDataMirror__c mirror: failedMirrors) {
			System.assert(mirror.ErrorReason__c != null);
		}

	}

	// Create network's SpotDataMirrors
	private static Schedules__c createSchedule(String dealNumber) {
		Account testAcct = new Account();
		testAcct.Name = 'Test Account';
		testAcct.Billingcity = 'Wakarusa';
		insert testAcct;

		Contact contact = new Contact();
		contact.FirstName = 'Test';
		contact.LastName = 'Name';
		contact.Email = 'test@testemail.com';
		contact.Phone = '(758) 771-0091';
		contact.Account = testAcct;
		insert contact;

		Programs__c program = new Programs__c();
		program.Name = 'test';
		program.Cable_Synd__c = 'Cable';
		program.Station_Call_Letter__c = 'AWED';
		program.ClientCode__c = dealNumber;
		program.Clock_Start_Time__c = '';
		insert program;

		Deal__c testDeal = new Deal__c();
		testDeal.Program__c = program.id;
		testDeal.Contact__c = contact.id;
		testDeal.Network_Deal_Number__c = dealNumber;
		testDeal.Length__c = '1';
		insert testDeal;


		Schedules__c schedule = new Schedules__c();
		schedule.Week__c = date.today().toStartofWeek().addDays(-6);
		schedule.Units_Available__c = 5;
		schedule.Deal_Parent__c = testDeal.id;
		schedule.Days_Allowed__c = 'Mon';
		schedule.Start_Time__c = '06:00A';
		schedule.End_Time__c = '06:30A';
		schedule.Rate__c = 100;
		schedule.Units_Available__c = 5;
		insert schedule;

		return schedule;
	}

	private static List<SpotDataMirror__c> createSpotDataMirrors(Boolean positiveTestCase, Integer unitsAvailable, String dealNumber) {
		Integer rate = 0;
		if (positiveTestCase) {
			rate = 100;
		}

		List<SpotDataMirror__c> mirrors = new List<SpotDataMirror__c>();
		for (Integer i = 0; i < unitsAvailable; i++) {
			SpotDataMirror__c mirror = new SpotDataMirror__c();
			mirror.Network_Deal_Number__c = dealNumber;
			mirror.Network__c = 'test';
			mirror.Length__c = '1';
			mirror.Air_Date__c = date.today().toStartofWeek().addDays(-6);
			mirror.Air_Time__c = '6:0'+i+':00AM';
			mirror.Spot_Rate__c = rate;
			mirrors.add(mirror);
		}
		
		insert mirrors;
		return mirrors;
	}

	private static List<Spot_Data__c> getSpotDataFromScheduleId(Id scheduleId) {
		return [SELECT Id, 
					   Air_Time__c,
					   Schedule__c,
					   Air_Date__c,
					   Error__c
				  FROM Spot_Data__c 
				 WHERE Schedule__c = :scheduleId];
	}

	private static List<Spot_Data__c> getSpotDataFromMirrorIds(List<Id> mirrorIds) {
		return [SELECT Id, 
					   Air_Time__c,
					   Schedule__c,
					   Air_Date__c,
					   SpotDataMirror__c
				  FROM Spot_Data__c 
				 WHERE SpotDataMirror__c IN :mirrorIds];
	}

	private static List<SpotDataMirror__c> getFailedSpotDataMirrors() {
		return [SELECT Id,
			   		   Network_Deal_Number__c,
			   		   Network__c,
			   		   Air_Date__c,
			   		   ErrorReason__c
				  FROM SpotDataMirror__c
				 WHERE ErrorReason__c != null];
	}

	private static Map<Id, SpotDataMirror__c> getSpotDataMirrorsFromSpotData(List<Id> spotIds) {
		return new Map<Id, SpotDataMirror__c>([SELECT Id,
			   		   Network_Deal_Number__c,
			   		   Network__c,
			   		   Air_Date__c,
			   		   ErrorReason__c,
					   Spot_Data__c
				  FROM SpotDataMirror__c
				 WHERE Spot_Data__c in :spotIds]);
	}

}