objects/Deal__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Type__c</field>
                <operation>notEqual</operation>
                <value>history</value>
            </filterItems>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>Do Not Call</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Network_Deal_Number__c</fullName>
        <description>Deal number in Network&apos;s paper work, in Network&apos;s records.</description>
        <externalId>true</externalId>
        <inlineHelpText>Deal number in Network&apos;s paper work, in Network&apos;s records.  Equals 1 if the PI campaign is no longer airing on the network.</inlineHelpText>
        <label>Network Deal Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <label>[Dep]Rate</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Deal</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Deal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Prelog_Batch_Networks__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Prelog Batch Networks</label>
</CustomObject>

objects/Schedules__c.object
<CustomObject>
    <fields>
        <fullName>Deal_Parent__c</fullName>
        <label>Deal Parent</label>
        <referenceTo>Deal__c</referenceTo>
        <relationshipLabel>Schedules</relationshipLabel>
        <relationshipName>Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Network_Deal_Number__c</fullName>
        <formula>Deal_Parent__r.Network_Deal_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Network Deal Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <label>Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Units_Available__c</fullName>
        <label>Units Available</label>
        <precision>17</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <label>Schedule</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Spot_Data__c.object
<CustomObject>
    <description>Post log information for schedule</description>
    <fields>
        <fullName>Air_Date__c</fullName>
        <label>Air Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Air_Time__c</fullName>
        <label>Air Time</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Network_Deal_Number__c</fullName>
        <formula>Schedule__r.Deal_Parent__r.Network_Deal_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Network Deal Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Schedule__c</fullName>
        <label>Schedule</label>
        <referenceTo>Schedules__c</referenceTo>
        <relationshipLabel>Spot Data</relationshipLabel>
        <relationshipName>Spot_Data</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SpotDataMirror_Reference__c</fullName>
        <description>This is used to add  related  schedule id +spot data name+index number( of trigger.new).
used to relate this to spot data mirror record.</description>
        <label>SpotDataMirror Reference</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SpotDataMirror__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SpotDataMirror</label>
        <referenceTo>SpotDataMirror__c</referenceTo>
        <relationshipLabel>Spot Data</relationshipLabel>
        <relationshipName>Spot_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Spot_Rate__c</fullName>
        <label>Spot Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Spot Data</label>
    <nameField>
        <displayFormat>S-{000000}</displayFormat>
        <label>Spot Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Spot Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SpotDataMirror__c.object
<CustomObject>
    <fields>
        <fullName>Air_Date__c</fullName>
        <label>Air Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Air_Time__c</fullName>
        <label>Air Time</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ErrorReason__c</fullName>
        <label>[Dep]Error Reason</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Unit Length not found</fullName>
                </value>
                <value>
                    <fullName>Air Date does not match</fullName>
                </value>
                <value>
                    <fullName>Air Time does not match</fullName>
                </value>
                <value>
                    <fullName>Rate not found</fullName>
                </value>
                <value>
                    <fullName>Network Deal number not found</fullName>
                </value>
                <value>
                    <fullName>No Network Deal number</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Network_Deal_Number__c</fullName>
        <label>Network Deal Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Network__c</fullName>
        <label>Network</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Problem__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if a corresponding Spot Data record failed to be created during the Post Log upload (CHECKED = Spot Data record was  NOT created)</description>
        <inlineHelpText>Spot Data record was  NOT created</inlineHelpText>
        <label>[Dep]Need To Reprocess</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Schedule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Schedule</label>
        <referenceTo>Schedules__c</referenceTo>
        <relationshipLabel>Spot Data</relationshipLabel>
        <relationshipName>SpotDataMirror</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Spot_Data__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is used to link the related spot date record Created/Updated</description>
        <label>Spot Data</label>
        <referenceTo>Spot_Data__c</referenceTo>
        <relationshipLabel>Spot Data Mirrors</relationshipLabel>
        <relationshipName>Spot_Data_Mirrors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Spot_Rate__c</fullName>
        <label>Spot Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Spot Data Mirror</label>
    <nameField>
        <label>Spot Data Mirror Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Spot Data Mirrors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SpotDataScheduleBatchTest.cls
/**
 * @date 1/15/2019
 * @description Unit testing for SpotDataScheduleBatch.cls
 */
@IsTest
public with sharing class SpotDataScheduleBatchTest {

    //
    // Constants
    //
    private final static String SETTING_NAME = 'Quest';
    private final static String ALL_NETWORK_NAME = 'All';

    //
    // Testing Variables
    //
    private static TestSpotDataSelector spotDataSelector;
    private static SpotDataScheduleBatch batch;
    private static SpotDataScheduleService instance;

    /**
     * @description Method to run basic setup instructions in the beginning of each test
     */
    private static void basicSetup() {
        spotDataSelector = new TestSpotDataSelector();
        instance = new SpotDataScheduleService(SETTING_NAME);
        batch = new SpotDataScheduleBatch(instance);
        SpotDataScheduleService.spotDataSelector = spotDataSelector;

        // Create custom settings for retrieval
        Prelog_Batch_Networks__c testSetting = new Prelog_Batch_Networks__c(
                Name = SETTING_NAME
        );
        insert testSetting;
    }

    /**
     * @description Test the result of constructing a SpotDataScheduleBatch with different network names
     */
    @IsTest
    static void SpotDataScheduleBatch_SpotDataScheduleBatch_TestValidNetworkConstruction() {
        basicSetup();

        // Test random network name
        String networkName = Utils.randomString(8);
        instance = new SpotDataScheduleService(networkName);
        batch = new SpotDataScheduleBatch(networkName);
        System.assertEquals(networkName, instance.network);

        // Test 'All' networks
        String allNetworkName = ALL_NETWORK_NAME;
        instance = new SpotDataScheduleService(allNetworkName);
        batch = new SpotDataScheduleBatch(networkName);
        System.assertEquals('', instance.network);
    }

    /**
     * @description Test the result of constructing a SpotDataScheduleBatch with a few different lists
     */
    @IsTest
    static void SpotDataScheduleBatch_SpotDataScheduleBatch_TestMirrorIdListConstruction() {
        basicSetup();

        // Test Empty Mirror List
        List<Id> testList = new List<Id>();
        batch = new SpotDataScheduleBatch(testList);
        testListSizeAndContents(SpotDataScheduleBatch.service.spotDataMirrorIdList, testList);

        // Test Size-1 List
        List<Id> testList2 = new List<Id>{
                Id.valueOf('0018000000Lz2g1AAB')
        };
        batch = new SpotDataScheduleBatch(testList2);
        testListSizeAndContents(SpotDataScheduleBatch.service.spotDataMirrorIdList, testList2);

        // Test Multi-Size List (8)
        List<Id> testList3 = new List<Id>{
                Id.valueOf('0010R00000VLDM1QAP'),
                Id.valueOf('0018000000Lz2ftAAB'),
                Id.valueOf('0018000000Lz2fuAAB'),
                Id.valueOf('0018000000Lz2fwAAB'),
                Id.valueOf('0018000000Lz2fxAAB'),
                Id.valueOf('0018000000Lz2fyAAB'),
                Id.valueOf('0018000000Lz2fzAAB'),
                Id.valueOf('0018000000Lz2g0AAB')
        };
        batch = new SpotDataScheduleBatch(testList3);
        System.assertEquals(SpotDataScheduleBatch.service.spotDataMirrorIdList, testList3);
    }

    /**
     * @description Test the result of retrieving and processing data from the database, rather than providing a list of Ids
     */
    @IsTest
    static void SpotDataScheduleService_processSpotDataRecords_TestProcessingNetworkAllList() {
        basicSetup();

        // Fill database with stuff
        List<Schedules__c> schedules = getMockSchedule(1);
        getMockSpotData(10, schedules, null);

        // Make sure list is null
        instance.spotDataMirrorIdList = null;

        // Begin batch job
        Test.startTest();
        Database.executeBatch(batch);
        Test.stopTest();

        // Test successful batch job
        testValidInsertionAndUpdates(schedules.get(0).Id);
    }

    /**
     * @description Test the result of providing an empty list of Ids to be processed
     *  This should force the data to be pulled from a time frame specified
     */
    @IsTest
    static void SpotDataScheduleService_processSpotDataRecords_TestProcessingEmptyIdList() {
        basicSetup();

        List<Schedules__c> schedules = getMockSchedule(1);
        getMockSpotData(10, schedules, null);

        // Make sure list is empty
        List<Id> testList = new List<Id>();
        instance = new SpotDataScheduleService(testList);
        batch = new SpotDataScheduleBatch(instance);

        // Avoid network null
        instance.network = SETTING_NAME;

        // Begin batch job
        Test.startTest();
        Database.executeBatch(batch, 200);
        Test.stopTest();

        // Test successful batch job
        testValidInsertionAndUpdates(schedules.get(0).Id);
    }

    /**
     * @description Test the result of providing a filled list of Ids to be processed
     *  This should result in pulling SpotData from the database from the Ids provided
     */
    @IsTest
    static void SpotDataScheduleBatch_processSpotDataRecords_TestProcessingFilledIdList() {
        basicSetup();

        // Retrieve Mocked SpotData Ids
        List<Schedules__c> schedules = getMockSchedule(1);
        List<SpotDataMirror__c> spotDataMirrors = getMockSpotDataMirrors(10, schedules);
        List<Id> spotDataIds = new List<Id>();
        for (SpotDataMirror__c sdm : spotDataMirrors) {
            spotDataIds.add(sdm.Id);
        }
        instance = new SpotDataScheduleService(spotDataIds);
        batch = new SpotDataScheduleBatch(instance);
        SpotDataScheduleService.spotDataSelector = new SpotDataSelector();
        instance.network = SETTING_NAME;

        // Make sure selector will output data
        spotDataSelector.fabricatedList = getMockSpotData(10, schedules, spotDataMirrors);

        // Begin batch job
        Test.startTest();
        Database.executeBatch(batch);
        Test.stopTest();

        // Test sucessful batch job
        testValidInsertionAndUpdates(schedules.get(0).Id);
    }

    /**
     * @description Test the result of having no data pulled from the database
     */
    @IsTest
    static void SpotDataScheduleService_processSpotDataRecords_TestInvalidSpotDataListProcessing() {
        basicSetup();

        List<Id> testList = new List<Id>{
                Id.valueOf('0010R00000VLDL8QAP'),
                Id.valueOf('0010R00000VLDLNQA5'),
                Id.valueOf('0010R00000VLDLrQAP'),
                Id.valueOf('0010R00000VLDLwQAP'),
                Id.valueOf('0010R00000VLDM1QAP'),
                Id.valueOf('0018000000Lz2ftAAB'),
                Id.valueOf('0018000000Lz2fuAAB'),
                Id.valueOf('0018000000Lz2fwAAB')
        };
        instance = new SpotDataScheduleService(testList);
        batch = new SpotDataScheduleBatch(instance);

        // Avoid network null
        instance.network = SETTING_NAME;

        // Begin batch job
        Test.startTest();
        Database.executeBatch(batch);
        Test.stopTest();
    }

    /**
     * @description Helper method to test a list size and contents
     * @param expectedList The expected list size and contents
     * @param objectList The provided list size and contents
     */
    private static void testListSizeAndContents(List<Object> expectedList, List<Object> objectList) {
        // Check size
        System.assertEquals(expectedList.size(), objectList.size());

        // Check contents
        for (Object obj : objectList) {
            System.assert(expectedList.contains(obj));
        }
    }

    /**
     * @description Retrieve a list of mocked Schedule__c objects
     * @param amount The amount of mocked objects you want to fabricate
     * @return The inserted list of mocked objects
     */
    private static List<Schedules__c> getMockSchedule(Integer amount) {
        Contact con = new Contact(
                FirstName = 'FIRSTNAME',
                LastName = 'LASTNAME',
                Email = 'test@email.com',
                Phone = '5555555555'
        );
        insert con;
        Deal__c deal = new Deal__c(
                Contact__c = con.Id
        );
        insert deal;

        List<Schedules__c> result = new List<Schedules__c>();
        for (Integer i = 0; i < amount; i++) {
            Schedules__c schedule = new Schedules__c(
                    Deal_Parent__c = deal.Id,
                    Units_Available__c = 1,
                    Rate__c = 1
            );
            result.add(schedule);
        }
        insert result;
        return result;
    }

    /**
     * @description Retrieve a list of mocked Spot_Data__c objects
     * @param amount The amount of mocked objects you want to fabricate
     * @param mirrorMap OPTIONAL list of mirrors to map Id's to
     * @return The inserted list of mocked objects
     */
    private static List<Spot_Data__c> getMockSpotData(Integer amount, List<Schedules__c> scheduleMap, List<SpotDataMirror__c> mirrorMap) {
        List<Spot_Data__c> result = new List<Spot_Data__c>();
        for (Integer i = 0; i < amount; i++) {
            Spot_Data__c spotData = new Spot_Data__c(
                    Schedule__c = scheduleMap.get(0).Id
            );
            // Link to mirror reference
            if (mirrorMap != null && mirrorMap.size() > i) {
                spotData.SpotDataMirror_Reference__c = scheduleMap.get(0).Id + String.valueOf(mirrorMap.get(i).Id) + i;
            }
            result.add(spotData);
        }

        return result;
    }

    /**
     * @description Retrieve a list of mocked SpotDataMirror__c objects
     * @param amount The amount of mocked objects you want to fabricate
     * @return The inserted list of mocked objects
     */
    private static List<SpotDataMirror__c> getMockSpotDataMirrors(Integer amount, List<Schedules__c> scheduleMap) {
        List<SpotDataMirror__c> result = new List<SpotDataMirror__c>();

        for (Integer i = 0; i < amount; i++) {
            result.add(new SpotDataMirror__c(
                    Air_Date__c = Date.today(),
                    Air_Time__c = '02:00A',
                    Network__c = SETTING_NAME,
                    Network_Deal_Number__c = '0',
                    Spot_Rate__c = 0,
                    Schedule__c = scheduleMap.get(0).Id
            ));
        }
        insert result;
        return result;
    }

    /**
     * @description Retrieve a list of SpotDataMirror__c objects from an associated Schedule__c Id
     * @param scheduleId The Schedule__c Id being compared
     * @return The resulting list of SpotDataMirror__c objects
     */
    private static List<SpotDataMirror__c> getMirrorsFromScheduleId(Id scheduleId) {
        return [
                SELECT  Id,
                        Spot_Data__c,
                        ErrorReason__c,
                        Schedule__c,
                        Problem__c
                   FROM SpotDataMirror__c
                  WHERE Schedule__c = :scheduleId
        ];
    }

    /**
     * @description Retrieve a list of Spot_Data__c objects from an associated Schedule__c Id
     * @param scheduleId The Schedule__c Id being compared
     * @return The resulting list of Spot_Data__c objects
     */
    private static List<Spot_Data__c> getDataFromScheduleId(Id scheduleId) {
        return [
                SELECT  Id,
                        SpotDataMirror__c,
                        Schedule__c
                   FROM Spot_Data__c
                  WHERE Schedule__c = :scheduleId
        ];
    }

    /**
     * @description Retrieve a SpotDataMirror__c object with desired fields from it's Id
     * @param mirrorId The Id being used to retrieve the SpotDataMirror__c object
     * @return The resulting SpotDataMirror__c object
     */
    private static SpotDataMirror__c getMirrorFromId(Id mirrorId) {
        return [
                SELECT  Id,
                        Spot_Data__c,
                        ErrorReason__c,
                        Schedule__c,
                        Problem__c
                   FROM SpotDataMirror__c
                  WHERE Id = :mirrorId
        ];
    }

    /**
     * @description Run assertions to validate that processSpotDataRecords is performing its database insertions and updates properly
     * @param scheduleId The Id of the Schedule__c object being used to access the database records
     */
    private static void testValidInsertionAndUpdates(Id scheduleId) {
        // Re-query for spot data mirrors
        List<SpotDataMirror__c> mirrors = getMirrorsFromScheduleId(scheduleId);
        List<Spot_Data__c> data = getDataFromScheduleId(scheduleId);

        System.assertEquals(data.size(), mirrors.size());

        // Verify SpotDataMirror__c was updated
        for (Integer i = 0; i < data.size(); i++) {
            Spot_Data__c sd = data.get(i);
            SpotDataMirror__c sdm = getMirrorFromId(String.valueOf(sd.SpotDataMirror__c));

            System.assertEquals(sd.SpotDataMirror__c, sdm.Id);
            System.assertEquals(sd.Id, sdm.Spot_Data__c);
            System.assertEquals(null, sdm.ErrorReason__c);
            System.assertEquals(sd.Schedule__c, sdm.Schedule__c);
            System.assertEquals(false, sdm.Problem__c);
        }
    }

}