objects/Deal__c.object
<CustomObject>
    <label>Deal</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Deal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Schedules__c.object
<CustomObject>
    <fields>
        <fullName>Deal_Parent__c</fullName>
        <label>Deal Parent</label>
        <referenceTo>Deal__c</referenceTo>
        <relationshipLabel>Schedules</relationshipLabel>
        <relationshipName>Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Network_Deal_Number__c</fullName>
        <formula>Deal_Parent__r.Network_Deal_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Network Deal Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <label>Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Schedule</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Spot_Data__c.object
<CustomObject>
    <description>Post log information for schedule</description>
    <fields>
        <fullName>Length__c</fullName>
        <label>Length</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>30</fullName>
                </value>
                <value>
                    <fullName>45</fullName>
                </value>
                <value>
                    <fullName>60</fullName>
                </value>
                <value>
                    <fullName>90</fullName>
                </value>
                <value>
                    <fullName>120</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>75</fullName>
                </value>
                <value>
                    <fullName>180</fullName>
                </value>
                <value>
                    <fullName>300</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Network_Deal_Number__c</fullName>
        <formula>Schedule__r.Deal_Parent__r.Network_Deal_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Network Deal Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Schedule__c</fullName>
        <label>Schedule</label>
        <referenceTo>Schedules__c</referenceTo>
        <relationshipLabel>Spot Data</relationshipLabel>
        <relationshipName>Spot_Data</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SpotDataMirror__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SpotDataMirror</label>
        <referenceTo>SpotDataMirror__c</referenceTo>
        <relationshipLabel>Spot Data</relationshipLabel>
        <relationshipName>Spot_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Spot Data</label>
    <nameField>
        <displayFormat>S-{000000}</displayFormat>
        <label>Spot Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Spot Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SpotDataMirror__c.object
<CustomObject>
    <fields>
        <fullName>Length__c</fullName>
        <label>Length</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>30</fullName>
                </value>
                <value>
                    <fullName>45</fullName>
                </value>
                <value>
                    <fullName>60</fullName>
                </value>
                <value>
                    <fullName>90</fullName>
                </value>
                <value>
                    <fullName>120</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>75</fullName>
                </value>
                <value>
                    <fullName>180</fullName>
                </value>
                <value>
                    <fullName>300</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Network_Deal_Number__c</fullName>
        <label>Network Deal Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Schedule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Schedule</label>
        <referenceTo>Schedules__c</referenceTo>
        <relationshipLabel>Spot Data</relationshipLabel>
        <relationshipName>SpotDataMirror</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Spot_Data__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is used to link the related spot date record Created/Updated</description>
        <label>Spot Data</label>
        <referenceTo>Spot_Data__c</referenceTo>
        <relationshipLabel>Spot Data Mirrors</relationshipLabel>
        <relationshipName>Spot_Data_Mirrors</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Spot Data Mirror</label>
    <nameField>
        <label>Spot Data Mirror Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Spot Data Mirrors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ReprocessSpotDataMirrorRecords.cls
public with sharing class ReprocessSpotDataMirrorRecords 
{
	private static SpotDataSelector spotDataSelector = new SpotDataSelector();
	public void setSpotDataSelector(SpotDataSelector sSelector){
		spotDataSelector = sSelector;
	}

	ApexPages.StandardSetController SDMssc {get;set;}
	public String FilterId {get;set;}
	public String ObjectPrefix {get;set;}
	public ReprocessSpotDataMirrorRecords(ApexPages.StandardSetController ssc)
	{
		if (ssc != null)
		{
			SDMssc = ssc;
			System.debug('Filter Id - ' + ssc.getFilterId());
			FilterId = ssc.getFilterId();
			if (FilterId.length() > 15)
			{
				FilterId = FilterId.substring(0,15);
			}
			ObjectPrefix = Schema.getGlobalDescribe().get('SpotDataMirror__c').getDescribe().getKeyPrefix();
			
		}
	}
	public PageReference ReprocessSpotDataMirrorRecordsAction()
	{
		List<AsyncApexJob> AAJList = spotDataSelector.getJobsForSpotData();
		if (AAJList.size() == 0)
		{
			if (SDMssc != null)
			{
				List<SpotDataMirror__c> NewSDMList = SDMssc.getSelected();
				List<Id> SpotDataMIrrorIdList = new List<Id>();
				for(SpotDataMirror__c SDM : NewSDMList)
				{
					SpotDataMIrrorIdList.add(SDM.Id);
				}
				
				List<SpotDataMirror__c> SDMList = spotDataSelector.getMirrorsFromIds(SpotDataMIrrorIdList);
				
				List<Id> SpotDataMirrorWithNoScheduleList = new List<Id>();
				List<Id> SpotDataMirrorWithScheduleList = new List<Id>();
				
				for (SpotDataMirror__c SDM : SDMList)
				{
					if (SDM.Schedule__c == null )
					{
						SpotDataMirrorWithNoScheduleList.add(SDM.Id);
					}
					else if (SDM.Spot_Data__c == null)
					{
						SpotDataMirrorWithScheduleList.add(SDM.Id);
					}
				}
				
				if (SpotDataMirrorWithNoScheduleList.size() > 0)
				{
					List<SpotDataMirror__c> SpotDataMirrorList = Database.query('select '
							+ SaberGF.GetObjectsFieldsForQueries('SpotDataMirror__c')
							+ ' from SpotDataMirror__c where Id in '
							+ SaberGF.ReturnDynamicQueryList(SpotDataMirrorWithNoScheduleList));
					//SpotDataScheduleService.processSpotDataRecords(SpotDataMirrorList);
					SpotDataMirrorService.createSpotDataFromMirrors(SpotDataMirrorList);
				}
				
				if (SpotDataMirrorWithScheduleList.size() > 0)
				{
					List<SpotDataMirror__c> SpotDataMirrorList = Database.query('SELECT '
							+ SaberGF.GetObjectsFieldsForQueries('SpotDataMirror__c') + ','
							+ 'Schedule__r.Rate__c,Schedule__r.Deal_Parent__c,'
							+ 'Schedule__r.Deal_Parent__r.Length__c,'
							+ 'Schedule__r.Network_Deal_Number__c '
							+ 'FROM SpotDataMirror__c WHERE Id IN '
							+ SaberGF.ReturnDynamicQueryList(SpotDataMirrorWithScheduleList));
					SpotDataScheduleService.processSpotDataRecords(SpotDataMirrorList);
					//SpotDataMirrorService.createSpotDataFromMirrors(SpotDataMirrorList);
				}
				
				
			}
			if (FilterId != null)
			{
				return new PageReference('/' + ObjectPrefix + '?fcf=' + FilterId);
			}
			else
			{
				return new PageReference('/' + ObjectPrefix + '?fcf=00BC0000008vccx');
			}
		}
		else
		{
			ApexPages.addMessage(new ApexPages.Message(
					ApexPages.Severity.INFO,'A Spot Data Mirror Batch is already running or is preparing to run. '
							+ 'Please reprocess the records after the previous batch finishes running.'));
		}
		return null;
	}
	public PageReference GoBackButton()
	{
		if (FilterId != null)
		{
			return new PageReference('/' + ObjectPrefix + '?fcf=' + FilterId);
		}
		else
		{
			return new PageReference('/' + ObjectPrefix + '?fcf=00BC0000008vccx');
		}
	}
}