objects/Deal__c.object
<CustomObject>
    <fields>
        <fullName>ClientCode__c</fullName>
        <formula>Program__r.ClientCode__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ClientCode</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Type__c</field>
                <operation>notEqual</operation>
                <value>history</value>
            </filterItems>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>Do Not Call</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Network_Deal_Number__c</fullName>
        <description>Deal number in Network&apos;s paper work, in Network&apos;s records.</description>
        <externalId>true</externalId>
        <inlineHelpText>Deal number in Network&apos;s paper work, in Network&apos;s records.  Equals 1 if the PI campaign is no longer airing on the network.</inlineHelpText>
        <label>Network Deal Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Program</label>
        <referenceTo>Programs__c</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Deal</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Deal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PrelogData__c.object
<CustomObject>
    <fields>
        <fullName>Batch_Id__c</fullName>
        <label>Batch Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PrelogDataMirror__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Prelog Data Mirror</label>
        <referenceTo>PrelogDataMirror__c</referenceTo>
        <relationshipLabel>Prelog Data</relationshipLabel>
        <relationshipName>Prelog_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Schedule__c</fullName>
        <label>Schedule</label>
        <referenceTo>Schedules__c</referenceTo>
        <relationshipLabel>Prelog Data</relationshipLabel>
        <relationshipName>Prelog_Data</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Prelog Data</label>
    <nameField>
        <displayFormat>Pre-{0000000}</displayFormat>
        <label>Prelog Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prelog Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PrelogDataMirror__c.object
<CustomObject>
    <fields>
        <fullName>Batch_Id__c</fullName>
        <description>Stamp the batch Id on a failed mirror.</description>
        <label>Batch Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Deal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deal</label>
        <referenceTo>Deal__c</referenceTo>
        <relationshipLabel>Prelog Data Mirrors</relationshipLabel>
        <relationshipName>Prelog_Data_Mirrors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ErrorReason__c</fullName>
        <label>Error Reason</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Unit Length not found</fullName>
                </value>
                <value>
                    <fullName>Air Date does not match</fullName>
                </value>
                <value>
                    <fullName>Air Time does not match</fullName>
                </value>
                <value>
                    <fullName>Rate not found</fullName>
                </value>
                <value>
                    <fullName>Network Deal number not found</fullName>
                </value>
                <value>
                    <fullName>No Network Deal number</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PrelogData__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Prelog Data</label>
        <referenceTo>PrelogData__c</referenceTo>
        <relationshipLabel>Prelog Data Mirrors</relationshipLabel>
        <relationshipName>Prelog_Data_Mirrors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Schedule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Schedule</label>
        <referenceTo>Schedules__c</referenceTo>
        <relationshipLabel>Prelog Data Mirrors</relationshipLabel>
        <relationshipName>Prelog_Data_Mirrors</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Prelog Data Mirror</label>
    <nameField>
        <displayFormat>Prelog-{0000000}</displayFormat>
        <label>Prelog Data Mirror Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prelog Data Mirrors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Programs__c.object
<CustomObject>
    <description>Program/Distributor</description>
    <fields>
        <fullName>Cable_Synd__c</fullName>
        <label>Cable/Synd/PP</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cable</fullName>
                </value>
                <value>
                    <fullName>Syndication</fullName>
                </value>
                <value>
                    <fullName>PP</fullName>
                </value>
                <value>
                    <fullName>Bundle</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ClientCode__c</fullName>
        <description>Assigned by Finance</description>
        <inlineHelpText>Assigned by Finance</inlineHelpText>
        <label>ClientCode</label>
        <length>3</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Clock_Start_Time__c</fullName>
        <label>Clock Start Time</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>5AM</fullName>
                </value>
                <value>
                    <fullName>6AM</fullName>
                </value>
                <value>
                    <fullName>4AM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Station_Call_Letter__c</fullName>
        <label>Station Call Letter</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Schedules__c.object
<CustomObject>
    <fields>
        <fullName>Network_Deal_Number__c</fullName>
        <formula>Deal_Parent__r.Network_Deal_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Network Deal Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <label>Start Time</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>MGM_HD_Daypart__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>01:00A</fullName>
                </value>
                <value>
                    <fullName>01:30A</fullName>
                </value>
                <value>
                    <fullName>02:00A</fullName>
                </value>
                <value>
                    <fullName>02:30A</fullName>
                </value>
                <value>
                    <fullName>03:00A</fullName>
                </value>
                <value>
                    <fullName>03:30A</fullName>
                </value>
                <value>
                    <fullName>04:00A</fullName>
                </value>
                <value>
                    <fullName>04:30A</fullName>
                </value>
                <value>
                    <fullName>05:00A</fullName>
                </value>
                <value>
                    <fullName>05:30A</fullName>
                </value>
                <value>
                    <fullName>06:00A</fullName>
                    <default>true</default>
                    <label>06:00A</label>
                </value>
                <value>
                    <fullName>06:30A</fullName>
                </value>
                <value>
                    <fullName>07:00A</fullName>
                </value>
                <value>
                    <fullName>07:30A</fullName>
                </value>
                <value>
                    <fullName>08:00A</fullName>
                </value>
                <value>
                    <fullName>08:30A</fullName>
                </value>
                <value>
                    <fullName>09:00A</fullName>
                </value>
                <value>
                    <fullName>09:30A</fullName>
                </value>
                <value>
                    <fullName>10:00A</fullName>
                </value>
                <value>
                    <fullName>10:30A</fullName>
                </value>
                <value>
                    <fullName>11:00A</fullName>
                </value>
                <value>
                    <fullName>11:30A</fullName>
                </value>
                <value>
                    <fullName>12:00P</fullName>
                </value>
                <value>
                    <fullName>12:30P</fullName>
                </value>
                <value>
                    <fullName>01:00P</fullName>
                </value>
                <value>
                    <fullName>01:30P</fullName>
                </value>
                <value>
                    <fullName>02:00P</fullName>
                </value>
                <value>
                    <fullName>02:30P</fullName>
                </value>
                <value>
                    <fullName>03:00P</fullName>
                </value>
                <value>
                    <fullName>03:30P</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Units_Available__c</fullName>
        <label>Units Available</label>
        <precision>17</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <label>Schedule</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/PrelogDataBatchTest.cls
@IsTest
private class PrelogDataBatchTest {
	@IsTest
	private static void prelogDataBatch_createPrelogDataFromMirror_prelogDataCreated() {
		Schedules__c testSchedule = createSchedule('123', 'test', 'Mon');
		List<PrelogDataMirror__c> mirrors = createPrelogDataMirrors(true, Integer.valueOf(testSchedule.Units_Available__c), true, -6, false, false);
		List<Id> mirrorIds = new List<Id>();
		for (PrelogDataMirror__c mirror: mirrors) {
			mirrorIds.add(mirror.id);
		}

		insert new Prelog_Batch_Networks__c(Name = 'test');
		runBatchJob();
		Map<Id, PrelogData__c> prelogs = getPrelogDataFromMirrorIds(mirrorIds);
		System.assertNotEquals(prelogs, null);

	}

	@IsTest
	private static void prelogDataBatch_createPrelogDataFromMirror_prelogDataLookupPopulated() {
		Schedules__c testSchedule = createSchedule('123', 'test', 'Mon');
		List<PrelogDataMirror__c> mirrors = createPrelogDataMirrors(true, Integer.valueOf(testSchedule.Units_Available__c), true, -6, false, true);
		List<Id> mirrorIds = new List<Id>();
		for (PrelogDataMirror__c mirror: mirrors) {
			mirrorIds.add(mirror.id);
		}
		insert new Prelog_Batch_Networks__c(Name = 'test');
		runBatchJob();

		Map<Id, PrelogData__c> prelogs = getPrelogDataFromMirrorIds(mirrorIds);
		Map<Id, PrelogDataMirror__c> updatedMirrors = getPrelogDataMirrors(prelogs.keySet());
		System.assertNotEquals(null, updatedMirrors);
		System.assert(updatedMirrors.size() > 0);
		for (PrelogDataMirror__c mirror: updatedMirrors.values()) {

			System.assertNotEquals(null, mirror.PrelogData__c);
			System.assertNotEquals(null, mirror.Schedule__c );

		}
	}

	@IsTest
	private static void prelogDataBatch_createPrelogDataFromMirror_PrelogDataMirrorSuccessfullyCreated() {
		Schedules__c testSchedule = createSchedule('123','test','Mon');
		List<PrelogDataMirror__c> mirrors = createPrelogDataMirrors(true, Integer.valueOf(testSchedule.Units_Available__c), true, -6, false, false);
		insert new Prelog_Batch_Networks__c(Name = 'test');
		runBatchJob();
		PrelogDataMirror__c m = [SELECT Id, ErrorReason__c, Schedule__c,  Batch_Id__c FROM PrelogDataMirror__c WHERE Id =: mirrors[0].Id];
		System.assertEquals(null, m.Batch_Id__c);
	}


	@IsTest
	private static void prelogDataBatch_createPrelogDataFromMirror_InvalidNetworkDealNumber() {
		Schedules__c testSchedule = createSchedule('123', 'test', 'Mon');
		createPrelogDataMirrors(false, Integer.valueOf(testSchedule.Units_Available__c), true, -6, false, false);
		insert new Prelog_Batch_Networks__c(Name = 'test1');
		runBatchJob();
		List<PrelogDataMirror__c> failedMirrors = getFailedPrelogDataMirrors();
		System.assert(failedMirrors.size() == 0, 'Network deal number does not match or invalid');
	}

	@IsTest
	private static void prelogDataBatch_createPrelogDataFromMirror_RateNotFound() {
		Schedules__c testSchedule = createSchedule('123', 'test', 'mon');
		createPrelogDataMirrors(false, Integer.valueOf(testSchedule.Units_Available__c), true, -6, false, true);
		insert new Prelog_Batch_Networks__c(Name = 'test');
		runBatchJob();
		List<PrelogData__c> prelogs = getPrelogDataFromScheduleId(testSchedule.Id);
		System.assert(prelogs.size() == 0);

		List<PrelogDataMirror__c> failedMirrors = getFailedPrelogDataMirrors();
		AssetsCorrectErrorMessage(failedMirrors);
		System.assertEquals(failedMirrors[0].ErrorReason__c, 'Rate not found');
	}

	@IsTest
	private static void prelogDataBatch_createPrelogDataFromMirror_AirTimeNotFound() {
		Schedules__c testSchedule = createSchedule('123', 'test', 'mon');
		createPrelogDataMirrors(true, Integer.valueOf(testSchedule.Units_Available__c), true, -6, false, false);
		insert new Prelog_Batch_Networks__c(Name = 'test');
		runBatchJob();
		List<PrelogDataMirror__c> failedMirrors = getFailedPrelogDataMirrors();
		String error = failedMirrors[0].ErrorReason__c;
		System.assertEquals('Air Time Not Found', error);
		AssetsCorrectErrorMessage(failedMirrors);

	}

	@IsTest
	private static void prelogDataBatch_createPrelogDataFromMirror_UnitLengthNotFound() {
		Schedules__c testSchedule = createSchedule('123', 'test', 'mon');
		createPrelogDataMirrors(true, Integer.valueOf(testSchedule.Units_Available__c), true, -6, true, false);
		insert new Prelog_Batch_Networks__c(Name = 'test');
		runBatchJob();
		List<PrelogData__c> prelogs = getPrelogDataFromScheduleId(testSchedule.Id);
		System.assert(prelogs.size() == 0);

		List<PrelogDataMirror__c> failedMirrors = getFailedPrelogDataMirrors();
		AssetsCorrectErrorMessage(failedMirrors);
		String error = failedMirrors[0].ErrorReason__c;
		System.assertEquals(error, 'Unit Length not found');

	}

	private static Schedules__c createSchedule(String dealNumber, String programName, String airDate ) {
		Account testAcct = new Account();
		testAcct.Name = 'PrelogDataMirror Test';
		testAcct.Billingcity = 'Wakarusa';
		insert testAcct;

		Contact contact = new Contact();
		contact.FirstName = 'Test';
		contact.LastName = 'Name';
		contact.Email = 'test@testemail.com';
		contact.Phone = '(758) 771-0091';
		contact.Account = testAcct;
		insert contact;

		Programs__c program = new Programs__c();
		program.Name = programName;
		program.Cable_Synd__c = 'Cable';
		program.Station_Call_Letter__c = 'AWED';
		program.ClientCode__c = dealNumber;
		program.Clock_Start_Time__c = '7AM';
		insert program;

		Deal__c testDeal = new Deal__c();
		testDeal.Program__c = program.id;
		testDeal.Contact__c = contact.id;
		testDeal.Network_Deal_Number__c = dealNumber;
		testDeal.Length__c = '1';
		insert testDeal;


		Schedules__c schedule = new Schedules__c();
		schedule.Week__c = date.today().toStartofWeek().addDays(-6);
		schedule.Units_Available__c = 5;
		schedule.Deal_Parent__c = testDeal.id;
		schedule.Days_Allowed__c = airDate;
		schedule.Start_Time__c = '09:00A';
		schedule.End_Time__c = '09:30A';
		schedule.Rate__c = 100;
		schedule.Units_Available__c = 5;
		insert schedule;
		return [SELECT Id, Week__c, Deal_Parent__c, Deal_Parent__r.Network_Deal_Number__c, Days_Allowed__c, Start_Time__c, End_Time__c, Rate__c, Units_Available__c
		FROM Schedules__c WHERE Id =: schedule.Id];
	}

	private static List<PrelogDataMirror__c> createPrelogDataMirrors(Boolean isRate, Integer unitsAvailable,
			Boolean dealNumber, Integer airDateAddDay, Boolean scheduleLen,
			Boolean AirTimeNotFound) {


		List<PrelogDataMirror__c> mirrors = new List<PrelogDataMirror__c>();

		for (Integer i = 0; i < unitsAvailable; i++) {
			Deal__c deal = new Deal__c();
			PrelogDataMirror__c mirror = new PrelogDataMirror__c();
			mirror.NetworkDealNumber__c = dealNumber ? '123' : '321';
			mirror.Network__c = 'test';
			mirror.ScheduleLength__c = scheduleLen ? '100' : '1';
			mirror.AirDate__c = Date.today().toStartOfWeek().addDays(airDateAddDay);
			mirror.ScheduleTime__c = AirTimeNotFound ? '9:10:00AM' : '3:10:00PM';
			mirror.Rate__c = isRate ? 100 : null;
			mirror.Deal__c = deal.Id;
			mirror.Version__c = 1;
			mirrors.add(mirror);
		}

		insert mirrors;
		return mirrors;
	}

	private static List<PrelogData__c> getPrelogDataFromScheduleId(Id scheduleId) {
		return [SELECT Id,
				ScheduleTime__c,
				Schedule__c,
				AirDate__c,
				PrelogDataMirror__c,
				Batch_Id__c
		FROM PrelogData__c
		WHERE Schedule__c = :scheduleId];
	}

	private static Map<Id, PrelogData__c> getPrelogDataFromMirrorIds(List<Id> mirrorIds) {
		return new Map<Id, PrelogData__c> ([SELECT Id,
				ScheduleTime__c,
				Schedule__c,
				AirDate__c
		FROM PrelogData__c
		WHERE PrelogDataMirror__c = :mirrorIds]);
	}

	private static Map<Id, PrelogDataMirror__c> getPrelogDataMirrors(Set<Id> prelogIds) {
		return new Map<Id, PrelogDataMirror__c>([
				SELECT id,
						PrelogData__c,
						Schedule__c,
						ErrorReason__c
				FROM PrelogDataMirror__c
				WHERE PrelogData__c in :prelogIds
		]);
	}

	private static List<PrelogDataMirror__c> getFailedPrelogDataMirrors() {

		return [SELECT Id,
				ScheduleTime__c,
				Schedule__c,
				AirDate__c,
				Schedule__r.Days_Allowed__c,
				ErrorReason__c,
				Deal__c,
				PrelogData__c,
				Batch_Id__c
		FROM PrelogDataMirror__c
		WHERE ErrorReason__c != NULL];
	}

	private static void AssetsCorrectErrorMessage(List<PrelogDataMirror__c> mirror) {
		for(PrelogDataMirror__c failedMirrors : mirror) {
			System.assert(failedMirrors.Deal__c != null);
			System.assert(mirror.size() > 0);
		}
	}

	private static void runBatchJob() {
		Test.startTest();
		PrelogDataBatch batch = new PrelogDataBatch('test');
		Database.executeBatch(batch);
		Test.stopTest();
	}
}