objects/Deal__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Type__c</field>
                <operation>notEqual</operation>
                <value>history</value>
            </filterItems>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>Do Not Call</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <label>[Dep]Rate</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Deal</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Deal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Schedules__c.object
<CustomObject>
    <fields>
        <fullName>Deal_Parent__c</fullName>
        <label>Deal Parent</label>
        <referenceTo>Deal__c</referenceTo>
        <relationshipLabel>Schedules</relationshipLabel>
        <relationshipName>Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <label>Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Units_Available__c</fullName>
        <label>Units Available</label>
        <precision>17</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Week__c</fullName>
        <label>Week</label>
        <type>Date</type>
    </fields>
    <label>Schedule</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TestDataFactory.cls
@IsTest
public with sharing class TestDataFactory {

    public static Account account(Boolean insertAccount) {
        Account account = new Account(Name = 'Test');

        if (insertAccount) insert account;

        return account;
    }

    public static Contact contact(Boolean insertContact) {
        return contact(account(true).Id, insertContact);
    }

    public static Contact contact(Id accountId, Boolean insertContact) {
        Contact contact = new Contact(AccountId = accountId, LastName = 'Test', Email = 'test@test.com', Phone = '5555555555');

        if (insertContact) insert contact;

        return contact;
    }

    public static Deal__c deal(Boolean insertDeal) {
        return deal(contact(true).Id, insertDeal);
    }

    public static Deal__c deal(Id contactId, Boolean insertDeal) {
        Deal__c deal = new Deal__c(Contact__c = contactId);

        if (insertDeal) insert deal;

        return deal;
    }

    public static Schedules__c schedule(Boolean insertSchedule) {
        return schedule(deal(true).Id, insertSchedule);
    }

    public static Schedules__c schedule(Id dealId, Boolean insertSchedule) {
        return schedule(
            dealId,
            Date.today().toStartOfWeek().addDays(1),
            0,
            0,
            insertSchedule
        );
    }

    public static Schedules__c schedule(Id dealId, Date week, Decimal unitsAvailable, Decimal rate, Boolean insertSchedule) {
        Schedules__c schedule = new Schedules__c(
            Deal_Parent__c = dealId,
            Week__c = week,
            Units_Available__c = unitsAvailable,
            Rate__c = rate
        );

        if (insertSchedule) insert (SObject) schedule;

        return schedule;
    }
}