objects/Deal__c.object
<CustomObject>
    <label>Deal</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Deal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Prelog__b.object
<CustomObject>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <referenceTo>Programs__c</referenceTo>
        <relationshipLabel>Prelogs</relationshipLabel>
        <relationshipName>Prelogs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Schedule__c</fullName>
        <label>Schedule</label>
        <referenceTo>Schedules__c</referenceTo>
        <relationshipLabel>Prelogs</relationshipLabel>
        <relationshipName>Prelogs</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Prelog</label>
    <pluralLabel>Prelogs</pluralLabel>
</CustomObject>

objects/Prelog_Big_Object_Mapping__mdt.object
<CustomObject>
    <fields>
        <fullName>Source_Field__c</fullName>
        <label>Source Field</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Target_Field__c</fullName>
        <label>Target Field</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Prelog Big Object Mapping</label>
    <pluralLabel>Prelog Big Object Mappings</pluralLabel>
</CustomObject>

objects/PrelogData__c.object
<CustomObject>
    <fields>
        <fullName>Archived_Date__c</fullName>
        <label>Archived Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Schedule__c</fullName>
        <label>Schedule</label>
        <referenceTo>Schedules__c</referenceTo>
        <relationshipLabel>Prelog Data</relationshipLabel>
        <relationshipName>Prelog_Data</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Week__c</fullName>
        <formula>CASE( 
MOD(  AirDate__c - DATE(1900, 1, 7), 7), 
0, AirDate__c - 6, 
1, AirDate__c , 
2, AirDate__c -1, 
3, AirDate__c - 2, 
4,AirDate__c - 3, 
5, AirDate__c - 4, 
6, AirDate__c - 5, DATE(2001, 1, 1))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Week</label>
        <type>Date</type>
    </fields>
    <label>Prelog Data</label>
    <nameField>
        <displayFormat>Pre-{0000000}</displayFormat>
        <label>Prelog Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prelog Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Programs__c.object
<CustomObject>
    <description>Program/Distributor</description>
    <label>Program</label>
    <nameField>
        <label>Program</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Schedules__c.object
<CustomObject>
    <fields>
        <fullName>Deal_Parent__c</fullName>
        <label>Deal Parent</label>
        <referenceTo>Deal__c</referenceTo>
        <relationshipLabel>Schedules</relationshipLabel>
        <relationshipName>Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Week__c</fullName>
        <label>Week</label>
        <type>Date</type>
    </fields>
    <label>Schedule</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/PrelogBigObjectBatch.cls
public class PrelogBigObjectBatch implements Database.Batchable<sObject>{

    private List<Prelog_Big_Object_Mapping__mdt> prelogMappings;
    private Set<String> prelogFields;

    private Date startDate;
    private Date endDate;
    private Set<String> programIds;

    public PrelogBigObjectBatch(Date startDate, Date endDate, Set<String> programIds){
        this.startDate = startDate;
        this.endDate = endDate;
        this.programIds = programIds;

        prelogMappings = PrelogBigObjectBatchService.getPrelogMappings();
        prelogFields = PrelogBigObjectBatchService.getPrelogFields(prelogMappings);
    }

    public Database.QueryLocator start(Database.BatchableContext bc) {
        String query = 'SELECT ';
        query += String.join(new List<String>(prelogFields), ',');
        query += ' FROM PrelogData__c';
        query += ' WHERE Archived_Date__c = null AND Schedule__r.Week__c >= :startDate AND Schedule__r.Week__c <= :endDate';
        query += ' AND Schedule__r.Deal_Parent__r.Program__c IN :programIds';

        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext bc, List<SObject> records){
        List<Prelog__b> Prelogs_bo = new List<Prelog__b>();
        for(PrelogData__c prelog : (List<PrelogData__c>)records){
            Prelog__b pbo = new Prelog__b();
            for(Prelog_Big_Object_Mapping__mdt mapping : prelogMappings){
                if(mapping.Source_Field__c.contains('.')){
                    Object fieldValue = PrelogBigObjectBatchService.traverseParentObject(mapping.Source_Field__c, prelog);
                    pbo.put(mapping.Target_Field__c, fieldValue);
                }
                else{
                    pbo.put(mapping.Target_Field__c, prelog.get(mapping.Source_Field__c));
                }
            }
            Prelogs_bo.add(pbo);
        }

        List<Database.SaveResult> results = Database.insertImmediate(Prelogs_bo);
        List<Prelog__b> successfulPrelogs = new List<Prelog__b>();
        Integer iterator = 0;
        for (Database.SaveResult sr : results) {
            if (sr.isSuccess()) {
                successfulPrelogs.add(Prelogs_bo[iterator]);
            }
            else {
                for(Database.Error err : sr.getErrors()) {
                    System.debug('The following error has occurred.');
                    System.debug(err.getStatusCode() + ': ' + err.getMessage());
                    System.debug('Account fields that affected this error: ' + err.getFields());
                }
            }
            iterator++;
        }
        if(!successfulPrelogs.isEmpty()){
            System.enqueueJob(new PrelogBigObjectBatchService.UpdatePrelogs(successfulPrelogs));
        }

    }

    public void finish(Database.BatchableContext bc){

    }

    public static void run(Date startDate, Date endDate, Set<String> programIds){
        PrelogBigObjectBatch batch = new PrelogBigObjectBatch(startDate, endDate, programIds);
        Database.executeBatch(batch, 200);
    }

    public static void run(Date startDate, Date endDate){
        List<Programs__c> programs = PrelogWeekBatchService.getPrograms();
        Set<String> programIds = new Set<String>();
        for(Programs__c program : programs) programIds.add(program.Id);

        PrelogBigObjectBatch batch = new PrelogBigObjectBatch(startDate, endDate, programIds);
        Database.executeBatch(batch, 200);
    }

}