objects/Deal__c.object
<CustomObject>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Program</label>
        <referenceTo>Programs__c</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Deal</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Deal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Programs__c.object
<CustomObject>
    <description>Program/Distributor</description>
    <fields>
        <fullName>RCreconciled_Week__c</fullName>
        <label>RCreconciled Week</label>
        <type>Date</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Ratings_compiled__c.object
<CustomObject>
    <description>Compiled Ratings</description>
    <fields>
        <fullName>AUR__c</fullName>
        <inlineHelpText>Avg. Unit Rate</inlineHelpText>
        <label>AUR</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Budget_Label__c</fullName>
        <label>Budget Label</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Actual</fullName>
                </value>
                <value>
                    <fullName>Budget 1</fullName>
                </value>
                <value>
                    <fullName>Budget 2</fullName>
                </value>
                <value>
                    <fullName>Budget Label</fullName>
                </value>
                <value>
                    <fullName>GM Actual</fullName>
                </value>
                <value>
                    <fullName>GM Budget</fullName>
                </value>
                <value>
                    <fullName>Network Budget</fullName>
                </value>
                <value>
                    <fullName>Sales Goals</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Daypart__c</fullName>
        <label>Daypart</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>DA</fullName>
                </value>
                <value>
                    <fullName>EM</fullName>
                </value>
                <value>
                    <fullName>LN</fullName>
                </value>
                <value>
                    <fullName>ON</fullName>
                </value>
                <value>
                    <fullName>PR</fullName>
                </value>
                <value>
                    <fullName>Total Day</fullName>
                </value>
                <value>
                    <fullName>-</fullName>
                </value>
                <value>
                    <fullName>EF</fullName>
                </value>
                <value>
                    <fullName>LF</fullName>
                </value>
                <value>
                    <fullName>WK</fullName>
                </value>
                <value>
                    <fullName>WKND</fullName>
                </value>
                <value>
                    <fullName>DA - MF</fullName>
                </value>
                <value>
                    <fullName>DA - SS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Demographic__c</fullName>
        <label>Demographic</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Dollar_Amount__c</fullName>
        <inlineHelpText>Total Dollar Amount</inlineHelpText>
        <label>Dollar Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>INV__c</fullName>
        <inlineHelpText>Investment</inlineHelpText>
        <label>INV</label>
        <precision>9</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Playback__c</fullName>
        <label>Playback</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Live+SD | TV | Linear with VOD</fullName>
                </value>
                <value>
                    <fullName>LSD</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Programs__c</referenceTo>
        <relationshipLabel>Ratings Compiled</relationshipLabel>
        <relationshipName>Ratings_Compiled</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Actual or Budget</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Actual</fullName>
                    <default>true</default>
                    <label>Actual</label>
                </value>
                <value>
                    <fullName>Budget</fullName>
                </value>
                <value>
                    <fullName>Sales Goals</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Week__c</fullName>
        <label>Week</label>
        <type>Date</type>
    </fields>
    <label>Ratings Compiled</label>
    <nameField>
        <displayFormat>RC-{00000000}</displayFormat>
        <label>Ratings Compiled Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ratings Compiled</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Schedules__c.object
<CustomObject>
    <fields>
        <fullName>Day_of_Week__c</fullName>
        <formula>CASE(
MOD(  Week__c  - DATE(1900, 1, 7), 7), 
0, &quot;7Sun&quot;, 
1, &quot;1Mon&quot;, 
2, &quot;2Tues&quot;, 
3, &quot;3Wed&quot;, 
4, &quot;4Th&quot;, 
5, &quot;5Fri&quot;, 
6, &quot;6Sat&quot;, &quot;Error&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Day of Week</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Daypart__c</fullName>
        <formula>IF(OR(LEFT(TEXT(MGM_HD_Daypart__c), 2) = &quot;DA&quot;, LEFT(TEXT(MGM_HD_Daypart__c), 2) = &quot;EM&quot;, LEFT(TEXT(MGM_HD_Daypart__c), 2) = &quot;ON&quot;, LEFT(TEXT(MGM_HD_Daypart__c), 2) = &quot;PR&quot;, LEFT(TEXT(MGM_HD_Daypart__c), 2) = &quot;LN&quot;, LEFT(TEXT(MGM_HD_Daypart__c), 2) = &quot;EF&quot;, LEFT(TEXT(MGM_HD_Daypart__c), 2) = &quot;LF&quot;),LEFT(TEXT(MGM_HD_Daypart__c), 2), CASE( MGM_HD_Daypart__c, 

&quot;9A-6P – Day&quot;,&quot;DA&quot;, 
&quot;Day Live Game&quot;,&quot;DA&quot;, 
&quot;6P-12A – PR&quot;,&quot;PR&quot;, 
&quot;Prime Live Game&quot;,&quot;PR&quot;, 
&quot;JC - MS 7p-12a&quot;,&quot;PR&quot;, 
&quot;6A-9A – EM&quot;,&quot;EM&quot;, 
&quot;3A-6A -- ON&quot;,&quot;ON&quot;, 
&quot;JC - MS 12a-5a&quot;,&quot;ON&quot;, 
&quot;12A-3A -- LN&quot;,&quot;LN&quot;, 
&quot;SS 9a-4p&quot;,&quot;DA&quot;, 
&quot;MS 12a-2a&quot;,&quot;WC&quot;,
&quot;MS 2a-6a&quot;,&quot;ON&quot;, 
&quot;MS 1p-6p&quot;,&quot;DA&quot;, 
&quot;WC - MS 12a-2a&quot;,&quot;WC&quot;, 
&quot;Matinee Game MS&quot;,&quot;DA&quot;, 
&quot;Prime Game MS&quot;,&quot;PR&quot;, 
&quot;MS 7p-12a&quot;,&quot;PR&quot;, 
&quot;ROS-&quot;,&quot;ROS-&quot;, 
&quot;&quot;) 
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Daypart</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Deal_Parent__c</fullName>
        <label>Deal Parent</label>
        <referenceTo>Deal__c</referenceTo>
        <relationshipLabel>Schedules</relationshipLabel>
        <relationshipName>Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PI_Payout_TEST__c</fullName>
        <description>Roll up of payout amount from the PI Payout Child object</description>
        <label>PI Payout TEST</label>
        <summarizedField>PI_Payout__c.Payout_Amount__c</summarizedField>
        <summaryForeignKey>PI_Payout__c.Schedule__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Spot_Total__c</fullName>
        <label>Spot Total $</label>
        <summarizedField>Spot_Data__c.Spot_Rate__c</summarizedField>
        <summaryFilterItems>
            <field>Spot_Data__c.Status__c</field>
            <operation>notEqual</operation>
            <value>Discrepancy</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Spot_Data__c.Availability__c</field>
            <operation>equals</operation>
            <value>False</value>
        </summaryFilterItems>
        <summaryForeignKey>Spot_Data__c.Schedule__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Sum_Spot_Equiv_30__c</fullName>
        <label>Sum of Spot Equiv 30</label>
        <summarizedField>Spot_Data__c.Spot_Equiv_30__c</summarizedField>
        <summaryForeignKey>Spot_Data__c.Schedule__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Week__c</fullName>
        <label>Week</label>
        <type>Date</type>
    </fields>
    <label>Schedule</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Spot_Data__c.object
<CustomObject>
    <description>Post log information for schedule</description>
    <fields>
        <fullName>Day_of_Week__c</fullName>
        <formula>CASE( 
MOD(  Air_Date__c  - DATE(1900, 1, 7), 7), 
0, &quot;7Sun&quot;, 
1, &quot;1Mon&quot;, 
2, &quot;2Tues&quot;, 
3, &quot;3Wed&quot;, 
4, &quot;4Th&quot;, 
5, &quot;5Fri&quot;, 
6, &quot;6Sat&quot;, &quot;Error&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Day of Week</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Daypart__c</fullName>
        <formula>IF(AND(

OR(LEFT(Air_Time__c,2)=&quot;6:&quot;,LEFT(Air_Time__c,2)=&quot;7:&quot;,LEFT(Air_Time__c,2)=&quot;8:&quot;,LEFT(Air_Time__c,2)=&quot;9:&quot;),

OR(RIGHT( Air_Time__c ,2)=&quot;AM&quot;,RIGHT( Air_Time__c ,2)=&quot;am&quot;)),&quot;EM&quot;,

&quot;FALSE&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Daypart</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Spot_Equiv_30__c</fullName>
        <formula>VALUE(TEXT(Length__c)) / 30</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Spot Equiv :30</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Spot_Rate__c</fullName>
        <label>Spot Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Spot Data</label>
    <nameField>
        <displayFormat>S-{000000}</displayFormat>
        <label>Spot Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Spot Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Program.cls
/**
 *
 * Base class for Programs__c Wrapper
 */

public with sharing abstract class Program {
    protected Programs__c program_c {get;set;}
    private static ScheduleSelector scheduleSelector = new ScheduleSelector();
    private static SpotDataSelector spotDataSelector = new SpotDataSelector();

    public static void setScheduleSelector(ScheduleSelector sSelector) {
        scheduleSelector = sSelector;
    }

    public static void setSpotDataSelector(SpotDataSelector spSelector) {
        spotDataSelector = spSelector;
    }

    public static List<String> impFiveDayparts = new List<String>{
            'EM', 'DA', 'PR', 'LN', 'ON'
    };
    public static List<String> impFourDayparts = new List<String>{
            'EM', 'DA', 'PR', 'ON'
    };

    protected Program(Programs__c program) {
        this.program_c = program;
    }

    public List<Schedules__c> getSchedules() {
        return scheduleSelector.getSchedulesInWeek(program_c);
    }

    public abstract List<Ratings_compiled__c> getRatings();

    public abstract void setPrelog(Contact c, Date d);

    public abstract void setPostlog(Contact c, Date d);

    /**
     * imp_standard
     * @description Returns standard ratings (Ratings_compiled__C)
     *
     * @param result the mutable list of ratings (Ratings_compiled__C)
     * @param network the network (Programs__c)
     * @param scheds the schedules (Schedules__c) to use for calculating values
     *
     * @return Boolean representing if the list is finished and should be returned
     */
    public Boolean imp_standard(List<Ratings_compiled__c> result, List<Schedules__c> schedules, List<String> demos) {
        Decimal i = 0;
        Decimal d = 0;
        Decimal aur = 0;

        //Total Day calculation
        for (Schedules__c sched : schedules) {
            i = i + sched.Sum_Spot_Equiv_30__c;
            d = d + sched.Spot_Total__c + sched.PI_Payout_TEST__c;
        }
        if (i == 0 || d == 0) {
            return true;
        }
        for (String demoB : demos) {

            Decimal a = (program_c.Name.equals('BounceTV')) ? aur : (d / i);
            Ratings_compiled__c rcr = createIMPRating(program_c, demoB, 'Total Day', i, d, a);

            result.add(rcr);
        }
        i = 0.0;
        d = 0.0;
        for (String fdp : impFiveDayparts) {
            for (Schedules__c sched : schedules) {
                if (sched.Daypart__c == fdp) {
                    i = i + sched.Sum_Spot_Equiv_30__c;
                    d = d + sched.Spot_Total__c + sched.PI_Payout_TEST__c;
                }
            }
            if (i == 0 || d == 0) {
                aur = 0;
            } else {
                aur = d / i;
            }
            for (String demoB : demos) {
                Ratings_compiled__c rcr = createIMPRating(program_c, demoB, fdp, i, d, aur);

                result.add(rcr);
            }
            i = 0.0;
            d = 0.0;
        }
        return false;
    }

    /**
     * imp_demos
     * @description Returns ratings (Ratings_compiled__C) with specific demographic info
     *
     * @param result the mutable list of ratings (Ratings_compiled__C)
     * @param schedules the schedules (Schedules__c) to use for calculating values
     * @param dayParts the specific dayParts
     * @param demos the demographic information
     *
     * @return Boolean representing if the list is finished and should be returned
     */
    public List<Ratings_compiled__c> imp_demos(List<Schedules__c> schedules, List<String> dayParts, List<String> demos) {
        List<Ratings_compiled__c> result = new List<Ratings_compiled__c>();
        Decimal i = 0;
        Decimal d = 0;
        Decimal aur = 0;

        //Total Day calculation
        for (Schedules__c sched : schedules) {
            i = i + sched.Sum_Spot_Equiv_30__c;
            d = d + sched.Spot_Total__c + sched.PI_Payout_TEST__c;
        }
        if (i == 0 || d == 0) {
            return result;
        }
        for (String demoB : demos) {
            Ratings_compiled__c rcr = createIMPRating(program_c, demoB, 'Total Day', i, d, d / i);

            result.add(rcr);
        }
        i = 0.0;
        d = 0.0;
        for (String fdp : dayParts) {
            for (Schedules__c sched : schedules) {
                if (sched.Daypart__c == fdp) {
                    i = i + sched.Sum_Spot_Equiv_30__c;
                    d = d + sched.Spot_Total__c + sched.PI_Payout_TEST__c;
                }
            }
            if (i == 0 || d == 0) {
                aur = 0;
            } else {
                aur = d / i;
            }
            for (String demoB : demos) {
                Ratings_compiled__c rcr = createIMPRating(program_c, demoB, fdp, i, d, aur);

                result.add(rcr);
            }
            i = 0.0;
            d = 0.0;
        }
        return result;
    }

    /**
    * @author Adrian Pichardo
    * @date 04/09/2018
    * @description returns a list of ratings for Programs that require seperate Weekday and Weekend ratings records,
    *             loops through demographics and the DA daypart to created these seperate records.
    * @param List<Schedules__c> scheduleWknd - List of schedules used in this method to get the appropriate information for the
    *                                          ratings records.
    * @param List<String> demoBegl - Demographic info for Bounce Escape Grit Laff (Respectively)
    * @param List<String> schedIds - List for a loop to get all DA schedules from the scheduleWknd list
    * @param Programs__c prog - Program that caused the trigger
    * @param decimal amf - calculates INV for weekday ratings
    * @param decimal bmf - calculates Total Dollar for weekday ratings
    * @param decimal ass - calculates INV for weekend ratings
    * @param decimal bss - calculates Total Dollar for weekend ratings
    * @param decimal zzz - calculates PI Payout for weekday DA ratings
    * @return List<Ratings_compiled__c> weekendRC - List of rating records that will be returned
    **/
    public List<Ratings_compiled__c>insertWkndRC(List<Schedules__c> scheduleWknd) {
        List<Ratings_compiled__c> weekendRC = new List<Ratings_compiled__c>();
        List<String> demoBegl = new List<String>{
                'F18-34', 'F18-99', 'F25-54', 'F25-99', 'F35-64', 'F35-99', 'F50-99', 'F55-99', 'F65-99', 'HH', 'M18-34', 'M18-49', 'M18-99', 'M25-54', 'M25-99', 'M35-64', 'M35-99', 'M50-99', 'M55-99', 'M65-99', 'P18-34', 'P18-49', 'P18-99', 'P25-54', 'P25-99', 'P35-64', 'P35-99', 'P50-99', 'P55-99', 'P65-99'
        };
        List<String> schedIds = new List<String>();
        Programs__c prog = scheduleWknd[0].Deal_Parent__r.Program__r;
        Date week = scheduleWknd[0].Week__c;
        Decimal amf = 0;
        Decimal bmf = 0;
        Decimal ass = 0;
        Decimal bss = 0;
        Decimal zzz = 0;
        Decimal aur = 0;

        for (Schedules__c sc : scheduleWknd) {
            if (sc.Daypart__c == 'DA') {
                schedIds.add(sc.Id);
            }
        }

        for (Schedules__c schedid : scheduleWknd) {
            if (schedid.Daypart__c == 'DA') {
                zzz = zzz + schedid.PI_Payout_TEST__c;
            }
        }

        // Select Spot_Data__c objects
        List<Spot_Data__c> spots = spotDataSelector.GetSpotDataWithScheduleIds(schedIds);

        for (Spot_Data__c spot : spots) {
            if (spot.Day_of_Week__c.contains('Mon') || spot.Day_of_Week__c.contains('Tue') || spot.Day_of_Week__c.contains('Wed') || spot.Day_of_Week__c.contains('Th') || spot.Day_of_Week__c.contains('Fri')) {
                amf = amf + spot.Spot_Equiv_30__c;
                bmf = bmf + spot.Spot_Rate__c;
            }
            if (spot.Day_of_Week__c.contains('Sat') || spot.Day_of_Week__c.contains('Sun')) {
                ass = ass + spot.Spot_Equiv_30__c;
                bss = bss + spot.Spot_Rate__c;
            }

        }

        if (amf == 0 || bmf == 0) {
            aur = 0;
        } else {
            aur = (bmf + zzz) / amf;
        }

        for (String demoE : demoBegl) {
            Ratings_compiled__c rc = createWKNDRating(prog, week, demoE, 'DA - MF', amf, bmf + zzz, aur);

            weekendRC.add(rc);
        }

        if (ass == 0 || bss == 0) {
            aur = 0;
        } else {
            aur = (bss + zzz) / ass;
        }
        for (String demoE : demoBegl) {
            Ratings_compiled__c rca = createWKNDRating(prog, week, demoE, 'DA - SS', ass, bss, aur);

            weekendRC.add(rca);
        }

        return weekendRC;

    }

    /**
     * dprc_BASE
     * @description Returns the base DP ratings (Ratings_compiled_c)
     *
     * @param result the mutable list of ratings (Ratings_compiled_c)
     * @param network the network (Programs__c)
     * @param scheds the schedules (Schedules__c) to use for calculating values
     *
     */
    public void dprc_BASE(List<Ratings_compiled__c> result, Programs__c network, List<Schedules__c> scheds) {
        Decimal ir = 0;
        Decimal dr = 0;
        Decimal aur = 0;

        //Total Day calculation
        for (Schedules__c sched : scheds) {
            ir = ir + sched.Sum_Spot_Equiv_30__c;
            dr = dr + sched.Spot_Total__c + sched.PI_Payout_TEST__c;
        }
        if (dr == 0 || ir == 0) {
            aur = 0;
        } else {
            aur = dr / ir;
        }

        Ratings_compiled__c rcr = defaultDPRating(network, 'HH', 'Total Day', ir, dr, aur);

        result.add(rcr);
    }

    /**
     * createIMPRating
     * @description Creates a rating (Ratings_compiled_c) object for IMP networks (Programs__c)
     *
     * @param network the network (Programs__c)
     * @param demo the demographic information
     * @param idp the dayPart information
     * @param ir the INV value
     * @param dr the Dollar_Amount value
     * @param aur the AUR value
     *
     * @return the rating (Ratings_compiled__c) object
     */
    public Ratings_compiled__c createIMPRating(Programs__c network, String demo, String idp, Decimal ir, Decimal dr, Decimal aur) {
        Ratings_compiled__c result = new Ratings_compiled__c(
            Program__c = network.Id,
            Playback__c = 'Live+SD | TV | Linear with VOD',
            Demographic__c = demo,
            Budget_Label__c = 'Actual',
            Type__c = 'Actual',
            Daypart__c = idp,
            Week__c = network.RCreconciled_Week__c,
            INV__c = ir,
            Dollar_Amount__c = dr,
            AUR__c = aur
        );
        return result;
    }

    /**
     * createWKNDRating
     * @description Creates a rating (Ratings_compiled_c) object for weekends
     *
     * @param network the network (Programs__c)
     * @param week the Date for Monday of the rating (Ratings_compiled_c)
     * @param demo the demographic information
     * @param idp the dayPart information
     * @param ir the INV value
     * @param dr the Dollar_Amount value
     * @param aur the AUR value
     *
     * @return the rating (Ratings_compiled__c) object
     */
    public Ratings_compiled__c createWKNDRating(Programs__c network, Date week, String demo, String idp, Decimal ir, Decimal dr, Decimal aur) {
        Ratings_compiled__c result = new Ratings_compiled__c(
            Program__c = network.id,
            Playback__c = 'Live+SD | TV | Linear with VOD',
            Demographic__c = demo,
            Budget_Label__c = 'Actual',
            Type__c = 'Actual',
            Daypart__c = idp,
            Week__c = week,
            INV__c = ir,
            Dollar_Amount__c = dr,
            AUR__c = aur
        );
        return result;
    }

    /**
     * createDPRating
     * @description Creates a rating (Ratings_compiled_c) object for DP networks (Programs__c)
     *
     * @param network the network (Programs__c)
     * @param demo the demographic information
     * @param idp the dayPart information
     * @param ir the INV value
     * @param dr the Dollar_Amount value
     * @param aur the AUR value
     *
     * @return the rating (Ratings_compiled__c) object
     */
    public Ratings_compiled__c defaultDPRating(Programs__c network, String demo, String idp, Decimal ir, Decimal dr, Decimal aur) {
        Ratings_compiled__c result = new Ratings_compiled__c(
            Program__c = network.Id,
            Playback__c = 'Live+SD | TV | Linear with VOD',
            Demographic__c = demo,
            Budget_Label__c = 'Actual',
            Type__c = 'Actual',
            Daypart__c = idp,
            Week__c = network.RCreconciled_Week__c,
            INV__c = ir,
            Dollar_Amount__c = dr,
            AUR__c = aur
        );
        return result;
    }
}