objects/Deal__c.object
<CustomObject>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Program</label>
        <referenceTo>Programs__c</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <label>[Dep]Rate</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Deal</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Deal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Programs__c.object
<CustomObject>
    <description>Program/Distributor</description>
    <label>Program</label>
    <nameField>
        <label>Program</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Schedules__c.object
<CustomObject>
    <fields>
        <fullName>DealBrand__c</fullName>
        <formula>Deal_Parent__r.Brands__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>DealBrand</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DealProgram__c</fullName>
        <formula>Deal_Parent__r.Program__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>DealProgram</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Deal_Parent__c</fullName>
        <label>Deal Parent</label>
        <referenceTo>Deal__c</referenceTo>
        <relationshipLabel>Schedules</relationshipLabel>
        <relationshipName>Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <label>Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Units_Available__c</fullName>
        <label>Units Available</label>
        <precision>17</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Week__c</fullName>
        <label>Week</label>
        <type>Date</type>
    </fields>
    <label>Schedule</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/AvailabilityReportSyndication.cls
public class AvailabilityReportSyndication 
{
    public List<schedules__c> schedules;
    public List<programTeamModel> programTeams{get;set;}
    public Integer grand{get;set;}
    
    //Constructor definition
    public AvailabilityReportSyndication ()
    {
        getRecords();
    }
    private void getRecords() 
    {
    	programTeams = new List<programTeamModel>();
        schedules = [SELECT 
                        id, name, Week__c, Units_Available__c, Rate__c, DealProgram__c, Deal_Parent__c, 
                        Deal_Parent__r.Program__r.Team__c, DealBrand__c, Deal_Parent__r.Program__r.Cable_Synd__c 
                        FROM Schedules__c
                        WHERE Week__c >= LAST_N_DAYS:7 AND DealBrand__c = 'Availability' AND Deal_Parent__r.Program__r.Cable_Synd__c = 'Syndication' 
                        AND Deal_Parent__r.Program__r.Fixed_Inventory__c = false ORDER BY week__c LIMIT 1000
                    ];
        // 
        System.debug('######Records found==>'+schedules.size()+'###'+schedules);

        Map<String, Map<Date, List<Schedules__c>>> teamMap = new Map<String, Map<Date, List<Schedules__c>>>();
        for(Schedules__c sch: schedules)
        {
            if(sch.Deal_Parent__r.Program__r.Team__c != null)
            {
                Map<Date, List<Schedules__c>> weekMap = teamMap.get(sch.Deal_Parent__r.Program__r.Team__c);
                if(weekMap != null)
                {
                    List<Schedules__c> scheds = weekMap.get(sch.Week__c);
                    if(scheds != null)
                    {
                        scheds.add(sch);
                    }else
                    {
                        weekMap.put(sch.Week__c, new List<Schedules__c>{sch});
                    }
                }
                else
                {
                    weekMap = new Map<Date, List<Schedules__c>>();
                    weekMap.put(sch.Week__c, new List<Schedules__c>{sch});
                    teamMap.put(sch.Deal_Parent__r.Program__r.Team__c, weekMap);
                }
            }
        }
        grand = 0;
        for(String t : teamMap.keySet())
        {
            programTeamModel ptm = new programTeamModel();
            ptm.team = t;
            Map<Date, List<Schedules__c>> wMap = teamMap.get(t);
            
            List<Date> lstDates = new List<Date>();
            List<weekModel> wModelList = new List<weekModel>();
            integer i=0;
            lstDates.addAll(wMap.keySet());
            lstDates.sort();
            for(Date d : lstDates)
            {
              	weekModel wModel = new weekModel();
                List<Schedules__c> s = wMap.get(d);
                wModel.week = d;
                wModel.schList = s;
                wModelList.add(wModel);
                wModel.wCount = s.size();
                i += wModel.wCount;
            }
            ptm.weeks = wModelList;
            ptm.tCount = i;
            programTeams.add(ptm);
            grand += ptm.tCount;
        }
        
    }
    public void save() 
    {
        Set<Schedules__c> updatedSch = new Set<Schedules__c>();
        List<Schedules__c> updatedSchList = new List<Schedules__c>();
        for(programTeamModel p : programTeams)
        {
            List<weekModel> weekList = p.weeks;
            for(weekmodel w : weekList)
            {
                List<schedules__c> sList = w.schList;
                for(Schedules__c s : sList)
                {
                    updatedSch.add(s);
                }
            }
        }
        for(Schedules__c s:updatedSch)
        {
            updatedSchList.add(s);
        }
        upsert updatedSchList;
        system.debug('@@@@@@ Records saved####');
        getrecords();
    }
    class weekModel 
    {
        public integer wCount{get;set;}
        public Date week {get;set;}
        public List<Schedules__c> schList {get;set;}
        public weekModel()
        {
            schList = new List<Schedules__c>();
        }
    }
    class programTeamModel 
    {
        public Integer tCount{get;set;}
        public String team {set;get;}
        public List<weekModel> weeks {get;set;}
        public programTeamModel()
        {
            weeks = new List<weekModel>();
        }
    }
}