objects/PrelogData__c.object
<CustomObject>
    <fields>
        <fullName>AdvertiserProduct__c</fullName>
        <label>Advertiser/Product</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Agency__c</fullName>
        <label>Agency</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AirDate__c</fullName>
        <label>Air Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BreakCode__c</fullName>
        <label>Break Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field1__c</fullName>
        <label>800#</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MaterialDescription__c</fullName>
        <label>Material Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrderProductDescription__c</fullName>
        <label>Order Product Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PrelogDataMirrorReference__c</fullName>
        <label>Prelog Data Mirror Reference</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PrelogDataMirror__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Prelog Data Mirror</label>
        <referenceTo>PrelogDataMirror__c</referenceTo>
        <relationshipLabel>Prelog Data</relationshipLabel>
        <relationshipName>Prelog_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <label>Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ScheduleAdID__c</fullName>
        <label>Schedule Ad-ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ScheduleLength__c</fullName>
        <label>Schedule Length</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ScheduleTime__c</fullName>
        <label>Schedule Time</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Schedule__c</fullName>
        <label>Schedule</label>
        <referenceTo>Schedules__c</referenceTo>
        <relationshipLabel>Prelog Data</relationshipLabel>
        <relationshipName>Prelog_Data</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TimePeriod__c</fullName>
        <label>Time Period</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <label>Version</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Prelog Data</label>
    <nameField>
        <displayFormat>Pre-{0000000}</displayFormat>
        <label>Prelog Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prelog Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PrelogDataMirror__c.object
<CustomObject>
    <fields>
        <fullName>AdvertiserProduct__c</fullName>
        <label>Advertiser/Product</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Agency__c</fullName>
        <label>Agency</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AirDate__c</fullName>
        <label>Air Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BreakCode__c</fullName>
        <label>Break Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ErrorReason__c</fullName>
        <label>Error Reason</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Unit Length not found</fullName>
                </value>
                <value>
                    <fullName>Air Date does not match</fullName>
                </value>
                <value>
                    <fullName>Air Time does not match</fullName>
                </value>
                <value>
                    <fullName>Rate not found</fullName>
                </value>
                <value>
                    <fullName>Network Deal number not found</fullName>
                </value>
                <value>
                    <fullName>No Network Deal number</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Field1__c</fullName>
        <label>800#</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MaterialDescription__c</fullName>
        <label>Material Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrderProductDescription__c</fullName>
        <label>Order Product Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PrelogData__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Prelog Data</label>
        <referenceTo>PrelogData__c</referenceTo>
        <relationshipLabel>Prelog Data Mirrors</relationshipLabel>
        <relationshipName>Prelog_Data_Mirrors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Problem__c</fullName>
        <defaultValue>false</defaultValue>
        <label>[Dep]Problem</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <label>Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ScheduleAdID__c</fullName>
        <label>Schedule Ad-ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ScheduleLength__c</fullName>
        <label>Schedule Length</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ScheduleTime__c</fullName>
        <label>Schedule Time</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Schedule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Schedule</label>
        <referenceTo>Schedules__c</referenceTo>
        <relationshipLabel>Prelog Data Mirrors</relationshipLabel>
        <relationshipName>Prelog_Data_Mirrors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TimePeriod__c</fullName>
        <label>Time Period</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <label>Version</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Prelog Data Mirror</label>
    <nameField>
        <displayFormat>Prelog-{0000000}</displayFormat>
        <label>Prelog Data Mirror Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prelog Data Mirrors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PrelogDataScheduleBatch.cls
global class PrelogDataScheduleBatch implements Database.Batchable <SObject>
{
	private static PrelogDataSelector prelogDataSelector = new PrelogDataSelector();

	public void setPrelogDataSelector(PrelogDataSelector pDSelector){
		prelogDataSelector = pDSelector;
	}
	global List<Id> PrelogDataMirrorIdList;
	global PrelogDataScheduleBatch(List<Id> pPrelogDataMirrorIdList)
	{
		PrelogDataMirrorIdList = pPrelogDataMirrorIdList;
	}
	global PrelogDataScheduleBatch()
	{
		
	}
	global database.QueryLocator start(Database.BatchableContext BC)
	{
		System.debug('PrelogDataMirrorIdList - ' + PrelogDataMirrorIdList);
		if (PrelogDataMirrorIdList == null)
		{
			//string TodayDate = Date.Today().year() + '-' + (Date.Today().month()< 10? '0' + Date.Today().month() : Date.Today().month()) + '-' + (Date.Today().day()< 10? '0' + Date.Today().day() : Date.Today().day());
			return Database.getQueryLocator('select ' + SaberGF.GetObjectsFieldsForQueries('PrelogDataMirror__c') + ' from PrelogDataMirror__c where PrelogData__c = null AND Schedule__c != null AND CreatedDate >= LAST_WEEK');
		}
		else
		{
			if (PrelogDataMirrorIdList.size() > 0)
			{
				return Database.getQueryLocator('select ' + SaberGF.GetObjectsFieldsForQueries('PrelogDataMirror__c') + ' from PrelogDataMirror__c where Id in ' + SaberGF.ReturnDynamicQueryList(PrelogDataMirrorIdList));
			}
			else
			{
				return Database.getQueryLocator('select ' + SaberGF.GetObjectsFieldsForQueries('PrelogDataMirror__c') + ' from PrelogDataMirror__c where PrelogData__c = null AND Schedule__c != null AND CreatedDate >= LAST_WEEK');
			}
		}
	}
	global void execute(Database.BatchableContext BC, List<PrelogDataMirror__c> scope)
	{
		PrelogDataScheduleBatch.ProcessPrelogDataRecords(scope);
	}
	global static void ProcessPrelogDataRecords(List<PrelogDataMirror__c> scope)
	{
		List<PrelogData__c> PrelogDataList = new List<PrelogData__c>();
		Integer Increment = 0;
		Map<String, PrelogDataMirror__c> UniqueIdPrelogDataMirrorMap = new Map<String, PrelogDataMirror__c>();
		for (PrelogDataMirror__c SDM : scope)
		{
			PrelogData__c PrelogDataRec = new PrelogData__c();
	        PrelogDataRec.AdvertiserProduct__c = SDM.AdvertiserProduct__c;
	        PrelogDataRec.Agency__c = SDM.Agency__c;
	        PrelogDataRec.AirDate__c = SDM.AirDate__c;
	        PrelogDataRec.BreakCode__c = SDM.BreakCode__c;
	        PrelogDataRec.Field1__c = SDM.Field1__c;
	        PrelogDataRec.MaterialDescription__c = SDM.MaterialDescription__c;
	        PrelogDataRec.OrderProductDescription__c = SDM.OrderProductDescription__c;
	        PrelogDataRec.PrelogDataMirror__c = SDM.Id;
	        PrelogDataRec.Rate__c = SDM.Rate__c;
	        PrelogDataRec.Schedule__c = SDM.Schedule__c;
	        PrelogDataRec.ScheduleAdID__c = SDM.ScheduleAdID__c;
	        PrelogDataRec.ScheduleLength__c = SDM.ScheduleLength__c;
	        PrelogDataRec.ScheduleTime__c = SDM.ScheduleTime__c;
	        PrelogDataRec.TimePeriod__c = SDM.TimePeriod__c;
	        PrelogDataRec.Version__c = SDM.Version__c;
	        PrelogDataRec.PrelogDataMirrorReference__c=SDM.Schedule__c+String.valueOf(SDM.Id)+Increment;
	        UniqueIdPrelogDataMirrorMap.put(SDM.Schedule__c+String.valueOf(SDM.Id)+Increment,SDM);
	        System.debug('map value - ' + (SDM.Schedule__c+String.valueOf(SDM.Id)+Increment) + ' - ' + SDM.Id);
	        Increment++;
	        PrelogDataList.add(PrelogDataRec);
		}
		if (PrelogDataList.size() > 0)
		{
			Database.insert(PrelogDataList, false);
			List<PrelogDataMirror__c> SDMList = new List<PrelogDataMirror__c>();
			for (PrelogData__c SP : prelogDataSelector.getProcessPrelogDataRecords(UniqueIdPrelogDataMirrorMap))
			{
				if (UniqueIdPrelogDataMirrorMap.containsKey(SP.PrelogDataMirrorReference__c))
				{
					System.debug('SP values - ' + SP.PrelogDataMirrorReference__c + ' - ' + UniqueIdPrelogDataMirrorMap.get(SP.PrelogDataMirrorReference__c).Id);
					SDMList.add(new PrelogDataMirror__c(Id = UniqueIdPrelogDataMirrorMap.get(SP.PrelogDataMirrorReference__c).Id, PrelogData__c = SP.Id, ErrorReason__c = null,Schedule__c = SP.Schedule__c, Problem__c = false));
				}
			}
			Database.update(SDMList, false);
		}
	}
	global void finish(Database.BatchableContext BC)
	{
		
	}
}