objects/PrelogDataMirror__c.object
<CustomObject>
    <fields>
        <fullName>AirDate__c</fullName>
        <label>Air Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>NetworkDealNumber__c</fullName>
        <label>Network Deal Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Network__c</fullName>
        <label>Network</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <label>Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ScheduleLength__c</fullName>
        <label>Schedule Length</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ScheduleTime__c</fullName>
        <label>Schedule Time</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <label>Version</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Prelog Data Mirror</label>
    <nameField>
        <displayFormat>Prelog-{0000000}</displayFormat>
        <label>Prelog Data Mirror Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prelog Data Mirrors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Programs__c.object
<CustomObject>
    <description>Program/Distributor</description>
    <fields>
        <fullName>Cable_Synd__c</fullName>
        <label>Cable/Synd/PP</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cable</fullName>
                </value>
                <value>
                    <fullName>Syndication</fullName>
                </value>
                <value>
                    <fullName>PP</fullName>
                </value>
                <value>
                    <fullName>Bundle</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ClientCode__c</fullName>
        <description>Assigned by Finance</description>
        <inlineHelpText>Assigned by Finance</inlineHelpText>
        <label>ClientCode</label>
        <length>3</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Clock_Start_Time__c</fullName>
        <label>Clock Start Time</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>5AM</fullName>
                </value>
                <value>
                    <fullName>6AM</fullName>
                </value>
                <value>
                    <fullName>4AM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Prelog_Version__c</fullName>
        <label>Prelog Version</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Station_Call_Letter__c</fullName>
        <label>Station Call Letter</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/MLBNHLSetVersionTest.cls
@isTest
private class MLBNHLSetVersionTest {
	
	private static void createProgram() {
		Programs__c program = new Programs__c();
		program.Name = 'MLB';
		program.Cable_Synd__c = 'Cable';
		program.Station_Call_Letter__c = 'AWED';
		program.ClientCode__c = '1';
		program.Clock_Start_Time__c = '';
		program.Prelog_Version__c = 1.0;
		insert program;
	}

	private static void createPreLogMirror(Integer version) {
		PrelogDataMirror__c mirror = new PrelogDataMirror__c();
		mirror.Network__c = 'MLB';
		mirror.ScheduleLength__c = '1';
		mirror.AirDate__c = date.today().toStartofWeek().addDays(-6);
		mirror.ScheduleTime__c = '6:01:00AM';
		mirror.Rate__c = 100.0;
		mirror.NetworkDealNumber__c = '100';
		mirror.Version__c = version;
		insert mirror;
	}

	@isTest static void testMLBSetVersion_preLogMirrorWithCorrectVersion_preLogVersionSetCorrectly() {
		createProgram();
		createPreLogMirror(99);

		Test.startTest();
		MLBNHLSetVersion setVersionBatch = new MLBNHLSetVersion('MLB');
		Database.executeBatch(setVersionBatch);
		Test.stopTest();

		List<PreLogDataMirror__c> mirrors = getPreLogMirrors();
		for (PreLogDataMirror__c mirror: mirrors) {
			System.assert(mirror.Version__c == 1.0);
		}
	}

	@isTest static void testMLBSetVersion_preLogMirrorWithIncorrectVersion_preLogVersionNotSet() {
		createProgram();
		createPreLogMirror(2);
		
		Test.startTest();
		MLBNHLSetVersion setVersionBatch = new MLBNHLSetVersion('MLB');
		Database.executeBatch(setVersionBatch);
		Test.stopTest();

		List<PreLogDataMirror__c> mirrors = getPreLogMirrors();
		for (PreLogDataMirror__c mirror: mirrors) {
			System.assert(mirror.Version__c != 1.0);
		}

	}

	private static List<PreLogDataMirror__c> getPreLogMirrors() {
		return [SELECT id,
					   Version__c
				  FROM PrelogDataMirror__c
				 WHERE Network__c = 'MLB'];
	}
	
}