objects/Programs__c.object
<CustomObject>
    <description>Program/Distributor</description>
    <label>Program</label>
    <nameField>
        <label>Program</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Ratings_compiled__c.object
<CustomObject>
    <description>Compiled Ratings</description>
    <label>Ratings Compiled</label>
    <nameField>
        <displayFormat>RC-{00000000}</displayFormat>
        <label>Ratings Compiled Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ratings Compiled</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Schedules__c.object
<CustomObject>
    <fields>
        <fullName>CALC_EQUIV_30__c</fullName>
        <formula>if( AND(Units_Available__c &gt;0, NOT(DealBrand__c = &quot;GM Units&quot;)), 
(VALUE(TEXT(Deal_Parent__r.Length__c)) * Units_Aired__c 
/ 30 ), 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>if( AND(Units_Available__c &gt;0,  NOT(DealBrand__c   =  &quot;GM Units&quot;)),
(case(Deal_Parent__r.Length__c, &quot;10&quot;,10, &quot;30&quot;, 30, &quot;45&quot;, 45, &quot;60&quot;, 60, &quot;75&quot;, 75, &quot;105&quot;, 105, &quot;120&quot;, 120, &quot;240&quot;, 240, &quot;300&quot;, 300, &quot;15&quot;, 15, &quot;90&quot;, 90, &quot;180&quot;, 180, &quot;1710&quot;, 1710, 0) * UnitsA</inlineHelpText>
        <label>CALC EQUIV :30</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Dollars__c</fullName>
        <formula>if(  PI_Payout_TEST__c &gt;0,  PI_Payout_TEST__c *20/17, 

if( PI_Payout__c &gt; 0 ,  PI_Payout__c * 20/17, 

if( Units_Aired__c &lt; 0,  0,
CASE(Deal_Parent__r.Status__c, &quot;Canceled&quot;, 0,  &quot;Pre-Empted&quot;, 0,

 Rate__c  *   Units_Aired__c)

)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Dollars</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Schedule</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Program_Onyx.cls
/**

 */

public with sharing class Program_Onyx extends Program {

    public Program_Onyx(Programs__c program) {
        super(program);
    }

    public override List<Ratings_compiled__c> getRatings() {
        List<Ratings_compiled__c> result = new List<Ratings_compiled__c>();
        List<Schedules__c> scheds = super.getSchedules();
        if (scheds == null || scheds.isEmpty()) {
            return null;
        }

        Decimal ir = 0;
        Decimal dr = 0;
        Decimal aur = 0;

        for (Schedules__c sched : scheds) {
            ir = ir + sched.CALC_EQUIV_30__c;
            dr = dr + sched.Total_Dollars__c;
        }
        if (dr == 0 || ir == 0) {
            aur = 0;
        } else {
            aur = dr / ir;
        }

        Ratings_compiled__c rcro = super.defaultDPRating(program_c, 'HH', 'Total Day', ir, dr, aur);

        result.add(rcro);

        return result;
    }

    public override void setPrelog(Contact c, Date d) {
    }

    public override void setPostlog(Contact c, Date d) {
    }
}