objects/Programs__c.object
<CustomObject>
    <description>Program/Distributor</description>
    <fields>
        <fullName>RCreconciled_Week__c</fullName>
        <label>RCreconciled Week</label>
        <type>Date</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Ratings_compiled__c.object
<CustomObject>
    <description>Compiled Ratings</description>
    <fields>
        <fullName>AUR__c</fullName>
        <inlineHelpText>Avg. Unit Rate</inlineHelpText>
        <label>AUR</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Budget_Label__c</fullName>
        <label>Budget Label</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Actual</fullName>
                </value>
                <value>
                    <fullName>Budget 1</fullName>
                </value>
                <value>
                    <fullName>Budget 2</fullName>
                </value>
                <value>
                    <fullName>Budget Label</fullName>
                </value>
                <value>
                    <fullName>GM Actual</fullName>
                </value>
                <value>
                    <fullName>GM Budget</fullName>
                </value>
                <value>
                    <fullName>Network Budget</fullName>
                </value>
                <value>
                    <fullName>Sales Goals</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Daypart__c</fullName>
        <label>Daypart</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>DA</fullName>
                </value>
                <value>
                    <fullName>EM</fullName>
                </value>
                <value>
                    <fullName>LN</fullName>
                </value>
                <value>
                    <fullName>ON</fullName>
                </value>
                <value>
                    <fullName>PR</fullName>
                </value>
                <value>
                    <fullName>Total Day</fullName>
                </value>
                <value>
                    <fullName>-</fullName>
                </value>
                <value>
                    <fullName>EF</fullName>
                </value>
                <value>
                    <fullName>LF</fullName>
                </value>
                <value>
                    <fullName>WK</fullName>
                </value>
                <value>
                    <fullName>WKND</fullName>
                </value>
                <value>
                    <fullName>DA - MF</fullName>
                </value>
                <value>
                    <fullName>DA - SS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Demographic__c</fullName>
        <label>Demographic</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Dollar_Amount__c</fullName>
        <inlineHelpText>Total Dollar Amount</inlineHelpText>
        <label>Dollar Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>INV__c</fullName>
        <inlineHelpText>Investment</inlineHelpText>
        <label>INV</label>
        <precision>9</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Playback__c</fullName>
        <label>Playback</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Live+SD | TV | Linear with VOD</fullName>
                </value>
                <value>
                    <fullName>LSD</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Programs__c</referenceTo>
        <relationshipLabel>Ratings Compiled</relationshipLabel>
        <relationshipName>Ratings_Compiled</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Actual or Budget</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Actual</fullName>
                    <default>true</default>
                    <label>Actual</label>
                </value>
                <value>
                    <fullName>Budget</fullName>
                </value>
                <value>
                    <fullName>Sales Goals</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Week__c</fullName>
        <label>Week</label>
        <type>Date</type>
    </fields>
    <label>Ratings Compiled</label>
    <nameField>
        <displayFormat>RC-{00000000}</displayFormat>
        <label>Ratings Compiled Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ratings Compiled</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Schedules__c.object
<CustomObject>
    <fields>
        <fullName>Daypart__c</fullName>
        <formula>IF(OR(LEFT(TEXT(MGM_HD_Daypart__c), 2) = &quot;DA&quot;, LEFT(TEXT(MGM_HD_Daypart__c), 2) = &quot;EM&quot;, LEFT(TEXT(MGM_HD_Daypart__c), 2) = &quot;ON&quot;, LEFT(TEXT(MGM_HD_Daypart__c), 2) = &quot;PR&quot;, LEFT(TEXT(MGM_HD_Daypart__c), 2) = &quot;LN&quot;, LEFT(TEXT(MGM_HD_Daypart__c), 2) = &quot;EF&quot;, LEFT(TEXT(MGM_HD_Daypart__c), 2) = &quot;LF&quot;),LEFT(TEXT(MGM_HD_Daypart__c), 2), CASE( MGM_HD_Daypart__c, 

&quot;9A-6P – Day&quot;,&quot;DA&quot;, 
&quot;Day Live Game&quot;,&quot;DA&quot;, 
&quot;6P-12A – PR&quot;,&quot;PR&quot;, 
&quot;Prime Live Game&quot;,&quot;PR&quot;, 
&quot;JC - MS 7p-12a&quot;,&quot;PR&quot;, 
&quot;6A-9A – EM&quot;,&quot;EM&quot;, 
&quot;3A-6A -- ON&quot;,&quot;ON&quot;, 
&quot;JC - MS 12a-5a&quot;,&quot;ON&quot;, 
&quot;12A-3A -- LN&quot;,&quot;LN&quot;, 
&quot;SS 9a-4p&quot;,&quot;DA&quot;, 
&quot;MS 12a-2a&quot;,&quot;WC&quot;,
&quot;MS 2a-6a&quot;,&quot;ON&quot;, 
&quot;MS 1p-6p&quot;,&quot;DA&quot;, 
&quot;WC - MS 12a-2a&quot;,&quot;WC&quot;, 
&quot;Matinee Game MS&quot;,&quot;DA&quot;, 
&quot;Prime Game MS&quot;,&quot;PR&quot;, 
&quot;MS 7p-12a&quot;,&quot;PR&quot;, 
&quot;ROS-&quot;,&quot;ROS-&quot;, 
&quot;&quot;) 
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Daypart</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PI_Payout_TEST__c</fullName>
        <description>Roll up of payout amount from the PI Payout Child object</description>
        <label>PI Payout TEST</label>
        <summarizedField>PI_Payout__c.Payout_Amount__c</summarizedField>
        <summaryForeignKey>PI_Payout__c.Schedule__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Spot_Total__c</fullName>
        <label>Spot Total $</label>
        <summarizedField>Spot_Data__c.Spot_Rate__c</summarizedField>
        <summaryFilterItems>
            <field>Spot_Data__c.Status__c</field>
            <operation>notEqual</operation>
            <value>Discrepancy</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Spot_Data__c.Availability__c</field>
            <operation>equals</operation>
            <value>False</value>
        </summaryFilterItems>
        <summaryForeignKey>Spot_Data__c.Schedule__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Sum_Spot_Equiv_30__c</fullName>
        <label>Sum of Spot Equiv 30</label>
        <summarizedField>Spot_Data__c.Spot_Equiv_30__c</summarizedField>
        <summaryForeignKey>Spot_Data__c.Schedule__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Week__c</fullName>
        <label>Week</label>
        <type>Date</type>
    </fields>
    <label>Schedule</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Program_BounceTVLocal.cls
/**

 */

public with sharing class Program_BounceTVLocal extends Program {

    public Program_BounceTVLocal(Programs__c program) {
        super(program);
    }

    public override List<Ratings_compiled__c> getRatings() {
        Decimal i = 0;
        Decimal d = 0;
        Decimal aur = 0;

        List<Ratings_compiled__c> result = new List<Ratings_compiled__c>();
        List<Schedules__c> scheds = super.getSchedules();

        //Total Day calculation
        for (Schedules__c sched : scheds) {
            i = i + sched.Sum_Spot_Equiv_30__c;
            d = d + sched.Spot_Total__c + sched.PI_Payout_TEST__c;
        }
        if (i == 0 || d == 0) {
            return result;
        } else {
            aur = d / i;
        }
        
        Ratings_compiled__c rcr = new Ratings_compiled__c(
            Program__c = program_c.Id,
            Playback__c = 'Live+SD | TV | Linear with VOD',
            Budget_Label__c = 'Actual',
            Type__c = 'Actual',
            Demographic__c = 'HH',
            Daypart__c = 'Total Day',
            Week__c = program_c.RCreconciled_Week__c,
            INV__c = i,
            Dollar_Amount__c = d,
            AUR__c = aur
        );
        result.add(rcr);

        i = 0.0;
        d = 0.0;
        for (String fdp : impFiveDayparts) {
            for (Schedules__c sched : scheds) {
                if (sched.Daypart__c == fdp) {
                    i = i + sched.Sum_Spot_Equiv_30__c;
                    d = d + sched.Spot_Total__c;
                }
            }
            if (i == 0 || d == 0) {
                aur = 0;
            } else {
                aur = d / i;
            }

            Ratings_compiled__c rcrr = new Ratings_compiled__c(
                Program__c = program_c.Id,
                Playback__c = 'Live+SD | TV | Linear with VOD',
                Budget_Label__c = 'Actual',
                Type__c = 'Actual',
                Demographic__c = 'HH',
                Daypart__c = fdp,
                Week__c = program_c.RCreconciled_Week__c,
                INV__c = i,
                Dollar_Amount__c = d,
                AUR__c = aur
            );
            result.add(rcrr);

            i = 0.0;
            d = 0.0;
        }
        return result;
    }

    public override void setPrelog(Contact c, Date d) {
        c.Bounce_Prelog_Week__c = d;
    }

    public override void setPostlog(Contact c, Date d) {
        c.Bounce_Post_Week__c = d;
    }
}