objects/Programs__c.object
<CustomObject>
    <description>Program/Distributor</description>
    <fields>
        <fullName>RCreconciled_Week__c</fullName>
        <label>RCreconciled Week</label>
        <type>Date</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Ratings_compiled__c.object
<CustomObject>
    <description>Compiled Ratings</description>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Programs__c</referenceTo>
        <relationshipLabel>Ratings Compiled</relationshipLabel>
        <relationshipName>Ratings_Compiled</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Actual or Budget</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Actual</fullName>
                    <default>true</default>
                    <label>Actual</label>
                </value>
                <value>
                    <fullName>Budget</fullName>
                </value>
                <value>
                    <fullName>Sales Goals</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Week__c</fullName>
        <label>Week</label>
        <type>Date</type>
    </fields>
    <label>Ratings Compiled</label>
    <nameField>
        <displayFormat>RC-{00000000}</displayFormat>
        <label>Ratings Compiled Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ratings Compiled</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/RatingTestSelector.cls
/**

 *
 * RatingsSelector
 * Testing Selector for Ratings_compiled__c objects
 */

public with sharing class RatingTestSelector extends RatingSelector {
    private static String OBJ = 'Ratings_compiled__c';

    public override List<Ratings_compiled__c> GetRatings(List<SObjectField> fields) {
        String query = 'SELECT ' + String.join(FieldsToStrings(fields), ', ') + ' FROM ' + OBJ;
        return Database.query(query);
    }

    public override List<Ratings_compiled__c> GetRatingsForProgram(Programs__c program) {
        return new List<Ratings_compiled__c> { (Ratings_compiled__c)
                new sfab_FabricatedSObject(Ratings_compiled__c.class)
                .setField(Ratings_compiled__c.Program__c, program.Id)
                .setField(Ratings_compiled__c.Week__c, program.RCreconciled_Week__c)
                .setField(Ratings_compiled__c.Type__c, 'actual')
                .toSObject()
        };
    }


    private List<String> FieldsToStrings(List<SObjectField> fields) {
        List<String> result = new List<String>();
        for (SObjectField field : fields) {
            result.add(field.getDescribe().name);
        }
        return result;
    }
}