objects/Programs__c.object
<CustomObject>
    <description>Program/Distributor</description>
    <fields>
        <fullName>RCreconciled_Week__c</fullName>
        <label>RCreconciled Week</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Reconciled_Week__c</fullName>
        <inlineHelpText>The last fully reconciled week in Salesforce</inlineHelpText>
        <label>Reconciled Week</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <inlineHelpText>Blue, Red, Green, Orange</inlineHelpText>
        <label>Team</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ProgramSelector.cls
/**

 *
 * ProgramSelector
 * Selector for Programs__c objects
 */

public with sharing virtual class ProgramSelector {
    private static String OBJ = 'Programs__c';

    public virtual List<Programs__c> GetPrograms(List<SObjectField> fields) {
        String query = 'SELECT ' + String.join(FieldsToStrings(fields), ', ') + ' FROM ' + OBJ;
        return Database.query(query);
    }

    public virtual List<Programs__c> GetProgramsWithIds(List<String> Ids) {
        return [
                SELECT Id,
                       Name,
                       RCreconciled_Week__c,
                       Team__c
                  FROM Programs__c
                 WHERE Id IN :Ids
        ];
    }

    public virtual List<Programs__c> getProgramsForBundleSpotsBatchStart(String network) {
        return [SELECT Id,
                       Reconciled_Week__c,
                       Name
                  FROM Programs__c
                 WHERE Name = :network];
    }


    private List<String> FieldsToStrings(List<SObjectField> fields) {
        List<String> result = new List<String>();
        for (SObjectField field : fields) {
            result.add(field.getDescribe().name);
        }
        return result;
    }
}