objects/RaycomMonthlyLineItem__c.object
<CustomObject>
    <description>This object is a temporary holder for Raycom data. A report is run monthly and sent to Marathon. Marathon uploads the report via a Salesforce import. As the records are created a Visual Flow sees them and does some manipulation to compare them against the Raycom Key (indexed) field on Spot Data records. When it finds a match it copies the Invoice Number (the Order number plus a suffix) into the Spot Data. The Flow also marks these records for deletion after 15 days in order to keep stored data size down.</description>
    <fields>
        <fullName>Invoice__c</fullName>
        <label>Invoice #</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Key__c</fullName>
        <formula>OrderNumber__c&amp;CASE( 
MONTH (BillingMonth__c ), 
1, &quot;January&quot;, 
2, &quot;February&quot;, 
3, &quot;March&quot;, 
4, &quot;April&quot;, 
5, &quot;May&quot;, 
6, &quot;June&quot;, 
7, &quot;July&quot;, 
8, &quot;August&quot;, 
9, &quot;September&quot;, 
10, &quot;October&quot;, 
11, &quot;November&quot;, 
&quot;December&quot; 
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Key</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Spot_Data_Failure_Count__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Spot Data Failure Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Spot_Data_Failure_Message__c</fullName>
        <label>Spot Data Failure Message</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Raycom Monthly Line Item</label>
    <nameField>
        <displayFormat>{YYYY}-{MM}-{00000}</displayFormat>
        <label>Raycom Monthly Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Raycom Monthly Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Spot_Data__c.object
<CustomObject>
    <description>Post log information for schedule</description>
    <fields>
        <fullName>RaycomKeyIndexed__c</fullName>
        <externalId>true</externalId>
        <label>Raycom Key Indexed</label>
        <length>24</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Raycom_Invoice_Number__c</fullName>
        <description>Raycom Invoice Number, Order number + Month/Version</description>
        <label>Invoice Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Spot Data</label>
    <nameField>
        <displayFormat>S-{000000}</displayFormat>
        <label>Spot Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Spot Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/RaycomMonthlyLineItemBatch.cls
global class RaycomMonthlyLineItemBatch implements Database.Batchable<sObject> {

    global static Boolean forceExceptionError {
        get {
            if(forceExceptionError == null) forceExceptionError = false;
            return forceExceptionError;
        }
        set;
    }
    
    webservice static void init() {
        Database.executeBatch(new RaycomMonthlyLineItemBatch(), 1);
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator([select 
                                         Id, 
                                         Key__c, 
                                         Invoice__c,
                                         Spot_Data_Failure_Count__c 
                                         from RaycomMonthlyLineItem__c
                                         where Spot_Data_Failure_Count__c < 3
                                        ]);
    }
    
    // expectation is this job is run with a batch size of 1 due to previously-indentified locking issues.
    global void execute(Database.BatchableContext BC, List<sObject> scope) {
        
        RaycomMonthlyLineItem__c lineItem = (RaycomMonthlyLineItem__c)scope[0];
        
        // limit at 9990 to save a few DML rows for delete or update process below.
        List<Spot_Data__c> spotDatas = [select 
                                    Id, 
                                    Raycom_Invoice_Number__c, 
                                    RaycomKeyIndexed__c 
                                    from Spot_Data__c 
                                    where RaycomKeyIndexed__c = :lineItem.Key__c 
                                    and Raycom_Invoice_Number__c = null 
                                    limit 9990
                                   ];
        
        List<Spot_Data__c> updatedSpotDatas = new List<Spot_Data__c>();
    
        for(Spot_Data__c sd : spotDatas) {
            sd.Raycom_Invoice_Number__c = lineItem.Invoice__c;
            updatedSpotDatas.add(sd);
        }    
    
        try {
            if(forceExceptionError == true) throw new TestException();
            if(!updatedSpotDatas.isEmpty()) update updatedSpotDatas;
        	delete lineItem;
        }
        catch(Exception ex) {
            // if it fails, increment the failure counter
            if(lineItem.Spot_Data_Failure_Count__c == null) lineItem.Spot_Data_Failure_Count__c = 0;
            lineItem.Spot_Data_Failure_Count__c = lineItem.Spot_Data_Failure_Count__c + 1;
            lineItem.Spot_Data_Failure_Message__c = ex.getMessage().left(4000);
            update lineItem;
        }
        
    }
    
    global void finish(Database.BatchableContext BC) {
        
        List<RaycomMonthlyLineItem__c> retryLineItems = [select 
                                                         Id 
                                                         from RaycomMonthlyLineItem__c 
                                                         where Spot_Data_Failure_Count__c < 3
                                                         limit 1
                                                        ];
        
        if(!retryLineItems.isEmpty() && !Test.isRunningTest()) {
            Database.executeBatch(new RaycomMonthlyLineItemBatch(), 1);
        }
        
    }
    
    public class TestException extends Exception {}
    
}