objects/Schedules__c.object
<CustomObject>
    <fields>
        <fullName>Long_Form__c</fullName>
        <description>Long Form Time Periods for All Networks</description>
        <label>Long Form</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>A-12:00</fullName>
                </value>
                <value>
                    <fullName>A-12:30</fullName>
                </value>
                <value>
                    <fullName>A-1:00</fullName>
                </value>
                <value>
                    <fullName>A-1:30</fullName>
                </value>
                <value>
                    <fullName>A-2:00</fullName>
                </value>
                <value>
                    <fullName>A-2:30</fullName>
                </value>
                <value>
                    <fullName>A-3:00</fullName>
                </value>
                <value>
                    <fullName>A-3:30</fullName>
                </value>
                <value>
                    <fullName>A-4:00</fullName>
                </value>
                <value>
                    <fullName>A-4:30</fullName>
                </value>
                <value>
                    <fullName>A-5:00</fullName>
                </value>
                <value>
                    <fullName>A-5:30</fullName>
                </value>
                <value>
                    <fullName>A-6:00</fullName>
                </value>
                <value>
                    <fullName>A-6:30</fullName>
                </value>
                <value>
                    <fullName>A-7:00</fullName>
                </value>
                <value>
                    <fullName>A-7:30</fullName>
                </value>
                <value>
                    <fullName>A-8:00</fullName>
                </value>
                <value>
                    <fullName>A-8:30</fullName>
                </value>
                <value>
                    <fullName>A-9:00</fullName>
                </value>
                <value>
                    <fullName>A-9:30</fullName>
                </value>
                <value>
                    <fullName>A-10:00</fullName>
                </value>
                <value>
                    <fullName>A-10:30</fullName>
                </value>
                <value>
                    <fullName>A-11:00</fullName>
                </value>
                <value>
                    <fullName>A-11:30</fullName>
                </value>
                <value>
                    <fullName>P-12:00</fullName>
                </value>
                <value>
                    <fullName>P-12:30</fullName>
                </value>
                <value>
                    <fullName>P-1:00</fullName>
                </value>
                <value>
                    <fullName>P-1:30</fullName>
                </value>
                <value>
                    <fullName>P-2:00</fullName>
                </value>
                <value>
                    <fullName>P-2:30</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <label>Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Week__c</fullName>
        <label>Week</label>
        <type>Date</type>
    </fields>
    <label>Schedule</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/EntryCheckHelper.cls
public class EntryCheckHelper {

    public class FBModels {
        public String lfDayPart { set; get; }
        public String key { get; set; }
        public List<FBEntryModel> fbEntryModels { get; set; }
        public FBEntryModel grandTotal { get; set; }
        public Decimal totalRate { get; set; }
        public Integer totalCount { get; set; }
        public Boolean chkbox { get; set; }
        public FBModels() {
            chkbox = false;
        }
    }

    public class FBEntryModel {
        public Schedules__c schedule { get; set; }
        //Week__C ==> for passing
        public boolean showEditable { set; get; }
        public integer wYear { set; get; }
        public integer wMonth { set; get; }
        public integer wDay { set; get; }
        public decimal sumOfRate { get; set; }
        public integer recordCount { get; set; }
        public integer rCount { get; set; }
        public boolean isSubTotal { get; set; }
        public string color { set; get; }
        public String getWeekStr() {
            return schedule.Week__c.Year() + '-' + schedule.Week__c.Month() + '-' + schedule.Week__c.Day();
        }

        public void setWeek(Date d) {
            wYear = d.year();
            wMonth = d.month();
            wDay = d.day();
            showEditable = false;
        }
        public FBEntryModel() {
            color = 'rgb(194,84,84)';
            sumOfRate = 0;
            recordCount = 0;
            schedule = new Schedules__c(rate__c = 0);

            //schedule.Week__c = fbEntryList.get(i).schedule.Week__c;
            //schedule.Long_Form__c = fbEntryList.get(i).schedule.Long_Form__c;
            //schedule.Rate__c =0;
        }
    }

    public class ModelTotals {
        public double sumOfRate { set; get; }
        public integer recordCount { set; get; }
        public string color { set; get; }
        public boolean isSubTotal { get; set; }

        public ModelTotals() {
            sumOfRate = 0;
            recordCount = 0;
            color = 'red';
            isSubTotal = false;
        }
    }

    public class HeadingModel {
        public String cols { get; set; }
        public Date startOfWeek { get; set; }
    }
}