objects/Schedules__c.object
<CustomObject>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Filler__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check if this order is Filler to be used in case of a tape or inventory issue.</description>
        <inlineHelpText>Check if this order is Filler to be used in case of a tape or inventory issue.</inlineHelpText>
        <label>[Dep]Filler</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ISCI_CODE__c</fullName>
        <label>ISCI CODE</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LF_Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Brand for Long Form.  Received in Allocation letter post deal</description>
        <label>[Dep]LF Brand</label>
        <referenceTo>Brands__c</referenceTo>
        <relationshipLabel>Schedules</relationshipLabel>
        <relationshipName>Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Long_Form__c</fullName>
        <description>Long Form Time Periods for All Networks</description>
        <label>Long Form</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>A-12:00</fullName>
                </value>
                <value>
                    <fullName>A-12:30</fullName>
                </value>
                <value>
                    <fullName>A-1:00</fullName>
                </value>
                <value>
                    <fullName>A-1:30</fullName>
                </value>
                <value>
                    <fullName>A-2:00</fullName>
                </value>
                <value>
                    <fullName>A-2:30</fullName>
                </value>
                <value>
                    <fullName>A-3:00</fullName>
                </value>
                <value>
                    <fullName>A-3:30</fullName>
                </value>
                <value>
                    <fullName>A-4:00</fullName>
                </value>
                <value>
                    <fullName>A-4:30</fullName>
                </value>
                <value>
                    <fullName>A-5:00</fullName>
                </value>
                <value>
                    <fullName>A-5:30</fullName>
                </value>
                <value>
                    <fullName>A-6:00</fullName>
                </value>
                <value>
                    <fullName>A-6:30</fullName>
                </value>
                <value>
                    <fullName>A-7:00</fullName>
                </value>
                <value>
                    <fullName>A-7:30</fullName>
                </value>
                <value>
                    <fullName>A-8:00</fullName>
                </value>
                <value>
                    <fullName>A-8:30</fullName>
                </value>
                <value>
                    <fullName>A-9:00</fullName>
                </value>
                <value>
                    <fullName>A-9:30</fullName>
                </value>
                <value>
                    <fullName>A-10:00</fullName>
                </value>
                <value>
                    <fullName>A-10:30</fullName>
                </value>
                <value>
                    <fullName>A-11:00</fullName>
                </value>
                <value>
                    <fullName>A-11:30</fullName>
                </value>
                <value>
                    <fullName>P-12:00</fullName>
                </value>
                <value>
                    <fullName>P-12:30</fullName>
                </value>
                <value>
                    <fullName>P-1:00</fullName>
                </value>
                <value>
                    <fullName>P-1:30</fullName>
                </value>
                <value>
                    <fullName>P-2:00</fullName>
                </value>
                <value>
                    <fullName>P-2:30</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <label>Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Sold</fullName>
                    <default>true</default>
                    <label>Sold</label>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TEST__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Notes whether a particular schedule is a test.</description>
        <label>TEST</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Units_Preempted__c</fullName>
        <label>Units Preempted</label>
        <precision>17</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Week__c</fullName>
        <label>Week</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>X800_Number__c</fullName>
        <description>800 Number for Spot</description>
        <label>800 Number</label>
        <type>Phone</type>
    </fields>
    <label>Schedule</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/EditManagementSchedule.cls
/**
@ name        :        EditManagementSchedule
@ author        :        
@ date        :        12 September, 2011
@ description    :     To edit the schedule records
*/

public class EditManagementSchedule{
    Public List<Schedules__c> sechList;
    Public Schedules__c schedule{get;set;}
    Public Boolean closeWindow{get;set;}
    public EditManagementSchedule(){
        closeWindow = false;
        schedule = new Schedules__c();
        sechList = new List<Schedules__c>();
        Boolean whereFlag = true; 
                
        Set<Id> ids = new Set<Id>();
        for(integer i=0; i<apexpages.currentpage().getParameters().keySet().size(); i++){
            string value = apexpages.currentpage().getParameters().get('id_' + i);
            if(value != null && value.trim().length() >= 15){
                ids.add(value);
            }
        }
       
        system.debug('$$$ Ids = ' + ids); 
        
        //system.debug('### query From and To = '+query);
        
        sechList = getSchedules(ids);
        
        system.debug('### sechList Size : '+sechList.size());
        system.debug('### sechList : '+sechList);
    }
    
    private List<Schedules__c> getSchedules(Set<Id> ids){
         List<Schedules__c> schedules = [Select 
                                             id, Week__c, Long_Form__c, Units_Preempted__c,
                                             Rate__c, LF_Brand__c, X800_Number__c, Name,
                                             Comments__c,Filler__c, Test__c, ISCI_CODE__c, Status__c 
                                        FROM Schedules__c
                                        Where id in:ids]; 
         return schedules;
    }
    
    public pageReference save(){
        if(sechList != null && sechList.size() > 0){
               for(Schedules__c sech : sechList){
                    
                    if(schedule.Rate__c != null)
                        sech.Rate__c = schedule.Rate__c;
                    
                    if(schedule.X800_Number__c != null)
                        sech.X800_Number__c = schedule.X800_Number__c;
                    
                    if(schedule.Comments__c != null)
                        sech.Comments__c = schedule.comments__c;
                        
                    if(schedule.ISCI_CODE__c != null)
                        sech.ISCI_CODE__c = schedule.ISCI_CODE__c;
                     
                    if(schedule.Test__c != null)
                        sech.Test__c = schedule.Test__c;
                        
                    if(schedule.Status__c != null)
                        sech.Status__c = schedule.Status__c;
                    
                    sech.Filler__c = schedule.Filler__c;
                }
                
                update sechList;
                closeWindow = true;
                     
        }
        //PageReference pg = new PageReference('/apex/managementReport');
        return null;
    }
    
    public PageReference cancel(){
        PageReference pg = new PageReference('/apex/managementReport');
        return pg;
    }
}