objects/Schedules__c.object
<CustomObject>
    <fields>
        <fullName>Days_Allowed__c</fullName>
        <description>Select days that the schedule is allowed to air</description>
        <inlineHelpText>Select the days that this schedule CAN air on.</inlineHelpText>
        <label>Days Allowed</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Mon</fullName>
                </value>
                <value>
                    <fullName>Tue</fullName>
                </value>
                <value>
                    <fullName>Wed</fullName>
                </value>
                <value>
                    <fullName>Thu</fullName>
                </value>
                <value>
                    <fullName>Fri</fullName>
                </value>
                <value>
                    <fullName>Sat</fullName>
                </value>
                <value>
                    <fullName>Sun</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>End_Time__c</fullName>
        <label>End Time</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>MGM_HD_Daypart__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>01:00A</fullName>
                </value>
                <value>
                    <fullName>01:30A</fullName>
                </value>
                <value>
                    <fullName>02:00A</fullName>
                </value>
                <value>
                    <fullName>02:30A</fullName>
                </value>
                <value>
                    <fullName>03:00A</fullName>
                </value>
                <value>
                    <fullName>03:30A</fullName>
                </value>
                <value>
                    <fullName>04:00A</fullName>
                </value>
                <value>
                    <fullName>04:30A</fullName>
                </value>
                <value>
                    <fullName>05:00A</fullName>
                </value>
                <value>
                    <fullName>05:30A</fullName>
                </value>
                <value>
                    <fullName>06:00A</fullName>
                    <default>true</default>
                    <label>06:00A</label>
                </value>
                <value>
                    <fullName>06:30A</fullName>
                </value>
                <value>
                    <fullName>07:00A</fullName>
                </value>
                <value>
                    <fullName>07:30A</fullName>
                </value>
                <value>
                    <fullName>08:00A</fullName>
                </value>
                <value>
                    <fullName>08:30A</fullName>
                </value>
                <value>
                    <fullName>09:00A</fullName>
                </value>
                <value>
                    <fullName>09:30A</fullName>
                </value>
                <value>
                    <fullName>10:00A</fullName>
                </value>
                <value>
                    <fullName>10:30A</fullName>
                </value>
                <value>
                    <fullName>11:00A</fullName>
                </value>
                <value>
                    <fullName>11:30A</fullName>
                </value>
                <value>
                    <fullName>12:00P</fullName>
                </value>
                <value>
                    <fullName>12:30P</fullName>
                </value>
                <value>
                    <fullName>01:00P</fullName>
                </value>
                <value>
                    <fullName>01:30P</fullName>
                </value>
                <value>
                    <fullName>02:00P</fullName>
                </value>
                <value>
                    <fullName>02:30P</fullName>
                </value>
                <value>
                    <fullName>03:00P</fullName>
                </value>
                <value>
                    <fullName>03:30P</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OrderLineNumber__c</fullName>
        <label>Order Line Number</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <label>Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <label>Start Time</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>MGM_HD_Daypart__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>01:00A</fullName>
                </value>
                <value>
                    <fullName>01:30A</fullName>
                </value>
                <value>
                    <fullName>02:00A</fullName>
                </value>
                <value>
                    <fullName>02:30A</fullName>
                </value>
                <value>
                    <fullName>03:00A</fullName>
                </value>
                <value>
                    <fullName>03:30A</fullName>
                </value>
                <value>
                    <fullName>04:00A</fullName>
                </value>
                <value>
                    <fullName>04:30A</fullName>
                </value>
                <value>
                    <fullName>05:00A</fullName>
                </value>
                <value>
                    <fullName>05:30A</fullName>
                </value>
                <value>
                    <fullName>06:00A</fullName>
                    <default>true</default>
                    <label>06:00A</label>
                </value>
                <value>
                    <fullName>06:30A</fullName>
                </value>
                <value>
                    <fullName>07:00A</fullName>
                </value>
                <value>
                    <fullName>07:30A</fullName>
                </value>
                <value>
                    <fullName>08:00A</fullName>
                </value>
                <value>
                    <fullName>08:30A</fullName>
                </value>
                <value>
                    <fullName>09:00A</fullName>
                </value>
                <value>
                    <fullName>09:30A</fullName>
                </value>
                <value>
                    <fullName>10:00A</fullName>
                </value>
                <value>
                    <fullName>10:30A</fullName>
                </value>
                <value>
                    <fullName>11:00A</fullName>
                </value>
                <value>
                    <fullName>11:30A</fullName>
                </value>
                <value>
                    <fullName>12:00P</fullName>
                </value>
                <value>
                    <fullName>12:30P</fullName>
                </value>
                <value>
                    <fullName>01:00P</fullName>
                </value>
                <value>
                    <fullName>01:30P</fullName>
                </value>
                <value>
                    <fullName>02:00P</fullName>
                </value>
                <value>
                    <fullName>02:30P</fullName>
                </value>
                <value>
                    <fullName>03:00P</fullName>
                </value>
                <value>
                    <fullName>03:30P</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Schedule</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/OrderLineNumberBatch.cls
global class OrderLineNumberBatch implements Database.Batchable<sObject> 
{    

    global OrderLineNumberBatch()
    {
        //database.executebatch(new OrderLineNumberBatch(),50);
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC)
    {
        return Database.getQueryLocator([SELECT id, OrderLineNumber__c, Days_Allowed__c, Start_Time__c, End_Time__c, Rate__c 
                                   FROM Schedules__c 
                                   WHERE Start_Time__c!=NULL AND  End_Time__c!=NULL AND Days_Allowed__c !=NULL AND Rate__c !=NULL ]);
    }

    global void execute(Database.BatchableContext BC, List<Schedules__c > scope)
    {
        try
        {
          string starttime;
            list<string> startsplit = new list<string>();
            string endtime;
            list<string> endsplit = new list<string>();
            string daysallowed;
            
            list<string> ratesplit = new list<string>();
          
            List<Schedules__c> ScheduleToUpdate = new List<Schedules__c>();

            for(Schedules__c sch: scope)
            {
            
            
            startsplit = sch.Start_Time__c.split(':', 2); 
            system.debug('START TIME SPLIT: ' + startsplit);
            endsplit = sch.End_Time__c.split(':', 2); 
            system.debug('END TIME SPLIT: ' + endsplit );
            
            //Find start 3 digit  
            if(sch.Start_Time__c.contains('P'))
            {
                starttime = string.valueof(integer.valueof(startsplit[0]) + 12);
                if(startsplit[1].contains('3'))
                {
                    starttime += '3';
                }
                else
                {
                    starttime += '0';    
                } 
            }
            else
            {
                starttime = startsplit[0];  
                if(startsplit[1].contains('3'))
                {
                    starttime += '3';
                }
                else
                {
                    starttime += '0';    
                }   
            }  
            system.debug('FIRST PART: ' +starttime);
            //Find end 3 digit   
            if(sch.End_Time__c.contains('P'))
            {
                //integer intend = integer.valueof(endsplit[0]) + 12 ;
                endtime = string.valueof(integer.valueof(endsplit[0]) + 12);
                if(endsplit[1].contains('3'))
                {
                    endtime += '3';
                }
                else
                {
                    endtime += '0';    
                } 
            }
            else
            {
                endtime = endsplit[0];  
                if(endsplit[1].contains('3'))
                {
                    endtime += '3';
                }
                else
                {
                    endtime += '0';    
                }   
            }    
            system.debug('SECOND PART: ' +endtime );
            
            //Find 3 digit Days Allowed
            //First digit 
            if(sch.Days_Allowed__c.contains('Mon') && sch.Days_Allowed__c.contains('Tue') && sch.Days_Allowed__c.contains('Wed') )
            {
                daysallowed = '7';
            }
            else if(sch.Days_Allowed__c.contains('Mon') && sch.Days_Allowed__c.contains('Wed') )
            {
                daysallowed = '6';    
            }
            else if(sch.Days_Allowed__c.contains('Tue') && sch.Days_Allowed__c.contains('Wed') )
            {
                daysallowed = '5';    
            }  
            else if(sch.Days_Allowed__c.contains('Mon') && sch.Days_Allowed__c.contains('Tue') )
            {
                daysallowed = '4';    
            } 
            else if(sch.Days_Allowed__c.contains('Wed') )
            {
                daysallowed = '3';    
            }  
            else if(sch.Days_Allowed__c.contains('Tue') )
            {
                daysallowed = '2';    
            }  
            else if(sch.Days_Allowed__c.contains('Mon') )
            {
                daysallowed = '1';    
            }   
            else
            {
                daysallowed = '0';    
            }
            //Second digt
            if(sch.Days_Allowed__c.contains('Thu') && sch.Days_Allowed__c.contains('Fri') )
            {
                daysallowed += '3';
            }
            else if(sch.Days_Allowed__c.contains('Fri') )
            {
                daysallowed += '2';    
            }
            else if(sch.Days_Allowed__c.contains('Thu') )
            {
                daysallowed += '1';    
            }  
            else
            {
            daysallowed += '0';    
            }
            //Third digit
            if(sch.Days_Allowed__c.contains('Sat') && sch.Days_Allowed__c.contains('Sun') )
            {
                daysallowed += '3';
            }
            else if(sch.Days_Allowed__c.contains('Sat') )
            {
                daysallowed += '2';    
            }
            else if(sch.Days_Allowed__c.contains('Sun') )
            {
                daysallowed += '1';    
            }  
            else
            {
                daysallowed += '0';    
            }
            system.debug('THIRD PART: ' +daysallowed );

            string rating='';
            string spaceholders='';
            integer spacedifference =0;
            
            
            rating = string.valueof(integer.valueof(sch.Rate__c * 100)); 
            spacedifference = 9 - rating.length();
            
            
            for(integer i = 0; i < spacedifference; i++)
            {
                spaceholders += '0';    
            }   
            
            string  newrating = spaceholders + rating;
            system.debug('FOURTH PART: ' +rating );

            sch.OrderLineNumber__c = starttime + endtime + daysallowed + newrating ; 
            system.debug('Schedule Order Line Number: ' +sch.OrderLineNumber__c);
            ScheduleToUpdate.add(sch);

        }
        update ScheduleToUpdate;
        } 
        catch(exception e)
        {
                  
        }               
    }           
    global void finish(Database.BatchableContext BC)
    { 
    
    }
}