objects/Spot_Data__c.object
<CustomObject>
    <description>Post log information for schedule</description>
    <fields>
        <fullName>Availability__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Availability</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Day_of_Week__c</fullName>
        <formula>CASE( 
MOD(  Air_Date__c  - DATE(1900, 1, 7), 7), 
0, &quot;7Sun&quot;, 
1, &quot;1Mon&quot;, 
2, &quot;2Tues&quot;, 
3, &quot;3Wed&quot;, 
4, &quot;4Th&quot;, 
5, &quot;5Fri&quot;, 
6, &quot;6Sat&quot;, &quot;Error&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Day of Week</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Schedule__c</fullName>
        <label>Schedule</label>
        <referenceTo>Schedules__c</referenceTo>
        <relationshipLabel>Spot Data</relationshipLabel>
        <relationshipName>Spot_Data</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SpotDataMirror_Reference__c</fullName>
        <description>This is used to add  related  schedule id +spot data name+index number( of trigger.new).
used to relate this to spot data mirror record.</description>
        <label>SpotDataMirror Reference</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SpotDataMirror__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SpotDataMirror</label>
        <referenceTo>SpotDataMirror__c</referenceTo>
        <relationshipLabel>Spot Data</relationshipLabel>
        <relationshipName>Spot_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Spot_Equiv_30__c</fullName>
        <formula>VALUE(TEXT(Length__c)) / 30</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Spot Equiv :30</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Spot_Rate__c</fullName>
        <label>Spot Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Spot Data</label>
    <nameField>
        <displayFormat>S-{000000}</displayFormat>
        <label>Spot Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Spot Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SpotDataMirror__c.object
<CustomObject>
    <fields>
        <fullName>Schedule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Schedule</label>
        <referenceTo>Schedules__c</referenceTo>
        <relationshipLabel>Spot Data</relationshipLabel>
        <relationshipName>SpotDataMirror</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Spot_Data__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is used to link the related spot date record Created/Updated</description>
        <label>Spot Data</label>
        <referenceTo>Spot_Data__c</referenceTo>
        <relationshipLabel>Spot Data Mirrors</relationshipLabel>
        <relationshipName>Spot_Data_Mirrors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Spot_Equiv_30__c</fullName>
        <formula>VALUE(TEXT(Length__c)) / 30</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Spot Equiv :30</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Spot_Rate__c</fullName>
        <label>Spot Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Spot Data Mirror</label>
    <nameField>
        <label>Spot Data Mirror Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Spot Data Mirrors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SpotDataSelector.cls
/**
 * @date 1/15/2019
 * @description Database Selector for Spot_Data__c objects
 */
public with sharing virtual class SpotDataSelector {

    public virtual List<Spot_Data__c> GetSpotDataWithScheduleIds(List<String> Ids) {
        return [
                SELECT Day_of_Week__c,
                       Spot_Equiv_30__c,
                       Spot_Rate__c
                  FROM Spot_Data__c
                 WHERE Schedule__c IN :Ids
        ];
    }

    public virtual Spot_Data__c[] getSpotsForSpotsExist(Id sch) {
        return [SELECT Schedule__c, Availability__c
                  FROM Spot_Data__c
                 WHERE Availability__c = true
                   AND Schedule__c = :sch];
    }


    private List<String> FieldsToStrings(List<SObjectField> fields) {
        List<String> result = new List<String>();
        for (SObjectField field : fields) {
            result.add(field.getDescribe().name);
        }
        return result;
    }
  
    /**
     * @description Retrieve a list of Spot_Data__c objects from a provided mirror reference map
     * @param refMap The map being used to reference the SpotData
     * @return The resulting list of SpotData from the database
     */
    public virtual List<Spot_Data__c> getSpotDataFromReferenceMap(Map<String, SpotDataMirror__c> refMap) {
        return [
                SELECT Id,
                       Schedule__c,
                       Name,
                       SpotDataMirror_Reference__c
                  FROM Spot_Data__c
                 WHERE SpotDataMirror_Reference__c IN :refMap.keySet()
        ];
    }

    public virtual List<SpotDataMirror__c> getMirrorsFromIds(List<Id> ids) {
        return [
                SELECT Id,
                       Name,
                       Spot_Data__c,
                       Schedule__c
                  FROM SpotDataMirror__c
                 WHERE Id IN : ids
        ];
    }

    public virtual List<AsyncApexJob> getJobsForSpotData() {
        return [
                SELECT Id,
                       ApexClassId,
                       Status
                  FROM AsyncApexJob
                 WHERE ((Status = 'Processing' OR Status = 'Queued' OR Status = 'Preparing')
                   AND (ApexClass.Name='SpotDataScheduleBatch' OR ApexClass.Name='SpotDataBatch')
                   AND JobType='BatchApex' )
        ];
    }

}