objects/Spot_Data__c.object
<CustomObject>
    <description>Post log information for schedule</description>
    <fields>
        <fullName>SpotDataMirror__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SpotDataMirror</label>
        <referenceTo>SpotDataMirror__c</referenceTo>
        <relationshipLabel>Spot Data</relationshipLabel>
        <relationshipName>Spot_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Spot Data</label>
    <nameField>
        <displayFormat>S-{000000}</displayFormat>
        <label>Spot Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Spot Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SpotDataMirror__c.object
<CustomObject>
    <fields>
        <fullName>Spot_Data__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is used to link the related spot date record Created/Updated</description>
        <label>Spot Data</label>
        <referenceTo>Spot_Data__c</referenceTo>
        <relationshipLabel>Spot Data Mirrors</relationshipLabel>
        <relationshipName>Spot_Data_Mirrors</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Spot Data Mirror</label>
    <nameField>
        <label>Spot Data Mirror Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Spot Data Mirrors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestSpotDataSelector.cls
/**
 * @date 1/15/2019
 * @description Mock database selector for unit testing with SpotDataSelector.cls
 */
public with sharing class TestSpotDataSelector extends SpotDataSelector {

    //
    // Fields
    //
    public Integer fabricationAmount { get; set; }
    public Map<SObjectField, Object> fabricationFields { get; set; }
    public List<Spot_Data__c> fabricatedList { get; set; }

    /**
     * Construct a TestSpotDataSelector
     *  Initialize Fields
     */
    public TestSpotDataSelector() {
        this.fabricationAmount = 0;
        this.fabricationFields = new Map<SObjectField, Object>();
        this.fabricatedList = new List<Spot_Data__c>();
    }

    /**
     * {@inheritDocs}
     *
     * @return A fabricated list of spot data being "loaded" from the reference map
     */
    public override List<Spot_Data__c> getSpotDataFromReferenceMap(Map<String, SpotDataMirror__c> refMap) {
        if (this.fabricatedList.isEmpty()) {
            List<Spot_Data__c> result = new List<Spot_Data__c>();

            return result;
        } else {
            return this.fabricatedList;
        }
    }

}