objects/SpotDataClone__c.object
<CustomObject>
    <fields>
        <fullName>AirDate__c</fullName>
        <label>AirDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OrderNumber__c</fullName>
        <label>OrderNumber</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>SpotDataClone</label>
    <nameField>
        <label>SpotDataClone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SpotDataClones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SpotDataCloneMaker.cls
public class SpotDataCloneMaker {
    public static void createClones(){
        Integer counter = 0;
        List<SpotDataClone__c> clones = new List<SpotDataClone__c>();
        while(counter < 500){
            SpotDataClone__c  sdc = new SpotDataClone__c ();
     		Integer day = Integer.valueof((Math.random() * 28)) + 1; 
            Integer month = Integer.valueof((Math.random() * 11)) + 1;
            Integer year = Integer.valueof((Math.random() * 19)) + 2000;
            //air date           
            Date myDate = Date.newInstance(year, month, day); 
			sdc.AirDate__c = myDate;
            //order number
            sdc.OrderNumber__c = Integer.valueof((Math.random() * 20));
			clones.add(sdc);
            counter++;
        }
        insert clones;
    }
    
    public static void deleteRecords(){
        List<SpotDataClone__c> clones = [select id from SpotDataClone__c];
        delete clones;
          
    }
}