objects/Spot_Data__c.object
<CustomObject>
    <description>Post log information for schedule</description>
    <fields>
        <fullName>Day_of_Week__c</fullName>
        <formula>CASE( 
MOD(  Air_Date__c  - DATE(1900, 1, 7), 7), 
0, &quot;7Sun&quot;, 
1, &quot;1Mon&quot;, 
2, &quot;2Tues&quot;, 
3, &quot;3Wed&quot;, 
4, &quot;4Th&quot;, 
5, &quot;5Fri&quot;, 
6, &quot;6Sat&quot;, &quot;Error&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Day of Week</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Spot_Equiv_30__c</fullName>
        <formula>VALUE(TEXT(Length__c)) / 30</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Spot Equiv :30</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Spot_Rate__c</fullName>
        <label>Spot Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Spot Data</label>
    <nameField>
        <displayFormat>S-{000000}</displayFormat>
        <label>Spot Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Spot Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/SpotDataTestSelector.cls
/**

 *
 * SpotDataTestSelector
 * Selector for Spot_Data__c objects
 */

public with sharing class SpotDataTestSelector extends SpotDataSelector {

//    public override List<Spot_Data__c> GetSpotData(List<SObjectField> fields) {
//        String query = 'SELECT ' + String.join(FieldsToStrings(fields), ', ') + ' FROM ' + OBJ;
//        return Database.query(query);
//    }

    public override List<Spot_Data__c> GetSpotDataWithScheduleIds(List<String> Ids) {
        return new List<Spot_Data__c> {
                (Spot_Data__c) new sfab_FabricatedSObject(Spot_Data__c.class)
                    .setField(Spot_Data__c.Day_of_Week__c, 'Mon,Sat')
                    .setField(Spot_Data__c.Spot_Equiv_30__c, 1.0)
                    .setField(Spot_Data__c.Spot_Rate__c, 1.0)
                .toSObject()
        };
    }


    private List<String> FieldsToStrings(List<SObjectField> fields) {
        List<String> result = new List<String>();
        for (SObjectField field : fields) {
            result.add(field.getDescribe().name);
        }
        return result;
    }
}