objects/Tape__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Traffic</relationshipLabel>
        <relationshipName>Tapes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Brand</label>
        <referenceTo>Brands__c</referenceTo>
        <relationshipLabel>Traffic</relationshipLabel>
        <relationshipName>Tapes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Flight_End__c</fullName>
        <label>Flight End</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Flight_Start__c</fullName>
        <label>Flight Start</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ISCI_2__c</fullName>
        <label>ISCI 2</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ISCI_3__c</fullName>
        <label>ISCI 3</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ISCI__c</fullName>
        <label>ISCI</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Length__c</fullName>
        <label>Length</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>30</fullName>
                </value>
                <value>
                    <fullName>60</fullName>
                </value>
                <value>
                    <fullName>120</fullName>
                </value>
                <value>
                    <fullName>300</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>1710</fullName>
                </value>
                <value>
                    <fullName>90</fullName>
                </value>
                <value>
                    <fullName>180</fullName>
                </value>
                <value>
                    <fullName>240</fullName>
                </value>
                <value>
                    <fullName>45</fullName>
                </value>
                <value>
                    <fullName>75</fullName>
                </value>
                <value>
                    <fullName>05</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Program</label>
        <referenceTo>Programs__c</referenceTo>
        <relationshipLabel>Traffic</relationshipLabel>
        <relationshipName>Tapes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rotation__c</fullName>
        <label>Rotation</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Spot</fullName>
                </value>
                <value>
                    <fullName>50-50 Split</fullName>
                </value>
                <value>
                    <fullName>Pattern</fullName>
                </value>
                <value>
                    <fullName>Limited Ratio</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>X800_Number__c</fullName>
        <label>800 Number</label>
        <type>Phone</type>
    </fields>
    <label>Traffic</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Traffic</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TapeSelector.cls
/**
 * @date 1/9/2019
 * @description Tape Selector used for querying tapes via DML
 */
public with sharing virtual class TapeSelector {

    /**
     * @description The Object being Selected from
     */
    private final String OBJ = 'Tape__c';

    /**
     * @description Retrieve a list of Tape's with the specified fields
     *
     * @param fields The fields being specified to be retrieved from the list of tapes
     *
     * @return The retrieved list of tapes from the database
     */
    public virtual List<Tape__c> getTapes(List<SObjectField> fields) {
        return Database.query('SELECT ' + String.join(getFieldNames(fields), ', ') + ' FROM ' + OBJ);
    }

    /**
     * @description Retrieve a list of tapes from start week and end week
     *
     * @param startDate The first week being selected from
     * @param endDate The end week being selected from
     *
     * @return The retrieved list from the database
     */
    public virtual List<Tape__c> getTapesInFlightRange(Date startDate, Date endDate) {
        return [
                SELECT  Id,
                        Name,
                        X800_Number__c,
                        Account__c,
                        Brand__c,
                        Flight_End__c,
                        Flight_Start__c,
                        ISCI_2__c,
                        ISCI_3__c,
                        Program__c,
                        Rotation__c,
                        Length__c,
                        ISCI__c
                   FROM Tape__c
                  WHERE Flight_Start__c <= :startDate
                   AND Flight_End__c >= :endDate
        ];
    }

    /**
     * @description Retrieve a single Tape__c instance from a requested Id
     *
     * @param TapeId The Id of the requested Tape__c
     *
     * @return The resulting Tape__c SObject
     */
    public virtual Tape__c getTapeFromId(Id TapeId) {
        return [
                SELECT Id,
                        Name,
                        X800_Number__c,
                        Account__c,
                        Brand__c,
                        Flight_Start__c,
                        Flight_End__c,
                        ISCI_2__c,
                        ISCI_3__c,
                        Program__c,
                        Rotation__c,
                        Length__c,
                        ISCI__c
                   FROM Tape__c
                  WHERE Id = :TapeId
        ];
    }

    /**
     * @description Retrieve a list of Field names from a list of fields
     *
     * @param fields The fields being accessed
     *
     * @return The names of the fields requested
     */
    private List<String> getFieldNames(List<SObjectField> fields) {
        List<String> result = new List<String>();
        for (SObjectField field : fields) {
            result.add(field.getDescribe().name);
        }
        return result;
    }
}